### DISCUSSION TITLE
What happens if the ShardAwareDeduplicateFilter is not used

### DISCUSSION THREAD

**Discussion by ASatanicPickle** [grafana/mimir#10651] [Help and support]
Hi,

We have a very large tenant with about 800K blocks and the when the compactor runs the ShardAwareDeduplicateFilter, that filter takes about 24h - 30h to complete.

What would happen if that filter wasn't run?  Would it be okay to compact with duplicate blocks?  Or, if there's something else we could do that would be awesome too.

Thanks

**Comment by deniszh** [comment]
Hi @ASatanicPickle ,
Could you please share your compactor config? How many compactors do you use?

PS: we're using following for one of big tenants:
```
...
      compactor_split_and_merge_shards: 16 # recommended - 1 shard per every 8 million
      compactor_split_groups: 16 # recommended - 1 shard per every 8 million
      compactor_tenant_shard_size: 16 # Give 90% of total compactor replicas to this tenant
...
compactor:
...
  replicas: 20
  podDisruptionBudget:
    maxUnavailable: 20%
  resources:
    limits:
      cpu: 4
      memory: 12Gi
    requests:
      cpu: 2
      memory: 12Gi
  extraArgs:
    compactor.compaction-concurrency: 1
    compactor.compaction-interval: 1h
    compactor.ring.wait-stability-max-duration: 30m
    compactor.meta-sync-concurrency: 200
    compactor.block-sync-concurrency: 50
    compactor.max-compaction-time: 0
...
```
