### DISCUSSION TITLE
Bug: Ruler showing incredible amount of network traffic

### DISCUSSION THREAD

**Discussion by ecktom** [grafana/mimir#10654] [Help and support] [answered]
### What is the bug?

We've recently deployed [beyla](https://github.com/grafana/beyla) into our observability cluster running Mimir to gather some metrics about how traffic flows. A really great tool! Kudos to the team!

This brought up some interesting results. `Ruler` is by far our top consumer in terms of data coming in. Also the index-cache has much more traffic flowing than I would have expected but this is maybe a question for some other day ;) 

<img width="1278" alt="Image" src="https://github.com/user-attachments/assets/1bd92478-6636-4137-afaa-9bcfd19d1d76" />

Looking at the ruler specifically we can see that most traffic is coming in from the store-gateways followed by the ingesters.
<img width="1280" alt="Image" src="https://github.com/user-attachments/assets/827d9ef1-1ba1-4122-b041-97ccb792414f" />

We than figured out that we've configured compression a long time back between `distributor` and `ingesters` using `-ingester.client.grpc-compression=snappy` on the `distributor` but apparently never did so for the `ruler` as we were not using it at that time. 
So we moved ahead and added `-ruler.client.grpc-compression=snappy` and `-ruler.query-frontend.grpc-client-config.grpc-compression=snappy` at the `ruler` which surprisingly had 0 effect.
Next thing we tried was adding:
```
ruler:
  ruler_client:
    grpc_compression: snappy
  query_frontend:
    address: "dns:///gridx-sre-mimir-query-frontend.mimir:9095"
    grpc_client_config:
      grpc_compression: snappy
```
to the structured config and restarting the `ruler` which did the trick. Looking at CPU/Memory/Network metrics of the `ruler` we saw some unexpected results, all of them improved massively (we applied the change at 16:45 and rolled back at 17:33). The change of CPU/Memory is a mystery for me.
<img width="1279" alt="Image" src="https://github.com/user-attachments/assets/aae22543-0a57-42f0-b202-d426715b1789" />

However, it seems we've just moved the issue somewhere else... ;) At the same time we noticed that the `queriers` are receiving much more traffic in a very similar proportion.
<img width="1277" alt="Image" src="https://github.com/user-attachments/assets/f2acca85-c7ba-4797-9b2f-6448be079612" />
Much more traffic is flowing between `queriers` and `ingester`/`store-gateways` which we can also see on the Mimir Reads Dashboard in terms of RPS of all of those components on the read path.
<img width="1278" alt="Image" src="https://github.com/user-attachments/assets/69a3fce4-5f80-4ac8-8157-dc44abff853b" />

Looking at the Mimir Ruler dashboard it looks like the ruler just stopped doing requests
<img width="1354" alt="Image" src="https://github.com/user-attachments/assets/06e771dd-6723-4504-826a-ecaa92f7c240" />

Total traffic is much worse than before as also traffic between the `store-gateway` and the `index-cache` increased a lot
<img width="1302" alt="Image" src="https://github.com/user-attachments/assets/118483dd-54ea-49ee-920e-ea38c1e5564b" />

We tried adding `frontend.grpc_client_config.grpc_compression` and `frontend_worker.grpc_client_config.grpc_compression` on top which did not seem to have any effect after restarting the `queriers` and the `query-frontends`. Is there anything we're missing or which could explain this pattern? 

### What was your environment?

- AWS
- Kubernetes
- mimir-distributed-5.5.1
- 2.14.2

**Comment by deniszh** [comment, marked as answer]
In my experience grpc client config in Mimir is quite cryptic. I would recommend to pick up one option (either config or cli) and don't mix it up without need. Try to configure snappy compression everywhere in config, it's lightweight enough to not bring too much load and [recommended for production](https://grafana.com/docs/mimir/latest/manage/run-production-environment/production-tips/#network).
Something like
```
    alertmanager:
      alertmanager_client:
        grpc_compression: snappy
    frontend:
      grpc_client_config:
        grpc_compression: snappy
    frontend_worker:
      query_scheduler_grpc_client_config:
        grpc_compression: snappy
      grpc_client_config:
        grpc_compression: snappy
    ingester_client:
      grpc_client_config:
        grpc_compression: snappy
    ruler:
      query_frontend:
        grpc_client_config:
          grpc_compression: snappy
      ruler_client:
        grpc_client_config:
          grpc_compression: snappy
    query_scheduler:
      grpc_client_config:
        grpc_compression: snappy
```
(I tried to make config proper but please check it before going full prod).
This config should work for both external and internal ruler modes.
