### DISCUSSION TITLE
My alert rules don't load by Mimir. Need a help to got my error

### DISCUSSION THREAD

**Discussion by rmalenko** [grafana/mimir#10719] [Help and support]
My alert rules don't load by Mimir.

I expect Mimir should read rules from `/etc/mimir/rulerstorage/prometheus_alert_rules.yml`

I have broken my brain to get where I'm wrong. I would appreciate your help.

```yml
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter

multitenancy_enabled: true

# Configure Mimir to use Minio as object storage backend.
common:
  skipped: .....

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /etc/mimir/rulerstorage/

alertmanager_storage:
  backend: s3
  storage_prefix: alertmanager
  s3:
    endpoint: fra1.digitaloceanspaces.com
    bucket_name: mimir
    access_key_id: DO
    secret_access_key: +7KZ
    insecure: false
    signature_version: v4

ruler:
  alertmanager_url: http://10.13.3.251:9093,http://10.13.0.115:9093,http://10.13.185.243:9093
  rule_path: ./data-ruler/
  notification_timeout: 30s
  enable_api: true
  ring:
    instance_addr: 10.135.185.248

alertmanager:
  retention: 48h
  enable_api: true
  data_dir: ./data-alertmanager/
  grafana_alertmanager_compatibility_enabled: false
  sharding_ring:
    instance_addr: 10.135.185.248

skipped: ......
```

My rules is:
```
groups:
  - name: Promtail
    rules:
    - alert: PromtailRequestErrors
      expr: 100 * sum(rate(promtail_request_duration_seconds_count{status_code=~"5..|failed"}[1m])) by (namespace, job, route, instance) / sum(rate(promtail_request_duration_seconds_count[1m])) by (namespace, job, route, instance) > 10
  skipped: ....
```

But http://mimir.domain.com/alertmanager/#/status displays me this rule

```yml
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
  smtp_hello: localhost
  smtp_require_tls: true
```
