### DISCUSSION TITLE
How to tune Mimir for an expensive tenant

### DISCUSSION THREAD

**Discussion by ericlee123** [grafana/mimir#11201] [Help and support]
Hello Mimir community,

Recently, we have been trying to tackle query performance issues with a particular metric, `inbound_latency`, on a particular tenant, `hat`.

Here are the details of our situation:
* The query we are running is: `histogram_count(sum by (http_status)  (delta(inbound_latency{}[2m])))`. A time window of 6 hours takes about 10-15 sec to complete, and a time window of 12 hours takes 20-30 sec to complete. Any longer just times out in Grafana.
* `inbound_latency` has 14 labels associated with it. Its cardinality is on the order of 10^13, so in the trillions. The way I'm defining cardinality here is going through each label and multiplying the number of unique values all together.
  - There are 4 labels with very high numbers of unique values: 740, 442, 140, and 130.
  - Calling `/prometheus/api/v1/cardinality/active_series` on this metric returns 135671, which is the largest value of all of our metrics.
* Our current Mimir deployment is as follows (just going to mention the relevant parts):
  - `ingester` has 52 containers, each with 8 CPU and 14 GB memory
  - `store-gateway` has 10 containers, each with 4 CPU and 4 GB memory
    + These allocations are equal or greater than the values recommended in the [capacity planning doc](https://grafana.com/docs/mimir/latest/manage/run-production-environment/planning-capacity/).
  - For configuration parameters:
    + All forms of caching are enabled.

```
# this excerpt doesn't include everything, just what I thought is relevant to this discussion
ingester:
  ring:
    replication_factor: 3
    zone_awareness_enabled: false

store_gateway:
  sharding_ring:
    zone_awareness_enabled: false

limits:
  ingestion_rate: 100000
  ingestion_burst_size: 2000000
  max_label_names_per_series: 60
  ingestion_tenant_shard_size: 3
  max_global_series_per_user: 0
  native_histograms_ingestion_enabled: true
  out_of_order_time_window: 30d
  results_cache_ttl: 1w
  results_cache_ttl_for_out_of_order_time_window: 5m
  cardinality_analysis_enabled: true
  store_gateway_tenant_shard_size: 3
  compactor_blocks_retention_period: 3y
  compactor_split_and_merge_shards: 2 # use even number
  compactor_split_groups: 6 # use even number
```

### Problem

The issue I'm running into is that our InfluxDB equivalent for this data (same tags for the labels we have in Mimir) can query 30 days into the past, whereas we can barely hit a single day in Mimir. One thing we tried was to increase the shard size for `ingester` and `store-gateway`, but that seemingly had no affect on query performance. This was the change we attempted:
```
overrides:
  hat:
    ingestion_tenant_shard_size: 9
    store_gateway_tenant_shard_size: 9
```

The thinking was that, maybe originally, just having 3 instances of `ingester` and `store-gateway` each was not sufficient in serving our most expensive tenant, so we should increase the number of instances serving these requests. But because we observed no changes, I'm wondering if we are going about this incorrectly.

How can we tune our Mimir deployment to better serve this particular tenant? Please let me know if I can provide any more details about the scenario.
