### DISCUSSION TITLE
Prometheus HA replica's not deduplicated from query results.

### DISCUSSION THREAD

**Discussion by BlackDex** [grafana/mimir#11451] [Help and support]
Hello there,

I have a setup where multiple clusters which use prometheus-operator send metrics to an alloy instance which collects these metrics and then sends them to mimir.

Now that prometheus-operator setup is using 2 prometheus instances per cluster which remote-write to the alloy instance, and that of course causes duplicate metrics.

Now i have configured the `ha_replica_label` and `ha_cluster_label` to be correct, which resulted in now showing a third metric, which is without the `prometheus_replica` label, which looks to be good, but i still see the others also when i run a query.

I have now also enabled the `ha_tracker`, but i still see 3 metrics instead of just one.
All pods have be restarted/re-deployed, except for all ingesters, which takes a long time to get into the ready state, and it does them all one-by-one which takes a long time.

Is there something i have missed or overlooked?

**Comment by BlackDex** [comment]
Also, in our previous setup we used thanos, which also had `prometheus_replica` label as a replicaLabel configured, and it stored both values, but only returned one.

And the prometheus-operator isn't HA in the sense that there is only one prometheus sending metrics, they both are.
So i need some way of deduplication i guess.

**Comment by deniszh** [comment]
Did you deploy Consul or Etcd for HA tracker? Documentation is quite good, just follow it and it should work - https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/

**Reply by BlackDex** [reply]
I think i used the memberlist function, but as it turned out, that isn't fast enough. I have not yet tried the other options.

But i now dropped the replica label. But that does produce a lot of errors though

**Reply by deniszh** [reply]
As far as I understand, HA tracker **require** consul or etcd, [memberlist is not supported](https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/#configure-the-ha-tracker-kv-store).
```
    Note

    memberlist isn’t supported.

    Memberlist-based KV stores propagate updates using the Gossip protocol, which is too slow for the HA tracker.

    The result would be that different distributors might see a different Prometheus server elected as leaders at the same time.
```

No need to use consul or etcd for ring, you can use it only for HA tracker. I.e. take [bitnami consul](https://artifacthub.io/packages/helm/bitnami/consul), install small 3 node cluster and provide 
```
distributor:
  ha_tracker:
    enable_ha_tracker: true
      kvstore:
        store: consul
        consul:
          host: bitnami-consul-headless.<YOUYRNAMESPACE>.svc.cluster.local:8500
```

**Reply by BlackDex** [reply]
Well, it works, but, as it stated, it's too slow.

**Reply by BlackDex** [reply]
Would it btw be beneficial to move other kvstore items over to consule? Or keep those on memberlist?

**Reply by deniszh** [reply]
For us memberlist works fine as service discovery. If you not using consul already I see no point for migration.

**Comment by BlackDex** [comment]
Ok, i have configured consul, and i see the key/values in the consol-ui, but i still see a lot of `the sample has been rejected because another sample with the same timestamp, but a different value, has already been ingested` errors on all distributors.

All distributors have been restarted with the new config, just not all ingesters though, not sure if that is needed too.

I have the following configured:
```yaml
structuredConfig:
    limits:
      # Accept Prometheus Replicas
      accept_ha_samples: true
      ha_cluster_label: cluster_name
      ha_replica_label: prometheus_replica
    distributor:
      ha_tracker:
        enable_ha_tracker: true
        kvstore:
          store: consul
          prefix: "ha-tracker/"
          consul:
            host: "mimir-consul-headless.obs.svc.cluster.local.:8500"
```

I might need some patients hehe.
