### DISCUSSION TITLE
setup in Kubernetes

### DISCUSSION THREAD

**Discussion by djmcint** [grafana/mimir#11641] [General]
HI all, 

So attempting to setup mimir using Helm. 
I'v created my custom.yaml  and running it 
`helm install mimir ocp_helm_charts/mimir-distributed -n my-namespace -f templates/small.yaml -f templates/custom.yaml`

the custom.yaml is like 

```
minio:
  enabled: false
rbac:
  create: false
  type: scc
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
mimir:
  structuredConfig:
    alertmanager_storage:
      backend: "s3"
      s3:
        access_key_id: "YYYYYYY"
        bucket_name: "s3-vm-mimialm-stg"
        endpoint: "s3-stg-xxxxxx.com"
        secret_access_key: "*****"
    blocks_storage:
      backend: s3
      s3:
        access_key_id: "xxxxxxxx"
        bucket_name: "s3-va-mimirblocks-stg"
        endpoint: "s3-stg-xxxxxxx.com"
        secret_access_key: "*******"
    ruler_storage:
      s3:
        bucket_name: s3-va-mimirrules-stg
        access_key_id: "xxxxxxx"
        endpoint: 3-stg-xxxxxxxx.com
        secret_access_key: "******"

nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: mimir.test.xxxxxxxxx.com
        paths:
          - path: /
            pathType: Prefix
    tls:    
```
After running get some pods that fails to start 
```
$ k get deployments
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
mimir-distributor               0/1     0            0           74m
mimir-nginx                     1/1     1            1           74m
mimir-querier                   0/1     0            0           74m
mimir-query-frontend            0/1     1            0           74m
mimir-query-scheduler           2/2     2            2           74m

$ k get pods
NAME                                             READY   STATUS             RESTARTS        AGE
mimir-alertmanager-0                             0/1     Pending            0               74m
mimir-nginx-757c8d459f-g9x8j                     1/1     Running            0               74m
mimir-query-frontend-69c6c9b888-bnl5x            0/1     CrashLoopBackOff   19 (104s ago)   74m
mimir-query-scheduler-5fd9b56448-9c7tj           1/1     Running            0               74m
mimir-query-scheduler-5fd9b56448-kxdhh           1/1     Running            0               74m
mimir-store-gateway-zone-b-0                     0/1     Pending            0               74m
```

I get a bunch of PVC that I would like to control and customize this in my custom.yaml 
```
NAME                                   STATUS    VOLUME          CAPACITY   ACCESS MODES   STORAGECLASS   AGE
storage-mimir-alertmanager-0           Pending                                                            46m
storage-mimir-compactor-0              Pending                                                            46m
storage-mimir-ingester-zone-a-0        Pending                                                            46m
storage-mimir-ingester-zone-b-0        Pending                                                            46m
storage-mimir-ingester-zone-c-0        Pending                                                            46m
storage-mimir-store-gateway-zone-a-0   Pending                                                            46m
storage-mimir-store-gateway-zone-b-0   Pending                                                            46m
storage-mimir-store-gateway-zone-c-0   Pending                                                            46m      
```   
The PVC pending certainly are impacting the pods 

My question is , How do I declare in my custom.yaml the persistentVolumes ?   Can somebody give me and example ? 
Help appreciated.   (Rookie on kube so sorry if this seems obvious to others)
