### DISCUSSION TITLE
Usage of Set Rule Group HTTP API

### DISCUSSION THREAD

**Discussion by balbirthomas** [grafana/mimir#1863] [Help and support] [answered]
Hi I am trying to upload an alert rule group to Mimir Alertmanager using its HTTP API.

When I use a `curl` command line such as
```
$ curl  -d @cpu_overuse.yaml -H "Content-Type: application/yaml" http://<ENDPOINT-IP>:9009/prometheus/config/v1/rules/anonymous
```
I see the following error
```
2022-05-17T09:37:23.283Z [mimir] level=error ts=2022-05-17T09:37:23.283026808Z caller=api.go:470 org_id=anonymous msg="unable to unmarshal rule group payload"
 err="yaml: mapping values are not allowed in this context"
 ```
 I infer this is coming from [here](https://github.com/grafana/mimir/blob/main/pkg/ruler/api.go#L470). I would like to write scripts using the HTTP API to control and configure Mimir. 
 
I do find that many other HTTP APIs do work as expected. I am however unable to make the [set-rule-group](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#set-rule-group) HTTP API work using the `curl` command line shown above. I am only using `curl` to learn and explore this API. As far as I can tell I am providing all requisite HTTP headers. I am not providing `X-Scope-OrgID` since I have disabled multi-tenancy. 

 I can confirm `mimirtool` does work when used to upload the very same rule group file. Also I have checked the same [rule group file](https://github.com/grafana/mimir/files/8707247/cpu_overuse.txt) using `mimirtool` `lint`, `check` and `prepare`, all of which passed. 
 
 Could this be a bug or am I missing something ?

**Comment by pracucci** [comment, marked as answer]
Does it work if you substitute `-d` with `--data-binary` to your curl command? Reason is that `-d` doesn't preserve carriage returns and newlines.

_We mention it in https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#set-alertmanager-configuration: if it fixes your issue, we should mention it for https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#set-rule-group too._

**Reply by balbirthomas** [reply]
I did try this. It does not work with `--data-binary` either. The error message in Mimir logs are
```
2022-05-17T11:10:13.907Z [mimir] level=error ts=2022-05-17T11:10:13.907306162Z caller=api.go:479 org_id=anonymous msg="unable to validate rule group payload" err="invalid rules config: rule group name must not be empty"
```
The response returned by the HTTP request is
```
$ curl --data-binary "@cpu_overuse.yaml" -H "Content-Type: application/yaml" http://<ENDPOINT-IP>:9009/prometheus/config/v1/rules/anonymous
invalid rules config: rule group name must not be empty
```

I am using the `--data-binary` option when using `curl` to upload an Alertmanager configuration and that does work as expected. 

I did also use `promtool` to check the rule group file (linked above). That also passed after I removed the `namespace` attribute which `promtool` does not recognize.

**Reply by pracucci** [reply]
> invalid rules config: rule group name must not be empty

This looks a different issue. Can I see the content of the rules `.yaml` file?

**Reply by balbirthomas** [reply]
I am pasting it below and also [linking it here](https://github.com/grafana/mimir/files/8707931/cpu_overuse.txt)
```
namespace: anonymous
groups:
    - name: cpuoveruse
      rules:
        - alert: cpu_over_use
          expr: 'process_cpu_seconds_total > 10'
          labels:
            severity: Low
          annotations:
            description: '{{ $labels.instance }} of job {{ $labels.job }} has used too much CPU.'
            summary: Instance {{ $labels.instance }} CPU over use
```
(A pointless alert rule only for testing and learning).

**Reply by pracucci** [reply]
I think I understood the issue. The API you're calling allows you to create 1 rule group, not namespace (which is a set of groups). So the actual content of the file you upload should be:

```
name: cpuoveruse
rules:
  - alert: cpu_over_use
    expr: 'process_cpu_seconds_total > 10'
    labels:
      severity: Low
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has used too much CPU.'
      summary: Instance {{ $labels.instance }} CPU over use
```
