### DISCUSSION TITLE
Too Many Requests: ingestion rate limit (50000) exceeded while adding 500 samples

### DISCUSSION THREAD

**Discussion by miladjahandideh** [grafana/mimir#2081] [Help and support] [answered]
Which Parameter should I increase?

Too Many Requests: ingestion rate limit (**50000**) exceeded while adding **500** samples and 0 metadata

my config:

```YAML
mimir:
  config: |
    multitenancy_enabled: false

    limits:
      max_label_names_per_series: 200
      max_global_series_per_user: 1000000000
      ingestion_burst_size: 200000
      ingestion_rate: 150000
      max_global_series_per_metric: 200000000
  
```

Log of Prometheus Pod

```
ts=2022-06-11T07:20:37.778Z caller=dedupe.go:112 component=remote level=error remote_name=130066 url=http://XXX:8080/api/v1/push msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 429 Too Many Requests: ingestion rate limit (50000) exceeded while adding 500 samples and 0 metadata"
```

And Also Alert

```
Description: Prometheus monitoring/prometheus-kube-prometheus-stack-prometheus-0 failed to send 16.5% of the samples to 2f0a43:http://grafana-mimir-XXX:8080/api/v1/push

```
