### DISCUSSION TITLE
Ingesters cannot connect to S3 storage - Compactor can

### DISCUSSION THREAD

**Discussion by Andysimcoe** [grafana/mimir#2135] [Help and support]
I'm using 2.1.0, running in AWS ECS cluster, the EC2 instances have an IAM role attached which allows both listing of the bucket and all actions on any objects. 

If I upload a file from the host to the bucket, the compactor discovers this as a user and proceeds to create a directory with that name and uploads the file bucket-index.json.gz.  This at least confirms the IAM role is fine and in theory the config is too. 

The exact same configuration (Mimir conf is on a shared EFS and mounted as a volume for all containers) doesn't work for  ingesters, the logs for the ingester:

`level=warn ts=2022-06-19T18:58:27.064578882Z caller=sanity_check.go:116 msg="Unable to successfully connect to configured object storage (will retry)" err="blocks storage: unable to successfully send a request to object storage: Get \"https://mimir-bucket.s3.dualstack.us-east-1.amazonaws.com/sanity-check-at-startup\": context deadline exceeded"`

The storage config:

```
blocks_storage:
  backend: s3
  s3:
    endpoint: s3.us-east-1.amazonaws.com
    region: us-east-1
    bucket_name: mimir-bucket
    insecure: false
    signature_version: v4
    http:
      insecure_skip_verify: true
    sse:
      type: "SSE-S3"
```

It seems strange to me the compactor doesn't have a problem but the ingesters never pass the sanity check. Is there a step I should be doing? From what I can tell from other posts no, that should be it.
