### DISCUSSION TITLE
Issues using mimir.structuredConfig to override values

### DISCUSSION THREAD

**Discussion by jgutschon** [grafana/mimir#2214] [Help and support] [answered]
I am working on installing the mimir-distributed helm chart into our Kubernetes cluster with ArgoCD, and I am attempting to use an S3 bucket for blocks_storage. So far, I have mostly successfully deployed the project, however all querier, compactor, ingester, and store-gateway pods are failing and have an error message with:
`no s3 endpoint in config file`

I am currently trying to use `mimir.structuredConfig` to set the extra config values, but none of the fields that have been supplied in my `values.yaml` can be seen in the Secret resource created in `mimir-config.yaml`. As far as I can tell, the "mimir.calculatedConfig" template should be picking this up when it runs the helm templating [here](https://github.com/grafana/mimir/blob/e11ac855ba074308735271208931c20bc2ce0445/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L99), but that doesn't seem to be the case.

The first bit of my `values.yaml` for the parent chart is as follows:

```yaml
---
mimir-distributed:
  fullnameOverride: "mimir"

  mimir:
    structuredConfig:
      multitenancy_enabled: true
      ingester:
        zone_awareness_enabled: true
      frontend:
        parallelize_shardable_queries: true
      store_gateway:
        zone_awareness_enabled: true
      blocks_storage:
        backend: s3
```

I am also setting additional values using the helm parameters in the Argo application spec as follows:

```yaml
parameters:
  - name: "mimir-distributed.serviceAccount.name"
    value: "mimir-{{ .Values.stack }}"
  - name: "mimir-distributed.serviceAccount.annotations.\
          eks\\.amazonaws\\.com/role-arn"
    value: "arn:aws:iam::{{ .Values.awsAccountId }}:role\
           /mimir-{{ .Values.stack }}"
  - name: "mimir-distributed.mimir.structuredConfig.blocks_storage.s3.endpoint"
    value: "s3.{{ .Values.clusterRegion }}.amazonaws.com"
  - name: "mimir-distributed.mimir.structuredConfig.blocks_storage.s3.region"
    value: "{{ .Values.clusterRegion }}"
  - name: "mimir-distributed.mimir.structuredConfig.blocks_storage.s3.bucket_name"
    value: "mimir-tsdb-{{ .Values.stack }}"
```

None of the values listed under the `structuredConfig` field can be seen in the Kubernetes Secret when reading it with:
`kubectl get secret -n infra-mimir mimir-config -o jsonpath="{.data.mimir\.yaml}" | base64 -D`, either from `values.yaml` or from the values set in the helm parameters.

I'm not sure if there is something I'm missing on my end but the templating here doesn't seem to merge `mimir.structuredConfig` with the templated `mimir.config`.

Any help would be greatly appreciated here.
