### DISCUSSION TITLE
Different retention period by tenant

### DISCUSSION THREAD

**Discussion by Mojito2110** [grafana/mimir#2371] [Help and support] [answered]
Hello folks

good jobs for mimir;

Is it possible to configure  different retention period for each tenant ? 
tenant-a retention : 3 months
tenant-b retention : 1 year

If it s possible how can we do that ?

**Comment by pstibrany** [comment, marked as answer]
Hello,

yes, this is definitely possible by using "runtime configuration". For example you can put this into your runtime configuration file:

```
overrides:
    "tenant-a":
        compactor_blocks_retention_period: 12w
    "tenant-b":
        compactor_blocks_retention_period: 1y
```

We cannot use `3m` for 3 months, because `m` is used for minutes. We can only use `y` for years, `w` for weeks or `d` for days.

https://grafana.com/docs/mimir/latest/operators-guide/configuring/about-runtime-configuration/
