### DISCUSSION TITLE
I need advice on how to use S3 as storage for Mimir!

### DISCUSSION THREAD

**Discussion by k-saito0107** [grafana/mimir#2473] [Help and support] [answered]
I would like to use S3 as storage for Mimir. So I rewrote the "demo.yaml" from the [official page](https://grafana.com/docs/mimir/latest/operators-guide/getting-started/) as follows and tried to set up S3 as storage, but I could not get Mimir to work. I would appreciate it if someone could give me some advice.
```
multitenancy_enabled: false

blocks_storage:
  backend: s3
  s3:
    endpoint: s3.ap-northeast-1.amazonaws.com
    region: ap-northeast-1
    bucket_name: hoge
    insecure: true
  tsdb:
    dir: /data/tsdb
  bucket_store:
    sync_dir: /data/tsdb-sync

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler_storage:
  backend: s3
  s3:
    endpoint: s3.ap-northeast-1.amazonaws.com
    region: ap-northeast-1
    bucket_name: hoge
    insecure: true

server:
  http_listen_port: 9009
  log_level: error

store_gateway:
  sharding_ring:
    replication_factor: 1
```
