### DISCUSSION TITLE
Grafana Dashboard showing No Data, GCS Bucket has no Data

### DISCUSSION THREAD

**Discussion by luvpreetsingh** [grafana/mimir#2604] [Help and support] [answered]
I have created a separate kubernetes cluster where I have launched prometheus, grafana and mimir using helm. I have used GCS bucket as object storage. Every pod is running fine but the GCS bucket does not have any file or folder in it. The grafana dashboard for mimir writes and mimir reads is also empty. There is no error in any of the pods and I am getting confused now. So, please help me figure out what am I doing wrong here? I will explain my setup below.

Here is prometheus helm values file,

```
server:

  global:
    scrape_interval: 1m
    scrape_timeout: 30s
    evaluation_interval: 1m
    external_labels:
      cluster: monitoring-cluster

  extraFlags:
    - web.enable-lifecycle
    - web.enable-remote-write-receiver

  remoteWrite:
    - url: http://mimir-nginx/api/v1/push
      remote_timeout: 30s
      follow_redirects: true
      headers:
        X-Scope-OrgID: monitoring-cluster

  persistentVolume:
    size: 120Gi

  statefulSet:
    enabled: true

  retention: "1d"
```

Here is my mimir helm values file

```
# this is the mimir config
mimir:
  config: |
    activity_tracker:
      filepath: /data/metrics-activity.log
    blocks_storage:
      backend: gcs
      bucket_store:
        sync_dir: /data/tsdb-sync
      gcs:
        bucket_name: my-gcp-mimir-tsdb
      tsdb:
        dir: /data/tsdb
    compactor:
      data_dir: /data
    frontend:
      align_queries_with_step: true
      log_queries_longer_than: 10s
    frontend_worker:
      frontend_address: mimir-query-frontend-headless.monitoring.svc:9095
    ingester:
      ring:
        final_sleep: 0s
        num_tokens: 512
        unregister_on_shutdown: false
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      max_label_names_per_series: 1000
      max_global_series_per_user: 0
      max_global_series_per_metric: 0
      ingestion_rate: 1000000
      ingestion_burst_size: 2000000
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - mimir-gossip-ring
    runtime_config:
      file: /var/mimir/runtime.yaml
    server:
      grpc_server_max_concurrent_streams: 1000

minio:
  enabled: false

# don't need alertmanager initially
alertmanager:
  enabled: false

# don't need ruler initially
ruler:
  enabled: false

ingester:
  resources:
    requests:
      cpu: 300m
      memory: 512Mi

  # need high disk space for ingester as it stores the samples on disk
  persistentVolume:
    size: 64Gi

  extraVolumes:
    - name: gcp-creds
      secret:
        secretName: gcp-credentials

  extraVolumeMounts:
    - name: gcp-creds
      mountPath: /var/secrets/google
      readOnly: true

  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/secrets/google/gcp-credentials.json"

store_gateway:
  # need high disk space for ingester as it stores fetches the blocks from bucket and stores on the disk
  persistentVolume:
    size: 64Gi

  extraVolumes:
    - name: gcp-creds
      secret:
        secretName: gcp-credentials

  extraVolumeMounts:
    - name: gcp-creds
      mountPath: /var/secrets/google
      readOnly: true

  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/secrets/google/gcp-credentials.json"

compactor:
  # need high disk space as it keeps and combines all the blocks
  persistentVolume:
    size: 64Gi

  extraVolumes:
    - name: gcp-creds
      secret:
        secretName: gcp-credentials

  extraVolumeMounts:
    - name: gcp-creds
      mountPath: /var/secrets/google
      readOnly: true

  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/secrets/google/gcp-credentials.json"

querier:
  replicas: 2

  resources:
    requests:
      cpu: 300m
      memory: 256Mi

query_frontend:
  replicas: 1

  resources:
    requests:
      cpu: 300m
      memory: 256Mi
```

There is no helm value file for grafana, I have just launched it as it.

Here is the status of everything running.

```
$ kubectl get pods -n monitoring
NAME                                            READY   STATUS    RESTARTS   AGE
grafana-85c95778cd-6pqms                        1/1     Running   0          14h
mimir-compactor-0                               1/1     Running   0          28m
mimir-distributor-5b9db4b6c4-crcsv              1/1     Running   0          28m
mimir-ingester-0                                1/1     Running   0          25m
mimir-ingester-1                                1/1     Running   0          26m
mimir-ingester-2                                1/1     Running   0          28m
mimir-nginx-546f7444d9-6tztn                    1/1     Running   0          12h
mimir-overrides-exporter-78b48cbbb-gt2t2        1/1     Running   0          28m
mimir-querier-79d6b7bffc-kbvx4                  1/1     Running   0          28m
mimir-querier-79d6b7bffc-pxhzl                  1/1     Running   0          27m
mimir-query-frontend-7bd69454fd-bqmkf           1/1     Running   0          28m
mimir-store-gateway-0                           1/1     Running   0          28m
prometheus-kube-state-metrics-77ddf69b4-9qk96   1/1     Running   0          24h
prometheus-node-exporter-4r5hm                  1/1     Running   0          14h
prometheus-node-exporter-spgll                  1/1     Running   0          14h
prometheus-server-0                             2/2     Running   0          14h
```

Everything is running perfectly fine but when I connect grafana to mimir, I get the dashboards showing No Data.

Prometheus is pushing data to mimir and dashboard is also rightly connected to the mimir datasource. I can tell because I see nginx logs. Not going to post all the logs but here it is,
```
10.64.3.17 - - [30/Jul/2022:08:41:40 +0000]  200 "POST /api/v1/push HTTP/1.1" 0 "-" "Prometheus/2.36.2" "-"
10.64.3.17 - - [30/Jul/2022:08:41:41 +0000]  200 "POST /api/v1/push HTTP/1.1" 0 "-" "Prometheus/2.36.2" "-"
10.64.3.17 - - [30/Jul/2022:08:41:46 +0000]  200 "POST /api/v1/push HTTP/1.1" 0 "-" "Prometheus/2.36.2" "-"
10.64.2.1 - - [30/Jul/2022:08:41:49 +0000]  200 "GET / HTTP/1.1" 2 "-" "kube-probe/1.22" "-"
10.64.2.27 - - [30/Jul/2022:08:41:55 +0000]  200 "POST /prometheus/api/v1/query HTTP/1.1" 63 "-" "Grafana/9.0.4" "-"
10.64.2.27 - - [30/Jul/2022:08:41:55 +0000]  200 "POST /prometheus/api/v1/query HTTP/1.1" 63 "-" "Grafana/9.0.4" "-"
10.64.2.27 - - [30/Jul/2022:08:41:55 +0000]  200 "POST /prometheus/api/v1/query HTTP/1.1" 63 "-" "Grafana/9.0.4" "-"
10.64.2.27 - - [30/Jul/2022:08:41:55 +0000]  200 "POST /prometheus/api/v1/query HTTP/1.1" 63 "-" "Grafana/9.0.4" "-"
```

Here are the last few logs from prometheus server,
```
ts=2022-07-30T08:01:37.675Z caller=dedupe.go:112 component=remote level=info remote_name=09f060 url=http://mimir-nginx/api/v1/push msg="Remote storage resharding" from=1 to=2
ts=2022-07-30T08:01:47.675Z caller=dedupe.go:112 component=remote level=info remote_name=09f060 url=http://mimir-nginx/api/v1/push msg="Remote storage resharding" from=2 to=1
```

So, what am I lacking here? Am I doing anything wrong here? Why is this setup not working?

**Comment by pracucci** [comment, marked as answer]
> Every pod is running fine but the GCS bucket does not have any file or folder in it.

Keep in mind a new Mimir cluster takes about 3 hours before the first blocks are uploaded to the bucket (more recent data only queried from ingesters). I'm mentioning it since I don't know how long Mimir was running.

> The grafana dashboard for mimir writes and mimir reads is also empty.

You configured Prometheus with:
```
      headers:
        X-Scope-OrgID: monitoring-cluster
```

This means Prometheus is remote writing with the tenant ID `monitoring-cluster`. When querying back from Mimir you need to inject the same HTTP header, to "authenticate" as `monitoring-cluster`. Have you configured this HTTP header in the Grafana datasource?

**Reply by luvpreetsingh** [reply]
> Keep in mind a new Mimir cluster takes about 3 hours before the first blocks are uploaded to the bucket

Yes, data in bucket started appearing.

> When querying back from Mimir you need to inject the same HTTP header, to "authenticate" as monitoring-cluster. Have you configured this HTTP header in the Grafana datasource?

Oh [like this?](https://github.com/grafana/mimir/blob/main/docs/sources/tutorials/play-with-grafana-mimir/config/grafana-provisioning-datasources.yaml#L12) 
I hadn't done this but after reading your answer I just did and I am still getting No Data.

<img width="718" alt="Screenshot 2022-08-01 at 3 42 30 PM" src="https://user-images.githubusercontent.com/23127804/182126691-fac391cd-bd58-4442-ba30-852065784e64.png">


<br>

Also, why does it say Ruler API enabled when I have disabled Ruler?
<img width="750" alt="Screenshot 2022-08-01 at 3 39 30 PM" src="https://user-images.githubusercontent.com/23127804/182126198-2a25bb05-24de-4be2-ac57-1deb67728eea.png">


Thanks.

**Reply by pracucci** [reply]
> I hadn't done this but after reading your answer I just did and I am still getting No Data.

If your Mimir cluster has multi-tenancy enabled, then the tenant ID used for querying metrics must be equal to the one used to write the metrics. So, if multi-tenancy was enabled, not setting the correct `X-Scope-OrgID` header in Grafana was a source of issue.

Question: is multi-tenancy enabled in your Mimir cluster? Multi-tenancy is enabled by default in Mimir. In the Helm chart it was disabled by default in version before 3.0.0, while the Helm chart 3.0.0 has enabled multi-tenancy by default ([see changelog](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/CHANGELOG.md#300)). Which version are you using?

> Also, why does it say Ruler API enabled when I have disabled Ruler?

I think it's a bug of how the `/api/v1/status/buildinfo` API endpoint works in Mimir. You disabled the ruler deployment, but Mimir doesn't know it. Mimir just looks at the config, and ruler API is enabled by default in the config. This is something we should improve in the `/api/v1/status/buildinfo` endpoint.

**Reply by pracucci** [reply]
>> Also, why does it say Ruler API enabled when I have disabled Ruler?
> I think it's a bug of how the /api/v1/status/buildinfo API endpoint works in Mimir

I created an issue to keep track of it: https://github.com/grafana/mimir/issues/2612

However, this is **unrelated** from the issue you're experiencing (empty query results).

**Reply by luvpreetsingh** [reply]
@pracucci I am using helm chart 3.0.0.
```
$ helm list -n monitoring
NAME      	NAMESPACE 	REVISION	UPDATED                             	STATUS  	CHART                  	APP VERSION
grafana   	monitoring	1       	2022-07-29 23:53:45.440197 +0530 IST	deployed	grafana-6.32.9         	9.0.4
mimir     	monitoring	5       	2022-08-02 14:13:38.073995 +0530 IST	deployed	mimir-distributed-3.0.0	2.2.0
prometheus	monitoring	3       	2022-07-30 13:09:07.563779 +0530 IST	deployed	prometheus-15.11.0
```

But how do I explicitly turn on multi-tenancy? I am on [this page](https://grafana.com/docs/mimir/latest/operators-guide/configuring/reference-configuration-parameters/#configuration-parameters) and there is a flag for `multitenancy_enabled`.

I have added that flag in my mimir.yaml, here

```
mimir:
  config: |
    multitenancy_enabled: true
    ... # rest of the config
```

I upgraded the helm release but I am still getting no data. Am I tweaking things at the wrong place?

**Reply by pracucci** [reply]
_Let me ping someone working on Helm._

**Reply by krajorama** [reply]
As @pracucci says, multi tenancy is enabled by default because the helm chart doesn't set it and it is the default as you pointed out in our docs. You did set it correctly explicitly in `mimir.config`. (Note: you can set your customizations in `mimir.structuredConfig` also, without having to copy the whole `mimir.config` , see [Upgrade the Grafana Mimir Helm chart from version 2.1 to 3.0](https://grafana.com/docs/mimir/latest/operators-guide/deploying-grafana-mimir/upgrade-helm-chart-2.1-to-3.0/)  , there's going to be proper documentation on this soon, PR pending).

We've tested multi tenancy with both Minio and GCS, it should work. If you see data in GCS, please double check that header you're setting in Grafana matches the tenant name "monitoring-cluster"

**Reply by luvpreetsingh** [reply]
@pracucci @krajorama I had a suspicion if even the mimir data was even being written to mimir?

I might be right there.


I just tried to create a new dashboard and tried to query metrics other than the mimir ones. Check the screenshot attached.
<img width="1022" alt="Screenshot 2022-08-04 at 11 37 16 AM" src="https://user-images.githubusercontent.com/23127804/182775213-fef6cf50-fe16-4f72-8297-cd1231317929.png">


The data is appearing here. So, my setup is correct.

Is there any flag I need to enable mimir monitoring? Why is the mimir Writes/Reads/Queries data not coming?

**Reply by luvpreetsingh** [reply]
When I type `cortex` in the query builder, it doesn't autocomplete and doesn't show anything. So I think that means that no cortex metrics are there in mimir.
<img width="984" alt="Screenshot 2022-08-04 at 12 01 24 PM" src="https://user-images.githubusercontent.com/23127804/182779074-b6c8fc12-5ea9-4e72-94b9-b91f6b58641a.png">

**Reply by pracucci** [reply]
> I had a suspicion if even the mimir data was even being written to mimir?

You need to configure Prometheus to scrape Mimir metrics and then remote write these metrics back to Mimir. You already configured Prometheus to remote write metrics to Mimir, so what's probably missing is enabling Prometheus to scrape Mimir metrics.

Since you're using the Mimir Helm chart, I would recommend following our getting started guide ([see doc](https://grafana.com/docs/mimir/latest/operators-guide/deploying-grafana-mimir/getting-started-helm-charts/). In particular, we have a section about [metamonitoring](https://grafana.com/docs/mimir/latest/operators-guide/deploying-grafana-mimir/getting-started-helm-charts/#set-up-metamonitoring), which is basically about scraping Mimir metrics.

**Reply by luvpreetsingh** [reply]
Thanks. I did that.

Here is the config I added
```
# enable monitoring of mimir
metaMonitoring:
  serviceMonitor:
    enabled: true
  grafanaAgent:
    enabled: true
    installOperator: true
    metrics:
      additionalRemoteWriteConfigs:
        - url: "http://mimir-nginx/api/v1/push"
          headers:
            X-Scope-OrgID: "monitoring-cluster"
```

But still many panels are empty. Anything else I need to configure in ingester or distributo?

<img width="1380" alt="Screenshot 2022-08-04 at 2 28 49 PM" src="https://user-images.githubusercontent.com/23127804/182807446-9bae93a5-bbaf-4280-a747-08f2ce58baaf.png">
