### DISCUSSION TITLE
Docs: Enable Alertmanager

### DISCUSSION THREAD

**Discussion by seaurching** [grafana/mimir#2698] [Help and support] [answered]
Hi, everyone:
  I need some help for initialization alertmanager with mimir. I download the version 2.2.0 and start it without anything change in configuration, while I access the alertmanager through browser with http://xxxx:8080/alertmanager, tips 404 ```not found```
Here is the start command:
```
./mirror
```
![image](https://user-images.githubusercontent.com/7349963/184092251-da24861f-62f3-4ea5-934e-927138892d9e.png)

![image](https://user-images.githubusercontent.com/7349963/184092190-d9c7d19f-a1a7-448d-a05b-45ea8466bffe.png)

**Comment by pracucci** [comment]
The [alertmanager component is optional ](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/alertmanager/) and not started by default. If you want to run it as part of your monolithic deployment you should just run mimir with the command `./mimir -target=all,alertmanager`.

That being said, keep in mind the next step to use the Alertmanager is to configure it for your tenant. Please checkout [this documentation](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/alertmanager/#multi-tenancy) to learn more how to do it, and feel free to ask any question you may have after reading it.

**Reply by seaurching** [reply]
> The [alertmanager component is optional ](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/alertmanager/) and not started by default. If you want to run it as part of your monolithic deployment you should just run mimir with the command `./mimir -target=all,alertmanager`.
> 
> That being said, keep in mind the next step to use the Alertmanager is to configure it for your tenant. Please checkout [this documentation](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/alertmanager/#multi-tenancy) to learn more how to do it, and feel free to ask any question you may have after reading it.

When I load alertmanager.yaml with command:
```
 ./mimirtool alertmanager load ../alertmanager/alertmanager.yml --address=http://127.0.0.1:8080/ --id alertmanager

cat ../alertmanager/alertmanager.yml
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:8060/dingtalk/webhook1/send'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

```
I can open http://xxxx:8080/alertmanager ui,and soon show message on mimir
```
level=info ts=2022-08-15T03:52:16.595113827Z caller=multitenant.go:1048 component=MultiTenantAlertmanager msg="deleted local directory for user" dir=/home/soft/mimir/data/alertmanager/alerts user=alerts
```

**Reply by pracucci** [reply]
Can you share your Mimir configuration, redacted of any sensitive information (but possibly keeping the filepath settings), please? I've the feeling there's a misconfiguration somewhere, but I don't have enough data to offer you a proper guidance.

**Reply by seaurching** [reply]
@pracucci  The configure is bellow
```
target: all,alertmanager
multitenancy_enabled: true
api:
    skip_label_name_validation_header_enabled: false
    alertmanager_http_prefix: /alertmanager
    prometheus_http_prefix: /prometheus
server:
    http_listen_network: tcp
    http_listen_port: 8080
    http_listen_conn_limit: 0
    grpc_listen_network: tcp
    grpc_listen_port: 9095
    log_format: logfmt
    log_level: info
distributor:
    ring:
        kvstore:
            store: memberlist
        instance_id: WEB-06
        instance_interface_names: ["br0"]
ingester:
    ring:
        kvstore:
            store: memberlist
        replication_factor: 1
        instance_id: WEB-06
        instance_interface_names: ["br0"]
limits:
    request_rate: 0
    request_burst_size: 0
    ingestion_rate: 500000
    ingestion_burst_size: 500000
    accept_ha_samples: false
    ha_max_clusters: 0
    max_label_name_length: 1024
    max_label_value_length: 2048
    max_label_names_per_series: 30
    max_metadata_length: 1024
    creation_grace_period: 10m
    enforce_metadata_metric_name: true
    ingestion_tenant_shard_size: 0
    max_global_series_per_user: 150000
    max_global_series_per_metric: 20000
    max_global_metadata_per_user: 0
    max_global_metadata_per_metric: 0
    max_global_exemplars_per_user: 0
    out_of_order_time_window: 0s
    max_fetched_chunks_per_query: 2000000
    max_fetched_series_per_query: 0
    max_fetched_chunk_bytes_per_query: 0
    max_query_lookback: 0s
    max_query_length: 0s
    max_query_parallelism: 14
    max_labels_query_length: 0s
    max_cache_freshness: 1m
    max_queriers_per_tenant: 0
    query_sharding_total_shards: 16
    query_sharding_max_sharded_queries: 128
    cardinality_analysis_enabled: false
    label_names_and_values_results_max_size_bytes: 419430400
    label_values_max_cardinality_label_names_per_request: 100
    ruler_evaluation_delay_duration: 0s
    ruler_tenant_shard_size: 0
    ruler_max_rules_per_rule_group: 20
    ruler_max_rule_groups_per_tenant: 70
    store_gateway_tenant_shard_size: 0
    compactor_blocks_retention_period: 0s
    compactor_split_and_merge_shards: 0
    compactor_split_groups: 1
    compactor_tenant_shard_size: 0
    compactor_block_upload_enabled: false

blocks_storage:
    backend: filesystem
    filesystem:
        dir: /home/soft/mimir/data/tsdb
    bucket_store:
        sync_dir: /home/soft/mimir/data/tsdb-sync
        sync_interval: 15m0s
        bucket_index:
            enabled: true
            update_on_error_interval: 1m0s
            idle_timeout: 1h0m0s
    tsdb:
        dir: /home/soft/mimir/data/tsdb
compactor:
    data_dir: /home/soft/mimir/data/compactor
    sharding_ring:
        kvstore:
            store: memberlist
        instance_id: WEB-06
        instance_interface_names: ["br0"]
store_gateway:
    sharding_ring:
        kvstore:
            store: memberlist
        replication_factor: 1
        instance_id: WEB-06
        instance_interface_names: ["br0"]
tenant_federation:
    enabled: false
activity_tracker:
    filepath: /home/soft/mimir/log/metrics-activity.log
    max_entries: 1024
ruler:
    external_url: "http://10.0.66.20:8080/ruler"
    ruler_client:
        tls_enabled: false
    rule_path: /home/soft/mimir/data/ruler/
    alertmanager_url: "http://127.0.0.1:8080/alertmanager"
    ring:
        kvstore:
            store: memberlist
        instance_id: WEB-06
        instance_interface_names: ["br0"]
    enable_api: true
    query_stats_enabled: true
    query_frontend:
        address: "10.0.66.20"
    tenant_federation:
        enabled: false
ruler_storage:
    backend: filesystem
    filesystem:
        dir: /home/soft/mimir/data/rules
runtime_config:
    period: 10s
memberlist:
    node_name: "web06"
    randomize_node_name: true
    stream_timeout: 10s
    retransmit_factor: 4
    pull_push_interval: 30s
    gossip_interval: 200ms
    gossip_nodes: 3
    gossip_to_dead_nodes_time: 30s
    dead_node_reclaim_time: 0s
    compression_enabled: true
    advertise_addr: ""
    advertise_port: 7946
    min_join_backoff: 1s
    max_join_backoff: 1m0s
    max_join_retries: 10
    #join_members: ["localhost"]
    abort_if_cluster_join_fails: false
    rejoin_interval: 5s
    bind_port: 7946
alertmanager:
    data_dir: /home/soft/mimir/data/alertmanager/
    retention: 120h0m0s
    external_url: http://10.0.66.20:8080/alertmanager
    sharding_ring:
      instance_interface_names: ["br0"]

      replication_factor: 1
    enable_api: true
alertmanager_storage:
    backend: filesystem
    filesystem:
        dir: /home/soft/mimir/data/alertmanager/alertmanager
```

**Reply by pracucci** [reply]
I think the alertmanager's `data_dir: /home/soft/mimir/data/alertmanager/` conflicts with the alertmanager storage's `dir: /home/soft/mimir/data/alertmanager/alertmanager`, because `/home/soft/mimir/data/alertmanager/alertmanager` is a sub-directory of `/home/soft/mimir/data/alertmanager/`.

Try to configure them as:
```
alertmanager:
    data_dir: /home/soft/mimir/data/alertmanager/
    // rest of the config...
    
alertmanager_storage:
    backend: filesystem
    filesystem:
        dir: /home/soft/mimir/data/alertmanager-storage
```

**Reply by pracucci** [reply]
_I'm working to add a validation in Mimir code, to make sure this sort of misconfiguration is detected at startup._

**Reply by pracucci** [reply]
I've opened a PR to introduce a sanity check on the configured filesystem directories: https://github.com/grafana/mimir/pull/2828

**Reply by seaurching** [reply]
@pracucci  When set  "manage alerts via alerting ui" to true, set the alertmanager data source to mimir(The prometheus datasource is mimir which collect data from official prometheus by setting remote-write to mimir). Mimir-alertmanager set "recevie grafana alerts" to true. I cann't receive any alert message
![image](https://user-images.githubusercontent.com/7349963/186573412-e9c74159-dbd3-4827-9018-d08276dd34c9.png)
![image](https://user-images.githubusercontent.com/7349963/186573530-04b8aeb7-ba03-4495-9d6a-2cc29f5a3d2e.png)
### Grafana Alerting
![image](https://user-images.githubusercontent.com/7349963/186573685-c79f93ed-4cc5-460c-8ccf-30ce9eee8e0d.png)
### contact points
![image](https://user-images.githubusercontent.com/7349963/186573781-68f31183-a833-4640-920c-66e89b429119.png)
### notification policies
![image](https://user-images.githubusercontent.com/7349963/186573823-0fd168a5-9ffc-41b4-acea-f8b259d7d488.png)

**Reply by seaurching** [reply]
@pracucci @jpkrohling  Loading prometheus alert rules,the health status is error. Please see image. Where Can I specify the address and port
![image](https://user-images.githubusercontent.com/7349963/186590166-be683950-9dca-4ee1-9249-acc1583c8058.png)

**Reply by pracucci** [reply]
> I cann't receive any alert message

I can see a firing alert in one of the screenshots, so I guess (1) the alerting rule is correctly evaluated by the Mimir ruler and (2) the firing rule is correctly notified to the Mimir Alertmanager, but for some reason the notification is not successfully delivered from the Mimir Alertmanager to your contact points. I can see you configured two webhooks in the contact points. If there's any error notifying these contact points, you should find related errors in the Mimir Alertmanager logs. Could you check it, please?

**Reply by seaurching** [reply]
@pracucci I have see another issue. When alerts appeared, the alert will not sendout. See this :
![image](https://user-images.githubusercontent.com/7349963/186833189-a286f96d-8aeb-4459-965d-b025fbf20bf5.png)

#### Notificate Policy is match all labels
![image](https://user-images.githubusercontent.com/7349963/186833385-3e05f587-1d06-422e-be6b-70f137866c44.png)

**Reply by pracucci** [reply]
The Grafana Alerting UI is just an UI over the Mimir Alertmanager APIs. Can we try to remove the Grafana Alerting UI from the stack for a moment, and focus on the Mimir Alertmanager until we get it working? Then we re-add the Grafana Alerting UI in the stack.

You can configure the Mimir Alertmanager using the `mimirtool` command line tool ([binaries available here](https://github.com/grafana/mimir/releases/tag/mimir-2.2.0)). The `mimirtool` [documentation is here](https://grafana.com/docs/mimir/latest/operators-guide/tools/mimirtool/#alertmanager).

### How to interact with Mimir Alertmanager

```
# Show the current Alertmanager config for your tenant (replace "<tenant>" with your tenant ID)
./mimirtool alertmanager get --address=http://10.0.66.20:8080 --id="<tenant>"

# Load a new Alertmanager config from a .yaml file (replace "<tenant>" with your tenant ID)
./mimirtool alertmanager load --address=http://10.0.66.20:8080 --id="<tenant>" ./alertmanager-config.yaml
```

The `alertmanager-config.yaml` is a file containing the Prometheus Alertmanager configuration ([specs here](https://prometheus.io/docs/alerting/latest/configuration/)). However, since you already configured it using the Grafana Alertmanager UI, the command `mimirtool alertmanager get` should show the current configuration and you can start mangling from it.

The Mimir Alertmanager UI is exposed at `http://10.0.66.20:8080/alertmanager`. You can open it to see which alerts are firing.

### The workflow I suggest

1. Run `mimirtool alertmanager get` to get the current Alertmanager config for your tenant (if you can, share it with us, redacting sensitive information). Make sure everything is configured as you expect.
1. Open `http://10.0.66.20:8080/alertmanager` and ensure some alert is firing.
1. If at least an alert is firing, then we expect such alert to get notified through the configured Alertmanager receiver(s). Since you're not receiving the notification(s), then either the Alertmanager config is incorrect or there should be some errors in your Alertmanager logs with details about the issue.

**Reply by seaurching** [reply]
I have already load alertmanger.yaml with mimirtool.  Please see #2856 . When I restarted mimir, will send one of alert message. For unprocessed alert  waiting for half an hour still no message received
Alertmanager's config:
```
global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
    enable_http2: true
route:
  receiver: webhook
  group_by:
  - alertname
  continue: false
  group_wait: 30s
  group_interval: 35s
  repeat_interval: 40s
inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal:
  - alertname
  - dev
  - instance
receivers:
- name: webhook
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
      enable_http2: true
    url: http://10.0.66.20:8060/dingtalk/webhook1/send
    max_alerts: 5
templates: []
```
