### DISCUSSION TITLE
Add Alertmanager datasource tips

### DISCUSSION THREAD

**Discussion by seaurching** [grafana/mimir#2741] [Help and support] [answered]
I started mimir by command:
```
./mimir --target=all,alertmanager
```
And the service's status is running
![image](https://user-images.githubusercontent.com/7349963/185015316-5cc092dd-8234-4eab-a633-417664d869b0.png)

Alertmanager's Ring Status is:
![image](https://user-images.githubusercontent.com/7349963/185015571-0ffeaa2c-d8eb-4e94-a368-d611f0ef20e0.png)

I load the alertmanager.conf with mimirtool, show configs,like this
```
./Downloads/mimirtool-darwin-amd64 alertmanager get --id=miyamoto.local --address=http://127.0.0.1:8080
 cat alertmanager.conf
global:
  resolve_timeout: 2m
  smtp_smarthost: 'qiyx1@qq.com:587'
  smtp_from: 'mail_from@qq.com'
  smtp_require_tls: true
  smtp_auth_username: 'mail@qq.com'
  smtp_auth_password: 'password'
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: team-prometheus-mails
receivers:
- name: 'team-prometheus-mails'
  email_configs:
  - to: 'qiyongxiao@elion.com.cn'
---
# template
{{ define "wechat.down.message" }}
{{ range .Alerts }}
= Instance or Sevice Down =
Level: {{ .Labels.severity }}
Type: {{ .Labels.alertname }}
Host: {{ .Labels.instance }}
Service: {{ .Labels.name }}
Details: {{ .Annotations.description }}
----------------------------
{{ end }}
{{ end }}
```
#### When add an datasource for alertmanager, show this message. For more information see below
<img width="877" alt="WX20220816" src="https://user-images.githubusercontent.com/7349963/185014964-c3ab5ad1-fb7e-44bc-bdf4-30d4155bbf38.png">

```
It looks like you have chosen a Mimir or Cortex implementation, but detected a Prometheus endpoint. Please update implementation selection and try again.
```
