### DISCUSSION TITLE
Getting error trying to upload to S3 compatible bucket (Netapp)

### DISCUSSION THREAD

**Discussion by tannerrs** [grafana/mimir#2797] [Help and support]
After configuring the Mimir helm chart to use S3, the ingester logs show this error:

level=error ts=2022-08-22T12:58:07.232034936Z caller=shipper.go:160 user=anonymous msg="shipping failed" block=01GB2KBY3AR8EA6DAB6DRPNJ61 err="upload index: upload file /data/tsdb/anonymous/01GB2KBY3AR8EA6DAB6DRPNJ61/index as 01GB2KBY3AR8EA6DAB6DRPNJ61/index: upload s3 object: The Content-MD5 you specified is not valid."

When trying the mimirtools bucket validation, I get the exact same message.

My config for storage is:

```
    blocks_storage:
      backend: s3
      bucket_store:
        chunks_cache:
          backend: memcached
          memcached:
            addresses: <memcache address>
            timeout: 450ms
        index_cache:
          backend: memcached
          memcached:
            addresses: <memcach address>
        metadata_cache:
          backend: memcached
          memcached:
            addresses: <memcache address>
        sync_dir: /data/tsdb-sync
      s3:
        endpoint: <endpoint>
        bucket_name: dev-mimir-tsdb
        access_key_id: < access ID>
        secret_access_key: <access secret>
        insecure: true        
      tsdb:
        dir: /data/tsdb
```

Any help appreciated.
