### DISCUSSION TITLE
AlertManager datasource is added but not appearing while adding alerts

### DISCUSSION THREAD

**Discussion by luvpreetsingh** [grafana/mimir#2826] [Help and support] [answered]
Hi, hope everyone is doing fine

I have added mimir and mimir alertmanager datasources in grafana with the below config,

```
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: mimir
        type: prometheus
        url: http://mimir-nginx/prometheus
        isDefault: true
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          alertmanagerUid: 'alertmanager'
        secureJsonData:
          httpHeaderValue1: monitoring-cluster
      - name: mimir-alertmanager
        type: alertmanager
        uid: alertmanager
        access: proxy
        url: http://mimir-nginx/
        editable: true
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          implementation: cortex
        secureJsonData:
          httpHeaderValue1: monitoring-cluster
```

The datasources are working fine. I have dashboards which are consuming mimir datasource and they are working fine..

But when I go to grafana alerts sections to add alerts, it says no datasource found, please check the below screenshot

<img width="982" alt="Screenshot 2022-08-24 at 3 12 09 PM" src="https://user-images.githubusercontent.com/23127804/186386549-9961c91d-9f9c-4fdd-a4f0-f998734dcb67.png">

Also, `Managing Alerts via Alerting UI` option is enabled

Have I done anything wrong while provisioning the datasources? Or Am I missing something or doing it totally wrong? Why is it not able to find the datasource?
