### DISCUSSION TITLE
Access to s3 bucket

### DISCUSSION THREAD

**Discussion by rrusso1982** [grafana/mimir#2853] [Help and support] [answered]
#### Describe the bug
I am attempting to deploy grafana mimir on an amazon EKS cluster with s3 as it's backend storage.  It have the necessary buckets created, EKS cluster running, IRSA enabled on the cluster, IAM roles deployed, and service account setup with the role annotation attached.  

When I start up mimir using helm I am getting this error from any pod attempting to use the s3 storage
```
level=warn ts=2022-08-25T21:48:07.218854521Z caller=sanity_check.go:116 msg="Unable to successfully connect to configured object storage (will retry)" err="2 errors: blocks storage: unable to successfully send a request to object storage: Access Denied; ruler storage: unable to successfully send a request to object storage: Access Denied"
```
Hoping into the pod shows that the pod is showing the correct aws role but the software is still unable to connect even though the permissions to the bucket are currently set to s3:*.

Any assistance with this would be appreciated

#### Expected behavior

I expect the pods to be able to connect to their object storage correctly.

#### Environment

- Infrastructure: AWS EKS and s3 object storage
- Deployment tool: helm

#### Additional Context
Here is a snippet of my configuration
```
mimir:
  structuredConfig:
    blocks_storage:
      backend: s3
      s3:
        bucket_name: mimir-us-east-2
        endpoint: s3.us-east-2.amazonaws.com
        region: us-east-2
        sse:
          type: "SSE-S3"
```
