### DISCUSSION TITLE
prometheus remote write multi-zone replica issues

### DISCUSSION THREAD

**Discussion by jgutschon** [grafana/mimir#2931] [Help and support] [answered]
Hello, I am working on deploying version 3.0.0 of the mimir helm chart and I'm currently having some issues getting Prometheus remote write to work properly. When prometheus attempts to send metrics to mimir (through the `mimir-nginx` service), the distributor pods log this error repeatedly:

```
msg="POST /api/v1/push (500) 1.999681ms Response: \"at least 2 live replicas required across different availability zones, could only find 1\\n\" ws: false; Connection: close; Content-Encoding: snappy; Content-Length: 43721; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.32.1; X-Prometheus-Remote-Write-Version: 0.1.0; X-Scope-Orgid: anonymous;
```

This same error is also visible in the prometheus logs in the response to the remote write request. I'm not sure which component it's referring to here, but I've verified that both the ingester and distributor services are being replicated across two availability zones. 

My helm `values.yaml` configuration is as follows:

<details>

```
---
mimir-distributed:
  fullnameOverride: "mimir"

  mimir:
    structuredConfig:
      multitenancy_enabled: false

      limits:
        accept_ha_samples: true

      distributor:
        ha_tracker:
          enable_ha_tracker: true
          kvstore:
            store: inmemory

      ingester:
        ring:
          zone_awareness_enabled: true

      store_gateway:
        sharding_ring:
          zone_awareness_enabled: true

      frontend:
        parallelize_shardable_queries: true

  nginx:
    ingress:
      tls: {}

  rbac:
    create: false

  compactor:
    replicas: 1

  distributor:
    replicas: 4

  ingester:
    replicas: 4
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: target
                  operator: In
                  values:
                    - ingester
            topologyKey: topology.kubernetes.io/zone

  chunks-cache:
    enabled: true
    replicas: 2

  index-cache:
    enabled: true
    replicas: 3

  metadata-cache:
    enabled: true
    replicas: 1

  results-cache:
    enabled: true
    replicas: 1

  minio:
    enabled: false

  overrides_exporter:
    enabled: false

  alertmanager:
    enabled: false

  ruler:
    enabled: false

  store_gateway:
    replicas: 1
```

</details>

Any help would be greatly appreciated, thanks!
