### DISCUSSION TITLE
How to configure querying data form Long Term Storage

### DISCUSSION THREAD

**Discussion by mdvaliyullah** [grafana/mimir#3015] [Help and support] [answered]
what are the configuration required for querying data form LongTerm Storage in grafana

**Comment by pracucci** [comment]
Mimir queries metrics in the long-term storage by default. Metrics data up to 12h old is required from ingesters, while older data is queries from the long-term storage (object storage) via the Mimir store-gateway component.

Does this answer your question? If not, could you share more details, please?

**Reply by mdvaliyullah** [reply]
I am setting up mimir locally in monolithic mode connecting to blob storage, I am able to send the data to long term storage but unable to see the data in grafana. below is my configuration details.. am i missing something?

```yaml
limits:
  enforce_metadata_metric_name: true
common:
  storage:
    backend: ..* #(you can ignore the config for storage)
     
blocks_storage:
  storage_prefix: blocks
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
    sync_interval: 15m
  tsdb:
    dir: /tmp/mimir/tsdb
    flush_blocks_on_shutdown: true
    ship_interval: 1m

frontend:
  align_queries_with_step: true
  log_queries_longer_than: 10s
  split_queries_by_interval: 24h
  cache_results: true
  results_cache:
    backend: "memcached"
    memcached:
      addresses: "127.0.0.1:11211"    

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist
  cleanup_interval: 15m    

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

server:
  http_listen_port: 9009
  log_level: info

store_gateway:
  sharding_ring:
    replication_factor: 1
```
