### DISCUSSION TITLE
Import prometheus alert rules through remote_write

### DISCUSSION THREAD

**Discussion by Ferrany1** [grafana/mimir#3115] [Help and support]
Hello, is it somehow possible to get rules and show them in Grafana Alerting. Currently I'm only receiving metrics, but can't see any rules for a specific Prometheus node

**Comment by pracucci** [comment]
You have two options to evaluate rules when using Mimir:
1. Configure rules evaluation in Prometheus, and remote write the recording rule series to Mimir
2. Run rules evaluation directly in Mimir

## Configure rules evaluation in Prometheus

When you decide to keep your rules evaluation in Prometheus, both recording and alerting rules will be evaluated by Prometheus. The series generated by the recording rules will be remote written to Mimir (like any other series) and thus will be queryable via Mimir.

In this scenario, you would have to configure Grafana Alerting to use the Prometheus Alertmanager as datasource. It should allow you to view the alerts, but **not** edit them (not supported by Prometheus Alertmanager).

## Run rules evaluation directly in Mimir

In this setup, you configure the recording and alerting rules evaluation directly in Mimir. The Mimir ruler component is responsible to evaluate your rules. Alerting notifications are sent by the [Mimir ruler](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/ruler/) to the [Mimir alertmanager](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/alertmanager/) (which is a superset of the Prometheus Alertmanager).

In this scenario, you would have to configure Grafana Alerting to use the Mimir Alertmanager as datasource. It will allow you both to view and edit / create the alerts, because the Mimir Alertmanager includes a set of API used by Grafana Alerting to manage your alerts configuration.

Does this answer your question?

**Reply by Ferrany1** [reply]
Unfortunately, I still couldn't  make it work as wanted. Alerts by themselves are working correct, but without adding prometheus directly as datasource I can't scrap any rules from Prometheus Alertmanager nor Mimir

**Reply by pracucci** [reply]
> but without adding prometheus directly as datasource I can't scrap any rules from Prometheus Alertmanager nor Mimir

Could you clarify it, please? Could you share more details about your setup?

**Reply by Ferrany1** [reply]
> > but without adding prometheus directly as datasource I can't scrap any rules from Prometheus Alertmanager nor Mimir
> 
> Could you clarify it, please? Could you share more details about your setup?

datasource.yaml
```
apiVersion: 1

datasources:
  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir-1:8080/prometheus
    editable: true
    isDefault: true
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'anonymous'

  - name: Mimir Alertmanager
    uid: alertmanager
    type: alertmanager
    access: proxy
    url: http://mimir-1:8080/alertmanager
    editable: true
    jsonData:
      implementation: prometheus
      httpHeaderName1: 'X-Scope-OrgID'
      alertmanagerUid: 'alertmanager'
    secureJsonData:
      httpHeaderValue1: 'anonymous'

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3101
    jsonData:
      maxLines: 1000
```

prometheus.yml
```
global:
  scrape_interval:     20s
  evaluation_interval: 20s
  external_labels:
    host: monitoring-host
    cluster: monitoring-host
    namespace: monitoring-host

remote_write:
  - url: http://mimir-1:8080/api/v1/push

alerting:
  alertmanagers:
    - scheme: http
      path_prefix: /alertmanager
      static_configs:
        - targets:
            - "mimir-1:8080"

rule_files:
  - '/etc/prometheus/alerts/global_rules.yaml'

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: mimir
    static_configs:
      - targets: [ 'mimir-1:8080' ]
        labels:
          pod: 'mimir-1'
      - targets: [ 'mimir-2:8080' ]
        labels:
          pod: 'mimir-2'
      - targets: [ 'mimir-3:8080' ]
        labels:
          pod: 'mimir-3'
```

mimir.yml
```
target: all,alertmanager,overrides-exporter,ruler

multitenancy_enabled: false
no_auth_tenant: "anonymous"

memberlist:
  join_members: [ mimir-1, mimir-2, mimir-3 ]

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /mimir/tsdb-sync
  filesystem:
    dir: /mimir/data/tsdb
  tsdb:
    dir: /mimir/tsdb

ruler:
  rule_path: /mimir/ruler
  alertmanager_url: http://127.0.0.1:8080/alertmanager

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /mimir/fs_rules
  local:
    directory: /etc/mimir/rules

alertmanager:
  data_dir: /mimir/alertmanager
  fallback_config_file: /etc/mimir/alertmanager.yml
  external_url: http://127.0.0.1:8080/alertmanager

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /mimir/alerts

server:
  log_level: warn
  http_listen_port: 8080
```

<img width="2426" alt="contact_points" src="https://user-images.githubusercontent.com/62963660/194055080-a9524607-0075-4e5f-b613-318221621cab.png">
<img width="2426" alt="rules" src="https://user-images.githubusercontent.com/62963660/194055099-b81b21f8-84ca-4ac4-86af-9acbebce90a3.png">
