### DISCUSSION TITLE
Mimir blocks retention

### DISCUSSION THREAD

**Discussion by Ferrany1** [grafana/mimir#3242] [Help and support]
Hello, unfortunately I didn't manage to find a way to enable retention for blocks, currently I'm running everything on a low disk space machine and until stalling want to enable retention for example older than 3 days.

I've tried to use, but unfortunately it didn't help since as I understand my blocks yet doesn't escape to compactor (±7day series collection)
```
limits:
  compactor_blocks_retention_period: 72h
```
  
mimir.yaml
 ```
target: all,alertmanager,overrides-exporter,ruler

multitenancy_enabled: false
no_auth_tenant: "anonymous"

memberlist:
  join_members: [ mimir-1, mimir-2 ]

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /mimir/tsdb-sync
  filesystem:
    dir: /mimir/data/tsdb
  tsdb:
    dir: /mimir/tsdb

limits:
  compactor_blocks_retention_period: 72h

server:
  log_level: warn
  http_listen_port: 8080
```
