### DISCUSSION TITLE
Configuring Mimir Ruler with Grafana

### DISCUSSION THREAD

**Discussion by spyder007** [grafana/mimir#3270] [Help and support] [answered]
I have been running into some issues trying to manage Alerts in Mimir using Grafana.

Overall, my configuration is pretty simple:  I'm using the `mimir-distributed` Helm chart (as a subchart) with the following values:

``` yaml
global:
  extraEnvFrom:
    - secretRef:
        name: mimir-minio-secret
minio: 
  enabled: false
alertmanager:
  enabled: true
  persistentVolume:
    storageClass: nfs-client
ingester:
  persistentVolume:
    storageClass: nfs-client
store_gateway:
  persistentVolume:
    storageClass: nfs-client
compactor:
  persistentVolume:
    storageClass: nfs-client
ruler:
  enabled: true
nginx:
  ingress:
    enabled: true
    hosts:
      - host: "https://my.host.net"
        paths:
          - path: /
            pathType: Prefix
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/service-upstream: "true"
    tls: []
mimir:
  structuredConfig:
    alertmanager_storage:
      backend: s3
      s3:
        access_key_id: ${MINIO_USERNAME}
        bucket_name: mimir-ruler
        endpoint: minio.local:9000
        insecure: true
        secret_access_key: ${MINIO_PASSWORD}
    blocks_storage:
      s3:
        access_key_id: ${MINIO_USERNAME}
        bucket_name: mimir-tsdb
        endpoint: minio.local:9000
        insecure: true
        secret_access_key: ${MINIO_PASSWORD}
    ruler_storage:
      backend: s3
      s3:
        access_key_id: ${MINIO_USERNAME}
        bucket_name: mimir-ruler
        endpoint: minio.local:9000
        insecure: true
        secret_access_key: ${MINIO_PASSWORD}
    limits:
      max_global_series_per_user: 0
      ingestion_rate: 40000
      ingestion_burst_size: 100000
      out_of_order_time_window: 
metaMonitoring:
  serviceMonitor:
    enabled: true
    interval: 1m
    scrapeTimeout: 30s

````

With this configuration, Mimir works fine, and it's a remote-write target for my other Prometheus instances (one in each cluster).

Within Grafana, I have configured a Prometheus datasource using this url: `https://my.host.net/prometheus`

Again, I can get data out of Mimir and my dashboards seem to work fine.  However, when I go to manage alerts in Grafana (using `Alerting -> + new alert rule`, I cannot choose my Mimir data source for a `Mimir or Loki alert`.  My Loki data source shows, but not Mimir.

![image](https://user-images.githubusercontent.com/4701399/196984459-a298b200-1f60-47d7-b5f7-b6eda9229a4d.png)

The ruler components seems to be running correctly:  calls to `https://my.host.net/prometheus/api/v1/rules` return success with no data (since I don't have groups setup yet)

``` json
{
"status":"success",
"data":{
  "groups":[]
},
"errorType":"",
"error":""}
```
and `https://my.host.net/ruler/ring` returns an active instance with a good heartbeat.

I had originally thought that I needed to change the `prometheus_http_prefix`, as suggested by [This page](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-mimir-loki-managed-rule/), but, according to @dimitarvdimitrov, that documentation is out of date and the default should work.

I know, with the alert manager, I had to pre-configure my `anonymous` tenant in order to add the Alert Manager instance as a Grafana data source.  Is this a case where i need to pre-configure the ruler for the anonymous tenant as well?

**Comment by pracucci** [comment, marked as answer]
> Again, I can get data out of Mimir and my dashboards seem to work fine. However, when I go to manage alerts in Grafana (using Alerting -> + new alert rule, I cannot choose my Mimir data source for a Mimir or Loki alert. My Loki data source shows, but not Mimir.

Which Grafana version are you running? Can you try with the latest stable, if you're not running it yet? There were some issues in "old" Grafana versions.

**Reply by spyder007** [reply]
Sorry, should have included those details:

Grafana v9.2.0
Mimir v2.3.1

I updated my `image.tag` to 9.2.1, but I'm still seeing the same behavior.

**Reply by dimitarvdimitrov** [reply]
I tried reproducing this, but with no luck. It works ok for me. I've got two ideas:

1. The datasource should have a setting called "Manage alerts via Alerting UI." Can you make sure that it is selected?

2. Can you open the network tab in your browser and then refresh the page for new alerts groups (`Alerting -> + new alert rule`), and see if any requests return a HTTP 404 or an HTTP 5xx? IIRC all requests should succeed and grafana should correctly discover that the prometheus datasource is a Mimir.

**Reply by spyder007** [reply]
@dimitarvdimitrov Opening the dev tools in chrome, I found the issue:
![image](https://user-images.githubusercontent.com/4701399/197258648-ab07e94d-7435-4635-8691-3da6e22a9da6.png)
Grafana lives on a different subdomain than mimir (grafana.mydomain.local vs mimir.mydomain.local).  Most of the functionality works fine, but Chrome doesn't like this setup.

Oddly enough, I opened the site in MS Edge and my Mimir database shows, so it looks to be browser specific.

So, my next question is, where is it appropriate to set that Access-Control-Allow-Origin header?  I'm running mimir-distributed in Kubernetes behind nginx-ingress, so I have two layers of ingress:

Cluster Ingress -> Mimir Ingress -> appropriate mimir services

And, outside of the cluster, I have a small nginx reverse proxy to forward traffic around.  I tried adding a header to the Mimir Ingress config, but that didn't seem to have an effect.

**Reply by dimitarvdimitrov** [reply]
You  can try configuring the nginx that comes with the mimir-distributed chart.

The directive is something like `add_header Access-Control-Allow-Origin grafana.mydomain.local` ([SO](https://stackoverflow.com/a/16308982/5683949)). it would be best if you do not copy the `nginx.nginxConfig.file` helm value because it's very long and we update it not-so-rarely. It's possible to provide a string that's injected in the default value of `nginx.nginxConfig.file`. It's called `nginx.nginxConfig.httpSnippet`. So maybe something like

```yaml
nginx:
  nginxConfig:
    httpSnippet: |
      add_header Access-Control-Allow-Origin grafana.mydomain.local
```

There's also `nginx.nginxConfig.serverSnippet`, which gets in side the server block inside the http in the nginx config. Not sure which will be a better place for this.
