### DISCUSSION TITLE
Alert Manager not found in both sources

### DISCUSSION THREAD

**Discussion by dpewsey** [grafana/mimir#3297] [Help and support]
Hello,

trying to set up an alert for mimir  
```
cat redis_up.yaml
namespace: SRE
groups:
    - name: Redis
      rules:
        - alert: redis status
          expr: redis_up{job="redis_exporter_targets"} == 1
          for: 1m
          labels:
            severity: warning
            type: redis
          annotations:
            description: A Redis instance is down\n VALUE= {{ $value }}
            summary: A redis instance down (instance {[ $labels.instance }})
```
`mimirtool rules load redis_up.yaml` uploads the job
however the alert doesn't show up via the alertmanager ui

 I also get this when trying to verify
```
mimirtool alerts verify
INFO[0000] alert found that was not in both sources      alertname="redis status" state="map[__name__:ALERTS alertname:redis status alertstate:firing instance:redis://api-redis.service.consul:6382 job:redis_exporter_targets severity:warning type:redis]"
```

How does one create an alert to match? Is there another place the rules need to be created?
