### DISCUSSION TITLE
Mimir cannot connect on S3

### DISCUSSION THREAD

**Discussion by lesomora** [grafana/mimir#3322] [Help and support]
I've finished my mimir deployment on my baremetal kubernetes cluster. 

I'm using MinIO with s3 service provide. I tried created a new bucket named mimir and I did that setup on mimir.conf 

```yaml
blocks_storage:
      backend: s3
      s3:
        endpoint: minio.gru.lwmon.com.br
        bucket_name: mimir
        access_key_id: user
        secret_access_key: pass
        insecure: true
```

But when Mimir Ingester will write on S3 I got this error: 

```
check exists: stat s3 object: Access Denied.
```

My Nginx return to me this:  "HEAD /mimir/anonymous/01GGD9EB4JRVZ5BJGWXK25RVHS/meta.json HTTP/1.1" 403 0 "-" "MinIO (linux; amd64) minio-go/v7.0.16 thanos-ingester/ (go1.17.8)"

The mimir access s3 with bucket-name.domain or I can force domain/bucket my cluster only access that way -->>> domain/bucket

Can someone help me ?
