### DISCUSSION TITLE
Replicate instances over multiple hosts

### DISCUSSION THREAD

**Discussion by dimitar-ivanov-93** [grafana/mimir#3359] [Help and support] [answered]
Hi guys, I am currently trying to set up the Mimir instances from the demo that replicate data between each other. But instead of setting the containers on one host, I am trying to run them from different EC2 instances for higher availability in case of single instance downtime. The current configuration is as follows:

The docker-compose.yml part from the first EC2 instance:
```
  mimir-1:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yml"]
    hostname: mimir-1
    volumes:
      - ./config/mimir.yml:/etc/mimir.yml
      - ./config/alertmanager-fallback-config.yml:/etc/alertmanager-fallback-config.yml
      - mimir-1-data:/data
  ```
The mimir.yml config from the first machine:
```
target: all,alertmanager,overrides-exporter

# Configure Mimir to use Minio as object storage backend.
common:
  storage:
    backend: s3
    s3:
      endpoint: --
      region: --
      access_key_id: --
      secret_access_key: --
      insecure: --
      bucket_name: --

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

# Use memberlist, a gossip-based protocol, to enable the 3 Mimir replicas to communicate
memberlist:
  join_members: [ IP_OF_FIRST_HOST, IP_OF_SECOND_HOST ]

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://127.0.0.1:8080/alertmanager
  ring:
    # Quickly detect unhealthy rulers to speed up the tutorial.
    heartbeat_period: 2s
    heartbeat_timeout: 10s

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/alertmanager-fallback-config.yml
  external_url: http://localhost:9009/alertmanager

server:
  log_level: warn
  ```
Respectively, the compose part from the second EC2 instance:
  ```
    mimir-2:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yml"]
    hostname: mimir-2
    volumes:
      - ./config/mimir.yml:/etc/mimir.yml
      - ./config/alertmanager-fallback-config.yml:/etc/alertmanager-fallback-config.yml
      - mimir-2-data:/data
```
The mimir.yml on the second EC2 instance is identical to the first.

As expected, the joined instances were 0 due to the port not being exposed, which led to the following warning:
```
containers-mimir-2-1     | level=warn ts=2022-11-02T11:19:42.216948225Z caller=memberlist_client.go:563 msg="memberlist fast-join finished" joined_nodes=0 elapsed_time=20.001673025s
containers-mimir-2-1     | level=warn ts=2022-11-02T11:20:02.217984797Z caller=memberlist_client.go:598 msg="joining memberlist cluster: failed to reach any nodes" retries=0 err="2 errors occurred:\n\t* Failed to join IP_ADDRESS:7946: dial tcp IP_ADDRESS:7946: i/o timeout\n\t* Failed to join IP_ADDRESS:7946: dial tcp IP_ADDRESS:7946: i/o timeout\n\n"
```
After that I have linked port 7946 from the container to the same port on the host in hope that it will be able to reach eachother, but I had no luck.
Added block to both compose files:
```
    ports:
      - 8080:8080
      - 7946:7946
```
When making a request to the hosts' port 7946, I get the following error from mimir:
```
containers-mimir-2-1     | level=error ts=2022-11-02T11:53:49.502969966Z caller=tcp_transport.go:318 component="memberlist TCPTransport" msg="unknown message type" msgType=G remote=IP_ADDRESS:59631
```
I have looked into Mirroring requests to a second Mimir cluster using Envoy Proxy, but I would very much like to avoid that and keep the high-availability setup with replication of instances, just on separate hosts.

Any suggestions are welcome!
