### DISCUSSION TITLE
problems installing mimir using helmchart

### DISCUSSION THREAD

**Discussion by sersanherr** [grafana/mimir#3451] [Help and support]
Hi, we are having some problems using the mimir-distributed helmchart.

We are getting this error when trying to install

**Error: parse error at (mimir-distributed/templates/validate.yaml:38): unclosed action**

We are using the all the default values.yaml except **minio disabled** and we are pasing our storage configuration as:

```
mimir:
  structuredConfig: 
    common:
      storage:
        backend: s3
        s3:
          endpoint: xxxxxxxxxxxx
          access_key_id: xxxxxxxxxxxxxxxxxxxxxx
          secret_access_key: xxxxxxxxxxxxxxxxxxxxxxxx
          insecure: true
          bucket_name: xxxxxxxxxxxxxxxxx

    blocks_storage:
      storage_prefix: blocks 
```

Seems to be a problem with the templating expressions in the validate.yaml.
Any idea on what the problem may be?

helm version
version.BuildInfo{Version:"v3.6.2+5.el8", GitCommit:"eb607dd4f123eaedab662cef21008d177f2c3426", GitTreeState:"clean", GoVersion:"go1.15.13"}
