### DISCUSSION TITLE
when i rollout restart ingester, distributor occur error log,at least 2 live replicas required, could only find 1 - unhealthy

### DISCUSSION THREAD

**Discussion by kwenzh** [grafana/mimir#3560] [Help and support]
when i rollout restart ingester,  distributor occur error log, 
```
level=warn ts=2022-11-29T12:20:03.883116232Z caller=logging.go:86 traceID=1d6b8feac433899f msg="POST /api/v1/push (500) 567.742µs Response: \"at least 2 live replicas required, could only find 1 - unhealthy instances: 10.244.158.7:9095\\n\" ws: false; Connection: close; Content-Encoding: snappy; Content-Length: 6220; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.26.1; X-Prometheus-Remote-Write-Version: 0.1.0; X-Scope-Orgid: anonymous; "

```

but no one pod ip is 10.244.158.7

![image](https://user-images.githubusercontent.com/38367518/204528347-733e69b8-3ed3-4ea7-8b52-aa2ce2238485.png)

some ingster starting log, ingester-14
```
level=info ts=2022-11-29T11:35:09.294367653Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5756 maxSegment=5769
level=info ts=2022-11-29T11:35:27.507504781Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5757 maxSegment=5769
level=info ts=2022-11-29T11:35:45.712193413Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5758 maxSegment=5769
level=info ts=2022-11-29T11:36:05.734217654Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5759 maxSegment=5769
level=info ts=2022-11-29T11:36:23.939091357Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5760 maxSegment=5769
level=info ts=2022-11-29T11:36:42.347255239Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5761 maxSegment=5769
level=info ts=2022-11-29T11:36:59.963055819Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5762 maxSegment=5769
level=info ts=2022-11-29T11:37:10.689662183Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5763 maxSegment=5769
level=info ts=2022-11-29T11:37:28.727453163Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5764 maxSegment=5769
level=info ts=2022-11-29T11:37:46.966350211Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5765 maxSegment=5769
level=info ts=2022-11-29T11:38:07.670661416Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5766 maxSegment=5769
level=info ts=2022-11-29T11:38:26.115827781Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5767 maxSegment=5769
level=info ts=2022-11-29T11:38:41.912058985Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5768 maxSegment=5769
level=info ts=2022-11-29T11:38:41.930956482Z caller=head.go:702 user=anonymous msg="WAL segment loaded" segment=5769 maxSegment=5769
level=info ts=2022-11-29T11:38:41.931025672Z caller=head.go:739 user=anonymous msg="WAL replay completed" checkpoint_replay_duration=29.379200278s wal_replay_duration=4m42.760356707s wbl_replay_duration=914ns total_replay_duration=5m13.235067745s
level=info ts=2022-11-29T11:38:58.624778613Z caller=db.go:1704 user=anonymous msg="Compactions disabled"
level=info ts=2022-11-29T11:38:58.624857004Z caller=ingester.go:1608 user=anonymous msg="Running compaction after WAL replay"
level=info ts=2022-11-29T11:38:58.67270908Z caller=ingester.go:1784 msg="successfully opened existing TSDBs"
level=info ts=2022-11-29T11:38:58.673004412Z caller=mimir.go:762 msg="Application started"
level=info ts=2022-11-29T11:38:58.712021471Z caller=lifecycler.go:612 msg="existing entry found in ring" state=ACTIVE tokens=512 ring=ingester

```

how distributor find the alive ingeser?  and keep Consistent state

**Comment by kwenzh** [comment]
https://grafana.com/docs/mimir/latest/operators-guide/architecture/memberlist-and-the-gossip-protocol/

**Reply by kwenzh** [reply]
use default memberlist

**Comment by pracucci** [comment]
_Sorry for the super late reply. This discussion slipped and I haven't noticed it. Sorry, again._

Could you share your Mimir configuration, please?

**Reply by kwenzh** [reply]
> _Sorry for the super late reply. This discussion slipped and I haven't noticed it. Sorry, again._
> 
> Could you share your Mimir configuration, please?

nothing  it is okay , this is mimir config
```
mimir.yaml: |
    activity_tracker:
      filepath: /data/metrics-activity.log
    alertmanager:
      data_dir: /data
      enable_api: true
      external_url: /alertmanager
    alertmanager_storage:
      backend: s3
      s3:
        access_key_id: xxxxxxxxxxxxxxx
        bucket_name: mimirxxxxxxxxxxxxx
        endpoint: xxxxxxxxxxxxxxxx:12001
        insecure: true
        secret_access_key: xxxxxxxxxxxx
    blocks_storage:
      backend: s3
      bucket_store:
        chunks_cache:
          backend: memcached
          memcached:
            addresses: dns+sdc-mimir-chunks-cache.mimir.svc:11211
            max_item_size: 5242880
            timeout: 450ms
        index_cache:
          backend: memcached
          memcached:
            addresses: dns+sdc-mimir-index-cache.mimir.svc:11211
            max_item_size: 5242880
        metadata_cache:
          backend: memcached
          memcached:
            addresses: dns+sdc-mimir-metadata-cache.mimir.svc:11211
            max_item_size: 5242880
        sync_dir: /data/tsdb-sync
      s3:
        access_key_id: HxxxxxxxxxxxxxxxxxxxxxPDR
        bucket_name: mimirxxxxxxxxxxxxxx
        endpoint: xxxxxxxxxxxxxxx:12001
        insecure: true
        secret_access_key: jxxxxxxxxxxxxxxxxxxGSkp
      tsdb:
        dir: /data/tsdb
    compactor:
      data_dir: /data
    frontend:
      align_queries_with_step: true
      cache_results: true
      log_queries_longer_than: 10s
      parallelize_shardable_queries: true
      results_cache:
        backend: memcached
        memcached:
          addresses: dns+sdc-mimir-results-cache.mimir.svc:11211
          max_item_size: 5242880
      scheduler_address: sdc-mimir-query-scheduler-headless.mimir.svc:9095
    frontend_worker:
      scheduler_address: sdc-mimir-query-scheduler-headless.mimir.svc:9095
    ingester:
      ring:
        replication_factor: 2
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    distributor:
      ha_tracker:
        enable_ha_tracker: true
        kvstore:
          store: etcd
          etcd:
            endpoints: ["sdc-mimir-etcd:2379"]
            username: "root"
            password: "xxxxxxxxxxxxx"
    limits:
      accept_ha_samples: true
      ha_cluster_label: prometheus_dc
      ha_replica_label: prometheus_replica

      ingestion_burst_size: 50000000
      ingestion_rate: 700000
      max_global_series_per_user: 1000000000
      max_label_names_per_series: 50
      max_query_parallelism: 224
      request_rate: 700000
      request_burst_size:  50000000
      out_of_order_time_window: 5m

    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - dns+sdc-mimir-gossip-ring.mimir.svc.cluster.local:7946
    querier:
      max_concurrent: 16
    query_scheduler:
      max_outstanding_requests_per_tenant: 1600
    ruler:
      alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.sdc-mimir-alertmanager-headless.mimir.svc.cluster.local/alertmanager
      enable_api: true
      rule_path: /data
    ruler_storage:
      backend: s3
      s3:
        access_key_id: xxxxxxxxxxxxxxxxx
        bucket_name: mimir-xxxxxxxxx
        endpoint: xxxxxxxxxxxx:12001
        insecure: true
        secret_access_key: xxxxxxxxxxxxxxxxxxxkp
    runtime_config:
      file: /var/mimir/runtime.yaml
    server:
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_connection_age: 2m
      grpc_server_max_connection_age_grace: 5m
      grpc_server_max_connection_idle: 1m
    store_gateway:
      sharding_ring:
        replication_factor: 2
        tokens_file_path: /data/tokens

```

**Reply by pracucci** [reply]
The issue is caused by `replication_factor: 2`. Currently, replication factor 2 is not fully supported and shouldn't be used. See https://github.com/grafana/mimir/issues/3844#issuecomment-1370568929 for more information.

**Reply by kwenzh** [reply]
> The issue is caused by `replication_factor: 2`. Currently, replication factor 2 is not fully supported and shouldn't be used. See [#3844 (comment)](https://github.com/grafana/mimir/issues/3844#issuecomment-1370568929) for more information.

default value is 3

**Reply by kwenzh** [reply]
> The issue is caused by `replication_factor: 2`. Currently, replication factor 2 is not fully supported and shouldn't be used. See [#3844 (comment)](https://github.com/grafana/mimir/issues/3844#issuecomment-1370568929) for more information.

but `unregister_on_shutdown` is false

**Reply by kwenzh** [reply]
modif config :
```

    ingester:
      ring:
        replication_factor: 3
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /data/tokens
        unregister_on_shutdown: true

```
