### DISCUSSION TITLE
Setting up Mimir with helm chart in AWS EKS cluster using S3 buckets, fails to use the k8s service account

### DISCUSSION THREAD

**Discussion by allan-bailey** [grafana/mimir#3986] [Help and support] [answered]
I've setup loki in a similar manner, but it uses the service account which allows it to use the proper IAM role for access to S3.

With Mimir (helm chart 4.0.1), it's complaining about missing "AWS Access Key".  So far I've found nothing in the docs about
why it's trying to use those.  They should default to "" or null.

**Comment by allan-bailey** [comment]
The actual message is:

`blocks storage: unable to successfully send a request to object storage: The AWS Access Key Id you provided does not exist in our records.`

**Comment by allan-bailey** [comment, marked as answer]
Solution was to disable minio.

**Comment by rafilkmp3** [comment]
Can you share your values.yaml? I haven't found an example of that

**Reply by allan-bailey** [reply]
The relevant part of the values.yaml for helm is just:
```
minio:
  enabled: false
```

The related part for setting up the S3 buckets looks like this:
```
mimir:
  enterprise:
    enabled: false

  graphite:
    enabled: false

  structuredConfig:
    limits:
      max_global_series_per_user: 20000000
      ingestion_rate: 200000
      ingestion_burst_size: 1000000
    ruler_storage:
      backend: s3
      s3:
        endpoint: s3.us-west-2.amazonaws.com
        region: us-west-2
        bucket_name: <prefix>-mimir-ruler
        insecure: false
    alertmanager_storage:
      backend: s3
      s3:
        endpoint: s3.us-west-2.amazonaws.com
        region: us-west-2
        bucket_name: <prefix>-mimir-alertmanager
        insecure: false
    blocks_storage:
      backend: s3
      s3:
        endpoint: s3.us-west-2.amazonaws.com
        region: us-west-2
        bucket_name: <prefix>-mimir-blocks
        insecure: false           

```
