### DISCUSSION TITLE
at least 2 live replicas required across different availability zones, could only find 1

### DISCUSSION THREAD

**Discussion by mdvaliyullah** [grafana/mimir#4005] [Help and support] [answered]
Running mimir in monolithic mode across 2 Data centres with replication factor 2, unable to push metrics to mimir getting the below error on mimir-proxy as shown below. Please advise

at least 2 live replicas required across different availability zones, could only find 1

```
target: all,overrides-exporter

server:
  log_level: info

distributor:
  pool:
    health_check_ingesters: true
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s  
    kvstore:
      store: memberlist

querier:
  lookback_delta: 1m
  query_store_after: 0s
  query_ingesters_within: 0s
  shuffle_sharding_ingesters_enabled: true

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    grpc_compression: gzip

ingester:  
  ring:
    final_sleep: 0s
    num_tokens: 512
    tokens_file_path: /data/tokens
    heartbeat_period: 2s
    heartbeat_timeout: 10s
    unregister_on_shutdown: true    
    kvstore:
      store: memberlist
    replication_factor: 2
    instance_availability_zone: "region-details"
    zone_awareness_enabled: true

limits:
  max_global_series_per_user: 0
  out_of_order_time_window: 30m
  compactor_block_upload_enabled: true
  
blocks_storage:
  storage_prefix: blocks
  bucket_store:
    sync_dir: /data/tmp/mimir/tsdb-sync
    sync_interval: 5m
    ignore_blocks_within: 0s
    metadata_cache:
      bucket_index_content_ttl: 1m
      tenants_list_ttl: 1m
      tenant_blocks_list_ttl: 1m
      metafile_doesnt_exist_ttl: 1m    
  tsdb:
    dir: /data/ingester
    flush_blocks_on_shutdown: true
    ship_interval: 1m

compactor:
  data_dir: /data/compactor
  sharding_ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s  
    kvstore:
      store: memberlist
  cleanup_interval: 5m   

store_gateway:
  sharding_ring:
    replication_factor: 2
    tokens_file_path: /data/tokens
    heartbeat_period: 2s
    heartbeat_timeout: 10s
    instance_availability_zone: "region-details"   
    zone_awareness_enabled: true 
    kvstore:
      store: memberlist     

ruler:
  rule_path: /data/ruler
  poll_interval: 2s  
  #alertmanager_url: http://127.0.0.1:8080/alertmanager
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s
    kvstore:
      store: memberlist

ruler_storage:
  storage_prefix: "ruler"

memberlist:
  join_members : [ host_members_details] 
```
