### DISCUSSION TITLE
Usage of Mimir http API and S3 default retention

### DISCUSSION THREAD

**Discussion by ofiry-tm** [grafana/mimir#4284] [Help and support]
I installed Mimir, and im sending data from Prometheus to Mimir via remote Write, and its working. 
I see the data in Grafana when I use Mimir as a datasource.
Im interested to use some of the API requests that is in this doc: https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/
But most of them gives me 404.
my mimir's nginx conf is simple:
```
mimir-distributed:
  nginx:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: <my-ingress-class>
      hosts:
        - host: <my-mimir-host>
          paths:
            - path: /
              pathType: Prefix
```

and when i send for example, this GET request: 
```
https://<my-mimir-host>/ready
```

I see in the nginx logs this error:

```
2023/02/23 12:22:51 [error] 11#11: *17673 open() "/etc/nginx/html/ready" failed (2: No such file or directory), client: <ip>, server: , request: "GET /ready HTTP/1.1", host: "<my-host>"
```
and I recieve a 404 from the mimir nginx.

so, I wanted to ask: do the default nginx configuration should route requests to all the Mimir components ?
or is it something i should configure?

Acoording to the API doc, I would expect the default nginx conf will route requests from the nginx to all other components, but i see thats not the case.

did I missed something? or I just need to explicitly configure the mimir nginx so that it will route requests to all the mimir components?

and one more question about the s3 storage,
I read that by default, there is no retention of the data that is being saved by mimir in s3,
but I clearly see that mimir delete files from the s3, 
how do you explain this ?
