### DISCUSSION TITLE
/ready endpoint always returning 503 in monolithic mode

### DISCUSSION THREAD

**Discussion by egarbi** [grafana/mimir#4416] [Help and support]
I set readiness within Kubernetes deployment to check for /ready endpoint for Mimir's pods.

Even on working nodes that are ingesting and storing data without issues this endpoint never comes up and always returns 503.
I have now set `/services` instead and it's working fine, but that's more of a workaround.

Can someone tell me how to properly set readiness for monolithic mode? I extracted these settings from the helm chart `mimir-distributed`, maybe the monolithic mode uses a diff approach? it doesn't seem to be the case after reading the docs.

This is the deployment I have tried in EKS
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mimir
    spec:
      spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mimir
                topologyKey: "topology.kubernetes.io/zone"
              weight: 100
      volumes:
        - name: mimir-config
          configMap:
            name: mimir-configmap
      containers:
        - name: mimir-container
          image: grafana/mimir:2.6.0
          args:
            - "-config.file=/etc/mimir/mimir.yml"
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 3
```
