### DISCUSSION TITLE
Gaps when displaying metrics in Grafana

### DISCUSSION THREAD

**Discussion by andreimiclea99** [grafana/mimir#4696] [Help and support] [answered]
I am trying Grafana Mimir as a POC for my current project.

I encountered a gap in the metrics, (on every grafana dashboards) when trying to display the metrics for the last 12 hours, the metrics for around 2 hours are missing.
The gap is continuously appearing only when I try to query the metrics for the last 12 hours, see the pictures below:

<img width="435" alt="mimirgap1" src="https://user-images.githubusercontent.com/44814444/230591623-69ebef26-ed0e-4dac-940c-f06137c28774.png">

another time, but the same issue:
<img width="443" alt="mimirgap2" src="https://user-images.githubusercontent.com/44814444/230591734-a5650478-746d-4a36-beb8-b1c199854873.png">

Even when querying the metrics for the last 7 days i still see the same issue:

<img width="743" alt="mimirgap3" src="https://user-images.githubusercontent.com/44814444/230592277-61f7143d-9a7e-4066-88df-acb2ff938e3e.png">

As you can see the problem is always there, the metrics are not lost but for some reason are not displaying properly.

I deployed the mimir-distributed helm chart and here are the configs:

```
   blocks_storage:
      backend: gcs
      bucket_store:
        sync_dir: /data/tsdb-sync
      gcs:
        bucket_name: ""
        service_account: ""
      tsdb:
        retention_period: 6h
        dir: /data/tsdb
    compactor:
      max_closing_blocks_concurrency: 2
      max_opening_blocks_concurrency: 4
      symbols_flushers_concurrency: 4
      data_dir: "/data"
      sharding_ring:
        wait_stability_min_duration: 1m
    frontend:
      parallelize_shardable_queries: false
      align_queries_with_step: true
      log_queries_longer_than: 10s
      max_outstanding_per_tenant: 4096
      split_queries_by_interval: 0
      scheduler_address: grafana-mimir-query-scheduler-headless.monitoring.svc:9095
    frontend_worker:
      grpc_client_config:
        max_send_msg_size: 419430400
      scheduler_address: grafana-mimir-query-scheduler-headless.monitoring.svc:9095
    distributor:
      ha_tracker:
        enable_ha_tracker: true
        kvstore:
          store: consul
          consul:
            host: http://consul-consul-expose-servers.monitoring.svc.cluster.local:8500
    ingester:
      ring:
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /data/tokens
        unregister_on_shutdown: true
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      accept_ha_samples: true
      ha_cluster_label: lh_cluster
      ha_replica_label: replica
      max_total_query_length: 1200h
      max_query_parallelism: 240
      max_cache_freshness: 10m
      max_label_names_per_series: 120
      max_global_series_per_user: 12000000
      ingestion_rate: 500000
      ingestion_burst_size: 10000000
      out_of_order_time_window: 480m
      compactor_blocks_retention_period: 336h
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - dns+grafana-mimir-gossip-ring.monitoring.svc.cluster.local:7946
    querier:
      max_concurrent: 2048
    query_scheduler:
      max_outstanding_requests_per_tenant: 4096
    server:
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_connection_age: 2m
      grpc_server_max_connection_age_grace: 5m
      grpc_server_max_connection_idle: 1m
      http_server_read_timeout: 3m
      http_server_write_timeout: 3m
```

There are memory issues in any of the components nor clear error logs in the mimir components.

Other meaningful information:

<img width="149" alt="in-mem-series" src="https://user-images.githubusercontent.com/44814444/230593305-be41d519-b3c7-4e39-a8b7-61499444d920.png"> 
<img width="224" alt="write-req" src="https://user-images.githubusercontent.com/44814444/230593323-b418f850-a3dc-4257-a1e9-9ff54e2a4766.png">
<img width="223" alt="read-request-sec" src="https://user-images.githubusercontent.com/44814444/230593336-45c7f30f-bd28-4420-8b79-dc86db683953.png">
<img width="678" alt="long-term" src="https://user-images.githubusercontent.com/44814444/230593345-9cc45820-207f-4df9-b31a-086f0dcb6b53.png">
<img width="887" alt="bucket" src="https://user-images.githubusercontent.com/44814444/230593607-d509ec45-c9c3-403a-aa90-1cef71b78e71.png">

I have tried to adjust the configs in different ways with no luck, in the begging I tried it without the query-scheduler, but the behaviour was the same.

Thank you.
```[tasklist]
```
