### DISCUSSION TITLE
All alarm message sented to by default root-policy

### DISCUSSION THREAD

**Discussion by seaurching** [grafana/mimir#4748] [Help and support]
#### Describe the bug
**我设置了匹配不同标签将告警发送到不同邮箱策略，可最终所有的告警信息都是从默认策略发出**
**I have been set the match label policy to send alert message to different email, but it always sent email by the default root policy**

Start Mimir (SHA or version)
![image](https://user-images.githubusercontent.com/7349963/232410069-50483772-a46a-4c3d-ae67-292b116baada.png)
#### Environment

- Infrastructure:
    Server on KVM
- Deployment tool
    systemd or service

#### Additional Context
![image](https://user-images.githubusercontent.com/7349963/232407424-d13fe585-d40b-436c-b775-8d1fbd6adc8e.png)
From abbove, I setted 3 match-lables plicy with 2 contact-point. While find a alert message that have label with `database: oracle` , the alert message was send by the default root-policy("运维",means operator engine). 
**从上面的图中所展示出来的，这里用2个报警组配置了三条match labels规则，最后一条上配置了3个label，分别是`database: redis`、`database: mysql`、`database: oracle`.
Is the 3 lables  is and not or? Like this:
**这三个label的匹配规则是"与"而不是"或"，就像下面这张图里面所展示的**
![image](https://user-images.githubusercontent.com/7349963/232435211-9cb725bb-667e-43f3-acbb-894eedd6c963.png)

This is the alertmanager config:
```json
{
  "template_files": {},
  "template_file_provenances": {},
  "alertmanager_config": {
    "global": {
      "resolve_timeout": "5m",
      "smtp_auth_password": "password",
      "smtp_auth_username": "syzf",
      "smtp_from": "syzf",
      "smtp_hello": "mimir",
      "smtp_require_tls": false,
      "smtp_smarthost": "smtp.exmail.qq.com:465"
    },
    "inhibit_rules": [
      {
        "equal": [
          "alertname",
          "dev",
          "instance"
        ],
        "source_match": {
          "severity": "critical"
        },
        "target_match": {
          "severity": "warning"
        }
      },
      {
        "equal": [
          "alertname",
          "instance"
        ],
        "source_match": {
          "severity": "panic"
        },
        "target_match": {
          "severity": "warning"
        }
      }
    ],
    "mute_time_intervals": [],
    "receivers": [
      {
        "name": "webhook",
        "webhook_configs": [
          {
            "send_resolved": true,
            "url": "http://10.0.66.20:8060/dingtalk/webhook1/send"
          }
        ]
      },
      {
        "email_configs": [
          {
            "require_tls": false,
            "send_resolved": true,
            "to": "cxp@elion.org"
          }
        ],
        "name": "运维"
      },
      {
        "email_configs": [
          {
            "require_tls": false,
            "send_resolved": true,
            "to": "vujf@elion.org"
          },
          {
            "require_tls": false,
            "send_resolved": true,
            "to": "cvju@elion.org"
          }
        ],
        "name": "研发"
      },
      {
        "email_configs": [
          {
            "require_tls": false,
            "send_resolved": true,
            "to": "154107938@elion.org"
          }
        ],
        "name": "dba"
      }
    ],
    "route": {
      "continue": false,
      "group_by": [],
      "group_interval": "5m",
      "group_wait": "30s",
      "matchers": [],
      "mute_time_intervals": [],
      "receiver": "运维",
      "repeat_interval": "6m",
      "routes": [
        {
          "continue": true,
          "group_by": [
            "alertname"
          ],
          "group_interval": "1m",
          "group_wait": "10s",
          "matchers": [
            "app=ready"
          ],
          "mute_time_intervals": [],
          "receiver": "研发",
          "repeat_interval": "5m",
          "routes": []
        },
        {
          "continue": true,
          "group_by": [
            "alertname"
          ],
          "matchers": [
            "app=domain"
          ],
          "mute_time_intervals": [],
          "receiver": "研发",
          "routes": []
        },
        {
          "continue": true,
          "group_by": [
            "alertname"
          ],
          "matchers": [
            "database=oracle",
            "database=mysql",
            "database=redis"
          ],
          "mute_time_intervals": [],
          "receiver": "dba",
          "routes": []
        }
      ]
    }
  }
}
```
And this is the mimir configuration:
```yaml
target: all,alertmanager
multitenancy_enabled: false
api:
    skip_label_name_validation_header_enabled: false
    alertmanager_http_prefix: /alertmanager
    prometheus_http_prefix: /prometheus
server:
    http_listen_port: 8080
    grpc_listen_port: 9095
distributor:
    ring:
        kvstore:
            store: memberlist
        instance_id: WEB-06-1
        instance_interface_names: ["br0"]
ingester:
    ring:
        kvstore:
            store: memberlist
        replication_factor: 1
        instance_id: WEB-06-1
        instance_interface_names: ["br0"]
blocks_storage:
    backend: filesystem
    filesystem:
        dir: /home/soft/mimir/data/blocks
    bucket_store:
        sync_dir: /home/soft/mimir/data/tsdb-sync
        bucket_index:
            enabled: true
    tsdb:
        dir: /home/soft/mimir/data/tsdb
compactor:
    data_dir: /home/soft/mimir/data/compactor
    sharding_ring:
        kvstore:
            store: memberlist
        instance_id: WEB-06-1
        instance_interface_names: ["br0"]
store_gateway:
    sharding_ring:
        kvstore:
            store: memberlist
        replication_factor: 1
        instance_id: WEB-06-1
        instance_interface_names: ["br0"]
tenant_federation:
    enabled: false
activity_tracker:
    filepath: /home/soft/mimir/log/metrics-activity.log
ruler:
    external_url: "http://10.0.66.20:8080/ruler"
    ruler_client:
        tls_enabled: false
    rule_path: /home/soft/mimir/data/ruler/
    alertmanager_url: "http://10.0.66.20:8080/alertmanager"
    ring:
        kvstore:
            store: memberlist
        instance_id: WEB-06-1
        instance_interface_names: ["br0"]
    enable_api: true
    query_stats_enabled: true
    query_frontend:
        address: "10.0.66.20:9095"
    tenant_federation:
        enabled: false
ruler_storage:
    backend: filesystem
    filesystem:
        dir: /home/soft/mimir/data/rules
runtime_config:
    period: 10s
memberlist:
    message_history_buffer_bytes: 204800
    node_name: "web06-1"
    randomize_node_name: true
    stream_timeout: 10s
    retransmit_factor: 4
    pull_push_interval: 30s
    gossip_interval: 200ms
    gossip_nodes: 3
    gossip_to_dead_nodes_time: 30s
    compression_enabled: true
    advertise_port: 7946
#    join_members: ["web06-1"]
    abort_if_cluster_join_fails: false
    bind_port: 7946
alertmanager:
    data_dir: /home/soft/mimir/data/alertmanager_storage
    external_url: http://10.0.66.20:8080/alertmanager
    sharding_ring:
    #  instance_interface_names: ["br0"]
      replication_factor: 2
    enable_api: true
alertmanager_storage:
    backend: filesystem
    filesystem:
        dir: /home/soft/mimir/data/alertmanager/
limits:
    request_rate: 0
    request_burst_size: 0
    ingestion_rate: 50000
    ingestion_burst_size: 200000
    max_global_series_per_user: 60000000
    max_global_series_per_metric: 20000000
    ruler_max_rules_per_rule_group: 0
    ruler_max_rule_groups_per_tenant: 0
```
