### DISCUSSION TITLE
Mimir - validate configuration for both mimir yaml and grafana setup

### DISCUSSION THREAD

**Discussion by velu4689** [grafana/mimir#4794] [Help and support]
Hi everyone,

Currently am trying a PoC with Mimir cluster and getting them integrated with Grafana. But I am confused with the way it behaves and so thought of clarifying with you all.

Clarification:
 - Do the configs mentioned below look good ?
 - Is the setup a correct mode for deployment or is there an issue ?

**Setup:**

**_- 2 node Mimir cluster ( monolithic mode) and an Elastic Load Balancer_** 

```yaml
multitenancy_enabled: false
target: all,alertmanager,overrides-exporter

common:
  storage:
    backend: s3
    s3:
      endpoint: s3.us-west-2.amazonaws.com
      region: us-west-2
      bucket_name: <bucket_A>
      secret_access_key: ""
      access_key_id: ""
      insecure: true

blocks_storage:
  backend: s3
  storage_prefix: blocks
  tsdb:
    retention_period: 3h
    dir: /data/ingester

memberlist:
        join_members: [Node-1-IP, Node-2-IP]

compactor:
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: Node-1-IP
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: Node-1-IP
    kvstore:
      store: memberlist
    replication_factor: 1

alertmanager:
  data_dir: /data/alertmanager
  external_url: http://Node-1-IP/alertmanager

ruler_storage:
  backend: s3
  storage_prefix: ruler

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://Node-1-IP/alertmanager
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s

server:
  http_listen_address: "Node-1-IP"
  http_listen_port: 9009
  log_level: info
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

store_gateway:
  sharding_ring:
    kvstore:
      store: memberlist
    replication_factor: 1
```

**- Prometheus is configured with a remote write option to the load balancer**
```yaml
    remote_write:
      - url: http://<>:9009/api/v1/push
```
  
**_- Dockerized version of Grafana configured pointing to read from Mimir cluster_**
    Data source: Prometheus
    URL: http://<Load Balancer IP>:9090
    HTTP Method: POST
    Prometheus type: Mimir
   Mimir version: >2.3.x
