### DISCUSSION TITLE
Mimir AlertManager Location Attribute issue on version 2.7.2

### DISCUSSION THREAD

**Discussion by nirmalkumar85** [grafana/mimir#4866] [Help and support]
Hi Everyone, 

We have deployed Mimir alertmanager v 2.7.1, as part of Mimir 2.1.0 distributed version

```bash
/var # mimir --version
Mimir, version 2.7.2 (branch: HEAD, revision: 76a1021)
  go version:       go1.20.3
  platform:         linux/amd64

```

```yaml
kind: StatefulSet
metadata:
...
  labels:
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.1.0
    helm.sh/chart: mimir-distributed-2.1.0
  name: mimir-alertmanager
.....
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: alertmanager
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
  serviceName: mimir-alertmanager
  template:
......
    spec:
      affinity: {}
      containers:
      - args:
        - -target=alertmanager
        - -config.file=/etc/mimir/mimir.yaml
        - -log.level=debug
        image: hub.docker.internal.cba/grafana/mimir:2.7.2
        imagePullPolicy: IfNotPresent
        name: alertmanager
        ports:
        - containerPort: 8080
          name: http-metrics
          protocol: TCP
        - containerPort: 9095
          name: grpc
          protocol: TCP
        - containerPort: 7946
          name: memberlist
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: http-metrics
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        
        securityContext:
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/mimir
          name: config
        - mountPath: /var/mimir
          name: runtime-config
        - mountPath: /data
          name: storage
        - mountPath: /tmp
          name: tmp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: mimir
      serviceAccountName: mimir
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: mimir-config
      - configMap:
          defaultMode: 420
          name: mimir-runtime
        name: runtime-config
      - emptyDir: {}
        name: tmp
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: mimir-alertmanager-56b5d866df
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updateRevision: mimir-alertmanager-56b5d866df
  updatedReplicas: 1

```

When we create and load new routes and receivers using mimirtool we get the following error:

```
ERRO[0000] response                                      body="error validating Alertmanager config: unknown time zone Australia/Sydney\n" status="400 Bad Request"
mimirtool: error: POST request to http://localhost:8081/api/v1/alerts failed: server returned HTTP status: 400 Bad Request, body: "error validating Alertmanager config: unknown time zone Australia/Sydney\n", try --help
```

Configuration:

```yaml
global:
  smtp_from: 'someemail@email.com'
route:
  receiver: 'default-receiver'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  group_by: [cluster, alertname]


  routes:

  - receiver: 'sns_warning'
    group_by: [post_to]
    matchers:
    - severity="warning"
    mute_time_intervals:
      - 12h-5d-offhours
      - 12h-7d-offhours
    continue: true

 - receiver: 'sns_critical'
    group_by: [post_to]
    matchers:
    - severity="critical"
    mute_time_intervals:
      - 12h-5d-offhours
      - 12h-7d-offhours

time_intervals:
  - name: 12h-5d-offhours
    time_intervals:
      - times:
        - start_time: 19:00
          end_time: 24:00
        - start_time: 00:00
          end_time: 07:00
        weekdays: ['monday:friday']
        location: Australia/Sydney
  - name: 12h-7d-offhours
    time_intervals:
      - times:
        - start_time: 19:00
          end_time: 24:00
        - start_time: 00:00
          end_time: 07:00
        location: Australia/Sydney
        weekdays: ['sunday:saturday']


inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [alertname, email_to, post_to, instance]

receivers:
  - name: 'sns_critical'
    sns_configs:
      - topic_arn: "{{ .GroupLabels.post_to }}"
        subject: somesubject
        attributes:
          key: severity
          value: critical
            
  - name: 'sns_warning'
    sns_configs:
      - topic_arn: "{{ .GroupLabels.post_to }}"
        subject: somesubject
        attributes:
          key: serverity
          value: warning
            
  - name: 'default-receiver'
    sns_configs:
      - topic_arn: "{{ .GroupLabels.post_to }}"
        subject: somesubject
        attributes:
          key: serverity
          value: warning
```
