### DISCUSSION TITLE
metaMonitoring image

### DISCUSSION THREAD

**Discussion by senthil13** [grafana/mimir#4875] [Help and support] [answered]
Hi Experts - 

I followed the link to enable the [monitoring](https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/#set-up-metamonitoring), I am using the helm chart type deployments. 

The only problem is, I am unable to modify the custom image repository. I won't be able to download images directly from the internet, so we have an in-house image repository from where we used to pull the image.  But I am unable to use custom image repository links for `mimir-meta-monitoring` and `mimir-meta-monitoring-logs` pods. Where to put the image values?  I tried multiple ways but it always going to quay.io. I dont find any documents. Please help. 

```
metaMonitoring:
  serviceMonitor:
    enabled: true
    image: 
      repository: XXXXXXXXXXXXXXXXXXX/prometheus-operator/prometheus-config-reloader
      tag: v0.47.0
      pullPolicy: IfNotPresent
  grafanaAgent:
    enabled: true
    image: 
      repository: XXXXXXXXXXXXXXXXXXXXXXXXXXX/grafana/agent
      tag: v0.28.0
      pullPolicy: IfNotPresent
    installOperator: true
    metrics:
      additionalRemoteWriteConfigs:
        - url: "http://mimir-nginx.mimir-test.svc:80/api/v1/push"
```

thanks
Senthil

**Comment by dimitarvdimitrov** [comment, marked as answer]
hey, from what I can see the image can be configured via the `imageRepo` field. This as added in this PR https://github.com/grafana/mimir/pull/4646 will be released with the 4.4.0 chart version and mimir 2.8 in the coming days/weeks.

```yaml
  grafanaAgent:
    # -- Controls whether to create PodLogs, MetricsInstance, LogsInstance, and GrafanaAgent CRs to scrape the
    # ServiceMonitors of the chart and ship metrics and logs to the remote endpoints below.
    # Note that you need to configure serviceMonitor in order to have some metrics available.
    enabled: false

    # -- Controls the image repository and tag for config-reloader and grafana-agent containers in the meta-monitoring
    # StatefulSet and DaemonSet created by the grafana-agent-operator. You can define one or both sections under imageRepo.
    # If a section is defined, you must pass repo, image and tag keys.
    imageRepo:
    #  configReloader:
    #    repo: quay.io
    #    image: prometheus-operator/prometheus-config-reloader
    #    tag: v0.47.0
    #  grafanaAgent:
    #    repo: docker.io
    #    image: grafana/agent
    #    tag: v0.29.0

```
