### DISCUSSION TITLE
Metamonitoring: metrics from mimir cluster are not available

### DISCUSSION THREAD

**Discussion by tagathi** [grafana/mimir#5058] [Help and support] [answered]
Hello,
I have installed Grafana Mimir via helm chart, Grafana via helm chart in the same k8s cluster, and have configured a Prometheus that is running in another cluster to remote write to Mimir. It works fine and I can see the Prometheus metrics in Grafana.
I also tried to enable metamonitoring in order to monitor the cluster on which Mimir is installed, by using the below configuration in values.yaml:

```
metaMonitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
    
  grafanaAgent:
    enabled: true
    installOperator: true

    metrics:
      enabled: true
      remote:
        url: 
        auth:
          username: admin
          passwordSecretName: "agent-secret"
          passwordSecretKey: "password"

      scrapeK8s:
        enabled: true
```
And I don't seem to get any metrics from this cluster in Grafana. Am I missing some step?
In Grafana operator pod I see this error: 
```
level=error ts=2023-05-23T12:31:57.69149559Z component=controller.grafanaagent name=dev-mimir-meta-monitoring namespace=dev-mimir msg="error during reconc
iling" err="failed to reconcile statefulset for shard: failed to create statefulset: admission webhook \"webhook.openpolicyagent.org\" denied the request:
 Fails CIS Benchmark - Do not admit privileged containers! 
```
Could this be related?
