### DISCUSSION TITLE
Grafana - Mimir- Query only cluster

### DISCUSSION THREAD

**Discussion by velu4689** [grafana/mimir#5105] [Development]
Hi Team,

I have a separate write only cluster which uses S3 as backend storage. I would like setup a query only cluster which will read/query the data from the S3 alone and not from the ingester (reason: we do not want to query any live data & just rely on Storage only data)

I would like to get your thoughts/opinions on the **query only cluster** being setup using the following configuration:

```yaml
###################################################################
target: read,backend,alertmanager,overrides-exporter

common:
  storage:
    backend: s3
    s3:
      endpoint: s3.us-west-2.amazonaws.com
      region: us-west-2
      bucket_name: <bucket_name>

blocks_storage:
  backend: s3
  storage_prefix: blocks
  bucket_store:
    sync_interval: 15m
  tsdb:
    retention_period: 2h
    ship_interval: 5m
    dir: /data/tsdb

memberlist:
  join_members: [<EC2_IP1>, <EC2_IP2>, <EC2_IP3>]

compactor:
  data_dir: /data/compactor
  compaction_interval: 15m
  cleanup_interval: 15m
  sharding_ring:
    instance_addr: <EC2_IP1>
    kvstore:
      store: memberlist

querier:
  query_ingesters_within: 15s
  query_store_after: 0
  max_query_into_future: 12h

frontend:
 align_queries_with_step: true
 cache_results: true
 log_queries_longer_than: 10s

#distributor:
#  ring:
#    instance_addr: <EC2_IP1>
#    kvstore:
#      store: memberlist
#  ha_tracker:
#    enable_ha_tracker: true

#ingester:
#  ring:
#    instance_addr: <EC2_IP1>
#    kvstore:
#      store: memberlist
#   replication_factor: 3

alertmanager:
  data_dir: /data/alertmanager
  external_url: http://<EC2_IP1>:9009/alertmanager

ruler:
  rule_path: /data/ruler
  alertmanager_url: http://<EC2_IP1>:8080/alertmanager
  ring:
    # Quickly detect unhealthy rulers to speed up the tutorial.
    heartbeat_period: 15s
    heartbeat_timeout: 1m

ruler_storage:
  backend: s3
  storage_prefix: ruler

server:
  http_listen_address: "<EC2_IP1>"
  http_listen_port: 9009
  log_level: info

store_gateway:
  sharding_ring:
    instance_addr:<EC2_IP1>
    kvstore:
      store: memberlist
      prefix: "/data/store_collectors"
    replication_factor: 3

limits:
  max_fetched_chunks_per_query: 50000000000
  max_label_names_per_series: 200
  max_global_series_per_user: 500000000000
  ingestion_rate: 1500000000
  ingestion_burst_size: 4000000000
```
