### DISCUSSION TITLE
Using the grafanaExploreURL function

### DISCUSSION THREAD

**Discussion by kdibragimov** [grafana/mimir#5132] [Help and support]
Hi, could you tell me how to use the [grafanaExploreURL](https://grafana.com/docs/mimir/latest/operators-guide/architecture/components/alertmanager/#templating) function in the default mimir-distributed template?

**Comment by dimitarvdimitrov** [comment]
Do you mean how to use it in the default alertmanager fallback config in the helm chart (`alertmanager.fallbackConfig`)?

**Reply by kdibragimov** [reply]
Yes, how can I use there?

**Reply by dimitarvdimitrov** [reply]
This is one example

```yaml
alertmanager:
  fallbackConfig:
    receivers:
    - name: 'team-x'
      slack_configs:
      - channel: '#alerts'
        text: "Go to Explore: {{ grafanaExploreURL "https://foo.bar" "datasourceUID" "now-12h" "now" "up{foo=\"bar\"}" }}"
```
