### DISCUSSION TITLE
Frequent gaps in metrics

### DISCUSSION THREAD

**Discussion by sahu-sunil** [grafana/mimir#5138] [Help and support]
I have deployed an instance of mimir monolith as statefulset (`/data` is PVC) and remote writing from **prometheus agents** as a sidecar to my applications. Metrics are being ingested but I am seeing frequent gaps (~ 30 - 100 secs) in all of the metrics.
I don't see any unusual in mimir's logs (except `msg="Invalidating forwarded broadcast" key=collectors/distributor version=3298 oldVersion=3297`. not sure if it has to do something with gaps)

I don't see anything in agent logs which denotes metrics drops or memory/cpu issues
Prometheus agent config:
```
global:
    scrape_interval: 60s
scrape_configs:
   - job_name: 'demo'
     static_configs:
       - targets: ['localhost:8000']
       - targets: ['localhost:9090']
       - targets: ['mimir-as-monolith.mimir-as-monolith.svc.cluster.local:9009']
remote_write:
- url: 'http://mimir-as-monolith.mimir-as-monolith.svc.cluster.local:9009/api/v1/push'
  remote_timeout: 60s
  queue_config:
    max_shards: 20
    capacity: 20000
    max_samples_per_send: 2000
    min_backoff: 30ms
    max_backoff: 100ms
```

Mimir's Config: 
```
target: all
multitenancy_enabled: false
shutdown_delay: 60s

blocks_storage:
  backend: s3
  bucket_store:
    max_chunk_pool_bytes: 12884901888
    sync_dir: /data/tsdb-sync
  s3:
    access_key_id: ***
    bucket_name: ****
    endpoint: ****
    secret_access_key:***
  tsdb:
    dir: /data/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

server:
  http_listen_port: 9009
  log_level: debug

limits:
  # Allow ingestion of out-of-order samples up to 5 minutes since the latest received sample for the series.
  out_of_order_time_window: 5m
  ingestion_rate: 100000
  ingestion_burst_size: 2000000

store_gateway:
  sharding_ring:
    replication_factor: 1

```
Matrics 5 mins Snap:
![image](https://github.com/grafana/mimir/assets/18591767/f425cc0c-1897-41b4-8d2c-9605a46a42b5)

Thanks in advance!
