### DISCUSSION TITLE
Grafana fails to query prometheus alerts from ruler

### DISCUSSION THREAD

**Discussion by tgrondier** [grafana/mimir#5358] [Help and support] [answered]
We're running Grafana (9.5) with Mimir (2.8) as datasources. We have migrated our alerts away from Prometheus into the mimir ruler, however we're having the following issue:

What we expect:

Grafana at the address `alerting/list` showing the prometheus alerts for the datasource, something similar to our prometheus datasources:

![image](https://github.com/grafana/mimir/assets/5384645/4cdeea45-d630-494b-bb41-1306f1c5c60f)

What we have, despite the ruler api being enabled:

```404 from rule state endpoint. Perhaps ruler API is not enabled?```

![image](https://github.com/grafana/mimir/assets/5384645/ace17156-dac2-4e17-8bcf-b5c896164bd9)

Here is our mimir config for the ruler:

```
ruler:
    external_url: REDACTED
    ruler_client:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: ""
        rate_limit: 0
        rate_limit_burst: 0
        backoff_on_ratelimits: false
        backoff_config:
            min_period: 100ms
            max_period: 10s
            max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
        tls_cipher_suites: ""
        tls_min_version: ""
    evaluation_interval: 1m0s
    poll_interval: 1m0s
    rule_path: /data/ruler
    alertmanager_url: SOME_URLS
    alertmanager_refresh_interval: 1m0s
    notification_queue_capacity: 10000
    notification_timeout: 10s
    alertmanager_client:
        tls_enabled: true
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
        tls_cipher_suites: ""
        tls_min_version: ""
        basic_auth_username: ""
        basic_auth_password: ""
    for_outage_tolerance: 1h0m0s
    for_grace_period: 2m0s
    resend_delay: 1m0s
    ring:
      ...
    enable_api: true
    enabled_tenants: ""
    disabled_tenants: ""
    query_stats_enabled: false
    query_frontend:
        address: dns:///mimir-query-frontend-service.mimir.svc:9095
        grpc_client_config:
            max_recv_msg_size: 104857600
            max_send_msg_size: 104857600
            grpc_compression: ""
            rate_limit: 0
            rate_limit_burst: 0
            backoff_on_ratelimits: false
            backoff_config:
                min_period: 100ms
                max_period: 10s
                max_retries: 10
            tls_enabled: false
            tls_cert_path: ""
            tls_key_path: ""
            tls_ca_path: ""
            tls_server_name: ""
            tls_insecure_skip_verify: false
            tls_cipher_suites: ""
            tls_min_version: ""
        query_result_response_format: protobuf
    tenant_federation:
        enabled: true

```

Grafana datasource:

```
mimir-datasource:
  url: https://mimir-query.some-url/prometheus
  type: prometheus
  access: proxy
  orgId: 1
  user: ""
  database: ""
  basicAuth: false
  isDefault: false
  jsonData:
    httpMethod: "POST"
    prometheusType: "Mimir"
    timeout: 120
    tlsAuth: true
    tlsAuthWithCACert: true
    keepCookies: []
    tlsSkipVerify: true
    httpHeaderName1: '...'
  secureJsonData:
    ...
  readOnly: true
```
