### DISCUSSION TITLE
Error related to container Thanos on Kubernetes

### DISCUSSION THREAD

**Discussion by Akhofreeze** [grafana/mimir#5380] [Help and support]
Hi 
#### Describe the issue
I'm facing an issue regarding my Mimir deployment on K8S. And don't really understand why ? 
Do you have any ideas ? 
`ts=2023-06-29T15:22:00.352901564Z caller=log.go:65 level=error msg="error running application" err="no container specified\ngithub.com/thanos-io/objstore/providers/azure.(*Config).validate\n\t/__w/mimir/mimir/vendor/github.com/thanos-io/objstore/providers/azure/azure.go:96\ngithub.com/thanos-io/objstore/providers/azure.NewBucketWithConfig\n\t/__w/mimir/mimir/vendor/github.com/thanos-io/objstore/providers/azure/azure.go:151\ngithub.com/thanos-io/objstore/providers/azure.NewBucket\n\t/__w/mimir/mimir/vendor/github.com/thanos-io/objstore/providers/azure/azure.go:146\ngithub.com/grafana/mimir/pkg/storage/bucket/azure.newBucketClient\n\t/__w/mimir/mimir/pkg/storage/bucket/azure/bucket_client.go:42\ngithub.com/grafana/mimir/pkg/storage/bucket/azure.NewBucketClient\n\t/__w/mimir/mimir/pkg/storage/bucket/azure/bucket_client.go:17\ngithub.com/grafana/mimir/pkg/storage/bucket.NewClient\n\t/__w/mimir/mimir/pkg/storage/bucket/client.go:167\ngithub.com/grafana/mimir/pkg/ruler.NewRuleStore\n\t/__w/mimir/mimir/pkg/ruler/storage.go:42\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initRulerStorage\n\t/__w/mimir/mimir/pkg/mimir/modules.go:679\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:787\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:218\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nerror initialising module: ruler-storage\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:787\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:218\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598"
`

Here is my mimir.yml config file:
```
apiVersion: v1
kind: Secret
metadata:
  name: mimir-config
type: Opaque
stringData:
  mimir.yml: |
    common:
      storage:
        backend: azure
        azure:
          account_key:  ACCOUNT_KEY
          account_name: SA_NAME
          endpoint_suffix: "blob.core.windows.net"

    activity_tracker:
      filepath: /data/metrics-activity.log  
      
    blocks_storage:
      azure:
        container_name: mimir-blocks
```
