### DISCUSSION TITLE
Is it possible to federate Mimir so its metrics can be read by a Prometheus?

### DISCUSSION THREAD

**Discussion by costa-danilo** [grafana/mimir#5468] [Help and support]
Hi, I'd like to make so a Prometheus can scrape the metrics of a Mimir under a specific X-Org-Id.
Is federation possible?

I was trying to do something like this but I it doesn't seem to work and I wouldn't know where to specify the X-Org-Id.
```
prometheusSpec:
      additionalScrapeConfigs:
        - job_name: test-federate
          metrics_path: '/prometheus/federate'
          params:
            'match[]':
              - '{job="spark-exporter"}'
          scrape_timeout: 25s
          scrape_interval: 30s
          honor_labels: true
          static_configs:
            - targets:
                - "monitoring-mimir-nginx.monitoring.svc:80"
              labels:
                env: test-federate
```
