### DISCUSSION TITLE
Cannot join cluster: received invalid msgType (72), expected pushPullMsg (6)

### DISCUSSION THREAD

**Discussion by Johan-Gi** [grafana/mimir#5491] [Help and support] [answered]
Hi!

I'm trying to setup Mimir on AWS EC2 backed ECS. Dynamic port allocation is being used, where the dynamic port is mapped to port 9009. 
When browsing and checking the memberlist status there's only one instance in there (should be 2) 

The logs are giving me error: 
```
ts=2023-07-13T08:07:43.381364845Z caller=memberlist_client.go:598 level=warn msg="joining memberlist cluster: failed to reach any nodes" retries=6 err="2 errors occurred:\n\t* Failed to join 10.120.15.115:32824: received invalid msgType (72), expected pushPullMsg (6) from=10.120.15.115:32824\n\t* Failed to join 10.120.15.136:32824: received invalid msgType (72), expected pushPullMsg (6) from=10.120.15.136:32824\n\n
```
I don't know what messagetype 72 is, or what I have misconfigured to make it not send the correct messagetype.
Does anyone know what is going wrong here?

The addresses and ports returned from the SRV record are correct 

mimir.yml
```
target: all,alertmanager,overrides-exporter

# Configure Mimir to use s3 as object storage backend.
common:
  storage:
    backend: s3
    s3:
      region: eu-west-1
      endpoint: s3.amazonaws.com
      insecure: true
      bucket_name: monitorxy-mimir-bucket

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  s3:
    bucket_name: monitorxy-mimirblocks-bucket
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester

# Use memberlist, a gossip-based protocol, to enable the Mimir replicas to communicate 
# https://grafana.com/docs/mimir/latest/operators-guide/configure/about-dns-service-discovery/
memberlist:
  abort_if_cluster_join_fails: false
  join_members: [dnssrv+mimir.mimir.local]
  max_join_retries: 30 #default 10

ruler:
  rule_path: /data/ruler
  alertmanager_url: dnssrv+http://mimir.mimir.local/alertmanager
  ring:
    # Quickly detect unhealthy rulers to speed up the tutorial.
    heartbeat_period: 2s
    heartbeat_timeout: 10s

# alertmanager:
#   data_dir: /data/alertmanager
#   fallback_config_file: /etc/alertmanager-fallback-config.yaml
#   external_url: dns+mimir.mimir.local:9009/alertmanager

server:
  http_listen_port: 9009
  log_level: debug
```

**Comment by dimitarvdimitrov** [comment, marked as answer]
memberlist listens on port 7946 by default (configured via `memberlist.advertise_port`). I'm not sure what port the `join_members` defaults to (9009?). If you specify the correct port, then this should go away. Let us know how it goes!

```yaml
memberlist:
  abort_if_cluster_join_fails: false
  join_members: [dnssrv+mimir.mimir.local:7964]
  max_join_retries: 30 #default 10
```
