### DISCUSSION TITLE
compactor_blocks_retention_period is ignored

### DISCUSSION THREAD

**Discussion by helmut72** [grafana/mimir#5513] [Help and support] [answered]
Hi,

after reading...

https://grafana.com/docs/mimir/latest/configure/configure-metrics-storage-retention/

... I want to test mimir's `compactor_blocks_retention_period` option and set it to `1d`. After mimir running longer than 24h it looks like this setting is ignored. Grafana still shows metrics older than 24h.

Here is my complete config:

```
blocks_storage:
    bucket_store:
        sync_dir: /data/tsdb-sync
    filesystem:
        dir: /data/blocks
    tsdb:
        dir: /data/tsdb
compactor:
    data_dir: /data/compactor
distributor:
    ring:
        instance_addr: 127.0.0.1
ingester:
    ring:
        instance_addr: 127.0.0.1
        replication_factor: 1
limits:
    compactor_blocks_retention_period: 1d
multitenancy_enabled: false
ruler_storage:
    filesystem:
        dir: /data/rules
server:
    http_listen_port: 9009
    log_level: warn
store_gateway:
    sharding_ring:
        replication_factor: 1
```

Filesystem is completely enough. It's for my homelab.

Is there anything else missing?

Thank you.
