### DISCUSSION TITLE
Alert rule not working after applying metric_relabel_configs for __name__

### DISCUSSION THREAD

**Discussion by mdvaliyullah** [grafana/mimir#5571] [Help and support] [answered]
I am using graphite mimir proxies which default gives the metric name as graphite_tagged or graphite_untagged. after applying metric_relabel_configs the metric name changes with the desired name but when we create an alert rule we get a message "received series has no metric name". please advise

```
  metric_relabel_configs: 
  - source_labels: ['name']
    target_label: __name__
    replacement: $1 
```
<img width="989" alt="image" src="https://github.com/grafana/mimir/assets/31310644/5a361ec4-be50-49c2-94b0-92c07aca72ca">

**Comment by pstibrany** [comment]
Hello. What does your alert look like?

**Reply by mdvaliyullah** [reply]
please find the screen shot of the same, I tried to search the `sum:cpu_load_shot` in the explorer but its not listing in the Metrics Browser list

<img width="1387" alt="image" src="https://github.com/grafana/mimir/assets/31310644/eef85565-ea6e-4703-86b1-eed9588b62b6">

**Comment by dimitarvdimitrov** [comment, marked as answer]
I think the relabelling config replaces `__name__` with an empty string when `name` is not present. This results in ingesting metrics with empty `__name__`, and seeing this error when querying. I think a simple fix would be to only relabel when `name` is non-empty:

```
  metric_relabel_configs: 
  - source_labels: ['name']
    target_label: __name__
    replacement: $1 
    regex: (.+) # default is (.*)
```
