### DISCUSSION TITLE
Discrepancy between Mimir and the actual data

### DISCUSSION THREAD

**Discussion by girishms-sentient** [grafana/mimir#5603] [Help and support]
The Mimir is configured and running, but the data I'm seeing in the Mimir Grafana dashboard does not match the actual Grafana for the cluster. Sometimes the displayed data is twice/thrice as accurate.

**Actual Grafana dashboard:**

<img width="1633" alt="unknown" src="https://github.com/grafana/mimir/assets/107147378/6e137e76-9234-4460-9eca-36f4d80add6b">

**Mimir Grafana:**

![unknown](https://github.com/grafana/mimir/assets/107147378/f48f8728-3a68-4e71-b00d-92ffa6cd3aed)

![unknown](https://github.com/grafana/mimir/assets/107147378/29061301-b48a-4277-8f9b-a9862bad55c6)

**Here's the mimir config:**

```
        ################ MIMIR CONFIGURATION #####################
        mimir:
          structuredConfig:
            ingester:
              ring:
                final_sleep: 0s
                num_tokens: 512
                tokens_file_path: /data/tokens
                heartbeat_period: 20s
                heartbeat_timeout: 60s
                unregister_on_shutdown: true
                kvstore:
                  store: memberlist
                replication_factor: 3
                zone_awareness_enabled: true

            memberlist:
              abort_if_cluster_join_fails: false
              compression_enabled: false
              join_members:
                - dns+{{ include "mimir.fullname" . }}-gossip-ring.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:{{ include "mimir.memberlistBindPort" . }}
              advertise_addr: ${MY_POD_IP}

            limits:
              compactor_blocks_retention_period: 604800s
              ingestion_rate: 500000
              max_global_series_per_metric: 9000000
              max_global_series_per_user: 9000000
              max_label_names_per_series: 60

            distributor:
              ring:
                kvstore:
                  store: memberlist

            compactor:
              data_dir: /data/compactor
              sharding_ring:
                heartbeat_period: 20s
                heartbeat_timeout: 60s  
                kvstore:
                  store: memberlist

            store_gateway:
              sharding_ring:
                heartbeat_period: 20s
                heartbeat_timeout: 60s
                zone_awareness_enabled: true 
                kvstore:
                  store: memberlist  

            ruler:
              rule_path: /data/ruler
              poll_interval: 2s
              ring:
                heartbeat_period: 20s
                heartbeat_timeout: 60s
                kvstore:
                  store: memberlist
          
          ############## MIMIR STORAGE ################
            blocks_storage:
              backend: s3
              bucket_store:
                max_chunk_pool_bytes: 12884901888 # 12GiB
              s3:
                endpoint: s3.us-west-2.amazonaws.com
                bucket_name: central-logging-mimir-bucket-block-storage        
                insecure: true
              tsdb:
                dir: /data/tsdb


            alertmanager_storage:
              backend: s3
              s3:
                endpoint: s3.us-west-2.amazonaws.com
                bucket_name: central-logging-mimir-bucket-alertmanager-storage 


            ruler_storage:
              backend: s3
              s3:
                endpoint: s3.us-west-2.amazonaws.com
                bucket_name: central-logging-mimir-bucket-ruler-storage         

        #############################################################

        global:
          extraEnv:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

        serviceAccount:
          create: true
          name: mimir
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxx
                                        
        alertmanager:
          persistentVolume:
            enabled: true
            storageClass: ebs-sc
          replicas: 2
          resources:
            limits:
              memory: 1.4Gi
            requests:
              cpu: 1
              memory: 1Gi
          statefulSet:
            enabled: true
          podAnnotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxx
          extraArgs:
            memberlist.bind-addr: ${MY_POD_IP}

        compactor:
          persistentVolume:
            size: 5Gi
            storageClass: ebs-sc
          podAnnotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxx
          extraArgs:
            memberlist.bind-addr: ${MY_POD_IP}

        distributor:
          replicas: 2
          podAnnotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxx
          extraArgs:
            memberlist.bind-addr: ${MY_POD_IP}

        ingester:
          persistentVolume:
            size: 50Gi
            storageClass: ebs-sc
          replicas: 3
          podAnnotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxx
          extraArgs:
            memberlist.bind-addr: ${MY_POD_IP}

        ruler:
          replicas: 1
          podAnnotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::xxxxxxxxxxx:role/xxxxxxxxxx
          extraArgs:
            memberlist.bind-addr: ${MY_POD_IP}

        store_gateway:
          persistentVolume:
            size: 10Gi
            storageClass: ebs-sc
          replicas: 3
          extraArgs:
            memberlist.bind-addr: ${MY_POD_IP}

        querier:
          replicas: 1
          extraArgs:
            memberlist.bind-addr: ${MY_POD_IP}

        admin-cache:
          enabled: true
          replicas: 2

        chunks-cache:
          enabled: true
          replicas: 2

        index-cache:
          enabled: true
          replicas: 1

        metadata-cache:
          enabled: true

        results-cache:
          enabled: true
          replicas: 2

        minio:
          enabled: false

        overrides_exporter:
          replicas: 1
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

        query_frontend:
          replicas: 1

        nginx:
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
              service.beta.kubernetes.io/aws-load-balancer-subnets: "xxxxxxxxx"
              service.beta.kubernetes.io/aws-load-balancer-type: external
          replicas: 1
          resources:
            limits:
              memory: 731Mi
            requests:
              cpu: 1
              memory: 512Mi

        # Grafana Enterprise Metrics feature related
        admin_api:
          replicas: 1
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi

        gateway:
          replicas: 1
          resources:
            limits:
              memory: 731Mi
            requests:
              cpu: 1
              memory: 512Mi
```

**Prometheus remote write:**

```
prometheus:
  prometheusSpec:
    remoteWrite:
      - url: http://xxxxxxxxxx.elb.us-west-2.amazonaws.com/api/v1/push
```

Is there anything I'm missing or is there a way to solve this issue?

**Comment by girishms-sentient** [comment]
@pstibrany  @pracucci  @DylanGuedes I would appreciate your assistance.

**Comment by dimitarvdimitrov** [comment]
Is it possible that you are scraping the same targets multiple times? you can check which targets are being scraped by checking the prometheus UI on the prometheis. One way this could be happening is that There are multiple Prometheus custom resources that are configured to scrape the same Service/PodMonitors

**Reply by girishms-sentient** [reply]
@dimitarvdimitrov All Prometheus targets are scraped exactly once. I still see that data is being replicated three times.

Actual Grafana:
<img width="1394" alt="image" src="https://github.com/grafana/mimir/assets/107147378/23227bc3-14bc-4a2d-a7d8-92a6f5ab5fe8">

Mimir Grafana:
<img width="1404" alt="image" src="https://github.com/grafana/mimir/assets/107147378/4a359fee-7bbc-4083-a64e-603bcf584a20">

@pstibrany @pracucci @DylanGuedes I would appreciate your help.

**Reply by girishms-sentient** [reply]
I could still see, Mimir continues to replicate data three times.

Running 3 replicas of ingester, 2 distributors, 1 compactor, 1 ruler.

```
        ################ MIMIR CONFIGURATION #####################
        mimir:
          structuredConfig:
            ingester:
              ring:
                final_sleep: 0s
                num_tokens: 512
                tokens_file_path: /data/tokens
                heartbeat_period: 20s
                heartbeat_timeout: 60s
                unregister_on_shutdown: true
                kvstore:
                  store: memberlist
                replication_factor: 3
                zone_awareness_enabled: false
              instance_limits:
                max_inflight_push_requests: 0

            memberlist:
              abort_if_cluster_join_fails: false
              compression_enabled: false
              join_members:
                - dns+{{ include "mimir.fullname" . }}-gossip-ring.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:{{ include "mimir.memberlistBindPort" . }}
              advertise_addr: ${MY_POD_IP}

            limits:
              ingestion_rate: 200000
              max_global_series_per_metric: 3000000
              max_global_series_per_user: 3001000                
              max_label_names_per_series: 60
              compactor_blocks_retention_period: 0s
              compactor_split_and_merge_shards: 0
              compactor_split_groups: 0

              max_query_parallelism: 224
              request_rate: 700000
              request_burst_size: 50000000
              ingestion_burst_size: 50000000
              out_of_order_time_window: 5m

```

<img width="1473" alt="image" src="https://github.com/grafana/mimir/assets/107147378/6ed58c74-f9fd-4641-a31b-5dd53cf79dd0">

Team, I would appreciate your help.

**Reply by pstibrany** [reply]
Could you try to query your Mimir instance using `curl` and share the result? It's difficult to understand what's happening from screenshot with cut-off series labels.

```
curl -s "http://hostname/api/prom/api/v1/query" -d query="$1"
```

You may need to supply additional authentication, based on your settings.

**Reply by girishms-sentient** [reply]
@pstibrany Mimir is running with Helm charts on the EKS cluster. Would you mind letting me know exactly what "mimir instance" you are talking about?

```
NAME                                        READY   STATUS    RESTARTS   AGE
grafana-5b96956464-np47g                    1/1     Running   0          3h15m
mimir-alertmanager-0                        1/1     Running   0          115m
mimir-alertmanager-1                        1/1     Running   0          116m
mimir-chunks-cache-0                        2/2     Running   0          3h15m
mimir-chunks-cache-1                        2/2     Running   0          3h15m
mimir-compactor-0                           1/1     Running   0          116m
mimir-distributor-58969ff755-5wjgk          1/1     Running   0          116m
mimir-distributor-58969ff755-m9ch7          1/1     Running   0          115m
mimir-index-cache-0                         2/2     Running   0          3h15m
mimir-index-cache-1                         2/2     Running   0          3h15m
mimir-ingester-0                            1/1     Running   0          113m
mimir-ingester-1                            1/1     Running   0          114m
mimir-ingester-2                            1/1     Running   0          116m
mimir-metadata-cache-0                      2/2     Running   0          3h15m
mimir-nginx-7bff5676-25dmv                  1/1     Running   0          3h15m
mimir-overrides-exporter-69d58fcf79-qxpgn   1/1     Running   0          116m
mimir-querier-7c47f656db-whzgn              1/1     Running   0          116m
mimir-query-frontend-7fc64d7964-4vjj5       1/1     Running   0          116m
mimir-query-scheduler-b768869bf-4zcrp       1/1     Running   0          115m
mimir-query-scheduler-b768869bf-pmqmb       1/1     Running   0          116m
mimir-results-cache-0                       2/2     Running   0          3h15m
mimir-results-cache-1                       2/2     Running   0          3h15m
mimir-rollout-operator-775c66455-268zz      1/1     Running   0          3h15m
mimir-ruler-75d6867ccd-rmcsq                1/1     Running   0          116m
mimir-store-gateway-0                       1/1     Running   0          113m
mimir-store-gateway-1                       1/1     Running   0          114m
mimir-store-gateway-2                       1/1     Running   0          116
```

**Reply by pstibrany** [reply]
I see nginx running between your pods so I assume you have some Ingress configured? I'd try to target its hostname.

**Reply by girishms-sentient** [reply]
Although I do not use any ingress, LoadBanalcer is configured for Nginx and I was able to see the 404 response below.

<img width="1168" alt="image" src="https://github.com/grafana/mimir/assets/107147378/7283db27-ec19-4046-8c33-455be954a776">

**Reply by dimitarvdimitrov** [reply]
the endpoint should be `/prometheus/api/v1/query` instead of `/api/prom/api/v1/query`. Mimir removed `/api/prom` with the 2.0 release.

**Reply by girishms-sentient** [reply]
Thanks @dimitarvdimitrov 

@pstibrany I can see the below response.

```
-bash-4.4$  curl -s "http://k8s-xxxxxxxxxxxxxxxxxxx.elb.us-west-2.amazonaws.com/prometheus/api/v1/query" -d query="$1"
{"status":"error","errorType":"bad_data","error":"invalid parameter \"query\": 1:1: parse error: no expression found in input"}
```

**Reply by pstibrany** [reply]
> ```
> -bash-4.4$  curl -s "http://k8s-xxxxxxxxxxxxxxxxxxx.elb.us-west-2.amazonaws.com/prometheus/api/v1/query" -d query="$1"
> {"status":"error","errorType":"bad_data","error":"invalid parameter \"query\": 1:1: parse error: no expression found in input"}
> ```

Sorry for confusion. You will need to pass the query instead of `$1` parameter. Eg. `(node_memory_MemFree_bytes / 1024^3)` from your previous screenshot.

**Reply by pstibrany** [reply]
So eg.

```console
$ curl -s "http://k8s-xxxxxxxxxxxxxxxxxxx.elb.us-west-2.amazonaws.com/prometheus/api/v1/query" -d query="(node_memory_MemFree_bytes / 1024^3)"
```

**Reply by girishms-sentient** [reply]
It appears that the response is the same as the previous screenshot, the data is being replicated three times.

```
-bash-4.4$ curl -s "http://k8s-xxxxxxxxxxxxxxxxxxxxx.elb.us-west-2.amazonaws.com/prometheus/api/v1/query" -d query="(node_memory_MemFree_bytes / 1024^3)"
{"status":"success","data":{"resultType":"vector","result":[
{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.104:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-7mbwz","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"2.893810272216797"]},

{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.104:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-7mbwz","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"2.8940505981445312"]},

{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.104:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-7mbwz","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"2.8892440795898438"]},

{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.132:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-vdfbg","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.596828460693359"]},

{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.132:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-vdfbg","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.594913482666016"]},

{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.132:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-vdfbg","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.596595764160156"]},

{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.135:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-5t6gq","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.596412658691406"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.135:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-5t6gq","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.595954895019531"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.135:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-5t6gq","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.592529296875"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.168:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-pwkqh","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"5.476314544677734"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.168:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-pwkqh","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"5.468334197998047"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.168:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-pwkqh","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"5.468265533447266"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.176:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-pgd9m","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"0.3936424255371094"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.176:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-pgd9m","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"0.39427947998046875"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.176:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-pgd9m","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"0.39470672607421875"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.192:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-5tnsp","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"9.731731414794922"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.192:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-5tnsp","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"9.741405487060547"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.192:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-5tnsp","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"9.739631652832031"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.233:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-rwpvd","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.618564605712891"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.233:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-rwpvd","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.617603302001953"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.233:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-rwpvd","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"4.615650177001953"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.248:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-6nsl6","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"5.744964599609375"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.248:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-6nsl6","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"5.743633270263672"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.248:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-6nsl6","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"5.743400573730469"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.29:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-s7sxs","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"3.6807785034179688"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.29:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-s7sxs","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-1","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"3.6807785034179688"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.29:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-s7sxs","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-2","service":"monitoring-prometheus-node-exporter"},"value":[1696345390,"3.681011199951172"]},{"metric":{"container":"node-exporter","endpoint":"http-metrics","environment":"dev-aws1","instance":"10.253.48.31:9100","job":"node-exporter","namespace":"monitoring","pod":"monitoring-prometheus-node-exporter-vk4h8","prometheus":"monitoring/monitoring-kube-prometheus-prometheus","prometheus_replica":"prometheus-monitoring-kube-prometheus-prometheus-0","service":"monitoring-prometheus-node-exporter"}

```

**Reply by pstibrany** [reply]
It's replicated 3 times, because it's coming from 3 different `prometheus_replica`s.

It seems like your HA deduplication is either not set up properly (eg. I can't see any cluster label, only `prometheus_replica` label), or it's not working.

**Reply by pstibrany** [reply]
Thank you for sharing raw JSON output, that's very useful in this troubleshooting.

**Reply by pstibrany** [reply]
To read more about HA deduplication feature: https://grafana.com/docs/mimir/latest/configure/configure-high-availability-deduplication/

In your case, perhaps configuring "cluster" label to `environment` and "replica" label to `prometheus_replicas` would work?

**Reply by girishms-sentient** [reply]
Thank you @pstibrany, After adding external labels on Prometheus and making the required changes to the ha-tracker on Mimir, I am able to get accurate data now.

Mimir:
```
            limits:
              ingestion_rate: 200000
              max_global_series_per_metric: 3000000
              max_global_series_per_user: 3000000                
              max_label_names_per_series: 60
              compactor_blocks_retention_period: 0s
              compactor_split_and_merge_shards: 0
              compactor_split_groups: 0
              accept_ha_samples: true
              ha_cluster_label: "environment"
              ha_replica_label: "__replica__"

            distributor:
              ring:
                kvstore:
                  store: memberlist
              instance_limits:
                max_inflight_push_requests: 0
              ha_tracker:
                enable_ha_tracker: true
                kvstore:
                  store: inmemory
                  prefix: ha-tracker
```

Prometheus:
```
prometheus:
  prometheusSpec:
    externalLabels:
      environment: {{ environment_name }}
      __replica__: prometheus_replica_{{ environment_name }}
    replicaExternalLabelNameClear: true
```

Now I could see some exceptions on Prometheus logs, "the sample has been rejected because another sample with the same timestamp, but a different value, has already been ingested". Btw it's not impacting anything, data in the mimir is fine and accurate.

```
ts=2023-10-06T12:33:46.907Z caller=dedupe.go:112 component=remote level=error remote_name=e64587 url=http://k8s-centralm-mimirngi-de1e8b696f-d9a0b2a1383dbad7.elb.us-west-2.amazonaws.com/api/v1/push msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: failed pushing to ingester: user=anonymous: the sample has been rejected because another sample with the same timestamp, but a different value, has already been ingested (err-mimir-sample-duplicate-timestamp). The affected sample has timestamp 2023-10-06T12:33:46.848Z and is from series {__name__=\"instance:node_cpu_utilisation:rate5m\", container=\"node-exporter\", endpoint=\"http-metrics\", environment=\"dev-aws1\", instance=\"10.253.48.104:9100\", job=\"node-exporter\", namespace=\"monitoring\", pod=\"monitoring-prometheus-node-exporter-l65f9\", prometheus=\"monitoring/monitoring-kube-prometheus-prometheus\", service=\"monitoring-prometheus-node-exporter\"}"
ts=2023-10-06T12:33:47.006Z caller=dedupe.go:112 component=remote level=error remote_name=e64587 url=http://k8s-centralm-mimirngi-de1e8b696f-d9a0b2a1383dbad7.elb.us-west-2.amazonaws.com/api/v1/push msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: failed pushing to ingester: user=anonymous: the sample has been rejected because another sample with the same timestamp, but a different value, has already been ingested (err-mimir-sample-duplicate-timestamp). The affected sample has timestamp 2023-10-06T12:33:46.848Z and is from series {__name__=\"instance_device:node_disk_io_time_seconds:rate5m\", container=\"node-exporter\", device=\"nvme0n1\", endpoint=\"http-metrics\", environment=\"dev-aws1\", instance=\"10.253.48.233:9100\", job=\"node-exporter\", namespace=\"monitoring\", pod=\"monitoring-prometheus-node-exporter-r5c7l\", prometheus=\"monitoring/monitoring-kube-prometheus-prometheus\", service=\"monitoring-prometheus-node-exporter\"}"
ts=2023-10-06T12:33:49.304Z caller=dedupe.go:112 component=remote level=error remote_name=e64587 url=http://k8s-centralm-mimirngi-de1e8b696f-d9a0b2a1383dbad7.elb.us-west-2.amazonaws.com/api/v1/push msg="non-recoverable error" count=500 exemplarCount=0 err="server returned HTTP status 400 Bad Request: failed pushing to ingester: user=anonymous: the sample has been rejected because another sample with the same timestamp, but a different value, has already been ingested (err-mimir-sample-duplicate-timestamp). The affected sample has timestamp 2023-10-06T12:33:48.681Z and is from series {__name__=\"ALERTS_FOR_STATE\", alertname=\"PrometheusRemoteStorageFailures\", container=\"prometheus\", endpoint=\"http-web\", environment=\"dev-aws1\", instance=\"7.0.253.144:9090\", job=\"monitoring-kube-prometheus-prometheus\", namespace=\"monitoring\", pod=\"prometheus-monitoring-kube-prometheus-prometheus-1\", prometheus=\"monitoring/monitoring-kube-prometheus-prometheus\", remote_name=\"e64587\", service=\"monitoring-kube-prometheus-prometheus\", severity=\"critical\", url=\"http://k8s-centralm-mimirngi-de1e8b696f-d9a0b2a1383dbad7.elb.us-west-2.amazonaws.com/api/v1/push\"}"
```
Do you have any suggestions for resolving this issue?
