### DISCUSSION TITLE
Getting metrics with duplicated labels, one set including __replica__, but no HA configuration has been enabled.

### DISCUSSION THREAD

**Discussion by wltbenade** [grafana/mimir#5920] [Help and support]
Hey all,

I've come across from weird behaviour that I hope someone can explain to me.

I've set up Mimir using the helm-distributed Helm chart, altering nothing except structuredConfig to S3 storage, and some persistent storage parameters for the various components.

I'm making use of GrafanaAgent CRs to control my ingestion, with an additionalScrapeConfig, running 3 scrape_jobs, defined on a single MetricsInstance to federate metrics from ClusterControl, and an Integration attached to the same MetricsInstance.

What's curious is that my config seems to be producing 2 sets of metrics for everything (one with a __replica__ label, one without), EXCEPT the Integration:
PostgreSQL coming from additionalScrapeConfig
```
pg_up{__replica__="replica-0", cluster="monitoring-system/grafana-agent", clusterid="[REDACTED]", instance="[REDACTED]", job="postgres", source="clustercontrol"}
pg_up{cluster="monitoring-system/grafana-agent", clusterid="[REDACTED]", instance="[REDACTED]", job="postgres", source="clustercontrol"}
```

MSSQL coming from Integration:
```
mssql_build_info{agent_hostname="[REDACTED]", cluster="monitoring-system/grafana-agent", instance="[REDACTED]", job="integrations/mssql", branch="HEAD", goarch="amd64", goos="linux", goversion="go1.20.6", revision="7ff76ca4", tags="netgo,builtinassets,promtail_journal_enabled", version="v0.35.3"}
```

I know it's something to do with my Mimir config, as I've check the metrics/target API, and all seems well there. I should mention that I'm running with HA deduplication off, as I'm still evaluating the stack, so it's single instances all the way.

If anyone has any idea what I'm doing wrong, I would be highly appreciative!

Cheers

**Comment by wltbenade** [comment]
Ok, so another day of digging, which included pulling my ENTIRE test deployment down, and rebuilding piece by piece, reveals that the duplication issue seems to stem from my additionScrapeConfigs defined on my MetricsInstance.

Here's my scrape config:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: additionalscrapeconfigs
  namespace: monitoring-system
stringData:
  jobs.yaml: |
    - job_name: 'clustercontrol'
      scrape_interval: 30s
      metrics_path: '/federate'
      honor_labels: true
      params:
        'match[]':
          - '{job=~"(node|prometheus|postgres|mongo)",instance=~"oss-(pscc-0370|pscc-0371|prcc-0363|drdc-01182|drdc-01183|dsdc-01184|prcc-0078|prcc-0079|pscc-0083|prcc-0616|pscc-0588|pscc-0589).*"}'
      relabel_configs:
        - action: hashmod
          modulus: $(SHARDS)
          source_labels:
          - __address__
          target_label: __tmp_hash
        - action: keep
          regex: $(SHARD)
          source_labels:
          - __tmp_hash
      
      metric_relabel_configs:
        - source_labels: [instance]
          regex: "oss-(pscc-0370|pscc-0371|prcc-0363).*"
          target_label: "clusterid"
          replacement: "CLUSTERID1" 
        - source_labels: [instance]
          regex: "oss-(drdc-01182|drdc-01183|dsdc-01184).*"
          target_label: "clusterid"
          replacement: "CLUSTERID2" 

        - source_labels: [instance]
          regex: "oss-(prcc-0078|prcc-0079|pscc-0083).*"
          target_label: "clusterid"
          replacement: "CLUSTERID3" 
        - source_labels: [instance]
          regex: "oss-(prcc-0616|pscc-0588|pscc-0589).*"
          target_label: "clusterid"
          replacement: "CLUSTERID4"

      static_configs:
        - targets:
          - 'clustercontrolprd:9090'
          - 'clustercontrolp01:9090'
          - 'clustercontrolp02:9090'
          - 'clustercontrolp03:9090'
          - 'clustercontrolp04:9090'
          - 'clustercontrolp05:9090'
          - 'clustercontrolp06:9090'
          - 'clustercontrolp07:9090'
          - 'clustercontrolp08:9090'
          - 'clustercontrolp09:9090'
          - 'clustercontrolp10:9090'
          - 'clustercontrolp11:9090'
          - 'clustercontrolp12:9090'
          - 'clustercontrolp13:9090'
          - 'clustercontrolp14:9090'
          - 'clustercontrolp15:9090'
          - 'clustercontrolp16:9090'
          - 'clustercontrolp17:9090'
          - 'clustercontrolp18:9090'
          - 'clustercontrolp19:9090'
```
