### DISCUSSION TITLE
How those replication and zone awareness work in detail / for my requirements

### DISCUSSION THREAD

**Discussion by JustNZ** [grafana/mimir#6033] [Help and support]
Hello,

So I saw in other posts here something about that the replication_factor should never be lower than 3 and then I read how zone_awareness works and got confused - so I wanna ask for explanation / help here.

I have two Datacenter's and on each Datacenter are two mimir servers running. All four servers should result on one mimir Cluster

So for each mimir Server in the different DC I have this part in the config.
Is that correct? is in this case the replication_factor of 2 correct?

DC1:
```
ingester:
    ring:
       replication_factor: 2
       zone_awareness_enabled: true
       instance_availability_zone: DC1
```

DC2:
```
ingester:
    ring:
       replication_factor: 2
       zone_awareness_enabled: true
       instance_availability_zone: DC2
```
