### DISCUSSION TITLE
Do I need any local persistence if I use remote block storage?

### DISCUSSION THREAD

**Discussion by SunSparc** [grafana/mimir#6081] [Help and support] [answered]
I have a Mimir cluster. I set it up using persistent volumes. It worked well. Then I updated it to use remote block storage. Do I need the persistent volumes anymore?

I have `tsdb` still defined in the `blocks_storage` configuration stanza:
```
  common:
    storage:
      backend: gcs
      gcs:
        bucket_name: <bucket_name>

  blocks_storage:
    storage_prefix: blocks
    tsdb:
      dir: /mimir/tsdb
```
And this is what the volume looks like on one of the Mimir instances:
```
mimir/
  tsdb/
    anonymous/
      01HARX3MVPNWWS3V3JSAES775S/
      01HAS3ZC3PZDXJ5QMV6X2SH317/
      01HASAV3BPG9BEWEH9B99HY3Q5/
      01HASHPTKPVYEPERJAF019730K/
      01HASRJHVP91V9JW4RK9GGWTF6/
      01HASZE93P6PJGRVVQKAHF8EMQ/
      01HAT6A0BPC9HH5KCW6SZ0JKPM/
      chunks_head/
      mimir.shipper.json
      thanos.shipper.json
      wal/
```

Since I am now using `gcs` as the `common.storage.backend`, can I safely remove the `blocks_storage.tsdb` section and discontinue using the persistent volumes?
