### DISCUSSION TITLE
I can see the historical data in S3 bucket only for 2 days. I cant see the data in s3 bucket. What it is causing to delete the metrics in S3 bucket

### DISCUSSION THREAD

**Discussion by frootima** [grafana/mimir#6343] [Help and support]
Hello Team,

I need urgent assistance with Mimir, and the data is being stored in an S3 bucket, however I can only see the last two days of data. I don't see any data when I adjust the time duration to the latest 30 days.

Below is my mimir configuration:
```
multitenancy_enabled: false
#target: all,alertmanager,overrides-exporter

common:
  storage:
    backend: s3
    s3:
      endpoint: s3.XXXX
      bucket_name: psre-o11y-mtf-mimir-blocks
      access_key_id: psre-o11y-storage-mtf
      secret_access_key: XXXXX
      insecure: false

blocks_storage:
  backend: s3
  storage_prefix: blocks
  tsdb:
    retention_period: 12h
    dir: /sys_apps_01/o11ypsre/mimir/logs/ingester

memberlist:
        join_members: [10.31.X.X,10.31.X.X,10.30.X.X]


compactor:
  data_dir: /sys_apps_01/o11ypsre/mimir/logs/compactor
  compaction_interval: 15m
  cleanup_interval: 15m
  sharding_ring:
    instance_addr: 10.31.X.X
    kvstore:
      store: memberlist



distributor:
  ring:
    instance_addr: 10.31.X.X
    kvstore:
      store: memberlist
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      store: inmemory

ingester:
  ring:
    instance_addr: 10.31.X.X
    kvstore:
      store: memberlist
    replication_factor: 2


ruler_storage:
  backend: s3
  storage_prefix: ruler

ruler:
  rule_path: /tmp/ruler
  ring:
    heartbeat_period: 15s
    heartbeat_timeout: 1m

server:
  http_listen_address: "10.31.X.X"
  http_listen_port: 9009
  log_level: info

store_gateway:
  sharding_ring:
    kvstore:
      store: memberlist
    replication_factor: 2
usage_stats:
   enabled: false

limits:
  max_label_names_per_series: 200
  max_global_series_per_user: 12000000
  ingestion_rate: 400000
  ingestion_burst_size: 8000000
  out_of_order_time_window: 5m
  compactor_blocks_retention_period: 2d
  accept_ha_samples: true
  ha_cluster_label: cluster
  ha_replica_label: __replica__
```
