### DISCUSSION TITLE
Mimir grafana/Kube-state-metrics

### DISCUSSION THREAD

**Discussion by rodrigoccaldas** [grafana/mimir#6367] [Help and support]
Hello,
We are facing some issues when trying to have our Kubernetes dashboards with metrics on grafana mimir. We already have KSM helmrelease (chart v5.7.0) installed on the cluster with the following values:

**KSM values**
```
    namespaceOverride: ""
    rbac:
      create: true
    releaseLabel: true
    prometheus:
      monitor:
        enabled: true
        interval: ""
        sampleLimit: 0
        targetLimit: 0
        labelLimit: 0
        labelNameLengthLimit: 0
        labelValueLengthLimit: 0
        scrapeTimeout: ""
        proxyUrl: ""
        honorLabels: true
        metricRelabelings: []
        relabelings: []
    selfMonitor:
      enabled: false

```

**Grafana mimir datasource:**
```
    datasources:
     datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Mimir
        type: prometheus
        url: http://mimir-nginx.mimir.svc.cluster.local/prometheus
        isDefault: true
        jsonData:
          httpHeaderName1: 'X-Scope-OrgID'
        secureJsonData:
          httpHeaderValue1: 'metamonitoring'
```
**Mimir metamonitoring values:**
```
    metaMonitoring:
      dashboards:
        enabled: true
        annotations:
          k8s-sidecar-target-directory: "/tmp/dashboards/mimir_dashboard"
          grafana_folder: "mimir"
        labels:
          grafana_dashboard: "1"
      serviceMonitor:
        enabled: true
      grafanaAgent:
        enabled: true
        imageRepo:
          configReloader:
            repo: quay.io
            image: prometheus-operator/prometheus-config-reloader
            tag: v0.47.0
          grafanaAgent:
            repo: docker.io
            image: grafana/agent
            tag: v0.29.0
        installOperator: true
        metrics:
          scrapeK8s:
            enabled: true
            kubeStateMetrics:
              namespace: kube-system
              labelSelectors:
                app.kubernetes.io/name: kube-state-metrics
```

<img width="1493" alt="image" src="https://github.com/grafana/mimir/assets/48653110/2b30473e-e46e-41be-94b3-141f5eaeac61">

Mimir chart version
```
chart: mimir-distributed
version: "5.1.0"
```

Also, we are able to see metrics when port-forwarding KSM pod.
<img width="1498" alt="image" src="https://github.com/grafana/mimir/assets/48653110/c17367a4-aa10-4310-b925-127660c824f0">

Any ideia why we are getting no data on k8s grafana dashboards? Is the grafana agent installed with metamonitoring enough or do we need to install another one in the same cluster?
Thanks a lot in advance.
