### DISCUSSION TITLE
expanding series: failed to fetch some blocks - err-mimir-store-consistency-check-failed

### DISCUSSION THREAD

**Discussion by kadhamecha-conga** [grafana/mimir#6372] [General]
hi team,

i'm getting this error  in store-gateway  as  **expanding series: failed to fetch some blocks (err-mimir-store-consistency-check-failed)**.

I see no pvc size issue for store-gateway, lot of space is still left.

query-frontend logs are as: 

` ts=2023-10-13T14:16:19.977205199Z caller=retry.go:78 level=error user=anonymous msg="error processing request" try=0 err="rpc error: code = Code(500) desc = {\"status\":\"error\",\"errorType\":\"internal\",\"error\":\"expanding series: failed to fetch some blocks (err-mimir-store-consistency-check-failed). The failed blocks are: 01HCBMXFQ55KYYYP5J05BKS12H 01HCE4N16N6EVZJKZKKN74Z090\"}"`

can you please help me to resolve it ?

mimir - 2.7.1

config for store-gateway: 
```
store_gateway:
  persistentVolume:
    storageClass: gp2
    size: 50Gi
  replicas: 6
  resources:
    limits:
      memory: 10Gi
    requests:
      cpu: 1
      memory: 8Gi
```

thanks.
