### DISCUSSION TITLE
Prometheus fails to push with "at least 2 live replicas required across different availability zones, could only find 1" despite there being enough replicas

### DISCUSSION THREAD

**Discussion by costa-danilo** [grafana/mimir#6400] [Help and support] [answered]
#### Describe the bug
Prometheus was unable to push to mimir returning error:
`msg="Failed to send batch, retrying" err="server returned HTTP status 500 Internal Server Error: at least 2 live replicas required across different availability zones, could only find 1 - unhealthy instances:`

This happened despite there being enough replicas available, details in the next section.

#### To Reproduce
I have 6 nodes, 2 for AZ

My mimir configuration is as follows:

```
  ingester:
    replicas: 18
    zoneAwareReplication:
      zones:
        - name: ad1
          nodeSelector:
            topology.kubernetes.io/zone: AZ-1
        - name: ad2
          nodeSelector:
            topology.kubernetes.io/zone: AZ-2
        - name: ad3
          nodeSelector:
            topology.kubernetes.io/zone: AZ-3
  store_gateway:
    replicas: 18
    zoneAwareReplication:
      zones:
        - name: ad1
          nodeSelector:
            topology.kubernetes.io/zone: AZ-1
        - name: ad2
          nodeSelector:
            topology.kubernetes.io/zone: AZ-2
        - name: ad3
          nodeSelector:
            topology.kubernetes.io/zone: AZ-3
  alertmanager:
    replicas: 6
    zoneAwareReplication:
      zones:
        - name: ad1
          nodeSelector:
            topology.kubernetes.io/zone: AZ-1
        - name: ad2
          nodeSelector:
            topology.kubernetes.io/zone: AZ-2
        - name: ad3
          nodeSelector:
            topology.kubernetes.io/zone: AZ-3
  nginx:
    replicas: 6
  compactor:
    replicas: 6
  distributor:
    replicas: 12
  querier:
    replicas: 12
  query_frontend:
    replicas: 6
  query_scheduler:
    replicas: 12
  ruler:
    replicas: 6
```

The nodes are tagged correctly and every replica is live, so for example the ingester has 6 replicas per AZ:
monitoring-mimir-ingester-ad1-(0 to 5)
monitoring-mimir-ingester-ad2-(0 to 5)
monitoring-mimir-ingester-ad3-(0 to 5)

What happened is that 2 (with two different AZs) of my 6 nodes became unavailable, so what's left is 2 nodes for one AZ and one node for the rest. Because in the Ingester example there would be 6 replicas in an AZ and 3 in each of the other two.
These remaining replicas so why couldn't prometheus push to Mimir? Am I doing something wrong with the configuration?
