### DISCUSSION TITLE
Mimir Ruler API unable to list rules with local storage

### DISCUSSION THREAD

**Discussion by andreimiclea99** [grafana/mimir#6639] [Help and support]
#### Describe the bug

I using Mimir 2.10.0 and deployed it using the "mimir-distributed-5.0.0" helm chart on k8s. I problem is that i can't see the Grafana mimir rules on Grafna UI nor by using the "mimirtool", the error is` body="unable to read rule dir /tmp/rules/anonymous: open /tmp/rules/anonymous: no such file or directory\n"`

the command is: `./mimirtool rules list --address=http://url.com --id=anonymous`

The rules are inside a Cofigmap in k8s.

#### To Reproduce
Steps to reproduce the behaviour:
```
mimir:
  config: |
    multitenancy_enabled: false
    no_auth_tenant: "anonymous"
    ruler:
      alertmanager_url: http://url/alertmanager
      enable_api: true
      
ruler:
  enabled: true
  extraVolumes: 
    - name: config-map-volume
      configMap:
        name: rules-configmap

  extraVolumeMounts:
    - name: config-map-volume
      mountPath: /tmp/rules


  extraArgs:
    ruler-storage.backend: local
    ruler-storage.local.directory: /tmp/rules
```

#### Expected behavior

According to https://grafana.com/docs/mimir/latest/references/architecture/components/ruler/#local-storage, was expected for this to work automatically.

#### Additional Context

I want to add that the rules are seen by the alertmanager and everything is good on that part, but I would like a way to see the rules.
