### DISCUSSION TITLE
Config use basicAuth and X-Scope-OrgID not query success in Grafana

### DISCUSSION THREAD

**Discussion by hainamtvvt** [grafana/mimir#6754] [Help and support]
#### Describe the bug
I want to use feature basicAuthen and i want to display name folder in bucket (*not anonymous*) in S3 
I following docs: https://grafana.com/docs/mimir/latest/manage/secure/authentication-and-authorization/

But When I query metrics in Grafana not successfull

In Grafana config add datasource with specify info of basicAuth.

**Comment by dimitarvdimitrov** [comment]
If you use the helm chart to deploy Mimir, then you can set basic auth on the nginx that the chart deploys. In that case you need to supply both `x-scope-orgid` and `Authorization` (basic auth) headers in requests.

**Reply by DayaDotan** [reply]
Hey @dimitarvdimitrov 

I am facing a similar issue.  
I have configured in the `values.yaml` file:
```yaml
nginx:
  basicAuth:
    enabled: true
    username: <username>
    password: <password>
```

And in Prometheus:
```yaml
remote_write:
  - URL: <mimir_url>
    basic_auth:
      username: <username>
      password: <password>
```

Up to this point, everything worked, and I could display the metrics in Grafana using the same parameters (username and password in Grafana).

However, when I add the headers in Prometheus:
```yaml
remote_write:
  - url:  <mimir_url>
    basic_auth:
      username: <username>
      password: <password>
    headers:
      X-Scope-OrgID: tenant1
```

I no longer receive the metrics in Grafana.

Do you have any ideas or suggestions on what needs to be changed in the configs to continue receiving metrics under a specific folder for the tenant instead of "anonymous"?
