### DISCUSSION TITLE
Config affinity in for Nginx-deployment not work

### DISCUSSION THREAD

**Discussion by hainamtvvt** [grafana/mimir#6834] [Help and support]
I have config for Nginx:
```
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
            - nginx
        topologyKey: "kubernetes.io/hostname"
```
but error:
![Screenshot 2023-12-06 135328](https://github.com/grafana/mimir/assets/63154819/a8e7b8bd-e3ed-411c-9ce8-c9d50bf5fdb0)

**Comment by dimitarvdimitrov** [comment]
affinity for the legacy nginx deployment must be a string:

```
affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
            - nginx
        topologyKey: "kubernetes.io/hostname"
```

if you use the new gateway deployment, then you can still use regular objects. See [Migrate to the unified gateway deployment for NGINX and GEM gateway in Helm](https://grafana.com/docs/helm-charts/mimir-distributed/latest/migration-guides/migrate-to-unified-proxy-deployment/)
