### DISCUSSION TITLE
Import data from prometheus tsdb failed

### DISCUSSION THREAD

**Discussion by oanqa** [grafana/mimir#6835] [Help and support] [answered]
when trying to backfill using mimirtool, there are error with message `ERRO[0008] failed uploading block                        error="block validation failed: failed to create temporary block directory" path=./01HG696A6PTMRK5QN351D7VXR5`

then if we try again to backfill the same block, this will result to this message
```
INFO[0000] making request to start block upload          block=01HG696A6PTMRK5QN351D7VXR5 file=meta.json path=./01HG696A6PTMRK5QN351D7VXR5
ERRO[0000] response                                      body="block validation failed\n" status="400 Bad Request"
ERRO[0000] failed uploading block                        error="request to start block upload failed: POST request to http://mimir-monolithic:8080/api/v1/upload/block/01HG696A6PTMRK5QN351D7VXR5/start failed: server returned HTTP status: 400 Bad Request, body: \"block validation failed\\n\"" path=./01HG696A6PTMRK5QN351D7VXR5
``` 

so we cannot upload the block, and cannot migrate to mimir from prometheus

**Comment by pstibrany** [comment]
Hello. Error message indicates that compactor cannot create directory in the directory configured by `-compactor.data-dir` option (it defaults to `./data-compactor/`. Please make sure that compactor has write access to that directory.

**Reply by oanqa** [reply]
Hi, thank you for response.

for your information this is my mimir config
```yaml
compactor:
      compaction_interval: 30m
      data_dir: /data/compactor
      deletion_delay: 2h
      first_level_compaction_wait_period: 25m
      max_closing_blocks_concurrency: 2
      max_opening_blocks_concurrency: 4
      sharding_ring:
        wait_stability_min_duration: 1m
      symbols_flushers_concurrency: 4
    frontend:
      parallelize_shardable_queries: true
    frontend_worker:
      frontend_address: mimir-monolithic-headless.monitoring.svc:9095
      grpc_client_config:
        max_send_msg_size: 419430400
```

i think that compactor can write in that directory
```
~ $ ls -la /data/compactor/
total 12
drwxr-sr-x    3 10001    10001         4096 Dec  6 09:05 .
drwxrwsr-x    7 root     10001         4096 Dec  6 08:26 ..
drwxr-sr-x    3 10001    10001         4096 Dec  6 08:26 compactor-meta-anonymous
```
