### DISCUSSION TITLE
How to set resource values in mimir-distributed helm chart?

### DISCUSSION THREAD

**Discussion by jonli662** [grafana/mimir#6847] [Help and support] [answered]
How do I set Resources (cpu/memory requests/limits) in my custom values-file for index-cache, metadata-cache, chunks-cache and results-cache for the mimir-distributed chart?
Theese seems to be hardcoded to null and not to accept dict as other components.
The thing is that our cluster have rules that forces us to specify limit-values: "forbidden: failed quota: xxx-resource-quota: must specify limits.cpu,limits.memory"

This does not work (the chart ignores it):
```
chunks-cache:
  enabled: false
  replicas: 2
  resources:
    limits:
      cpu: 0.3
      memory: 128Mi
    requests:
      cpu: 0.2
      memory: 128Mi
```
Is it because `resources: null` here?
https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L1822

Any idea how to solve this?

**Comment by dimitarvdimitrov** [comment, marked as answer]
I was able to get it working with the values you provided (plus toggling `enabled`)

```yaml
chunks-cache:
  enabled: true
  replicas: 2
  resources:
    limits:
      cpu: 0.3
      memory: 128Mi
    requests:
      cpu: 0.2
      memory: 128Mi
memcachedExporter:
  resources:
    limits:
      cpu: 0.3
      memory: 128Mi
    requests:
      cpu: 0.2
      memory: 128Mi
```

<details><summary>StatefulSet</summary>
<p>

```yaml
# Source: mimir-distributed/templates/chunks-cache/chunks-cache-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: release-name-mimir-chunks-cache
  labels:
    helm.sh/chart: mimir-distributed-5.2.0-weekly.265
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: memcached
    app.kubernetes.io/version: "r265"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
  namespace: "mimir-dedicated-44"
spec:
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: mimir
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/component: chunks-cache
  updateStrategy:
    type: RollingUpdate
  serviceName: release-name-mimir-chunks-cache

  template:
    metadata:
      labels:
        helm.sh/chart: mimir-distributed-5.2.0-weekly.265
        app.kubernetes.io/name: mimir
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "r265"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: chunks-cache
      annotations:

    spec:
      serviceAccountName: release-name-mimir
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        []
      nodeSelector:
        {}
      affinity:
        {}

      tolerations:
        []
      terminationGracePeriodSeconds: 60
      containers:
        - name: memcached
          image: memcached:1.6.22-alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.3
              memory: 128Mi
            requests:
              cpu: 0.2
              memory: 128Mi
          ports:
            - containerPort: 11211
              name: client
          args:
            - -m 8192
            - --extended=modern,track_sizes
            - -I 1m
            - -c 16384
            - -v
            - -u 11211
          env:
          envFrom:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
        - name: exporter
          image: prom/memcached-exporter:v0.13.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9150
              name: http-metrics
          args:
            - "--memcached.address=localhost:11211"
            - "--web.listen-address=0.0.0.0:9150"
          resources:
            limits:
              cpu: 0.3
              memory: 128Mi
            requests:
              cpu: 0.2
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
```

</p>
</details>
