### DISCUSSION TITLE
Cloudwatch metrics alert is not going to Firing state through Mimir Alertmanager

### DISCUSSION THREAD

**Discussion by Vaibhav-1995** [grafana/mimir#6881] [Help and support]
#### Issue
We are using prometheus-cloudwatch-exporter to scrape cloudwatch metrics and push them to mimir datasource. We are able to see those metrics in grafana explore under mimir datasource. But when we created alert rule in mimir ruler it is not going to Firing State even though the metric exceeds threshold value.

#### Please refer below details : -
![image](https://github.com/grafana/mimir/assets/103194544/c204b211-0e1f-42a5-9166-4b20f4dbd99a)

Alert rule in ruler configmap -
![image](https://github.com/grafana/mimir/assets/103194544/b6a888db-1856-4e01-9ac5-df9f5ce9be61)

Not going to Firing State from listed rule -
![image](https://github.com/grafana/mimir/assets/103194544/7d6d29c0-37b5-4a05-a76e-b36e9821d4ae)

#### Environment
- Infrastructure:  Kubernetes
- Mimir Version: 2.9.0
- Prometheus Cloudwatch Exporter Version: 0.25.1
- Deployment tool:  helm

#### Expected behavior

It should go to the Firing state and alert should get triggered for set rule as all required configurations in alertmanger are done.

Also if when I tested the same alert rule in grafana UI by creating it with Grafana managed alert then its going in firing state. Please see below image -
![image](https://github.com/grafana/mimir/assets/103194544/753c2006-d7c2-4671-8e09-f16fd74f9087)

**Comment by Vaibhav-1995** [comment]
HI Team,

Any updates?

**Comment by pstibrany** [comment]
Mimir evaluates rules as instant queries at "now" timestamp (in fact, `now - 1m` by default). At that point there are no series above 30, so no alert notification is sent.

<img width="1999" alt="SCR-20231211-jmyv" src="https://github.com/grafana/mimir/assets/895919/f1d7596c-ad65-4bc0-a34e-b66a1d946cfb">

**Reply by Vaibhav-1995** [reply]
@pstibrany  Thanks for you reply

Ok, Got it. 
But what can be done then so that we can get latest series data on graph in explore and I can enable alerting on those metrics. Because I have mentioned **scrape interval** time in prometheus job as **1m** and in cloudwatch-exporter values config file mentioned **period second** is **60**. But still latest data not getting in grafana explore.

See below prometheus job config - 
```yaml
      jobList:
       - job_name: 'cloudwatch-exporter'
         kubernetes_sd_configs:
         - role: service
         scrape_interval: 1m
         metrics_path: xxx
         relabel_configs:
           - target_label: __address__
             replacement: xxx-prometheus-cloudwatch-exporter.xxx.svc.cluster.local:9106
```

And please see below cloudwatch exporter config - 
```yaml
# Configuration is rendered with `tpl` function, therefore you can use any Helm variables and/or templates here
config: |-
  # This is the default configuration for prometheus-cloudwatch-exporter
  region: ap-south-1
  period_seconds: 60
  metrics:
  - aws_dimensions:
    - InstanceId
    aws_metric_name: CPUUtilization
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
```
