### DISCUSSION TITLE
Using Mimir with MinIO as storage backend

### DISCUSSION THREAD

**Discussion by MarcelGlaub** [grafana/mimir#6914] [Help and support] [answered]
I am trying to configure Mimir to use a MinIO VM as storage backend. With my custom values shown below, mimir complains that activity_tracker.filepath is not a path on a writeable volume:
`The 'activity_tracker.filepath' in 'mimir.config' should be set to a path that is on a writeable volume. For example: '/active-query-tracker/activity.log'`

I have not changed the default value (/active-query-tracker/activity.log). I am somewhat lost as to what I need to change this path to and would appreciate some help. 😄 

  ```
global:
    dnsService: rke2-coredns-rke2-coredns
  runtimeConfig:
    overrides:
      anonymous:
        ingestion_tenant_shard_size: 9
        max_global_series_per_user: 0
        max_fetched_series_per_query: 0  
        compactor_blocks_retention_period: 1d
  minio:
    enabled: false
  mimir:
    config: |
      common:
        storage:
          backend: S3
          s3: 
            endpoint: http://X.X.X.X:9000
            access_key_id: <username>
            secret_access_key: <password>
            insecure: true
  
      blocks_storage:
        backend: s3
        storage_prefix: blocks
        tsdb:
          retention_period: 168h
          dir: /data/ingester
  
      alertmanager_storage:
        backend: s3
        s3:
          bucket_name: mimir-alertmanager
  
      ruler_storage:
        backend: s3
        s3:   
          bucket_name: mimir-ruler
  
      blocks_storage:
        backend: s3
        s3:    
          bucket_name: mimir-blocks      
  distributor:
    extraArgs:
      distributor.ingestion-rate-limit: 0          
  ingester: 
    extraArgs:
      ingester.max-global-series-per-user: 0
      ingester.max-global-series-per-metric: 0
  nginx:
    replicas: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - host:  mimir.k8s-internal.datacenter.de 
          paths:
            - path: /     
              pathType: Prefix
      tls:
        - secretName: mimir-nginx-tls
          hosts:
            - mimir.k8s-internal.datacenter.de        
    basicAuth:
      enabled: true
      username: <username>
      password: <password>
```
