### DISCUSSION TITLE
No data on mimir/reads dashboard

### DISCUSSION THREAD

**Discussion by rosh0450** [grafana/mimir#7081] [Help and support] [answered]
I have enabled meta monitoring for my grafana mimir:

values.yaml 
```
metaMonitoring:
  dashboards:
    enabled: false

  serviceMonitor:
    enabled: true

  grafanaAgent:
    enabled: true

    metrics:
      enabled: true
      remote:
        url: "http://mimir-nginx.mimir.svc:80/api/v1/push"

      scrapeK8s:
        enabled: true
```

and i am able to see components specific metrics like `cortex_ingester_active_series`, `cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds` and others.

But when i imported the mimir/reads dashboard, it is completely empty.
![image](https://github.com/grafana/mimir/assets/59838688/fce6dbb4-2978-46b0-b54b-6ae3f590fb14)

Same is the case with other dashboards like mimir/write and others.

But for some odd reason when i remove the `rate` operation from the queries, i am getting correct data.
Example with `Label names queries / sec` panel in mimir/reads dashboard:
Before removing:
![image](https://github.com/grafana/mimir/assets/59838688/d49a87db-b8be-441e-bc14-fc5c0264150b)

After removing `rate` operation:
![image](https://github.com/grafana/mimir/assets/59838688/5b269934-acc6-4754-9ab8-b6ffa755df9d)

What can be the reason ?

Thanks.

**Comment by dimitarvdimitrov** [comment, marked as answer]
i suspect the scrape interval of the datasource and the actual scrape interval of the metamonitoring agent aren't aligned. The metamonitoring agent scrapes at 1m, so if the scrape interval of the datasource is anything lower, then `rate` functions wouldn't work properly. I recommend checking the configuration of the Grafana datasource.

**Reply by rosh0450** [reply]
So i changed the scrape duration for the data source(mimir) to 60s. Now I do see some data in the mimir/read dashboard. But the data doesn't seem correct.

![image](https://github.com/grafana/mimir/assets/59838688/6cc472fc-0f2f-4dc7-b051-407b8c651723)

For instance here requests/sec for query frontend is very low but it can't be correct because i have few dashboards deployed which are continuously reading from mimir as their data source.

**Comment by sojjan1337** [comment]
I just enabled the prometheusRule: under metaMonitoring in the mimir values-file.

```
prometheusRule:
  enabled: true
  mimirRules: true
  mimirAlerts: true
```

Such a simple thing, yet i didn't find an example how to fix it in the docs.
