### DISCUSSION TITLE
`/prometheus` endpoint gives 404 error page

### DISCUSSION THREAD

**Discussion by ryayon** [grafana/mimir#7082] [Help and support] [answered]
#### Describe the bug
`http://<ingress-host>/prometheus` gives 404 error page.
Also get 404 error from mimir-nginx pod using `curl http://mimir-distributed-nginx.<namespace>.svc/prometheus`

Both `api/v1/status/buildinfo` and `api/v1/status/buildinfo` endpoints are OK both Ingress and mimir-nginx pod (using internal service name)

#### To Reproduce
Just follow the documentation

#### Expected behavior

`/prometheus` endpoint should be requestable both from navigator or Grafana

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm 
                              [EDIT] v5.2.0-weekly.270

#### Additional Context

```
alertmanager:
  enabled: false

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: 'XXXXXX'
          access_key_id: 'YYYYYYYY'
          secret_access_key: 'ZZZZZZZZZ'
          insecure: true
          bucket_name: mimir
    blocks_storage:
      backend: s3
      storage_prefix: blocks

nginx:
  ingress:
    enabled: true
    hosts:
      - host: mimir.sndsdskd.qdqdqd
        paths:
          - path: /
            pathType: Prefix

overrides_exporter:
  enabled: false

query_scheduler:
  enabled: false

ruler:
  enabled: false
```
