### DISCUSSION TITLE
Mimir deduplication

### DISCUSSION THREAD

**Discussion by tagathi** [grafana/mimir#7083] [Help and support] [answered]
Hello,
I have deployed Mimir via helm. 
I initially deployed Mimir, I had duplicate entries from the redundant Prometheis.
So I enabled deduplication by configuring the following part in values.yaml file:
```
structuredConfig:
    limits:
      accept_ha_samples: true
      ha_cluster_label: prom_cluster
      ha_replica_label: __replica__
```
I also added the following configuration for distributor.ha_tracker,
```
ha_tracker:
        enable_ha_tracker: true
        ha_tracker_update_timeout_jitter_max: 10s
        ha_tracker_failover_timeout: 180s
        ha_tracker_update_timeout: 120s
        kvstore:
          store: etcd
          etcd:
            endpoints: 
              - etcd.etcd.svc.cluster.local:2379
            username: root
            password: xxxxxxx
```
but it turned out that I had put it in a totally wrong place, so it was ignored. Etcd did not show any keys, checking the ha_tracker status returned empty values, but deduplication worked (I no longer had duplicates) .
After some troubleshooting, during which I realized I had added the ha_tracker config in a wrong place, I correctly  added the above config under structuredConfig and now etcd is in use, and by checking the ha_tracker's page I can see elected cluster/replica.
So my question is, how does deduplication work if distributor.ha_tracker is not configured, but only if accept_ha_samples is set to true?
