### DISCUSSION TITLE
How to connect Grafana-Agent With Mimir

### DISCUSSION THREAD

**Discussion by SanthoshKumar18245** [grafana/mimir#7105] [Help and support]
guide me please , I know this is irrelevant .. I'll tell my story..

I installed grafana and prometheus and node exporter and cloud,jmx and mysql exporters. then my senior mentioned the grafana agent is able to do job which all exporters can do, so i decided to switch the agent with mimir but i can't able to configure these two so i decided to ask help here ...please help me 

agent.yaml
```
server:
log_level: info

metrics:
wal_directory: /tmp/agent
global:
scrape_interval: 60s
remote_write:
- url: http://127.0.0.1:9009/api/v1/push

integrations:
node_exporter:
enabled: true
```
please help me i have been trying to connect almost five days );
<img width="932" alt="git" src="https://github.com/grafana/mimir/assets/133011171/2883fc58-45a1-4bc7-8529-014be7020d1d">

**Comment by dimitarvdimitrov** [comment]
judging by the error you are seeing you should add a tenant ID to the requests. In the grafana agernt config

```yaml
server:
	log_level: info

metrics:
	wal_directory: /tmp/agent
	global:
		scrape_interval: 60s
		remote_write:
			- url: http://127.0.0.1:9009/api/v1/push
			  headers:
                X-Scope-OrgID: monitoring

integrations:
	node_exporter:
		enabled: true
```
