### DISCUSSION TITLE
Ingester pods failing to write to S3 bucket with following message "mkdir /blocks: permission denied"

### DISCUSSION THREAD

**Discussion by QuantumEnigmaa** [grafana/mimir#7200] [Help and support] [answered]
I have `mimir-distributed` chart deployed on a Kubernetes cluster. The object storage is configured as such : 
```
      structuredConfig:
        blocks_storage:
          backend: s3
          bucket_store:
            max_chunk_pool_bytes: 12884901888
            sync_dir: /data/tsdb-sync
          s3:
            bucket_name: <my_bucket>
        common:
          storage:
            s3:
              endpoint: <my_endpoint>
              region: <my_region>
            type: s3
```
To access this bucket, pods use the IRSA (Iam Role for Service Account) method and thus the `mimir` serviceaccount used by all mimir pods has the following annotation : `eks.amazonaws.com/role-arn: arn:aws:iam::<role_arn>:role/<role_name>`. This role has a policy allowing to create, get and delete objects in S3.
So basically all pods using the `mimir` service account should be able to create or retrieve objects from S3. 

I know this method works because this is what we use with our Loki setup on the same cluster and `loki-write` pods are able to create objects on their S3 bucket.

However, with mimit, `mimir-ingester` pods fail to push their data to S3 with the following message : 
```
ts=2024-01-24T10:08:25.256843691Z caller=shipper.go:162 level=error user=anonymous msg="uploading new block to long-term storage failed" block=01HMXBFJ4P2MHKHS3ER9YYC7XP err="upload chunks: upload file /data/tsdb/anonymous/01HMXBFJ4P2MHKHS3ER9YYC7XP/chunks/000001 as 01HMXBFJ4P2MHKHS3ER9YYC7XP/chunks/000001: mkdir /blocks: permission denied"
```
I checked on grafana and the pods do get metrics as I can see those, they're just not able to push it to S3.

Do you have an idea what might be causing this issue ?

**Comment by dimitarvdimitrov** [comment]
this looks like a breaking change in the 5.2 helm chart. It should be fixed in 5.2.1 (released just now). See https://github.com/grafana/mimir/issues/7196

**Comment by QuantumEnigmaa** [comment]
Thank you very much @dimitarvdimitrov for the answer, the 5.2.1 release did solve this, but now I have the following error message from the `ingester` pods : 
```
error loading config from /etc/mimir/mimir.yaml: Error parsing config file: can't unmarshal common config: key "blocks_storage": yaml: unmarshal errors:
  line 30: field type not found in type bucket.StorageBackendConfig
```
(some of them have `ruler_storage` instead of `blocks_storage`)

My `mimir-config` configmap is as follows (showing only the relevant parts) : 
```
    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data/tsdb-sync
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
      s3:
        bucket_name: <my_bucket>
    ruler_storage:
      s3:
        bucket_name: <my_bucket>
    alertmanager_storage:
      s3:
        bucket_name: <my_bucket>
    common:
      storage:
        s3:
          endpoint: <my_endpoint>
          region: <my_region>
        type: s3
```
So I'm a bit troubled by the mention of `bucket.StorageBackendConfig` as it's not mentioned in the [official doc](https://grafana.com/docs/mimir/latest/configure/configure-object-storage-backend/#s3)

Do you have any idea what might be causing this ?
