### DISCUSSION TITLE
Mimir Distributors Timing Out with 500 Errors, Despite Scaling

### DISCUSSION THREAD

**Discussion by GreyLilac09** [grafana/mimir#7517] [Help and support]
We are running the mimir-distributed chart. Once the # of ingested samples/sec surpasses a certain level, the number of 500 errors from the distributor components increases, no matter how much we try to scale the number of distributors and ingesters. 

<img width="1163" alt="Screenshot 2024-03-01 at 11 59 46 AM" src="https://github.com/grafana/mimir/assets/161868481/4c73e47a-0413-4adc-a595-f2aed0a31875">

Specifically, these 500 errors seem to be coming ContextDeadlineExceeded errors from the distributor component in attempting to connect to the ingesters.

<img width="1527" alt="Screenshot 2024-03-01 at 12 00 43 PM" src="https://github.com/grafana/mimir/assets/161868481/557b3dee-076e-438b-9a8d-13af3d164f85">

All the 500 errors seem to be the same:
```
ts=2024-03-01T17:02:06.833122331Z caller=logging.go:86 level=warn traceID=... msg="POST /api/v1/push (500) 2.013987101s Response: \"failed pushing to ingester: rpc error: code = DeadlineExceeded desc = context deadline exceeded\\n\" ws: false; Accept-Encoding: identity; Content-Encoding: snappy; Content-Length: 558457; ... X-Forwarded-Port: 443; X-Forwarded-Proto: https; X-Forwarded-Scheme: https; X-Prometheus-Remote-Write-Version: 0.1.0; ... X-Request-Id: 68522a3a2faa964e4130ae779d0fc049; X-Scheme: https; "
```

There doesn't seem to be a resource shortage; the ingester/distributors are not hitting their limits
<img width="1536" alt="Screenshot 2024-03-01 at 12 05 09 PM" src="https://github.com/grafana/mimir/assets/161868481/72ee6850-d97c-4cd6-9777-4cc169ae79ca">

Here are some things we've tried to no effect:
1. doubling the # of distributors/increasing the # of ingesters
2. increasing the # of IOPS on our S3 storage
3. increasing the mimir limit overrides (max_global_series_per_user/ max_global_series_per_metric/ingestion_burst_size/ingestion_rate)

Anyone have any tips on reducing the # of 5xx errors?

Our config we're using in the mimir-distributed helm chart:
```
runtimeConfig:
  overrides:
    anonymous:
      max_global_series_per_user: 25000000
      max_global_series_per_metric: 1500000
      ingestion_rate: 1000000
      ingestion_burst_size: 12000000
      max_label_names_per_series: 50
....
mimir:
  structuredConfig:
    multitenancy_enabled: false
    server:
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
    ingester:
      ring:
        replication_factor: 2
```
