### DISCUSSION TITLE
Missing data around ingesters memberlist but perfect from store

### DISCUSSION THREAD

**Discussion by catinsnowright** [grafana/mimir#7585] [Help and support] [answered]
Hi Team,
I am playing with Mimir to understand if i can use it in my cluster(deploy components - only puppet) - current build pretty much similar to Play-with-mimir article.  I am using only one tenant. 

5 instances with 5 Grafana Agent Flow mode each, writing node_exporter data to 3 Monolithic mode Mimirs which are behind Nginx load balancer, s3 storage - Minio. 

My problem is that after adding mimir datasource i see gaps of missing data for last 12 hours(which i am sure - tsdb default retention time period), but after - data perfectly consistent without any gaps.

I have removed all retention options and i still got 2 hours period with gaps(because of block ranges period), but rest  - complete perfect.

Also when i am refreshing panel every time it shows different data.
When i trying to debug - I have added each mimir as a separate source and for the same period of time each mimir has different data. Gaps from different sources covering by different ingesters. 

I might not understand if it's by design and the only way to see ingesters data - to use only one igester or with consul. 

How can i make grafana shows me panels without missing data when i see the panel in my grafana dashboards? 

I have been reading and experimenting with all configuration from issues here in git - but no luck. 

Could someone tell me the right direction?  

Thank you in advance. 

------------------------------------------------------------------------------------------------------------------------------------
At the beginning i have pretty much simple config to make sure most of configuration are default, but after i comes with one suggestion - 

https://github.com/grafana/mimir/discussions/4696#discussioncomment-8647567

So currently i have config:

```
alertmanager:
    sharding_ring:
        instance_addr: 0.0.0.0
alertmanager_storage:
    backend: s3
    s3:
        access_key_id: mimir_aki
        bucket_name: cluster1-alertmanager
        endpoint: miniostrg.dev-env.default.com
        insecure: true
        secret_access_key: '********'
blocks_storage:
    backend: s3
    bucket_store:
        ignore_blocks_within: 0s
        ignore_deletion_mark_delay: 30m0s
        metadata_cache:
            bucket_index_content_ttl: 3m0s
        sync_dir: /apps/mimir/tsdb-sync
        sync_interval: 5m0s
    s3:
        access_key_id: mimir_aki
        bucket_name: cluster1-tsdb
        endpoint: miniostrg.dev-env.default.com
        insecure: true
        secret_access_key: '********'
    tsdb:
        dir: /apps/mimir/tsdb
compactor:
    cleanup_interval: 10m0s
    compaction_interval: 15m0s
    data_dir: /apps/mimir/compactor
    first_level_compaction_wait_period: 20m0s
    max_closing_blocks_concurrency: 2
    max_opening_blocks_concurrency: 4
    sharding_ring:
        instance_addr: 0.0.0.0
        wait_stability_min_duration: 1m0s
    symbols_flushers_concurrency: 4
distributor:
    ring:
        instance_addr: 0.0.0.0
frontend:
    address: 0.0.0.0
    align_queries_with_step: true
    cache_results: true
    grpc_client_config:
        grpc_compression: snappy
    log_queries_longer_than: 1m0s
    max_outstanding_per_tenant: 4096
    results_cache:
        backend: memcached
        compression: snappy
        memcached:
            addresses: test-dev-cache.default.com:11211
            timeout: 1s
    scheduler_worker_concurrency: 2048
frontend_worker:
    grpc_client_config:
        max_send_msg_size: 419430400
ingester:
    ring:
        instance_addr: 0.0.0.0
        min_ready_duration: 0s
        num_tokens: 512
        tokens_file_path: /apps/mimir/tokens
ingester_client:
    grpc_client_config:
        grpc_compression: snappy
limits:
    compactor_blocks_retention_period: 1y
    compactor_split_groups: 8
    ingestion_burst_size: 350000
    ingestion_rate: 60000
    max_global_series_per_user: 0
    max_label_names_per_series: 60
    native_histograms_ingestion_enabled: true
    ruler_max_rule_groups_per_tenant: 0
    ruler_max_rules_per_rule_group: 0
memberlist:
    bind_addr:
        - 55.55.55.55(here is real machine ip address)
    cluster_label: cluster1_mimir
    join_members:
        - test-cluster1-mm-01.default.com:7946
        - test-cluster1-mm-02.default.com:7946
        - test-cluster1-mm-03.default.com:7946
    max_join_retries: 120
    rejoin_interval: 10s
multitenancy_enabled: false
querier:
    max_concurrent: 2048
    query_ingesters_within: 6h5m0s
    query_store_after: 0s
ruler:
    poll_interval: 2s
    ring:
        heartbeat_period: 2s
        heartbeat_timeout: 10s
        instance_addr: 0.0.0.0
ruler_storage:
    backend: s3
    s3:
        access_key_id: mimir_aki
        bucket_name: cluster1-rules
        endpoint: miniostrg.dev-env.default.com
        insecure: true
        secret_access_key: '********'
runtime_config:
    file: /etc/mimir/runtime_config.yml
server:
    grpc_server_max_concurrent_streams: 1000
    grpc_server_max_connection_age: 2m0s
    grpc_server_max_connection_age_grace: 5m0s
    grpc_server_max_connection_idle: 1m0s
    http_listen_address: 0.0.0.0
    http_listen_port: 9009
    http_server_read_timeout: 3m0s
    http_server_write_timeout: 3m0s
store_gateway:
    sharding_ring:
        instance_addr: 0.0.0.0
        tokens_file_path: /apps/mimir/tokens
target: all,alertmanager
```
