### DISCUSSION TITLE
<.memcached.addresses>: nil pointer evaluating interface {}.addresses

### DISCUSSION THREAD

**Discussion by rosh0450** [grafana/mimir#7760] [Help and support]
while installing mimir through helm i am getting this error:
`Error: template: mimir-distributed/templates/validate.yaml:58:22: executing "mimir-distributed/templates/validate.yaml" at <.memcached.addresses>: nil pointer evaluating interface {}.addresses
helm.go:88: [debug] template: mimir-distributed/templates/validate.yaml:58:22: executing "mimir-distributed/templates/validate.yaml" at <.memcached.addresses>: nil pointer evaluating interface {}.addresses`

but i have already disabled all the cache:
```
chunks-cache:
  enabled: false
index-cache:
  enabled: false
metadata-cache:
  enabled: false
results-cache:
  enabled: false
```

and instead have used redis:
```
mimir:
  structuredConfig: 
    blocks_storage:
      bucket_store:
        chunks_cache:
          backend: redis
          redis:
            endpoint: redis.mimir.svc.cluster.local:6379
            password: ******
        index_cache:
          backend: redis
          redis:
            endpoint: redis.mimir.svc.cluster.local:6379
            password: ******
        metadata_cache:
          backend: redis
          redis:
            endpoint: redis.mimir.svc.cluster.local:6379
            password: ******
        
    frontend:
      cache_results: true
      results_cache:
        backend: redis
        redis:
          endpoint: redis.mimir.svc.cluster.local:6379
          password: *****
```

**Comment by dimitarvdimitrov** [comment]
can you share your full values.yaml? I couldn't reproduce with the snippets that you have provided

```
0 ▶ cat /tmp/values.yaml
chunks-cache:
  enabled: false
index-cache:
  enabled: false
metadata-cache:
  enabled: false
results-cache:
  enabled: false

mimir:
  structuredConfig:
    blocks_storage:
      bucket_store:
        chunks_cache:
          backend: redis
          redis:
            endpoint: redis.mimir.svc.cluster.local:6379
            password: "******"
        index_cache:
          backend: redis
          redis:
            endpoint: redis.mimir.svc.cluster.local:6379
            password: "******"
        metadata_cache:
          backend: redis
          redis:
            endpoint: redis.mimir.svc.cluster.local:6379
            password: "******"

    frontend:
      cache_results: true
      results_cache:
        backend: redis
        redis:
          endpoint: redis.mimir.svc.cluster.local:6379
          password: "******"
0 ▶ helm template -f /tmp/values.yaml grafana/mimir-distributed
---
# Source: mimir-distributed/templates/alertmanager/alertmanager-pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: release-name-mimir-alertmanager
  labels:
...
```
