### DISCUSSION TITLE
Cannot get Grafana to recognize Mimir monolitic instance, bare metal

### DISCUSSION THREAD

**Discussion by jnunezgts** [grafana/mimir#7763] [Help and support]
Hello all,

I’m getting started with Mimir and I’m trying to connect the following running on the same machine:

* Mimir mimir-2.11.0-1
* grafana-enterprise-10.4.1

I can see than Mimir is running and shows no errors (Console looks good http://localhost:9009/)
Grafana also looks good on http://localhost:3000/
And yet when I try to setup a new datasource pointing to my new Mimir instance I get an error saying:

```
401 Unauthorized - There was an error returned querying the Prometheus API.
```

I want to have applications pushing data to Mimir (for long term storage, aggregation). The applications will not use Prometheus but OpenTelemetry (but they have a way to push compatible metrics).
Then Grafana will be able to display time series, etc. from Mimir stored data.

I was also checking [Grafana agent flow](https://grafana.com/docs/agent/latest/flow/tasks/collect-opentelemetry-data/), but do you need to have now 3 components to forward the data? And that still doesn’t solve the issue of Grafana not being able to talk to Mimir.

Below are my settings:

### /etc/mimir.config.yml
```yaml
multitenancy_enabled: true

usage_stats:
  enabled: false

server:
  http_listen_port: 9009
  log_level: error

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

limits:
  compactor_blocks_retention_period: 3m
  out_of_order_time_window: 10m

api:
  enable_otel_metadata_translation: true

distributor:
  ring:
    kvstore:
      store: memberlist
  pool:
    health_check_ingesters: true

ingester:
  ring:
    instance_interface_names:
      - vmx1.ZZZ
    instance_addr: 172.26.yy.xx

    min_ready_duration: 0s
    final_sleep: 0s
    num_tokens: 512

    kvstore:
      store: inmemory
    replication_factor: 1

blocks_storage:
  tsdb:
    dir: /scratch/grafana/tmp/mimir/tsdb

  bucket_store:
    sync_dir: /scratch/grafana/tmp/mimir/tsdb-sync

  filesystem:
    dir: /scratch/grafana/mimir/data/tsdb

compactor:
  data_dir: /scratch/grafana/tmp/mimir/compactor

ruler_storage:
  backend: local
  local:
    directory: /scratch/grafana/tmp/mimir/rules
```
### /etc/grafana/grafana.ini

```yaml
app_mode = production
instance_name = ${HOSTNAME}
[paths]
data = /scratch/grafana

[server]
protocol = http

domain = grafana.example.com

[analytics]
reporting_enabled = false
check_for_updates = true

[security]
admin_user = admin
admin_password = xxxx

[snapshots]

[dashboards]
versions_to_keep = 10
min_refresh_interval = 1m

[users]

[auth]

[auth.github]

name = GitHub
icon = github
enabled = false
allow_sign_up = true
auto_login = false
client_id = XXX
client_secret = YYYY
scopes = user:email,read:org
auth_url = https://ghe-myorg.example.com/login/oauth/authorize
token_url = https://ghe-myorg.example.com/login/oauth/access_token
api_url = https://ghe-myorg.example.com/api/v3/user

[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true

[smtp]
enabled = true
host = mail.example.com:25
from_address = myorgtechnologyus@example.com

[log]
[log.console]


[log.file]


log_rotate = true


max_days = 5

[alerting]
enabled = false
```

I went back and forth on the documentation and I don’t think I missed anything. Gladly I can paste my Mimir configuration here for review.

Thanks.
