### DISCUSSION TITLE
Configure block storage with private dns

### DISCUSSION THREAD

**Discussion by deggja** [grafana/mimir#7803] [Help and support] [answered]
Hello 🖖 
I am trying to configure block storage for Mimir using the mimir-distributed helm chart. I have a storage account in Azure, behind a private endpoint. I'd like for Mimir to use that private endpoint fqdn instead of the default public one. I am also using workload identity, which is why there is no reference to a key in my code.

I cant find any examples on how to configure this. Is it possible?
The only documentation on this I can find suggests the following:
```
common:
  storage:
    backend: azure
    azure:
      account_key: "${AZURE_ACCOUNT_KEY}" # This is a secret injected via an environment variable
      account_name: mimir-prod
      endpoint_suffix: "blob.core.windows.net"

blocks_storage:
  azure:
    container_name: mimir-blocks

alertmanager_storage:
  azure:
    container_name: mimir-alertmanager

ruler_storage:
  azure:
    container_name: mimir-ruler
```

This wil not work, as the endpoint_suffix should be privatelink.blob.core.windows.net for this to correctly reference the fqdn of the private endpoint.

I tried configuring this the following way:

```
mimir:
      structuredConfig:
        common:
          storage:
            backend: azure
            azure:
              account_name: "${AZURE_ACCOUNT_NAME}"
              endpoint_suffix: "privatelink.blob.core.windows.net"
```

However, this results in a certificate error:

```
tls: failed to verify certificate: x509: certificate is valid for *.blob.core.windows.net, not storage-account.privatelink.blob.core.windows.net\ncreate
```

Anyone got any tips?
