### DISCUSSION TITLE
creating a tenant for mimir

### DISCUSSION THREAD

**Discussion by rosh0450** [grafana/mimir#7854] [Help and support] [answered]
In multi tenancy mode, how do i create multiple tenants for mimir and setup authentication and authorization for it using bearer token.
This page https://grafana.com/docs/mimir/latest/manage/secure/authentication-and-authorization/ talks a bit about this, but doesn't tell how to create  a tenant and generate token for it.

I see installing mimir with this config, automatically create the tenants
```
runtimeConfig:
  overrides:
    tenant-infra:
      max_global_series_per_user: 100000000
      ingestion_rate: 5000000
      compactor_blocks_retention_period: 30d

    tenant-test:
      max_global_series_per_user: 100000
      ingestion_rate: 5000
      compactor_blocks_retention_period: 1d
```
but how to generate token for these?

thanks.
