### DISCUSSION TITLE
Query Frontend multiple addresses

### DISCUSSION THREAD

**Discussion by SunSparc** [grafana/mimir#7894] [Help and support]
I have a Mimir cluster running. Until now It has only been accessed by Grafana via an private internal address.

I have now have the need to send queries directly to Mimir outside of Grafana. I am not sure how best to configure an additional address into Mimir. This additional address should be accessible publicly.

One option, of course, is to just switch the current address to be publicly accessible and update Grafana to use that.

Another option might be to run a separate Query Frontend with a public address. Though I am not sure how to make a separate Query Frontend talk to the Queriers.

I am looking for some suggestions.

**Comment by SunSparc** [comment]
I decided to try setting up a separate instance of `query-frontend`. However, no queriers are connecting to it.

The `/ready` endpoint says:
```
Query Frontend not ready: not ready: number of queriers connected to query-frontend is 0
```

I am wondering what settings I am missing in order for a `query-frontend` running by itself to be able to connect with a monolithic mode Mimir cluster.

Would the `downstream_url` be used for that? Or is that only for connecting to Prometheus instances?

**Comment by SunSparc** [comment]
After reviewing the config for my Mimir cluster (shown below), and looking at the service status list (shown below), I decided that even though I have a `query_scheduler` block specified in the config, I apparently do not have a `query_scheduler` running. I decided to add the `query_scheduler` target. My cluster has been using the `target: all` setting. I checked the modules that are being used by "all":

```
./mimir-linux-amd64 -modules
alertmanager
all
backend
compactor *
continuous-test
distributor *
flusher
ingester *
overrides-exporter
querier *
query-frontend *
query-scheduler
read
ruler *
store-gateway *
write

Modules marked with * are included in target All.
```

With that information I tried to construct a new `target` list:
`target: compactor, distributor, ingester, querier, query-frontend, ruler, store-gateway, query-scheduler`

When I tried to run that, Mimir complained about every module:
```
msg="error running application" err="selected target ( ruler) is an internal module, which is not allowed"
msg="error running application" err="selected target ( store-gateway) is an internal module, which is not allowed"
msg="error running application" err="selected target ( query-scheduler) is an internal module, which is not allowed
etc...
```

**I am not sure what to do next. Any direction would be appreciated.**

-------

```
Service                         Status
-----------------------------   -------
active-groups-cleanup-service   Running
activity-tracker                Running
compactor                       Running
distributor-service             Running
ingester-ring                   Running
ingester-service                Running
memberlist-kv                   Running
querier                         Running
query-frontend                  Running
ruler                           Running
sanity-check                    Running
server                          Running
store-gateway                   Running
store-queryable                 Running
usage-stats                     Running
```


`config.yaml`:
```
          target: all

          multitenancy_enabled: false

          server:
            http_listen_address: {{ env "NOMAD_IP_http" }}
            http_listen_port: {{ env "NOMAD_PORT_http" }}
            grpc_listen_address: {{ env "NOMAD_IP_grpc" }}
            grpc_listen_port: {{ env "NOMAD_PORT_grpc" }}
            log_level: warn

          common:
            storage:
              backend: gcs
              gcs:
                bucket_name: mimir-bucket-name

          blocks_storage:
            storage_prefix: blocks
            tsdb:
              dir: /mimir/tsdb

          frontend_worker:
            frontend_address: {{ env "NOMAD_ADDR_grpc" }}
            dns_lookup_duration: 60m

          frontend:
            instance_interface_names:
              - eth0

          ruler_storage:
            storage_prefix: ruler

          compactor:
            sharding_ring:
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          distributor:
            ring:
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          ingester:
            ring:
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          ruler:
            ring:
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          store_gateway:
            sharding_ring:
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          alertmanager:
            sharding_ring:
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          query_scheduler:
            service_discovery_mode: dns    # ring
            ring:
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          overrides_exporter:
            ring:
              enabled: false
              kvstore:
                store: consul
              instance_interface_names:
                - eth0

          limits:
            ingestion_rate: 750000
            ingestion_burst_size: 7500000
            max_global_series_per_user: 9000000
            max_label_names_per_series: 60
```
