### DISCUSSION TITLE
[k8s, helm]nginx: [emerg] socket() :8080 failed (97: Address family not supported by protocol)

### DISCUSSION THREAD

**Discussion by 95lioma** [grafana/mimir#8038] [Help and support]
hello.
While installing to test mimir, the following log occurs in gateway-nginx.

The version I'm using is:
k8s: 1.27.9
helm: helm.sh/chart=mimir-distributed-5.3.0

```
nginx: [emerg] socket() :8080 failed (97: Address family not supported by protocol)
``` 
I looked up the bug and found that it has been resolved, but I'm curious why it's happening again.
https://github.com/grafana/mimir/issues/7210

```
values.yaml

gateway:
  nginx:
    config:
      enableIPv6: false
```

**Comment by dimitarvdimitrov** [comment]
this looks like an nginx config bug. Happy to help with making a change in the chart if you can help with finding how to fix it in nginx

**Comment by jammy-d** [comment]
Having experienced a similar issue, I'm leaning towards this is triggered because of some confusion between `nginx/nginx-configmap.yaml` and `gateway/nginx-config.yaml`, coupled with some discrepancy between the defaults of `.Values.nginx.nginxConfig.file` and `.Values.gateway.nginx.config.file`.

The behaviour is also coming differently when directly using `mimir-distributed` vs calling `lgtm-distributed` which pulls in `mimir-distributed` as a dependency

```yaml
gateway:
  enabledNonEnterprise: false
  nginx:
    config:
      enableIPv6: false
nginx:
  enabled: true
```

```bash
helm template lgtm grafana/mimir-distributed --dry-run --debug -f values.yaml --version 5.5.1 2>/dev/null | grep -A 3 "server {"
      server {
        listen 8080;
        listen [::]:8080;
```

```bash
helm template lgtm grafana/lgtm-distributed --dry-run --debug -f values.yaml --version 2.1.0  2>/dev/null | grep -A 3 "server {"
      server {
        listen             8080;
    
        location = / {
--
      server {
        listen 8080;
        listen [::]:8080;
```

---

```yaml
gateway:
  enabledNonEnterprise: true
  nginx:
    config:
      enableIPv6: false
nginx:
  enabled: true
```

```bash
helm template lgtm grafana/mimir-distributed --dry-run --debug -f values.yaml --version 5.5.1 2>/dev/null | grep -A 3 "server {"
      server {
        listen 8080;
        client_max_body_size 540M;
    
--
      server {
        listen 8080;
        listen [::]:8080;
```

```bash
helm template lgtm grafana/lgtm-distributed --dry-run --debug -f values.yaml --version 2.1.0  2>/dev/null | grep -A 3 "server {"
      server {
        listen             8080;
    
        location = / {
--
      server {
        listen 8080;
        listen [::]:8080;
```

---

```yaml
gateway:
  enabledNonEnterprise: false
  nginx:
    config:
      enableIPv6: false
nginx:
  enabled: false
```

```bash
helm template lgtm grafana/mimir-distributed --dry-run --debug -f values.yaml --version 5.5.1 2>/dev/null | grep -A 3 "server {"
```

```bash
helm template lgtm grafana/lgtm-distributed --dry-run --debug -f values.yaml --version 2.1.0  2>/dev/null | grep -A 3 "server {"
      server {
        listen             8080;
    
        location = / {
--
      server {
        listen 8080;
        listen [::]:8080;
```

---

```yaml
gateway:
  enabledNonEnterprise: true
  nginx:
    config:
      enableIPv6: false
nginx:
  enabled: false
```

```bash
helm template lgtm grafana/mimir-distributed --dry-run --debug -f values.yaml --version 5.5.1 2>/dev/null | grep -A 3 "server {"
      server {
        listen 8080;
        client_max_body_size 540M;
```

```bash
helm template lgtm grafana/lgtm-distributed --dry-run --debug -f values.yaml --version 2.1.0  2>/dev/null | grep -A 3 "server {"
      server {
        listen             8080;
    
        location = / {
--
      server {
        listen 8080;
        listen [::]:8080;
```

In addition, it seems that it is possible to workaround this by overriding `nginx.nginxConfig.file` when using `mimir-distributed` directly, but that doesn't work when calling it via `lgtm-distributed`
