### DISCUSSION TITLE
GrafanaMimir Alertmanager Datasource not working

### DISCUSSION THREAD

**Discussion by MarcelGlaub** [grafana/mimir#8065] [Help and support]
Hello everyone, I have  problems with creating Mimir alerts. 
My setup:
MinIO VM as S3 storage backend
One Kubernetes Cluster with Prometheus remote writing metrics to Mimir
A second Kubernetes Cluster running GrafanaMimir and Consul

Grafana v10.0.3
Mimir 5.0.0

First of all, I have my normal datasource via which I receive the metrics from Prometheus. The datasource works for querys and visualizing metrics in grafana. As soon as I go to AlertRules i get an error saying `Failed to load the Datasource configuration for Mimir: Failed to fetch` but the Datasource is still there for selection:
![image](https://github.com/grafana/mimir/assets/151658642/c3e6b6c8-6ba8-4794-b85c-6cb629d8b00e)

Then I actually have an Alertmanager Datasource, configured like this:
```
    - name: MimirAlertmanager
      type: alertmanager
      url: https://mimir.k8s-internal.datacenter.de/
      access: server
      jsonData:
        implementation: mimir
        handleGrafanaManagedAlerts: false
        tlsSkipVerify: true
      basicAuth: true
      basicAuthUser: <user>
      secureJsonData:
        basicAuthPassword: <pw>
```
Health check passes but the datasource is not displayed in AlertRules. If I put /alertmanager after the url I get the following error during the health check: `It looks like you have chosen a Mimir or Cortex implementation, but detected a Prometheus endpoint. Please update implementation selection and try again.`
But then when i put /alertmanager after the url and change the Implementation to Prometheus the HealthCheck Passes again. 

So to summarize: I don't understand how the config should look so that a datasource is displayed here in grafana as a Mimir datasource
![image](https://github.com/grafana/mimir/assets/151658642/a059a3bf-b681-4fdf-9772-2b00cbf79d0d)

I have tried what feels like all the possibilities. I also find the documentation quite confusing. for example: The documentation says to use the /prometheus prefix:
https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-mimir-loki-managed-rule/
and in turn it says that you should use /alertmanager:
https://grafana.com/docs/mimir/latest/references/architecture/components/alertmanager/

I can't see any errors in the grafana/ruler/alertmanager pod logs. I have configured ruler api, and external urls as described in the docs. 
My value files: 
[mimir_values.yaml.txt](https://github.com/grafana/mimir/files/15222652/mimir_values.yaml.txt)
[grafana_values.yaml.txt](https://github.com/grafana/mimir/files/15222639/grafana_values.yaml.txt)

I would be very grateful for suggestions 😃 

Cheers
Marcel
