### DISCUSSION TITLE
ingester.max-global-series-per-user: 2000000 is not parsable in ingester values

### DISCUSSION THREAD

**Discussion by kunalmehta-eve** [grafana/mimir#8136] [Help and support]
@pracucci @pstibrany 

To set max-global-series-per-user this is configuration we are using in helm chart 4.4.1 

```yaml
ingester:
  replicas: 3
  zoneAwareReplication:
    enabled: false
  resources:
    requests:
      cpu: "0.5"
      memory: 6Gi
    limits:
      cpu: "1"
      memory: 6Gi
  persistentVolume:
    size: 16Gi
  extraArgs:
    # Note that when increasing this to 1000000, the ingester couldn't start because of:
    # invalid value "1e+06" for flag -ingester.max-global-series-per-user: parse error
    "ingester.max-global-series-per-user": 990000
```

It is failing with this parsing error:

2024-05-03 15:00:54.068 | invalid value "2e+06" for flag -ingester.max-global-series-per-user: parse error |  
-- | -- | --
  |   | 2024-05-03 14:55:45.060 | Run with -help to get a list of available parameters

#### Expected behavior

Value should be allowed in variabe

#### Environment

- Infrastructure: [ Kubernetes]
- Deployment tool: [helm]
