### DISCUSSION TITLE
Grafana mimir distributed no s3 endpoint in config for compactor, ingester, querier, ruler, and store-gateway

### DISCUSSION THREAD

**Discussion by iiiceburg** [grafana/mimir#8177] [Help and support]
I deploy Grafana mimir distributed (Chart version 5.3.0) on GKE using Terraform and Helm and I face with an error **no s3 endpoint in config** for compactor, ingester, querier, ruler, and store-gateway

> error : "error running application" err="no s3 endpoint in config file\ngithub.com/thanos-io/objstore/providers/s3.validate\n\t/__w/mimir/mimir/vendor/github.com/thanos-io/objstore/providers/s3/s3.go:353\ngithub.com/thanos-io/objstore/providers/s3.NewBucketWithConfig\n\t/__w/mimir/mimir/vendor/github.com/thanos-io/objstore/providers/s3/s3.go:222\ngithub.com/grafana/mimir/pkg/storage/bucket/s3.NewBucketClient\n\t/__w/mimir/mimir/pkg/storage/bucket/s3/bucket_client.go:27\ngithub.com/grafana/mimir/pkg/storage/bucket.NewClient\n\t/__w/mimir/mimir/pkg/storage/bucket/client.go:163\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats\n\t/__w/mimir/mimir/pkg/mimir/modules.go:1013\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:830\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:228\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\ncreate usage-stats bucket client\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initUsageStats\n\t/__w/mimir/mimir/pkg/mimir/modules.go:1015\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:830\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:228\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650\nerror initialising module: usage-stats\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:830\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:228\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:267\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1650

**Here my config values**
```
nginx:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt"
    hosts:
      - host: mimir.foo.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: mimir-foo-tls
        hosts:
          - mimir.foo.com

serviceAccount:
  create : false
  name: mimir-gcs-sa

structuredConfig:
  common:
    storage:
      backend: gcs
      gcs:
        bucket_name: lgtm-bucket
        storage_prefix: grafana-mimir
        endpoint: https://storage.googleapis.com/storage/v1/xxxxxxxxx
        
blocks_storage:
  backend: gcs
  gcs:
    bucket_name: lgtm-bucket
    storage_prefix: grafana-mimir-blocks
    endpoint: https://storage.googleapis.com/storage/v1/xxxxxxxxx

alertmanager_storage:
  backend: gcs
  gcs:
    bucket_name: lgtm-bucket
    storage_prefix: grafana-mimir-alertmanager
    endpoint: https://storage.googleapis.com/storage/v1/xxxxxxxxx

ruler_storage:
  backend: gcs
  gcs:
    bucket_name: lgtm-bucket
    storage_prefix: grafana-mimir-ruler
    endpoint: https://storage.googleapis.com/storage/v1/xxxxxxxxx

minio:
  enabled: false
```
