### DISCUSSION TITLE
unable to run Mimir in single ingestor - `too many unhealthy instances in the ring`

### DISCUSSION THREAD

**Discussion by kirankumar-grootan** [grafana/mimir#8264] [Help and support]
unable to run Mimir in single replica ingester via helm chart

```
mimir:
  structuredConfig:
    store_gateway:
      sharding_ring:
        replication_factor: 1
    ingester:
      ring:
        replication_factor: 1
  ingester:
    replicas: 1

```

when I run query from grafana it shows `too many unhealthy instances in the ring`. I dont need HA for dev cluster thats why Im reducing the ingester to 1

**Comment by aknuds1** [comment]
Converting to discussion, as there's no evidence of a bug.

**Comment by kreeger** [comment]
I too had this issue, and played around with my Helm values until I got it working. I was originally missing `replication_factor: 1` in my `structuredConfig`! You'll also need `zone_awareness_enabled: false`, since to disable replication on `ingested`, and `store_gateway` means disabling zone awareness.

This is what did the trick for me (after setting `zoneAwareReplication: { enabled: false }` on `store_gateway` and `ingester`).

```yaml
mimir:
  structuredConfig:
    ingester:
      ring:
        zone_awareness_enabled: false
        replication_factor: 1
    store_gateway:
      sharding_ring:
        zone_awareness_enabled: false
        replication_factor: 1
```
