### DISCUSSION TITLE
Can Mimir AlertManager be used for Loki Ruler?

### DISCUSSION THREAD

**Discussion by hobbsh** [grafana/mimir#8267] [Help and support]
Hi,

I have been unable to get alerts to actually notify when using Alert Rules in the Loki helm chart, pointing `alertmanager_url` at the Mimir Alertmanager instance. I've searched through the docs extensively but I can't seem to uncover what I'm missing. Is there a catch or is this just not designed to work?

I can see `rule evaluating` logs in the ruler and the alert is even `Firing` in the Grafana Alerting dashboard, but nothing is being notified and I have not found evidence of errors/misconfiguration anywhere.

**Comment by thmshmm** [comment]
hey, it should work, using it in this setup as well.
```
loki:
  structuredConfig:
    auth_enabled: true
    ruler:
      alertmanager_url: http://lgtm-distributed-mimir-alertmanager:8080/alertmanager
```
Do you have multi-tenancy enabled everywhere? Loki in that case forwards the `X-Scope-OrgID` header.

**Reply by hobbsh** [reply]
Thanks for your reply! We don't have multi-tenancy enabled so I am assuming `auth_enabled` is a non-issue? This is our config using the `loki-distributed` chart values:

```yaml
     ruler:
       directories:
         fake:
           loki_rules.yaml: |
             groups:
               - name: loki_alerts
                 rules:
                   - alert: LogTestAlert
                     expr: sum by (service)(rate({app="api", environment="development"}[5m])) > 0
                     for: 5m
                     labels:
                       severity: critical
                       component: service
                     annotations:
                       message: This test alert should fire when there are logs for api in development
...
     loki:
       structuredConfig:
         ruler:
           enable_api: true
           alertmanager_url: http://mimir-distributed-alertmanager.mimir:8080/alertmanager
           enable_alertmanager_v2: true
           enable_sharding: true
```

**Reply by zktaiga** [reply]
Hey @hobbsh did you manage to make it work with the above? I think this is quite an undocumented problem.

**Reply by hobbsh** [reply]
@zktaiga No, it still doesn't work. I've tried just about everything it seems with no results.

**Reply by pstibrany** [reply]
I'm not very familiar with Alertmanager, but here's how I would start troubleshooting this:
* Can you see Loki sending alertmanager notifications in the logs? Are there any errors?
* Can you see alertmanager receiving notifications? (logs, metrics)

**Reply by hobbsh** [reply]
@pstibrany It is oddly silent. I can see rule evaluations happening in Loki but nothing that it's sending notifications to AlertManager, nor errors. Not sure if they show up in a different log level or what. Nothing in AlertManager logs but I also don't see any logs for any alerts, so that could be a log level thing worth investigating too.

Loki `ruler` logs for example, there are only three lines per evaluation, where I assume if it reaches out to AlertManager I might see another line or two for each evaluation:

```
level=info ts=2024-08-19T16:55:23.253735606Z caller=metrics.go:160 component=ruler evaluation_mode=local org_id=fake traceID=09f522d58be08b11 latency=fast query="(sum by (service)(rate({app=\"api\", environment=\"development\"}[5m])) > 0)" query_hash=94323469 query_type=metric range_type=instant length=0s start_delta=37.26216ms end_delta=37.262308ms step=0s duration=36.19781ms status=200 limit=0 returned_lines=0 throughput=28MB total_bytes=1.0MB total_bytes_structured_metadata=0B lines_per_second=26161 total_lines=947 post_filter_lines=947 total_entries=1 store_chunks_download_time=1.734156ms queue_time=0s splits=0 shards=0 chunk_refs_fetch_time=32.782542ms cache_chunk_req=2 cache_chunk_hit=2 cache_chunk_bytes_stored=0 cache_chunk_bytes_fetched=370352 cache_chunk_download_time=1.57753ms cache_index_req=68 cache_index_hit=68 cache_index_download_time=3.41357ms cache_stats_results_req=0 cache_stats_results_hit=0 cache_stats_results_download_time=0s cache_result_req=0 cache_result_hit=0 cache_result_download_time=0s |  
-- | --
  |   | 2024-08-19 10:55:23.271 | level=info ts=2024-08-19T16:55:23.217448673Z caller=engine.go:232 component=ruler evaluation_mode=local org_id=fake traceID=09f522d58be08b11 msg="executing query" type=instant query="(sum by (service)(rate({app=\"api\", environment=\"development\"}[5m])) > 0)" query_hash=94323469 |  
  |   | 2024-08-19 10:55:23.271 | level=info ts=2024-08-19T16:55:23.217386545Z caller=compat.go:66 user=fake rule_name=LogTestAlert rule_type=alerting query="(sum by (service)(rate({app=\"api\", environment=\"development\"}[5m])) > 0)" query_hash=94323469 msg="evaluating rule"
```

**Reply by thmshmm** [reply]
Have a look here https://github.com/thmshmm/demo-loki-alerting I used this to create a demo, maybe you can compare it to your setup.

**Reply by hobbsh** [reply]
Thanks @thmshmm! It looks like I'm definitely missing the `remote_write` block for the ruler, which makes sense. I'll report back shortly.

**Reply by hobbsh** [reply]
So I think `remote_write` was part of the issue, but now we have a tenant mismatch because the default tenant is `anonymous` on Mimir and `fake` on Loki. How is this typically reconciled? Should we set the tenant name to `anonymous` on the ruler `remote_write` clients?

**Reply by pstibrany** [reply]
If your Mimir is configured with multitenancy disabled, I'd expect that Mimr ignores the tenant coming from Loki.

Looking at the remote-write config options in Loki ruler, I'd perhaps try setting `remote_write.add_org_id_header` option to false, so that Loki doesn't report the tenant to alertmanager. (But I have no direct experience trying to setup Loki ruler with Mimir alertmanager, just guessing here.)

**Reply by hobbsh** [reply]
It looks like that option is only available in Loki 3.x - we are still on 2.9 because the `loki-distributed` chart does not support the new version yet.

**Reply by zktaiga** [reply]
Thought I'd chime in since I've made it work, was in a similar situation: different default tenants between Mimir/Loki. Ended up aligning the tenant names to match, and then just setting `alertmanager_url`.

By the way, I don't think `remote_write` has anything to do here. Rules are evaluated by the Loki Ruler and then sent to Mimir's Alertmanager (they don't go through Mimir). As far as I can see, `remote_write` just generates metrics and pushes them to Mimir for collection. 

My 2 cents with the loki chart in simple scalable mode:
```yaml
loki:
  auth_enabled: true
  rulerConfig:
    wal:
      dir: /var/loki/ruler-wal
    alertmanager_url: http://mimir-alertmanager.mimir.svc:8080/alertmanager
    external_url: https://grafana.com
    enable_alertmanager_v2: true
    enable_api: true
    external_labels:
      origin: loki
    remote_write:
      enabled: true
      client:
        url: http://mimir-nginx.mimir.svc:80/api/v1/push
```

This way, Grafana can connect to Loki's ruler API, you can create datasource-managed alerts (Loki ruler), they'll be created in object storage and then loaded by the ruler. Hope this helps!

**Reply by hobbsh** [reply]
Ok so what I had to do since I don't have access to disabling the org id header for the Loki ruler is to just add an AlertManager config for the `fake` tenant with `mimirtool`. Maybe I needed this either way, but with this `remote_write` config and a duplicate config for the `fake` tenant (just passing `--id=fake` to `mimirtool alertmanager load` like we do for `anonymous` tenant), it works!

```
        ruler:
          enable_api: true
          alertmanager_url: http://mimir-distributed-alertmanager.mimir:8080/alertmanager
          enable_alertmanager_v2: true
          enable_sharding: true
          remote_write:
            enabled: true
            clients:
              fake:
                url: http://mimir-distributed-gateway.mimir:8080/api/v1/push
```

**Comment by applejag** [comment]
We also used Mimir and Loki without multi-tenancy and was struck by this issue. We resolved it by adding this to our `mimir-distributed` Helm chart values:

```yaml
gateway:
  nginx:
    config:
      httpSnippet: |
        # Force override the X-Scope-OrgID header
        # as clients like Loki tries to use "fake"
        # but a Mimir without tenants should use "anonymous"
        map $http_x_scope_orgid $http_x_scope_orgid {
          "" "anonymous";
        }
```

This adds a snippet to the Nginx config used in the gateway so it always overrides the X-Scope-OrgID with `anonymous`. This overrides the default behavior of using the existing value if it exists: https://github.com/grafana/mimir/blob/7ef5c82df5ca3784f10c408d02b88cd3e30fee4b/operations/helm/charts/mimir-distributed/values.yaml#L3484-L3492

Then in our Loki config we point loki-ruler to the Mimir gateway:

```yaml
rulerConfig:
  rule_path: /tmp/loki/rules-temp
  storage:
    type: local
    local:
      directory: /etc/loki/rules
  external_labels:
    category: logs
  ring:
    kvstore:
      store: memberlist
  alertmanager_url: http://mimir-gateway.mimir.svc.cluster.local:80/alertmanager
```

To verify that this works, I created some Loki alerts that will always fire and then port-forwarded the Mimir gateway (`kubectl port-forward svc/mimir-gateway 8080:80`) and tried to access the Alertmanager (<http://localhost:8080/alertmanager/#/alerts>) to see that the alerts show up there as well, together with all of our Prometheus alerts from mimir-ruler.
