### DISCUSSION TITLE
Alertmanager configuration

### DISCUSSION THREAD

**Discussion by MarcelGlaub** [grafana/mimir#8284] [Help and support]
Hi, im trying to add a Alertmanager datasource in grafana with implementation as Mimir. 
This is the datasource config: 
```
    - name: Mimir Alertmanager
      type: alertmanager
      access: server
      url: http://mimir-alertmanager:8080/alertmanager
      editable: true
      isDefault: false
      jsonData:
        implementation: mimir
        tlsSkipVerify: true
```
When clicking Save & Test the Health Check fails with the following message as can be seen in the screenshot below:

"It looks like you have chosen a Mimir or Cortex implementation, but detected a Prometheus endpoint. Please update implementation selection and try again."

![image](https://github.com/grafana/mimir/assets/151658642/94daf2ad-c6d9-4fbe-9086-bd64bd02b701)

When i remove /alertmanager from the URL the Health Check passes but i can see this error in the grafana log: 
`logger=context userId=1 orgId=1 uname=admin t=2024-06-05T14:38:36.488722407Z level=info msg="Request Completed" method=GET path=/api/datasources/proxy/uid/e804f375-841d-49ea-a85f-47e880af88fe/api/v2/status status=404 remote_addr=10.2.49.5 time_ms=1 duration=1.313649ms size=19 referer=https://monitoring.k8s-internal.datacenter.de/datasources/edit/e804f375-841d-49ea-a85f-47e880af88fe handler=/api/datasources/proxy/uid/:uid/*
`
also when trying to create an alert rule i cannot select mimir/loki alerts since i dont have an compatible datasource:
![image](https://github.com/grafana/mimir/assets/151658642/8cb173cd-fb26-43e5-a4c8-2cb71c8cbd88)

Can someone explain to me whats going on here?
My alertmanager config is completly default im not overriding any paths or something like this.

Cheers
Marcel
