### DISCUSSION TITLE
Tenho 3 Instâncias de grafana Mimir no ECS Fargate da AWS as 3 estão se comunicando muito bem com o prometheus e estão gravando dados no s3 muito bem, mas estou enfrentando um problema . \n 1-elas não estão sincronizadas apesar de guardarem no mesmo bucket de S3. \n 2- quando sobe uma instancia nova, ela não consegue pegar o histórico dos dados no S3 \n 3- Se eu faço um novo deploy, ela não pega o histórico dos dados apesar de estar no s3 só começa a pegar os dados que está recebendo após o deploy. Onde eu posso melhorar?  Este é o meu Dockerfile e o config. O etcd não guardou nada desde que subi mas ele está operante só não sei o porque o MIMIR não está guardando cache nele.

### DISCUSSION THREAD

**Discussion by macsmarte** [grafana/mimir#8308] [Help and support]
```yaml

target: all,alertmanager,overrides-exporter
multitenancy_enabled: false

server:
  http_listen_port: 9009
  log_level: warn

  
common:
  storage:
    backend: s3
    s3:
      endpoint: s3.us-east-1.amazonaws.com
      region: us-east-1
      access_key_id: "xxxxxxxxx" # This is a secret injected via an environment variable
      secret_access_key: "xxxxxxxxxxxxx" # This is a secret injected via an environment variable
      bucket_name: mimir-xxxxxxx

blocks_storage:
  storage_prefix: blocks
  tsdb:
    dir: /data/ingester
    
activity_tracker: {}

alertmanager: {}

distributor:
  pool:
    health_check_ingesters: true

ingester_client:
  grpc_client_config:
    grpc_compression: gzip
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600

ingester:
  ring:
    final_sleep: 0s
    kvstore:
      # store: etcd
      etcd:
        endpoints: [100.0.131.185:2379]
        dial_timeout: 60s
        max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
    replication_factor: 1
    
 compactor:
  sharding_ring:
    kvstore:
      store: memberlist

ruler:
  enable_api: true

limits:
  ingestion_burst_size: 500000
  ingestion_rate: 250000
  max_global_series_per_user: 4000000

memberlist:
  advertise_addr: 127.0.0.1
  join_members:
    - "127.0.0.1"
  cluster_label: "mimir"
  cluster_label_verification_disabled: true

```
