### DISCUSSION TITLE
Alertmanager component error

### DISCUSSION THREAD

**Discussion by rosh0450** [grafana/mimir#8322] [Help and support]
I am getting this error in alertmanager:

```
ts=2024-06-10T11:30:02.868615817Z caller=multitenant.go:539 level=info component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"
ts=2024-06-10T11:30:11.848597431Z caller=dispatch.go:353 level=error component=MultiTenantAlertmanager user=tenant-infra component=dispatcher insight=true component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="gms-alerts/webhook[0]: notify retry canceled due to unrecoverable error after 1 attempts: unexpected status code 400: https://corp.webhook.office.com/webhookb2/<some-code>: Summary or Text is required."
```

i have created a contact point of type 'webhook'.

This is my alermanager's fallback config:
```
receivers:
    - name: default-receiver
route:
    receiver: default-receiver
```

Alertmanager's configuration:
```
alertmanager:
    data_dir: /data
    retention: 120h0m0s
    external_url: /alertmanager
    poll_interval: 15s
    max_recv_msg_size: 104857600
    sharding_ring:
        kvstore:
            store: memberlist
            prefix: alertmanagers/
            consul:
                host: localhost:8500
                acl_token: ""
                http_client_timeout: 20s
                consistent_reads: false
                watch_rate_limit: 1
                watch_burst_size: 1
                cas_retry_delay: 1s
            etcd:
                endpoints: []
                dial_timeout: 10s
                max_retries: 10
                tls_enabled: false
                tls_cert_path: ""
                tls_key_path: ""
                tls_ca_path: ""
                tls_server_name: ""
                tls_insecure_skip_verify: false
                tls_cipher_suites: ""
                tls_min_version: ""
                username: ""
                password: ""
            multi:
                primary: ""
                secondary: ""
                mirror_enabled: false
                mirror_timeout: 2s
        heartbeat_period: 15s
        heartbeat_timeout: 1m0s
        instance_id: mimir-alertmanager-0
        instance_interface_names:
            - eth0
        instance_port: 0
        instance_addr: ""
        instance_enable_ipv6: false
        replication_factor: 3
        zone_awareness_enabled: false
        instance_availability_zone: ""
    fallback_config_file: /configs/alertmanager_fallback_config.yaml
    peer_timeout: 15s
    enable_api: true
    grafana_alertmanager_compatibility_enabled: false
    max_concurrent_get_requests_per_tenant: 0
    alertmanager_client:
        remote_timeout: 2s
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: ""
        rate_limit: 0
        rate_limit_burst: 0
        backoff_on_ratelimits: false
        backoff_config:
            min_period: 100ms
            max_period: 10s
            max_retries: 10
        initial_stream_window_size: 63KiB1023B
        initial_connection_window_size: 63KiB1023B
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
        tls_cipher_suites: ""
        tls_min_version: ""
        connect_timeout: 5s
        connect_backoff_base_delay: 1s
        connect_backoff_max_delay: 5s
    persist_interval: 15m0s
    enable_state_cleanup: true
    utf8_strict_mode: false
```

And i have multi-tenancy enabled.

Below is my sample alert for testing:
![image](https://github.com/grafana/mimir/assets/59838688/1d91e8ff-97b0-42d0-bd70-fdde69fbdace)

Thanks in advance.
