### DISCUSSION TITLE
accessing mimir-distributed with a subpath /mimir

### DISCUSSION THREAD

**Discussion by DontWanna1** [grafana/mimir#8361] [Help and support]
I try to deploy the lgtm-distributed helm chart on a k3s cluster.

1. I can access mimir on / just fine
2. I can modify the `grafana:` section to serve a subpath
 ```grafana:
  ingress:
    enabled: false
    annotations:
    labels: {}
    path: /grafana
    hosts:
      - myhost.com
  grafana.ini:
    server:
      protocol: http
      domain: myhost.com
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      serve_from_sub_path: true
```
The noteworthy part is `root_url: "%(protocol)s://%(domain)s:%(http_port)s/grafana"`, which tells grafana to properly redirect (or something)
3. I can configure mimirs ingress to listen at `/mimir`, however, when trying to curl `curl myhost.com/mimir' I receive:
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.25.5</center>
</body>
</html>
```

While reading through: https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml
I noticed the line 2956:
```
location = / {
            return 200 'OK';
            auth_basic off;
          }
```
I recon that there needs to be some information on how to handle the additional path.

How can I do this?

Best Regards

**Comment by dimitarvdimitrov** [comment]
I think you're looking for these two config options

```yaml
api:
  # (advanced) HTTP URL path under which the Alertmanager ui and api will be
  # served.
  # CLI flag: -http.alertmanager-http-prefix
  alertmanager_http_prefix: <string> | default = "/alertmanager"

  # (advanced) HTTP URL path under which the Prometheus api will be served.
  # CLI flag: -http.prometheus-http-prefix
  prometheus_http_prefix: <string> | default = "/prometheus"
```

you can change them to `/mimir/prometheus` and `/mimir/alertmanager`. FYI this was an issue for mimitool until recently; the fix will be in mimirtool 2.13 https://github.com/grafana/mimir/issues/8018
