### DISCUSSION TITLE
Cortex  metrics mimir is not displayed

### DISCUSSION THREAD

**Discussion by flowramps** [grafana/mimir#8928] [Help and support]
Cortex_alertmanager_alerts metric is not being displayed in mimir metrics captures.

example of a query being instrumented on my dashboard to show the total alerts

```
sum(cluster_job_pod:cortex_alertmanager_alerts:sum{cluster=~"$cluster", job=~"($namespace)/((alertmanager|cortex|mimir|mimir-backend.*))"})
```

Obs: when consulting directly in the prometheus it is also not being displayed
![image](https://github.com/user-attachments/assets/cc6c0d9e-6e9c-4880-b2ab-ad6be0d8aa6e)

other queries are displayed, example:
![image](https://github.com/user-attachments/assets/24adf61a-9673-4c87-b055-c428507488d7)

 version 5.1.4  helm
 ```
 
 ####values#####
 metaMonitoring:
  dashboards:
    annotations:
      k8s-sidecar-target-directory: /tmp/dashboards/Mimir Dashboards
    enabled: true
    labels:
      grafana_dashboard: "1"
  metrics:
    enabled: true
    remote:
      headers: 
        "X-Scope-OrgID": eks-dev|eks-hml
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
  prometheusRule:
    enabled: true
    mimirAlerts: true
    mimirRules: true
    annotations: {}
    labels:
      release: prometheus
    namespace: mimir-distributed-dev
    groups:
    - name: mimir_dev_alerts #Alertas Inicio
      source_tenants: [ "eks-dev", "eks-hml" ]
 
 ```
