### DISCUSSION TITLE
Add labels based on HTTP Headers similar to X-Scope-OrgId

### DISCUSSION THREAD

**Discussion by NilsEngelbach** [grafana/mimir#8936] [Help and support]
I followed the documentation and deployed Mimir using an authenticating reverse proxy.

The authenticating proxy is adding the `X-Scope-OrgId` based on the claims provided in the `access_token` form the client.

The clients remote write config looks like this:

```yaml
remote_write:
  - url: "https://<host>/api/v1/push"
    remote_timeout: 20s
    oauth2:
      client_id: "<client_id>"
      client_secret: "<client_secret>"
      token_url: "https://<host>/oauth2/token"
```

Is it possible to add additional labels based on other HTTP Headers ( e.g. `X-Scope-SysID`)?

I know that it is possible to add additional labels on client side using `external_labels` but I want to add the labels on server side to make sure clients can not modify them.

```yaml
global:
  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    [ <labelname>: <labelvalue> ... ]
```
