### DISCUSSION TITLE
Mimir alertmanager, alerts & rules, with Grafana alloy

### DISCUSSION THREAD

**Discussion by ledoc** [grafana/mimir#9031] [Help and support]
Hello, you who read me, thank you already.
I'm trying to switch to grafana alloy with the LGTM stack and I'm having trouble adding the mimir alertmanager and, more specifically, the alerts [here](https://github.com/grafana/mimir/tree/main/operations/mimir-mixin-compiled) 
They are created but mimir is not aware of them.

I use Terraform and Helm to install the stack
To install Grafana alloy I use the Helm chart [k8s-monitoring](https://github.com/grafana/k8s-monitoring-helm/tree/main/charts/k8s-monitoring).
Here are the values for grafana alloy:
```yaml
cluster:
  name: monitoring

externalServices:
  prometheus:
    host: http://mimir-gateway
    basicAuth:
      username: mimir
      password: PROVIDED_BY_PARAM_USING_TF
    writeEndpoint: /api/v1/push
  loki:
    host: http://loki-gateway
    basicAuth:
      username: loki
      password: PROVIDED_BY_PARAM_USING_TF
  tempo:
    host: http://tempo-gateway:80
    basicAuth:
      username: tempo
      password: PROVIDED_BY_PARAM_USING_TF
    tls:
      insecure: true

traces:
  enabled: true
alloy:
  alloy:
    extraPorts:
      - name: "otlp-grpc"
        port: 4317
        targetPort: 4317
        protocol: "TCP"
      - name: "otlp-http"
        port: 4318
        targetPort: 4318
        protocol: "TCP"

metrics:
  scrapeInterval: 15s
  cost:
    enabled: false
  # kube-state-metrics:
  #   metricsTuning:
  #     - .*
  # cadvisor:
  #   metricsTuning:
  #     - .*
  # node-exporter:
  #   metricsTuning:
  #     - .*
  # kubelet:
  #   metricsTuning:
  #     - .*
opencost:
  enabled: false
```

To install mimir I use this [Helm chart](https://github.com/grafana/mimir/tree/main/operations/helm)
Here are the values for Mimir:
```yaml
minio:
  enabled: false
mimir:
  structuredConfig:
    common:
      storage:
        backend: gcs

    blocks_storage:
      backend: gcs
      gcs:
        bucket_name: PROVIDED_BY_PARAM_USING_TF

    ruler_storage:
      backend: gcs
      gcs:
        bucket_name: PROVIDED_BY_PARAM_USING_TF  
    
    alertmanager_storage:
      backend: gcs
      gcs:
        bucket_name: PROVIDED_BY_PARAM_USING_TF

    # ruler:  
    #   alertmanager_url: http://mimir-gateway/alertmanager

alertmanager:
  enabled: true
ingester:
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false
metaMonitoring:
  dashboards:
    enabled: true
  serviceMonitor:
    enabled: true
    clusterLabel: null
  prometheusRule:

    enabled: true
    mimirAlerts: true
    mimirRules: true
    annotations: {}
    labels: {} 
    groups: []

  runtimeConfig:
    overrides:
      anonymous:
        max_global_series_per_user: 1500000
nginx:
  enabled: false

gateway:
  enabledNonEnterprise: true
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-staging
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: PROVIDED_BY_PARAM_USING_TF
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
        - PROVIDED_BY_PARAM_USING_TF
        secretName: mimir-tls
  nginx:
    basicAuth:
      enabled: true
      username: mimir
      password: PROVIDED_BY_PARAM_USING_TF
```

I can see the pod of alertmanager, acces the UI of alertmanager, and also see PrometheusRules for alerts and records.
But everything is empty in alertmanager UI and alert rules section of Grafana.

I've tried and read a lot without success, I hope someone will be able to point me in the right direction. 

Thanks in advance
