### DISCUSSION TITLE
Reporting Rule not loaded to endpoint

### DISCUSSION THREAD

**Discussion by Uscholdo** [grafana/mimir#9552] [Help and support]
Hi.
I tried to add a reporting rule but it is not available at /prometheus/api/v1/rules.
My settings step by step:

**mimir-configs:**
```
mimir.yaml: |

    activity_tracker:
      filepath: /active-query-tracker/activity.log
    alertmanager:
      data_dir: /data/alertmanager
      enable_api: true
      external_url: /alertmanager
      fallback_config_file: /configs/alertmanager_fallback_config.yaml
    alertmanager_storage:
      backend: s3
      s3:
        access_key_id: mimir
        bucket_name: mimir-ruler
        endpoint: monitoring-minio.{{ .Release.Namespace }}.svc:9000
        insecure: true
        secret_access_key: supersecret
    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data/tsdb-sync
      s3:
        access_key_id: mimir
        bucket_name: mimir-tsdb
        endpoint: monitoring-minio.{{ .Release.Namespace }}.svc:9000
        insecure: true
        secret_access_key: supersecret
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
    compactor:
      compaction_interval: 30m
      data_dir: /data/compactor
      deletion_delay: 2h
      first_level_compaction_wait_period: 25m
      max_closing_blocks_concurrency: 2
      max_opening_blocks_concurrency: 4
      sharding_ring:
        wait_stability_min_duration: 1m
      symbols_flushers_concurrency: 4
    frontend:
      parallelize_shardable_queries: true
    frontend_worker:
      frontend_address: mimir-headless.{{ .Release.Namespace }}.svc:9095
      grpc_client_config:
        max_send_msg_size: 419430400
    ingester:
      ring:
        replication_factor: 1
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      max_cache_freshness: 10m
      max_query_parallelism: 240
      max_total_query_length: 12000h
      out_of_order_time_window: 1h
      compactor_blocks_retention_period: {{ .Values.metricRetentionTime }}
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members: []
    querier:
      max_concurrent: 16
    query_scheduler:
      max_outstanding_requests_per_tenant: 800
    ruler:
      enable_api: true
      rule_path: /data/ruler
    ruler_storage:
      backend: local
      local:
        directory: /tmp/ruler
    server:
      grpc_server_max_connection_age: 2m
      grpc_server_max_connection_age_grace: 5m
      grpc_server_max_connection_idle: 1m
    store_gateway:
      sharding_ring:
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
        wait_stability_min_duration: 1m
    usage_stats:
      installation_mode: helm
```

**StatefulSet.yaml:**
```
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: mimir
  namespace: {{ .Release.Namespace }}
  labels:
    app: mimir
    app.kubernetes.io/component: mimir
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: PlatformComponents-Monitoring
  annotations:
    tgw.global/registry : {{ .Values.global.registry }}
    tgw.global/environment : {{ .Values.global.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      creationTimestamp: null
      labels:
        app: mimir
    spec:
      priorityClassName: {{ .Values.global.priorityclass }}
      imagePullSecrets:
        - name: mimir
      restartPolicy: Always
      imagePullSecrets:
        - name: mimir-image-pull
      schedulerName: default-scheduler
      affinity: {}
      terminationGracePeriodSeconds: 240
      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mimir
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: rules
              mountPath: /data/ruler/rules.yaml
              subPath: rules.yaml
            - name: ruler-storage
              mountPath: /tmp/ruler/rules.yaml
              subPath: rules.yaml
            - name: config
              mountPath: /etc/mimir
            - name: storage
              mountPath: /data
            - name: active-queries
              mountPath: /active-query-tracker
          terminationMessagePolicy: File
          image: >-
            xxx.azurecr.io/base/grafana/mimir:{{ .Values.mimirversion }}
          args:
            - '-target=all'
            - '-config.expand-env=true'
            - '-config.file=/etc/mimir/mimir.yaml'
            - '-ingester.ring.instance-availability-zone=zone-default'
            - '-server.grpc.keepalive.max-connection-age=2562047h'
            - '-server.grpc.keepalive.max-connection-age-grace=2562047h'
            - '-query-frontend.grpc-client-config.grpc-compression=snappy'
            - '-query-scheduler.grpc-client-config.grpc-compression=snappy'
            - '-ruler.client.grpc-compression=snappy'
            - '-ruler.query-frontend.grpc-client-config.grpc-compression=snappy'
            - '-ingester.client.grpc-compression=snappy'
            - '-auth.multitenancy-enabled=false'
            - '-distributor.ingestion-burst-size=300000'
            - '-distributor.ingestion-rate-limit=100000'
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: mimir
      volumes:
        - name: rules
          configMap:
            name: mimir-rules
            defaultMode: 420
        - name: ruler-storage
          configMap:
            name: mimir-rules
            defaultMode: 420
        - name: config
          configMap:
            name: mimir
            items:
              - key: mimir.yaml
                path: mimir.yaml
            defaultMode: 420
        - name: active-queries
          emptyDir: {}
      dnsPolicy: ClusterFirst
  volumeClaimTemplates:
    - kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: storage
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        storageClassName: thin-csi
        volumeMode: Filesystem
      status:
        phase: Pending
  serviceName: mimir
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10
```

**My rules.yaml:**
```
groups:
  - name: test_recording_rule
    rules:
      - record: sum:up
        expr: sum(up)
```

**Additional infos:**
- The mounting works. My rules.yaml is located at /data/ruler and (for testing) at /tmp/ruler within my mimir pod
- I have the following permission: 
  drwxrwsr-x    2 root     10009400      4096 Jul  5 07:38 /data/ruler
  -rw-r--r--    1 root     10009400        94 Jul  5 07:37 /data/ruler/rules.yaml
  drwxr-xr-x    2 root     root            24 Jul  5 07:38 /tmp/ruler
  -rw-r--r--    1 root     10009400        94 Jul  5 07:37 /tmp/ruler/rules.yaml
- executing curl mimir.<namespace>.<cluster>:8080/prometheus/api/v1/rules returns {"status":"success","data":{"groups":[]},"errorType":"","error":""}

Can someone help me?
