### DISCUSSION TITLE
GrafanaMimir datasource shown as not compatible when creating Alert rules

### DISCUSSION THREAD

**Discussion by mglaub** [grafana/mimir#9671] [Help and support]
Hi,

im trying to get Alerting running with Mimir. When trying to create alert rules i cant choose a "Mimir or Loki alert" beacuse i do not have any compatible datasources. 
![image](https://github.com/user-attachments/assets/8e350865-3258-41c5-9eac-1886714055bc)

I have a Prometheus datasource with implementation & prometheusType Mimir setup which should be enough from what i understand.
Datasource config:
```
    - name: Mimir
      type: prometheus
      url: http://mimir.k8s-internal.datacenter.de/prometheus
      editable: true
      isDefault: true
      jsonData:
        tlsSkipVerify: true
        httpHeaderName1: X-Scope-OrgID
        manageAlerts: false
        implementation: mimir
        prometheusType: Mimir        
      basicAuth: true
      basicAuthUser: ...
      secureJsonData:
        basicAuthPassword: ...
        httpHeaderValue1: c50-inte|c50-preprod|c50-prod|dc-basic-inte|dc-basic-preprod|dc-basic-prod
````
I Also tryed to create a Alertmanager Datasource like this:
```  
  - name: Mimir Alertmanager
      type: alertmanager
      access: server
      url: http://mimir.k8s-internal.datacenter.de/
      editable: true
      isDefault: false
      jsonData:
        implementation: mimir
        tlsSkipVerify: true
      basicAuth: true
      basicAuthUser: ...
      secureJsonData:
        basicAuthPassword: ...
```
but that returns this error: 
![image](https://github.com/user-attachments/assets/3f751767-469a-462a-8890-96adfaedd03f)

I can also see these logs in grafana:
```
logger=context userId=1 orgId=1 uname=admin t=2024-10-18T13:20:32.245332835Z level=error msg="unexpected content type from upstream. expected YAML, got text/html" error="unexpected content type from upstream. expected YAML, got text/html" remote_addr=10.2.49.5 traceID=
logger=context userId=1 orgId=1 uname=admin t=2024-10-18T13:20:32.245468427Z level=error msg="Request Completed" method=GET path=/api/alertmanager/PAD28A8FB03F7D39C/config/api/v1/alerts status=500 remote_addr=10.2.49.5 time_ms=62 duration=62.420861ms size=94 referer="https://monitoring.k8s-internal.datacenter.de/alerting/notifications?alertmanager=Mimir+Alertmanager" handler=/api/alertmanager/:DatasourceUID/config/api/v1/alerts
logger=context userId=1 orgId=1 uname=admin t=2024-10-18T13:20:52.221086017Z level=info msg="Request Completed" method=GET path=/api/alertmanager/PAD28A8FB03F7D39C/config/api/v1/receivers status=404 remote_addr=10.2.49.5 time_ms=1 duration=1.062587ms size=24 referer="https://monitoring.k8s-internal.datacenter.de/alerting/notifications?alertmanager=Mimir+Alertmanager" handler=notfound
```
What am i missing here?
