### ISSUE TITLE
KEDA autoscaling additional requirements

### ISSUE THREAD

**Issue by bjorns163** [grafana/mimir#10265]
I've been testing the KEDA autoscaling option but when I connect it to the data source I'm missing some configuration options, also there's no option to authenticate to the data source. And if your data source has multiple instances of mimir in it, there is no way to filter the correct instance from the metrics.

In the ScaledObject there is a need for, `authModes`, with an `authenticationRef`, `ignoreNullValues` and `unsafeSsl` :

```  
triggers:
    - authenticationRef:
        name: keda-triggger-auth
      metadata:
        authModes: basic
        ignoreNullValues: 'true'
        unsafeSsl: 'false'
```

Additionally, in the query section of every `ScaledObject` you want to be able to set an extra label filter:

```
cluster_name="test"
```
