### ISSUE TITLE
Bug: Query-frontend 2.14 doesn't return complete timeseries in case of multi-tenancy

### ISSUE THREAD

**Issue by denraf** [grafana/mimir#10310]
### What is the bug?

When using mimir 2.14, the query frontend doesn't return the full timeseries when the tenants have different retention settings.
When just switching the query-frontend back to 2.13 all data shows up as expected with a multi-tenant datasource in Grafana.

### How to reproduce it?

Grafana datasource, with header X-Scope-OrgID: main|linkerd

Helm-distributed 5.5.0 install with config:
```
mimir:
  structuredConfig:
    # https://grafana.com/docs/mimir/latest/references/configuration-parameters/#limits
    tenant_federation:
      enabled: true
    limits:
      max_global_series_per_user: 100000000
      ingestion_rate: 2000000
      ingestion_burst_size: 50000000
      max_label_names_per_series: 50
      compactor_blocks_retention_period: 1y
    ruler:
      tenant_federation:
        enabled: true
runtimeConfig:
  overrides:
    linkerd:
      compactor_blocks_retention_period: 30d
```

### What did you think would happen?

Metrics belonging to the `main` tenant are visible for the full year.

### What was your environment?

Mimir 2.14
Kubernetes 1.30

### Any additional context to share?

When creating a new datasource in Grafana with X-Scope-OrgID set to `main` only, metrics for the full year are visible.
