### ISSUE TITLE
Bug: field max_global_series_per_user not found in type ingester.plain

### ISSUE THREAD

**Issue by hongbo-miao** [grafana/mimir#10593]
### What is the bug?

`max_global_series_per_user` in `runtimeConfig` failed.

### How to reproduce it?

This succeed:

```yaml
mimir:
  structuredConfig:
    limits:
      max_global_series_per_user: 1000000
```

This one failed:

```yaml
runtimeConfig:
  ingester_limits:
    max_global_series_per_user: 1000000
```

> load file: yaml: unmarshal errors: line 2: field max_global_series_per_user not found in type ingester.plain

![Image](https://github.com/user-attachments/assets/c8d0c6b3-7567-4d01-bc77-216f05dbc4e7)

### What did you think would happen?

I would expect changing `max_global_series_per_user` in `runtimeConfig` also works.

### What was your environment?

Kubbernetes: 1.30
Mimir: r328
Mimir Helm chart version: 5.7.0-weekly.328

### Any additional context to share?

There are more people met same error here: https://github.com/grafana/mimir/discussions/3130#discussioncomment-10984976
