### ISSUE TITLE
How to enable zero-ingestion feature flag?

### ISSUE THREAD

**Issue by metinogurlu** [grafana/mimir#10822]
Hi, I wanted to use `otel-created-timestamp-zero-ingestion-enabled` feature flag in a mimir-distributed helm deployment. It is both enabled in config and passed via argument but the generated metric values still start with positive values and counter resets doesn't create a zero value. 

Expected behavior must be, when counter reset occurs, counter value will be generated as first 0 and than the actual number. 

On mimir-prometheus `created-timestamp-zero-ingestion` flag also needs to be enabled as far as I understand but couldn't be sure since there's not enough documentation. 

OTel counter increases exported by Alloy. 

Here the running distributor arguments

```
    Args:
      -target=distributor
      -config.expand-env=true
      -config.file=/etc/mimir/mimir.yaml
      -server.grpc.keepalive.max-connection-age=60s
      -server.grpc.keepalive.max-connection-age-grace=5m
      -server.grpc.keepalive.max-connection-idle=1m
      -shutdown-delay=90s
      -distributor.otel-created-timestamp-zero-ingestion-enabled=true
```

and the configmap

```
    limits:
      max_cache_freshness: 10m
      max_query_parallelism: 240
      max_total_query_length: 12000h
      otel_created_timestamp_zero_ingestion_enabled: true
```
