### ISSUE TITLE
Idea: Allow runtime config managed externally

### ISSUE THREAD

**Issue by fyang13** [grafana/mimir#10963]
### What is the problem you are trying to solve?

In some deployments, user might want to manage runtime config dynamically outside of Helm-chart(e.g.: max_global_series_per_user for an environment with lots of tenants), it would be nice if user can optionally disable runtime config update through value file.

### Which solution do you envision (roughly)?

Update runtime-config template to observe the apply_runtime.enabled value, default to true.

### How long do you think this would take to be developed?

Small (<= 1 month dev)

**Comment by narqo** [comment]
> In some deployments, user might want to manage runtime config dynamically outside of Helm-chart

Mimir's [`-runtime-config.file`][1] config option (and its YAML variant) takes a list of files. Rather than expanding the chart with a new on/off switch, have you considered passing a second file, that your deployment manages externally?

This is what we do in Grafana cloud:

```
spec:
  containers:
  - args:
    ···
    -runtime-config.file=/etc/<··>/overrides.yaml,/etc/<··>/overrides.yaml,/etc/<··>/overrides.json.gz
```

[1]: https://grafana.com/docs/mimir/latest/configure/about-runtime-configuration/

**Comment by fyang13** [comment]
@narqo I like that approach! This way user can optionally use helm-chart to manage the initial set of the config and handle the dynamic part externally. And I see your example has .gz format, so that will also help the situation when config map size grows beyond 1MB.

**Comment by 56quarters** [comment]
Since multiple runtime config files can be used it seems like that solves this use case. I'm going to close this issue but please re-open if needed.

**Comment by fyang13** [comment]
@56quarters This issue is still needed for the deployment that's being managed via helm-chart? I don't see current helm-chart in this repo support the runtime-config.file option and it seems it's using configmap only? I have a draft PR [here](https://github.com/grafana/mimir/pull/10964) and probably will just go with the suggestion Dimitar has. What do you think?

**Comment by 56quarters** [comment]
> [@56quarters](https://github.com/56quarters) This issue is still needed for the deployment that's being managed via helm-chart? I don't see current helm-chart in this repo support the runtime-config.file option and it seems it's using configmap only? I have a draft PR [here](https://github.com/grafana/mimir/pull/10964) and probably will just go with the suggestion Dimitar has. What do you think?

You can specify a list of runtime configuration files from within the main configuration file:

```
runtime_config:
  # (advanced) How often to check runtime config files.
  # CLI flag: -runtime-config.reload-period
  [period: <duration> | default = 10s]

  # Comma separated list of yaml files with the configuration that can be
  # updated at runtime. Runtime config files will be merged from left to right.
  # CLI flag: -runtime-config.file
  [file: <string> | default = ""]
```

From https://grafana.com/docs/mimir/latest/configure/configuration-parameters/#configuration-parameters

**Comment by fyang13** [comment]
> > [@56quarters](https://github.com/56quarters) This issue is still needed for the deployment that's being managed via helm-chart? I don't see current helm-chart in this repo support the runtime-config.file option and it seems it's using configmap only? I have a draft PR [here](https://github.com/grafana/mimir/pull/10964) and probably will just go with the suggestion Dimitar has. What do you think?
> 
> You can specify a list of runtime configuration files from within the main configuration file:
> 
> ```
> runtime_config:
>   # (advanced) How often to check runtime config files.
>   # CLI flag: -runtime-config.reload-period
>   [period: <duration> | default = 10s]
> 
>   # Comma separated list of yaml files with the configuration that can be
>   # updated at runtime. Runtime config files will be merged from left to right.
>   # CLI flag: -runtime-config.file
>   [file: <string> | default = ""]
> ```
> 
> From https://grafana.com/docs/mimir/latest/configure/configuration-parameters/#configuration-parameters

Understood, but the helm-chart [here](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L471) only provide a way to configure it via single configmap?

**Comment by narqo** [comment]
I don't follow the issue now, sorry. The Helm chart's `runtimeConfig` values populate the `runtime.yaml`, which Mimir reads because of the default `runtime_config.file`. If you want to have another runtime config, which is managed externally, you can use the `structuredConfig` value to redefine Mimir's `runtime_config.file` and inject this external runtime config into the resources Helm manages. The chart provides all the extension points for that:

```
# my-values.yaml

mimir:
  structuredConfig:
    runtime_config:
      file: /var/{{ include "mimir.name" . }}/runtime.yaml,/var/mimir-ext/runtime2.yaml,/var/mimir-ext/runtime3.json

global:
  extraVolumes:
    - name: ext-runtime-configs
      configMap:
        name: mimir-ext-runtime-configs

  extraVolumeMounts:
    - name: ext-runtime-configs
      mountPath: /var/mimir-ext
```

<details>
<summary>Example of "ext-mimir-conf.yaml" ConfigMap</summary>

```
# ext-mimir-conf.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-ext-runtime-configs
  labels: {}
  namespace: mimir-1
data:
  runtimer2.yaml: |
    {}

  runtimer3.json: |
    {}
```

</details>
