### ISSUE TITLE
Docs: mimir-distributed keda autoscaling definition

### ISSUE THREAD

**Issue by seanankenbruck** [grafana/mimir#11449]
### Is your documentation request related to a feature? If so, which one?

This documentation request is related to PR #10266 . It would be nice if the available documentation provided a detailed description of the ScaledObject resource and calculations that are created by the helm chart when you enable:

```yaml
distributor:
  kedaAutoscaling:
    enabled: true
    preserveReplicas: false
    minReplicaCount: 1
    maxReplicaCount: 10
    targetCPUUtilizationPercentage: 70 # reduced from default of 100
    targetMemoryUtilizationPercentage: 70 # reduced from default of 100
    behavior:
      scaleDown:
        policies:
          - periodSeconds: 600
            type: Percent
            value: 10
```

This results in the following scaled object trigger definition deployed to a kubernetes cluster.

```yaml
triggers:
  - metadata:
      customHeaders: X-Scope-OrgId=tenant
      ignoreNullValues: "true"
      query: max_over_time(sum(sum by (pod) (rate(container_cpu_usage_seconds_total{container="distributor",namespace="mimir-test",}[5m]))
        and max by (pod) (up{container="distributor",namespace="mimir-test",}) > 0)[15m:])
        * 1000
      serverAddress: http://MIMIR-URL/prometheus
      threshold: "700"
      unsafeSsl: "false"
    type: prometheus
  - metadata:
      customHeaders: X-Scope-OrgId=tenant
      ignoreNullValues: "true"
      query: max_over_time(sum((sum by (pod) (container_memory_working_set_bytes{container="distributor",namespace="mimir-test",})
        and max by (pod) (up{container="distributor",namespace="mimir-test",}) > 0)
        or vector(0))[15m:]) + sum(sum by (pod) (max_over_time(kube_pod_container_resource_requests{container="distributor",namespace="mimir-test",
        resource="memory",}[15m])) and max by (pod) (changes(kube_pod_container_status_restarts_total{container="distributor",namespace="mimir-test",}[15m])
        > 0) and max by (pod) (kube_pod_container_status_last_terminated_reason{container="distributor",namespace="mimir-test",
        reason="OOMKilled",}) or vector(0))
      serverAddress: http://MIMIR-URL/prometheus
      threshold: "751619276"
      unsafeSsl: "false"
    type: prometheus
```

In my deployment of the helm chart, when you get the HPA definition. It shows the following calculated values:

```bash
kubectl get hpa keda-hpa-mimir-distributor -n mimir-test -o wide

NAME                                    REFERENCE        TARGETS                                  MINPODS   MAXPODS REPLICAS   AGE
keda-hpa-mimir-distributor   Deployment/mimir-distributor   50043m/700 (avg), 314609664/751619276 (avg)   2         6         2          116m
```

The calculated CPU and memory values seem to be in different units. Is there a reason why the calculated CPU values are in milicores but the threshold is of type 700(avg)? What is the unit that this average is displayed in? The memory metric does appear to be in type bytes for the calculated and the average threshold value but a clear definition would be helpful. 

### What is the solution that you would like or the expected outcome?

It would be great if there was a new document added to Mimir documentation that covers two things:

1. The configuration of keda autoscaling in the helm chart. Current docs only cover JSONNET. 
2. An explanation of the calculations created via the specification of `targetCPUUtilizationPercentage` and `targetMemoryUtilizationPercentage` in the helm chart. 

### What did you think would happen?

I expect the chart to configure the Prometheus query so that it returns the average CPU usage per pod, or configure the HPA to use value instead of averageValue if a total metric is returned so that the unit comparison is equivalent and it is easy to determine if the current load on the distributor will trigger a scale event or not. 

This would allow the threshold to be interpreted correctly and autoscaling to behave as expected. If there was documentation on using keda in the helm chart, then it would be easy to understand why the metric data displayed by the HPA are in different units. 

### What was your environment?

Kubernetes AKS deployment of mimir-distributed helm chart 5.7.0.

**Comment by dimitarvdimitrov** [comment]
Thanks for reporting this. There are some docs for autoscaling for Helm which are yet to be published with the next release some time in June/July. https://grafana.com/docs/helm-charts/mimir-distributed/next/configure/configure-autoscaling/

I opened a PR to clarify what the target utilization means in the values.yaml: https://github.com/grafana/mimir/pull/11489

Can you take a look and let me know if there's something missing? Thanks again 🙏

**Comment by seanankenbruck** [comment]
@dimitarvdimitrov thanks for creating that PR, I'll review it today. What I am still struggling to understand is why the calculated value shown by the HPA created from the ScaledObject inflates the current CPU usage to a value that doesn't really make sense. I just ran another very simple test to demonstrate the output shown by the HPA. 

```yaml
distributor:
  kedaAutoscaling:
    enabled: true
    preserveReplicas: false
    minReplicaCount: 1
    maxReplicaCount: 2
    targetCPUUtilizationPercentage: 25
  resources:
    requests:
      cpu: 250m
```

When the chart is rendered, the following calculation from the distributor-so.yaml file is used to determine the threshold:

`threshold: {{ mulf (include "mimir.cpuToMilliCPU" (dict "value" $cpu_request)) (divf .Values.distributor.kedaAutoscaling.targetCPUUtilizationPercentage 100) | floor | int64 | quote }}`

and correctly arrives at a value of 62m.

`threshold = 250m * 0.25 = 62.5m → floored to "62"`

After deploying the ScaledObject into my cluster, the corresponding HPA that gets created shows a calculated value for the average CPU metric to be 

`"s0-prometheus" (target average value):  54747m/ 62`

The unit specification shown in the HPA with an "m" at the end is misleading because it indicates that the target value is shown in millicores. The calculated value of 54747m is well above the cpu allocation for distributor pods that is 250m. 

By running the query used by the ScaledObject directly in Grafana the result returned is `54.74737659029304` . This is the true CPU usage for this pod in the test scenario described above. 

My question is this, why is this value shown in the HPA seemingly inflated or shown in the wrong unit?
