### ISSUE TITLE
Bug: Erorr on update OSS Mimir 2.16.0 docker

### ISSUE THREAD

**Issue by sdejong629** [grafana/mimir#11552]
### What is the bug?

When updating the docker image tag to 2.16.0, the docker images fails to start and craps out with a panic error (exit code 2).

```
panic: duplicate metrics collector registration attempted
mimir-cluster-mimir-1  |
mimir-cluster-mimir-1  | goroutine 1 [running]:
mimir-cluster-mimir-1  | github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0x4ff13a0, {0xc0018215d0?, 0x0?, 0x0?})
mimir-cluster-mimir-1  |        /__w/mimir/mimir/vendor/github.com/prometheus/client_golang/prometheus/registry.go:406 +0x66
mimir-cluster-mimir-1  | github.com/prometheus/client_golang/prometheus/promauto.Factory.NewCounterVec({{0x36fcf30?, 0x4ff13a0?}}, {{0x0, 0x0}, {0x0, 0x0}, {0x3061164, 0x3d}, {
mimir-cluster-mimir-1  | 0x3056891, 0x39}, ...}, ...)
mimir-cluster-mimir-1  |        /__w/mimir/mimir/vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go:276 +0x163
mimir-cluster-mimir-1  | github.com/grafana/mimir/pkg/util.NewRequestInvalidClusterValidationLabelsTotalCounter({0x36fcf30, 0x4ff13a0}, {0x2f9a0cf, 0xe}, {0x2f855e2, 0x4})
mimir-cluster-mimir-1  |        /__w/mimir/mimir/pkg/util/metrics.go:23 +0x1bc
mimir-cluster-mimir-1  | github.com/grafana/mimir/pkg/scheduler.NewScheduler({0x64, 0x0, {0x6400000, 0x6400000, {0x0, 0x0}, 0x0, 0x0, 0x0, {0x5f5e100, ...}, ...}, ...}, ...)
mimir-cluster-mimir-1  |        /__w/mimir/mimir/pkg/scheduler/scheduler.go:163 +0x689
mimir-cluster-mimir-1  | github.com/grafana/mimir/pkg/mimir.(*Mimir).initQueryScheduler(0xc00083a000)
mimir-cluster-mimir-1  |        /__w/mimir/mimir/pkg/mimir/modules.go:1095 +0xa8
mimir-cluster-mimir-1  | github.com/grafana/dskit/modules.(*Manager).initModule(0xc00094f2a8, {0xc000160604, 0xf}, 0xc000b6f758, 0xc00077f920)
mimir-cluster-mimir-1  |        /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136 +0x1ea
mimir-cluster-mimir-1  | github.com/grafana/dskit/modules.(*Manager).InitModuleServices(0xc00094f2a8, {0xc000520760, 0x2, 0xf?})
mimir-cluster-mimir-1  |        /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108 +0xe8
mimir-cluster-mimir-1  | github.com/grafana/mimir/pkg/mimir.(*Mimir).Run(0xc00083a000)
mimir-cluster-mimir-1  |        /__w/mimir/mimir/pkg/mimir/mimir.go:902 +0x387
mimir-cluster-mimir-1  | main.main()
mimir-cluster-mimir-1  |        /__w/mimir/mimir/cmd/mimir/main.go:227 +0xf85
mimir-cluster-mimir-1 exited with code 2
``` 

### How to reproduce it?

Currently running a cluster with 3 nodes running mimir 2.12.0, but also tested with 2.13.1 and 2.15.2 (current version).
Change the docker tag to for mimir to 2.16.0
Start docker-compose project
Errors out, no docker container is running

### What did you think would happen?

The container should just start, like in al the other updates we ran

### What was your environment?

Running 3 virtual machine (ubuntu 24.04) with each a docker compose project which contains only the mimir docker image. In front of the cluster us a simple nginx loadbalancer.

Mimir config is minimal
```
target: all,query-scheduler
multitenancy_enabled: false

server:
  log_level: debug
  http_listen_port: <port>

memberlist:
  join_members:
    - <fqdn_node_0>
    - <fqdn_node_1>
    - <fqdn_node_2>
  advertise_addr: <ip_address>

common:
  storage:
    backend: s3
    s3:
      endpoint: <set>
      region: <set>
      access_key_id: <set>
      secret_access_key: <set>

blocks_storage:
  s3:
    bucket_name: <bucket_metrics>

ruler_storage:
  s3:
    bucket_name: <bucket_ruler>

ingester:
  ring:
    instance_addr: <ip_address>

compactor:
  sharding_ring:
    instance_addr: <ip_address>

store_gateway:
  sharding_ring:
    instance_addr: <ip_address>

distributor:
  ring:
    instance_addr: <ip_address>

ruler:
  ring:
    instance_addr: <ip_address>

frontend:
  address: <ip_address>

query_scheduler:
  service_discovery_mode: ring
  ring:
    instance_addr: <ip_address>

limits:
  ingestion_rate: 800000
  ingestion_burst_size: 1200000
  max_global_series_per_user: 0
  compactor_blocks_retention_period: 1y
  max_label_value_length: 4096
```
