### ISSUE TITLE
Bug: [Helmchart] You have set ingester.zoneAwareReplication.migration.replicas, but ingester.zoneAwareReplication.migration.enabled=false

### ISSUE THREAD

**Issue by Breee** [grafana/mimir#11553]
### What is the bug?

When upgrading I get: 

```
Error: UPGRADE FAILED: execution error at (maas/charts/mimir/templates/validate.yaml:162:4): You have set ingester.zoneAwareReplication.migration.replicas, but ingester.zoneAwareReplication.migration.enabled=false. Please consult the Migrating from single zone with Helm document.
```

Although the values clearly state: 

```
  ingester:
    persistentVolume:
      enabled: false
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - ingester
            topologyKey: "kubernetes.io/hostname"
    zoneAwareReplication:
      enabled: false
      topologyKey: "kubernetes.io/hostname"
      migration:
        enabled: false
```

that means the default values of `ingester.zoneAwareReplication.migration.replicas`  seems to be wrong. 

### How to reproduce it?

see above

### What did you think would happen?

i would assume that if migration=false,  the replicas are automatically 0 by default

### What was your environment?

  - name: mimir-distributed
    alias: mimir
    version: "5.7.0"
    repository: "https://grafana.github.io/helm-charts"

### Any additional context to share?

Setting: 

```
     migration:
        replicas: 0
        enabled: false
``` 

fixes the problem, but confused us in the first place, because the upgrade just failed for no good reason.

**Comment by narqo** [comment]
> Fixed with Helm 3.18.1

@Breee could you check if the updated version of Helm itself fixes the problem? Please, reopen if not

**Comment by KaloyanHr** [comment]
I had the same issue on version 5.7.0 of mimir-distributed as well @z0rc @narqo 

In my case I had to update replicas from 0 to empty string to get it to not fail on templating:

```
    migration:
      # -- Indicate if migration is ongoing for multi zone ingester
      enabled: false
      # -- Exclude default zone on write path
      excludeDefaultZone: false
      # -- Enable zone-awareness, read path only
      readPath: false
      # -- Total number of replicas to start in availability zones when migration is enabled
      replicas: ""
      # -- Scale default zone ingesters to 0
      scaleDownDefaultZone: false
      # -- Enable zone-awareness, write path only
      writePath: false
```
