### ISSUE TITLE
Bug: Adding `compactor_blocks_retention_period` causes time-data corruption of samples in queries

### ISSUE THREAD

**Issue by ShadowJonathan** [grafana/mimir#11599]
### What is the bug?

~~This is something i've been debugging for the past couple of days, but when re-aligning our Alloy configuration from an existing (test) Mimir instance, to a new Production Mimir instance, we experienced corruption of the resultant data, looking like a sawtooth pattern, and changing on every reload;~~

After adding `compactor_blocks_retention_period` to my config, samples which fall within that range are misaligned to the time series.

![Image](https://github.com/user-attachments/assets/b2bcf26a-a6e5-4a45-bfde-e9acb4a186f2)

The problem seems to sit in the fact that all samples have slight milliseconds of offset, seen here; 

![Image](https://github.com/user-attachments/assets/6f980335-0f85-4a9b-8d47-ab314a4bc6f3)

![Image](https://github.com/user-attachments/assets/0afe4d91-8ce6-428e-844f-82e9a7ef0db3)

### How to reproduce it?

1. Setup testing/throwaway Mimir instance
2. Point Alloy remote write configurations at it
3. Setup second Mimir instance
4. Rewrite configuration of existing alloy service, and point at new (secondary) mimir instance

### What did you think would happen?

The WAL to be properly replayed, and new samples to be correctly ingested

### What was your environment?

3 VMs, one with Alloy, one with the initial Mimir, and one with the secondary Mimir.

Latest Mimir (2.16.0) and Alloy (1.8.3-1 Debian)

### Any additional context to share?

~~This issue got fixed by *completely resetting all state*, by deleting the mimir instance, and deleting *all* affected/affecting alloy instances.~~

Nevermind, this has not been fixed as of now, even after resetting all data;

![Image](https://github.com/user-attachments/assets/5cab51ac-52c2-42e2-ac79-275eb31cc829)

**Comment by ShadowJonathan** [comment]
I've just tried this with a default config, and it seems to work properly now.

<details>
<summary>(Default config)</summary>

```yaml
activity_tracker: {}

alertmanager: {}

 

alertmanager_storage:

  backend: local

 

blocks_storage:

  backend: filesystem

  bucket_store:

    sync_dir: /tmp/mimir/tsdb-sync

  filesystem:

    dir: /tmp/mimir/blocks

  tsdb:

    dir: /tmp/mimir/tsdb

compactor:

  sharding_ring:

    kvstore:

      store: inmemory

distributor:

  pool:

    health_check_ingesters: true

ingester:

  ring:

    final_sleep: 0s

    kvstore:

      store: inmemory

    min_ready_duration: 0s

    num_tokens: 512

    replication_factor: 1

ingester_client:

  grpc_client_config:

    grpc_compression: gzip

    max_recv_msg_size: 104857600

    max_send_msg_size: 104857600

limits:

  ingestion_burst_size: 500000

  ingestion_rate: 250000

 

multitenancy_enabled: false

ruler:

  enable_api: true
 

ruler_storage:

  backend: filesystem

  local:

    directory: /tmp/mimir/rules

server:

  grpc_server_max_concurrent_streams: 1000

  grpc_server_max_recv_msg_size: 104857600

  grpc_server_max_send_msg_size: 104857600

  http_listen_port: 9009
```
</details>

With my config looking like the following (minus identifiable details)

```yaml
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter


# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  tsdb:
    dir: /var/lib/mimir/ingester
  bucket_store:
    sync_dir: /var/lib/mimir/tsdb-sync
  backend: filesystem
  filesystem:
    dir: /var/lib/mimir/tsdb


# Blocks storage requires a prefix when using a common object storage bucket.
ruler_storage:
  filesystem:
    dir: /var/lib/mimir/r_storage


# Alertmanager storage requires a prefix when using a common object storage bucket.
alertmanager_storage:
  filesystem:
    dir: /var/lib/mimir/am_storage


ruler:
  rule_path: /var/lib/mimir/ruler
  alertmanager_url: http://127.0.0.1:9090/alertmanager
  ring:
    heartbeat_period: 5s
    heartbeat_timeout: 10s


alertmanager:
  data_dir: /var/lib/mimir/alertmanager
  external_url: https://[REDACTED]/alertmanager


server:
  http_listen_port: 9090
  http_listen_address: 127.0.0.1
  log_level: info


limits:
  compactor_blocks_retention_period: 6m


distributor:
  pool:
    health_check_ingesters: true


ingester:
  ring:
    final_sleep: 0s
    min_ready_duration: 0s
    num_tokens: 512
    replication_factor: 1
    kvstore:
      store: inmemory


compactor:
  data_dir: /var/lib/mimir/compactor


multitenancy_enabled: False
```
