### ISSUE TITLE
Runtime Configuration Overrides seem to be broken

### ISSUE THREAD

**Issue by jordan-simonovski** [grafana/mimir#1637]
#### Describe the bug
Currently encountering issues when trying to apply a custom configuration for overrides.max_global_series_per_user. The config object itself seems fine, but Mimir fails to unmarshal the value of this field. 

I had to also work backward and find the RuntimeConfig struct to even be able to apply this option. Possible documentation update too?

#### To Reproduce

Set my runtime config in my YAML to

```
runtimeConfig:
  ingester_limits:
    max_ingestion_rate: 200000
    max_series: 400000000
    max_tenants: 1000
    max_inflight_push_requests: 30000
  overrides:
    max_global_series_per_user: 0
```

Upon verifying if the ingesters are picking up the configuration I am receiving 

```
level=error ts=2022-04-05T23:47:12.841073115Z caller=manager.go:137 msg="failed to load config" err="load file: yaml: unmarshal errors:\n  line 8: cannot unmarshal !!int `0` into validation.plain"
```

#### Expected behavior

The max global series per user should be overridden to 0, allowing me to throw more load at it via load testing.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm
