### ISSUE TITLE
Provide an example Prometheus config compatible with Mimir dashboards and alerts

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1642]
Mimir dashboards and alerts have some [requirements](https://grafana.com/docs/mimir/latest/operators-guide/visualizing-metrics/requirements/) with regards to labels associated to Mimir metrics. We should provide an example Prometheus config adding such labels to the scraped metrics.

_This issue originated from this [Slack discussion](https://grafana.slack.com/archives/C039863E8P7/p1649257808077389)._

**Comment by wilfriedroset** [comment]
The documentation is quite helpful for users running Mimir in k8s.
For those running Mimir on baremetal some guidance would be helpful.

Discalmer: I'm running Mimir on baremetal 😅

**Comment by wilfriedroset** [comment]
Thank you for the huge amount of work shared. This deliver immediate value and actionnable insights.

All feedbacks are based on a baremetal deployment:
* one mimir execution per VM, one target per mimir execution, which means a VM per target
* `node_exporter` is installed on each vm and listen on localhost
* each VM runs its own Prometheus in `agent mode` to scrape localhost then remote write to mimir
  * reason: network hardening, one less port to bind, expose, iptables and, so on
* Rules and Alerting aren't used for now

* Dashboards have templated datasource which is very nice
* Dashboards with collapsed rows are great to avoid loading all panels at once

* Multi-line queries are easier to read in Grafana (when editing a panel), this is cosmetic 
  * Example of panel with a multi-line query: `Mimir / Reads`, row `Memcached – metadata cache (store-gateway accesses)`, panel `Requests / sec`
  * Example of panel without a multi-line query: `Mimir / Reads`, row `Gateway`, panel `latency`

* Not all panels have description, this could benefit users who do not have `editor` privileges in Grafana and can't see the underlying query. Some description are not really need as the panel name is quite sufficient
  * Example of panel with a description: `Mimir / Tenants`, row `Series and exemplars`, panel `series`
  * Example of panel without a description: `Mimir / Reads`, row `Cache – query results`, panels  `latency (old)` vs `latency (new)`

* Use of old panel type `Graph (old)` and `Table (old)`. /!\ this might depends on Grafana version
  * when in edit mode Grafana shows the following message `Consider switching to the XX visualization type. It is a more capable and performant version of this panel.`
  
* lots of panels use `container_*` which are not usable for baremetal deployment
  * example: `container_cpu_usage_seconds_total` vs `node_cpu_seconds_total`. 
  * example 2: `container_network_receive_bytes_total` vs `node_network_receive_bytes_total`
  * Idea keep a map of correspondance and align at build time, and document on how to adjust `instance_names` as the regex might be different: `compactor.*` vs `mimir-.*compactor.*`

* Here is a list of fully usable for baremetal deployment:
  * `Mimir / Queries`
  * `Mimir / Tenants`
  * `Mimir / Writes`

* Here is a list of dashboard which are too k8s oriented to be usable for baremetal deployment:
  * `Mimir / Compactor resources`
  * `Mimir / Reads resources`
  * `Mimir / Reads`: row `querier - autoscaling`
  * `Mimir / Writes resources`, apart from `In-memory series`
  * `Mimir / Reads networking`, apart from `inflight requests (per pod)` and `tcp connection (per pod)`
  * `Mimir / Writes networking`, apart from `inflight requests (per pod)` and `tcp connection (per pod)`
  * `Mimir / Rollout progress`
Alternatively, we can set `resources_dashboards_enabled: false` to not build the dashboards.

In several dashboard the row `Gateway` is usable only if the deployment also have cortex-gw
  * example: `Mimir / Reads`, `Mimir / Writes`

The dashboard `Mimir / Slow queries` requires to send Mimir logs to a Loki database.

The dahsboard `Mimir / Config`, isn't as insightful as it depends on the content of configuration file which can be different:
  * example: `http_listen_address`, `grpc_listen_address`, `cert_file`, `key_file`, `instance_id`, `instance_availability_zone`

## Improvement ideas

* In some case allowing filter on `{{instance}}`/`{{pod}}`/`{{target}}` could be useful
  * Examples: `Mimir / Compactor`, `Mimir / Object Store`
* `datasource` variable select all `Prometheus` datasource (based on the type). Using the filter feature them based on a regex would help user who have lots of Prometheus datasources
  * Examples: `.*mimir.*`

## Prometheus configuration samples

To be able to use the mixin while running mimir on baremetal I've configure the labels as follow.

```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    zone: [redacted]
    datacenter: [redacted]
    cluster_id: 0
    role: compactor

scrape_configs:
- job_name: baremetal/compactor
  static_configs:
  - targets:
    - [redacted]:9009
    labels:
      instance: mimir-0-compactor-1.[redacted]
      cluster: 0 # same as cluster_id
      namespace: baremetal 

- job_name: node
  metric_relabel_configs:
  - source_labels:
    - __name__
    regex: "^(go|promhttp_metric_handler|node_scrape_collector)_.*"
    action: drop
  static_configs:
  - targets:
    - localhost:9100
    labels:
      instance: mimir-0-compactor-1.[redacted]
```
Documentation says that each metrics must have 5 labels: cluster, namespace, job, pod, and instance.
Each host already has a label instance which is unique
For a baremetal deployment `hostname == pod == instance`.
As such when building the dashboard the following variables can set `per_instance_label=instance`  and `per_node_label=instance`.

The rest of the information system already use clustering label: `cluster_id`. Doing so lead to have a duplicate information because `cluster == cluster_id`.
Making the label `cluster` configurable would help to avoid duplication and ease the integration of Mimir metrics where clustering labels are already used.

While the documentation says that `cluster` label is not configurable `operations/mimir-mixin/config.libsonnet` has a setting `per_cluster_label` which allow that.
Setting `per_cluster_label: 'cluster_id'` produces a template variable like so `label_values(cortex_build_info, cluster_id)` which is the expected query.
Later on the variable is use like so `count(cortex_config_hash{cluster_id=~"$cluster", namespace=~"$namespace"}) by (sha256)`, again this is the expected behavior.
Is this correct or am I missing something?
