### ISSUE TITLE
Docs: document how to configure storage bucket (including authentication)

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#1785]
I've seen some questions from community about how to configure storage bucket and its authentication. We should add a documentation page to cover it, including:

- S3 authentication options (including IAM profile)
- GCS authentication options

References:
- [How a community user configured GCS](https://grafana.slack.com/archives/C039863E8P7/p1651085581167489)
- [Issues a community user faced setting up S3 with IAM auth](https://grafana.slack.com/archives/C039863E8P7/p1649236647938229)

**Comment by HeshamMeneisi** [comment]
@pracucci I'm also having an issue with the S3 IAM auth (IRSA). Can you share some details?

**Comment by pracucci** [comment]
We should extend the doc introduced in https://github.com/grafana/mimir/pull/2347.

**Comment by mtrin** [comment]
Hi all - I suggest clear examples on how to use structured config on helm, and how to configure Azure and\or how to config it so it uses your own StorageClass. (as well as sinppets for each implementation)
I realised you use Thanos backend and had to go read their docos (which are also a bit cryptic on how it does Azure)
here's how I configured using account/key
```
mimir:
  structuredConfig:
    multitenancy_enabled: false
    no_auth_tenant: aksclusterlower01
    common:
      storage:
        backend: azure
        azure:
          account_name: sttecdev02
          account_key: "${STORAGE_ACCOUNT_KEY}"
          endpoint_suffix: 'blob.core.windows.net'
    blocks_storage:
      backend: azure
      azure:
        container_name: platform-mimir-block-storage
    ruler_storage:
      backend: azure
      azure:
        container_name: platform-mimir-ruler-storage
    alertmanager_storage:
      backend: azure
      azure:
        container_name: platform-mimir-alertmanager-storage
```

**Comment by mtrin** [comment]
Ok after some digging I realised this is not supported because of the module that is used
https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob#prerequisites

Is there a way to use [Azure Blob CSI Driver](https://github.com/kubernetes-sigs/blob-csi-driver)? As I understand it won't be possible to use this due to multi-node filesystem limitation but in that case ReadWriteMany should work?

**Comment by pracucci** [comment]
> Is there a way to use [Azure Blob CSI Driver](https://github.com/kubernetes-sigs/blob-csi-driver)? As I understand it won't be possible to use this due to multi-node filesystem limitation but in that case ReadWriteMany should work?

I'm not aware of anyone using  [Azure Blob CSI Driver](https://github.com/kubernetes-sigs/blob-csi-driver) as a replacement for the object storage in Mimir, and I'm not familiar with it.

From a quick read to the doc, it looks like it allows you to "mount" an Azure storage container as a local disk / volume. If my understanding is correct, then please continue read the following.

Generally speaking, we strongly recommend to use our client directly talking to the object storage, with no layer in between (that's what we support). That being said, if you want to give it a try, you may consider using the Mimir `filesystem` backend type for the object storage, and configure the filesystem path to to the path where the driver mounted the volume.

**Comment by mtrin** [comment]
@pracucci thanks a lot for the clarification

**Comment by GrafanaWriter** [comment]
@pracucci and @osg-grafana - this issue is quite stale; is it resolved or should it be moved to Backlog for future planning?

**Comment by osg-grafana** [comment]
The action items within the description are still relevant.

**Comment by lindhe** [comment]
Hi! I'm just getting started with Mimir and want to pitch in with my two cents here.

I agree that it would be great if the documentation could be improved regarding S3 and especially authentication for that. I have configured Loki before, so I was kind of prepared for injection of environment variables needing an extra flag when starting. Yet I struggled with it and it was a lot of guesswork for me before I got everything right, not so fun.

Things that tripped me up:

- In Loki, the Helm chart value for extra args is `extraArgs: ['-config.expand-env=true']` but for Mimir it's `extraArgs: { config.expand-env: true }`.
- I checked [the architecture diagram for Mimir](https://grafana.com/docs/mimir/latest/get-started/about-grafana-mimir-architecture/) and it looked like only three components would communicate with S3: ingester, compactor and store-gateway. So I configured them with S3 credentials. But then it turns out some other components also require S3 credentials, for example alertmanager. It would be **great** if there was a chart value that helped me set `extraArgs` and `extraEnvFrom` automatically for all components that require S3 credentials.

**Comment by chrburmeister** [comment]
I'm having the same issue, the state of the docs is really bad. I want to deploy distributed Mimir on AKS and I cannot make the dam thing save anything to the object storage (azure blob in my case). Only the "mimir_cluster_seed.json" blob gets created. What obviously makes me think the connection works, but no other data is saved on the storage account. I set up a remote write from Prometheus and I can query the data with Grafana, no problems.

Can the config be verified somehow? Any suggestion would be appreciated.

**Comment by lindhe** [comment]
@chrburmeister I got it working by a config similar to this values file:

```yaml
alertmanager:
  extraArgs:
    config.expand-env: true
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-access-key

compactor:
  extraArgs:
    config.expand-env: true
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-access-key

ingester:
  extraArgs:
    config.expand-env: true
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-access-key

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          access_key_id: ${S3_ACCESS_KEY_ID}
          endpoint: s3.example.com
          region: us-east-1
          secret_access_key: ${S3_SECRET_ACCESS_KEY}
    blocks_storage:
      s3:
        bucket_name: example-mimir-blocks
    alertmanager_storage:
      s3:
        bucket_name: example-mimir-alertmanager
    ruler_storage:
      s3:
        bucket_name: example-mimir-ruler

minio:
  enabled: false

querier:
  extraArgs:
    config.expand-env: true
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-access-key

ruler:
  extraArgs:
    config.expand-env: true
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-access-key

store_gateway:
  extraArgs:
    config.expand-env: true
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-access-key
```

There's a lot of code repetition here. Unless I've missed something in the docs and config, this is unfortunately how to configure it right now. So this is a good example of why the docs needs to be improved. And perhaps a code change could also be made to the Helm chart reducing the need for all this repetition. Having common `extraArgs` and `extraEnvFrom` for all pods would reduce the repetition by a lot!

**Comment by chrburmeister** [comment]
Thanks @lindhe it works now for me. I use Mimir as a micro service and had to add the secret to other services as well - find my working version for Azure below:

## secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mirmir-storage-key
  namespace: monitoring
type: Opaque
data:
  AZURE_ACCOUNT_KEY: <base 64 encoded key>
```

## mimir values.yaml

```yaml
mimir:
  structuredConfig:
    common:
      storage:
        backend: "azure"
        azure:
          account_name: <storage account name>
          account_key: "${AZURE_ACCOUNT_KEY}"
          endpoint_suffix: blob.core.windows.net
    blocks_storage:
      backend: azure
      azure:
        container_name: mimir-blocks

    alertmanager_storage:
      backend: azure
      azure:
        container_name: mimir-alertmanager

    ruler_storage:
      backend: azure
      azure:
        container_name: mimir-ruler

ingester:
  replicas: 2
  extraEnvFrom:
    - secretRef:
        name: mirmir-storage-key
  zoneAwareReplication:
    enabled: false

querier:
  extraArgs:
    config.expand-env: true
  replicas: 1
  extraEnvFrom:
    - secretRef:
        name: mirmir-storage-key

compactor:
  extraEnvFrom:
    - secretRef:
        name: mirmir-storage-key
  replicas: 1

store_gateway:
  extraArgs:
    config.expand-env: true
  replicas: 1
  extraEnvFrom:
    - secretRef:
        name: mirmir-storage-key
ruler:
  extraArgs:
    config.expand-env: true
  replicas: 1
  extraEnvFrom:
    - secretRef:
        name: mirmir-storage-key

minio:
  enabled: false

alertmanager:
  replicas: 1
  extraEnvFrom:
    - secretRef:
        name: mirmir-storage-key

distributor:
  replicas: 1
  extraEnvFrom:
  - secretRef:
      name: mirmir-storage-key

overrides_exporter:
  replicas: 1

ruler_querier:
  replicas: 1

ruler_query_frontend:
  replicas: 1

ruler_query_scheduler:
  replicas: 1

query_frontend:
  replicas: 1

query_scheduler:
  replicas: 1

chunks-cache:
  replicas: 1

index-cache:
  replicas: 1

metadata-cache:
  replicas: 1

results-cache:
  replicas: 1

nginx:
  replicas: 2

gateway:
  replicas: 1

admin_api:
  replicas: 1

admin-cache:
  replicas: 1

graphite:
  querier:
    replicas: 1
  write_proxy:
    replicas: 1

gr-aggr-cache:
  replicas: 1

gr-metricname-cache:
  replicas: 1

federation_frontend:
  replicas: 1

continuous_test:
  replicas: 1
```

This also changes depending on the deployment mode. It really makes me consider another solution at this point...
