### ISSUE TITLE
Too much memory used and bad query performance

### ISSUE THREAD

**Issue by jackpgao** [grafana/mimir#1850]
We have 3119 target from Prometheus, each has 3600 metric, scrape_interval is 60sec.

4 Mimir node, config as below.

The Mimir use too much memory, and the query performance is bad.

<img width="978" alt="image" src="https://user-images.githubusercontent.com/3423412/168578043-8018bcd2-11b7-401a-985f-1cb2b750d6c1.png">

```yaml
blocks_storage:
    backend: s3
    s3:
        access_key_id: mimir
        bucket_name: mimir-blocks
        endpoint: xx:9000
        insecure: true
        secret_access_key: '********'
    tsdb:
        block_ranges_period:
            - 10m0s
        dir: /data1/mimir/ingester
limits:
    ingestion_burst_size: 20000000
    ingestion_rate: 1e+06
    max_global_series_per_metric: 200000000
    max_global_series_per_user: 1500000000
    max_label_names_per_series: 30000000
memberlist:
    join_members:
        - xx
        - xx
        - xx
        - xxx
server:
    log_level: debug
target: all,alertmanager,overrides-exporter
```

We use a Nginx  as load balance before the 4 node Mimir, and the nginx log show that the `/api/v1/push` only use about 10-20 ms, but the `/prometheus/api/v1/query_range` from Grafana is more than 5 sec.
