### ISSUE TITLE
Alert MimirCompactorHasNotUploadedBlocks always fires when running single-node

### ISSUE THREAD

**Issue by adeverteuil** [grafana/mimir#1898]
#### Describe the bug
I'm running GEM v2.0 in single-node configuration (for testing and training purposes).

I imported the mimir rules and alerts in Prometheus to monitor my GEM process.

The `MimirCompactorHasNotUploadedBlocks` alert is always firing, but there is no problem with the compactor.

#### To Reproduce

1. Start GEM v2.0 in single node configuration.
2. Set up Mimir rules and alerts in Prometheus to monitor GEM.

#### Environment

- Infrastructure: Ubuntu 20.04 VM, service managed by systemd
- Deployment tool: Ansible

#### Additional Context

This is the alert definition:
```
  - alert: MimirCompactorHasNotUploadedBlocks
    annotations:
      message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace
        }} has not uploaded any block in the last 24 hours.
    expr: |
      (time() - thanos_objstore_bucket_last_successful_upload_time{job=~".+/(compactor.*|cortex|mimir)"} > 60 * 60 * 24)
      and
      (thanos_objstore_bucket_last_successful_upload_time{job=~".+/(compactor.*|cortex|mimir)"} > 0)
    for: 15m
    labels:
      severity: critical
  - alert: MimirCompactorHasNotUploadedBlocks
    annotations:
      message: Mimir Compactor {{ $labels.pod }} in {{ $labels.cluster }}/{{ $labels.namespace
        }} has not uploaded any block in the last 24 hours.
    expr: |
      thanos_objstore_bucket_last_successful_upload_time{job=~".+/(compactor.*|cortex|mimir)"} == 0
    for: 24h
    labels:
      severity: critical
```

This is the firing alert labels:
```
amtool --alertmanager.url=http://localhost:9093 --output=extended alert
Labels                                                                                                                                                                                              Annotations                                                                                 Starts At                Ends At                  Generator URL                                                                                                                                                            State   
alertname="AlwaysFiring" severity="off"                                                                                                                                                             description="Always firing alert for tests." summary="Test alert"                           2022-05-02 20:28:22 UTC  2022-05-19 19:57:22 UTC  http://gem-lab-01:9090/graph?g0.expr=vector%281%29&g0.tab=1                                                                                                              active  
alertname="MimirCompactorHasNotUploadedBlocks" bucket="gem-tsdb" cluster="vm" component="purger" instance="gem-lab-01" job="default/mimir" namespace="default" pod="1" severity="critical"          message="Mimir Compactor 1 in vm/default has not uploaded any block in the last 24 hours."  2022-05-18 15:38:22 UTC  2022-05-19 19:56:22 UTC  http://gem-lab-01:9090/graph?g0.expr=thanos_objstore_bucket_last_successful_upload_time%7Bjob%3D~%22.%2B%2F%28compactor.%2A%7Ccortex%7Cmimir%29%22%7D+%3D%3D+0&g0.tab=1  active  
alertname="MimirCompactorHasNotUploadedBlocks" bucket="gem-tsdb" cluster="vm" component="store-gateway" instance="gem-lab-01" job="default/mimir" namespace="default" pod="1" severity="critical"   message="Mimir Compactor 1 in vm/default has not uploaded any block in the last 24 hours."  2022-05-18 15:38:22 UTC  2022-05-19 19:56:22 UTC  http://gem-lab-01:9090/graph?g0.expr=thanos_objstore_bucket_last_successful_upload_time%7Bjob%3D~%22.%2B%2F%28compactor.%2A%7Ccortex%7Cmimir%29%22%7D+%3D%3D+0&g0.tab=1  active  
alertname="MimirCompactorHasNotUploadedBlocks" bucket="gem-tsdb" cluster="vm" component="querier" instance="gem-lab-01" job="default/mimir" namespace="default" pod="1" severity="critical"         message="Mimir Compactor 1 in vm/default has not uploaded any block in the last 24 hours."  2022-05-18 15:38:22 UTC  2022-05-19 19:56:22 UTC  http://gem-lab-01:9090/graph?g0.expr=thanos_objstore_bucket_last_successful_upload_time%7Bjob%3D~%22.%2B%2F%28compactor.%2A%7Ccortex%7Cmimir%29%22%7D+%3D%3D+0&g0.tab=1  active  
alertname="MimirCompactorHasNotUploadedBlocks" bucket="gem-ruler" cluster="vm" component="ruler-storage" instance="gem-lab-01" job="default/mimir" namespace="default" pod="1" severity="critical"  message="Mimir Compactor 1 in vm/default has not uploaded any block in the last 24 hours."  2022-05-18 15:38:22 UTC  2022-05-19 19:56:22 UTC  http://gem-lab-01:9090/graph?g0.expr=thanos_objstore_bucket_last_successful_upload_time%7Bjob%3D~%22.%2B%2F%28compactor.%2A%7Ccortex%7Cmimir%29%22%7D+%3D%3D+0&g0.tab=1  active
```

These are the relevant metrics from GEM:
```
curl localhost:8080/metrics -s | grep thanos_objstore_bucket_last_successful_upload_time
# HELP thanos_objstore_bucket_last_successful_upload_time Second timestamp of the last successful upload to the bucket.
# TYPE thanos_objstore_bucket_last_successful_upload_time gauge
thanos_objstore_bucket_last_successful_upload_time{bucket="gem-admin",component="admin"} 1.6529838424426215e+09
thanos_objstore_bucket_last_successful_upload_time{bucket="gem-ruler",component="ruler-storage"} 0
thanos_objstore_bucket_last_successful_upload_time{bucket="gem-tsdb",component="compactor"} 1.6529888256145103e+09
thanos_objstore_bucket_last_successful_upload_time{bucket="gem-tsdb",component="ingester"} 1.6529868522036324e+09
thanos_objstore_bucket_last_successful_upload_time{bucket="gem-tsdb",component="purger"} 0
thanos_objstore_bucket_last_successful_upload_time{bucket="gem-tsdb",component="querier"} 0
thanos_objstore_bucket_last_successful_upload_time{bucket="gem-tsdb",component="store-gateway"} 0
```

Note that the alert fires for the components `ruler-storage`, `purger`, `querier` and `store-gateway` and it does not fire for the `compactor` component.
