### ISSUE TITLE
Include a working metamonitoring setup in helm chart

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2014]
#### Context

The helm chart as of now optionally creates [ServiceMonitors](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#servicemonitor) that are recognized by the Grafana Agent Operator and the Prometheus Operator.

#### Problem

This requires that the cluster operator also installs and configures either of these operators. The existing scrape configs also lack some metrics and labels to make them work with the monitoring mixin.

#### Proposal 

I propose to also include an installation of the Grafana Agent Operator as part of the chart. The chart will install the agent operator and configure a minimal grafana agent that scrapes Mimir/GEM and remote writes to an endpoint.

The scrape config should also work with the default monitoring mixin (ergo and Grafana Cloud Integration).

in values.yaml:

```yaml
metamonitoring:
  grafana_agent:
    # controls whether to install the operator or not (default: true)
    install_operator: true
    # controls creating grafana agent CRDs (MetricsInstance, LogsInstance, GrafanaAgent) that will scrape the 
    # service monitors of the chart and ship metrics to the remote_write endpoints below (default: true)
    enabled: true
      # controls whether to also write back the metrics to the mimir cluster (default: false)
    remote_write_back_to_mimir: false

    additional_remote_write_configs:
      - <prometheus_RW_config>
```
