### ISSUE TITLE
Context canceled error when trying to access blocks migrated from Thanos S3 object store 

### ISSUE THREAD

**Issue by svmaris** [grafana/mimir#2016]
#### Describe the bug

We've switched from Thanos to Mimir. Mimir is running in microservice mode using the Helm chart (`mimir-distributed`). We've copied the contents of our old S3 bucket to the mimir S3 bucket (in the anonymous/ prefix). Then we ran `metaconvert` to convert all the metadata, using this [guide](https://grafana.com/docs/mimir/latest/migration-guide/migrating-from-thanos-or-prometheus/). Conversion went fine, and subsequent runs of `metaconvert` with the `-dry-run` flag showed that all metadata was converted correctly.

Now, when trying to display the old graphs in Grafana, `mimir-store-gateway` throws the following errors:

```
mimir-store-gateway-0 store-gateway level=warn ts=2022-06-03T10:54:31.63189478Z caller=memcached_client.go:421 name=index-cache msg="failed to fetch items from memcached" numKeys=1 firstKey=E:anonymous:01G4F138W5RYFXJ20VF1GGFBQV:i-611vj96M6IZArqjFXewP_Hs-TJQ-8aRRmsInhjk6Q err="failed to wait for turn. Instance: : context canceled"
mimir-store-gateway-0 store-gateway level=warn ts=2022-06-03T10:54:31.632199965Z caller=grpc_logging.go:55 duration=45.035169ms method=/gatewaypb.StoreGateway/Series err="rpc error: code = Unknown desc = send series response hints: rpc error: code = Canceled desc = context canceled" msg=gRPC
mimir-store-gateway-0 store-gateway level=warn ts=2022-06-03T10:54:31.632423138Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=18.497943ms err="rpc error: code = Aborted desc = fetch series for block 01G4H422B6FRY8QA8JFNFGJCH9: load chunks: get range reader: fetching range [316288000, 316320000]: context canceled" msg=gRPC
mimir-store-gateway-0 store-gateway level=warn ts=2022-06-03T10:54:31.632758574Z caller=grpc_logging.go:55 method=/gatewaypb.StoreGateway/Series duration=44.972004ms err="rpc error: code = Aborted desc = fetch series for block 01G4EYX991ZMREGNRD7TSJHVP8: load chunks: get range reader: fetching range [146784000, 146832000]: Get \"https://redacted-mimir-tsdb.s3.dualstack.eu-central-1.amazonaws.com/anonymous/01G4EYX991ZMREGNRD7TSJHVP8/chunks/000009\": context canceled" msg=gRPC
```

There seems to be no indication as to *why* the context was cancelled.

I figured there might be a problem with the actual blocks or the connection to S3, but I had not trouble dowloading parts of the block in my test Pod (using `aws s3api get-object --range=...`)

#### To Reproduce

1. Copy Thanos blocks from object story to Mimir object store
2. Run metaconvert
3. Try to render a graph in Grafana using old data

#### Expected behavior

Working graphs using historical data

#### Environment

- Infrastructure: Kubernetes 1.23.5 on AWS, deployed using KOPS
- Deployment tool: Helm (values based on the `small.yaml` example in the helm repo

#### Additional Context

My mimir.yaml:

```
multitenancy_enabled: false

limits:
  max_label_names_per_series: 50
  ingestion_rate: 0
  max_global_series_per_user: 0
  max_global_series_per_metric: 0
  accept_ha_samples: true

activity_tracker:
  filepath: /data/metrics-activity.log

alertmanager:
  data_dir: '/data'
  enable_api: true
  external_url: '/alertmanager'

alertmanager_storage:
  backend: s3
  s3:
    endpoint: s3.eu-central-1.amazonaws.com
    region: eu-central-1
    bucket_name: redacted-mimir-alertmanager

frontend_worker:
  frontend_address: mimir-query-frontend-headless.prometheus.svc:9095

ruler:
  enable_api: true
  rule_path: '/data'
  alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.mimir-alertmanager-headless.prometheus.svc.cluster.local/alertmanager

ruler_storage:
  backend: s3
  s3:
    endpoint: s3.eu-central-1.amazonaws.com
    region: eu-central-1
    bucket_name: redacted-mimir-ruler

server:
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

frontend:
  log_queries_longer_than: 10s
  align_queries_with_step: true

compactor:
  data_dir: "/data"

ingester:
  ring:
    final_sleep: 0s
    num_tokens: 512

ingester_client:
  grpc_client_config:
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600

runtime_config:
  file: /var/mimir/runtime.yaml

memberlist:
  abort_if_cluster_join_fails: false
  compression_enabled: false
  join_members:
    - mimir-gossip-ring

# This configures how the store-gateway synchronizes blocks stored in the bucket. It uses Minio by default for getting started (configured via flags) but this should be changed for production deployments.
blocks_storage:
  backend: s3
  s3:
    endpoint: s3.eu-central-1.amazonaws.com
    region: eu-central-1
    bucket_name: redacted-mimir-tsdb
  tsdb:
    dir: /data/tsdb
  bucket_store:
    sync_dir: /data/tsdb-sync
    chunks_cache:
      backend: memcached
      memcached:
        addresses: dns+mimir-memcached.prometheus.svc:11211
        max_item_size: 1048576
    metadata_cache:
      backend: memcached
      memcached:
        addresses: dns+mimir-memcached-metadata.prometheus.svc:11211
        max_item_size: 1048576
    index_cache:
      backend: memcached
      memcached:
        addresses: dns+mimir-memcached-queries.prometheus.svc:11211
        max_item_size: 15728640
```
