### ISSUE TITLE
cluster_name in helm chart

### ISSUE THREAD

**Issue by tesharp** [grafana/mimir#2084]
#### Describe the bug
It does not seem to be possible to actually change the cluster name in ServiceMonitor. In `_helpers.tpl` it is reading the name from config if defined or default to `.Release.Name`, however `.cluster_name` is not valid config option.

```yaml
{{- define "mimir.clusterName" -}}
{{ (include "mimir.calculatedConfig" . | fromYaml).cluster_name | default .Release.Name }}
{{- end -}}
```

#### To Reproduce

1. Define `.cluster_name` in `.mimir.config`
2. Start Mimir
3. Mimir fails to start because it is not a valid option in config

#### Expected behavior

Mimir starts successfully and being able to override the cluster_name as configuration seems to suggest should be possible.

#### Workaround

Can work around it by adding an additional relabeling in configuration.

```yaml
serviceMonitor:
  enabled: true
  relabelings:
  - replacement: "<cluster_name>"
    targetLabel: cluster
```

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm
