### ISSUE TITLE
Docs:  adding overrides example for 'play-with-grafana-mimir'  tutorial 

### ISSUE THREAD

**Issue by songjiayang** [grafana/mimir#2278]
#### Is your documentation request related to a feature? If so, which one?

When I followed Mimir's tutorial to practice, it started quickly，this is very helpful for the overall understanding of Mimir. But when I wanted to test split merge compacting function, it taked a lot of time.

#### Describe the solution that you’d like or the expected outcome

adding `demo`  tenant overrides example.

Step 1: add `runtime_config` to [play-with-grafana-mimir/config/mimir.yaml](https://github.com/grafana/mimir/blob/main/docs/sources/tutorials/play-with-grafana-mimir/config/mimir.yaml)
```
runtime_config:
  file: /etc/overrides.yaml
```
Step2: add play-with-grafana-mimir/config/overrides.yaml

```
overrides:
  demo:
    compactor_split_and_merge_shards: 2
    compactor_split_groups: 2
```

Step3: update play-with-grafana-mimir/docker-compose.yml, add `./config/overrides.yaml:/etc/overrides.yaml` to mimir-[1-3]'s volumes.

```
mimir-1/2/3:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    hostname: mimir-1
    depends_on:
      - minio
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      -  ./config/overrides.yaml:/etc/overrides.yaml
      - ./config/alertmanager-fallback-config.yaml:/etc/alertmanager-fallback-config.yaml
      - mimir-1-data:/data
```
