### ISSUE TITLE
Multiple alert notifications are sent for an alert even when the repeat interval is 3h

### ISSUE THREAD

**Issue by goelankitt** [grafana/mimir#2323]
#### Describe the bug
Multiple alert notifications are sent for a single alert. It does not happen all the time but happens intermittently. In the following case, 5 notifications were sent within the first two mins of alert state becoming firing. We are running 3 alertmanager replicas with sharding enabled.

#### To Reproduce

1. I tested the alert on my staging setup. Mimir is deployed with the official helm chart. Other relevant configurations used are pasted below in the section additional context.
2. Apply an alert using mimirtool
3. Multiple notifications are sent intermittently for that alert. Sometimes I even received upto 5 alert notification within the first 5 mins when the alert started firing. Alertmanager logs show that the alert status was set to resolved and active over and over again.

Slack notifications:
<img width="597" alt="Screenshot 2022-07-05 at 13 56 26" src="https://user-images.githubusercontent.com/4493180/177322031-440d2346-712d-47ba-8dbb-833b0138d556.png">

I received a total 5 notifications. Two notifications at 13.17 PM and three notifications at 13.18 PM. The screenshot only shows the time of the first alert.

#### Expected behavior

I expected less alert notifications. We should get one notification every 3 hours since this is only alert configured on the system and has been continuously in firing state.
<img width="1111" alt="Screenshot 2022-07-05 at 14 02 21" src="https://user-images.githubusercontent.com/4493180/177322959-839823f4-c1a3-4f22-a0bb-f13e64f597af.png">

#### Environment

- Infrastructure: Mimir running on EKS
- Deployment tool: official mimir helm chart

#### Additional Context

The alert that was applied:
```
groups:
- name: cortex
  rules:
  - alert: IngesterMemoryUsageAlert3
    annotations:
      description: 1 Ingester memory usagew high description {{$labels.pod}}
      grafana: XXXXX
      runbook: XXXXX
      severity: warning
      summary: Ingester memory usage alert summary
      team: test
    expr: sum(container_memory_working_set_bytes{dh_cluster="clustername", pod=~"ingester_pod"}) by (pod, container_name)/sum(container_spec_memory_limit_bytes{dh_cluster="clustername", pod=~"ingester_pod"}) by (pod, container_name) * 100 > 30
    for: 3m
    labels:
      label_team: test
      severity: warning
```

Alertmanager config used:
```
global:
  resolve_timeout: 5m
  slack_api_url: 'SLACK_API_URL'

templates:
  - 'default.tmpl'

receivers:
  - name: observability-test
    slack_configs:
      - send_resolved: true
        channel: "slack-channel-name"
        username: "XXXXX"
        icon_url: "XXXXXX"
        title: "{{ .CommonAnnotations.summary }}"
        text: '{{ template "general.description" . }}'
        footer: '{{ template "general.footer" . }}'
        actions:
          - type: button
            text: Dashboard
            url: '{{- range $i, $alert := .Alerts -}}{{- if lt $i 1 -}}{{- index $alert.Annotations "grafana" -}}{{- end -}}{{- end -}}'
          - type: button
            text: Logs
            url: '{{- range $i, $alert := .Alerts -}}{{- if lt $i 1 -}}{{- index $alert.Annotations "logs" -}}{{- end -}}{{- end -}}'
          - type: button
            text: Runbook
            url: "{{ range .Alerts }}{{ .Annotations.runbook }}{{ end }}"

route:
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 3h
  receiver: observability-test
  group_by:
    - label_app
    - alertname

  routes:
    - receiver: observability-test
      group_by:
        - alertname
        - severity
      match:
        label_team: "test"
      group_wait: 10s
      continue: true

```

Mimir configuration for alertmanager:

```
mimir:
  config: |
    alertmanager:
      data_dir: data/alertmanager/
      enable_api: true
      sharding_ring:
        heartbeat_period: 1m0s
        heartbeat_timeout: 10m0s
        kvstore:
          consul:
            consistent_reads: false
            host: consul-host:8500
            http_client_timeout: 20s
          prefix: alertmanagers/
          store: consul

```

Alertmanager logs:
```
level=debug ts=2022-07-05T11:18:25.472116227Z caller=multitenant.go:990 component=MultiTenantAlertmanager msg="message received for replication" user=logistics key=nfl:logistics
level=debug ts=2022-07-05T11:18:25.472147499Z caller=dispatch.go:517 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher aggrGroup="{}/{label_team=\"test\"}:{alertname=\"IngesterMemoryUsageAlert3\", severity=\"warning\"}" msg=flushing alerts="[IngesterMemoryUsageAlert3[cb160db][active] IngesterMemoryUsageAlert3[f8fa344][active] IngesterMemoryUsageAlert3[71a0130][active] IngesterMemoryUsageAlert3[f0bcd2d][active] IngesterMemoryUsageAlert3[bc1fb80][active] IngesterMemoryUsageAlert3[6d00bb5][active] IngesterMemoryUsageAlert3[5f99b55][active] IngesterMemoryUsageAlert3[20fcb09][active] IngesterMemoryUsageAlert3[48a8f38][active] IngesterMemoryUsageAlert3[d0e1624][active]]"
level=debug ts=2022-07-05T11:18:25.473008965Z caller=grpc_logging.go:41 duration=52.795µs method=/alertmanagerpb.Alertmanager/UpdateState msg="gRPC (success)"
level=debug ts=2022-07-05T11:18:25.47306413Z caller=grpc_logging.go:41 method=/alertmanagerpb.Alertmanager/UpdateState duration=107.501µs msg="gRPC (success)"
level=debug ts=2022-07-05T11:18:25.695054665Z caller=notify.go:743 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher receiver=observability-test integration=slack[0] msg="Notify success" attempts=1
level=debug ts=2022-07-05T11:18:25.695161862Z caller=multitenant.go:990 component=MultiTenantAlertmanager msg="message received for replication" user=logistics key=nfl:logistics
level=debug ts=2022-07-05T11:18:25.696020069Z caller=grpc_logging.go:41 method=/alertmanagerpb.Alertmanager/UpdateState duration=56.784µs msg="gRPC (success)"
level=debug ts=2022-07-05T11:18:25.696105291Z caller=grpc_logging.go:41 method=/alertmanagerpb.Alertmanager/UpdateState duration=47.157µs msg="gRPC (success)"
level=debug ts=2022-07-05T11:18:32.671336948Z caller=logging.go:67 traceID=60a3ac293bdab90f msg="GET /ready (200) 35.618µs"
level=info ts=2022-07-05T11:18:40.051506825Z caller=multitenant.go:603 component=MultiTenantAlertmanager msg="synchronizing alertmanager configs for users"
level=debug ts=2022-07-05T11:18:40.188305863Z caller=multitenant.go:697 component=MultiTenantAlertmanager msg="adding configurations" num_configs=1
level=debug ts=2022-07-05T11:18:40.188432564Z caller=multitenant.go:775 component=MultiTenantAlertmanager msg="setting config" user=logistics
level=info ts=2022-07-05T11:18:40.188647144Z caller=multitenant.go:819 component=MultiTenantAlertmanager msg="updating new per-tenant alertmanager" user=logistics
level=debug ts=2022-07-05T11:18:40.190970857Z caller=dispatch.go:165 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher msg="Received alert" alert=IngesterMemoryUsageAlert3[6d00bb5][active]
level=debug ts=2022-07-05T11:18:40.191032535Z caller=dispatch.go:165 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher msg="Received alert" alert=IngesterMemoryUsageAlert3[bc1fb80][active]
level=debug ts=2022-07-05T11:18:40.19104467Z caller=dispatch.go:165 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher msg="Received alert" alert=IngesterMemoryUsageAlert3[d0e1624][active]
level=debug ts=2022-07-05T11:18:40.191069088Z caller=dispatch.go:517 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher aggrGroup="{}/{label_team=\"test\"}:{alertname=\"IngesterMemoryUsageAlert1\", severity=\"warning\"}" msg=flushing alerts="[IngesterMemoryUsageAlert1[36bb0af][resolved] IngesterMemoryUsageAlert1[f727845][resolved] IngesterMemoryUsageAlert1[1ae173b][resolved]]"
level=debug ts=2022-07-05T11:18:40.191079545Z caller=dispatch.go:517 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher aggrGroup="{}/{label_team=\"test\"}:{alertname=\"IngesterMemoryUsageAlert2\", severity=\"warning\"}" msg=flushing alerts="[IngesterMemoryUsageAlert2[6d3ccf4][resolved] IngesterMemoryUsageAlert2[4dab815][resolved] IngesterMemoryUsageAlert2[c0f0d15][resolved]]"
level=debug ts=2022-07-05T11:18:40.19109059Z caller=dispatch.go:165 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher msg="Received alert" alert=IngesterMemoryUsageAlert3[f8fa344][active]
level=debug ts=2022-07-05T11:18:40.191151704Z caller=dispatch.go:165 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher msg="Received alert" alert=IngesterMemoryUsageAlert3[5f99b55][active]
level=debug ts=2022-07-05T11:18:40.191151433Z caller=dispatch.go:517 component=MultiTenantAlertmanager user=logistics component=dispatcher insight=true component=dispatcher aggrGroup="{}/{label_team=\"test\"}:{alertname=\"IngesterMemoryUsageAlert3\", severity=\"warning\"}" msg=flushing alerts="[IngesterMemoryUsageAlert3[bc1fb80][active] IngesterMemoryUsageAlert3[6d00bb5][active] IngesterMemoryUsageAlert3[d0e1624][active]]"
```
