### ISSUE TITLE
Remote read for Prometheus from Mimir worked then stopped

### ISSUE THREAD

**Issue by sarasensible** [grafana/mimir#2510]
#### Describe the bug

Remote read from Mimir for Prometheus worked for a few hours then stopped - historical searches in Prometheus via Grafana only show data since the last pod reload.

#### To Reproduce

Configure remote read for Prometheus from Mimir, then deploy HA configuration as described in https://grafana.com/docs/mimir/latest/operators-guide/configuring/configuring-high-availability-deduplication/ with etcd as the backing store and wait longer than the TTL of the jwt auth token which defaults to 10 minutes in the etcd Helm chart

#### Expected behavior

Remote read should continue to work after a few hours

#### Environment

- Infrastructure: AWS EKS 1.21
- Deployment tool: Helm
- etcd Helm [chart](https://github.com/bitnami/charts/tree/master/bitnami/etcd) version 8.3.4, image version 3.5.4-debian-11-r14

#### Additional Context

I am using simple username/password authentication to etcd which seems like the only supported configuration in Mimir.  I am using the JWT auth token for etcd.

Update:  at first I thought this had to do with etcd, but now I'm not sure.  The error I was seeing is the following:

```
{"level":"warn","ts":"2022-07-21T18:45:33.135Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0002e6000/#initially=[etcd:2379]","attempt":0,"error":"rpc error: code = Unauthenticated desc = etcdserver: invalid auth token"}
```

Helm config for Mimir:
```
serviceAccount:
  create: false
  name: s3-full

minio:
  enabled: false

runtimeConfig:

alertmanager:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule

distributor:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule

overrides_exporter:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule

ruler:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule

query_frontend:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule

nginx:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule

store_gateway:
  replicas: 1
  sharding_ring:
    kvstore:
      store: memberlist
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule
  persistentVolume:
    size: 100Gi

ingester:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule
  persistentVolume:
    size: 100Gi

compactor:
  nodeSelector:
    role: metrics
  tolerations:
    - key: role
      operator: Equal
      value: metrics
      effect: NoSchedule
  persistentVolume:
    size: 100Gi

mimir:
  # -- Config file for Grafana Mimir, enables templates. Needs to be copied in full for modifications.
  config: |
    {{- if not .Values.enterprise.enabled -}}
    multitenancy_enabled: false
    {{- end }}
    limits:
      accept_ha_samples: true
      ha_cluster_label: cluster
      ha_replica_label: prometheus_replica
      ingestion_rate: 150000
      max_global_series_per_user: 1000000
      max_global_series_per_metric: 0
    activity_tracker:
      filepath: /data/metrics-activity.log
    alertmanager:
      data_dir: '/data'
      enable_api: true
      external_url: '/alertmanager'
    alertmanager_storage:
      backend: s3
      s3:
        endpoint: s3.${region}.amazonaws.com
        bucket_name: ${alertmanager_bucket}
        region: ${region}
    distributor:
      ha_tracker:
        enable_ha_tracker: true
        kvstore:
          store: etcd
          etcd:
            username: root
            password: ${password}
            endpoints:
              - etcd:2379
    frontend_worker:
      frontend_address: {{ template "mimir.fullname" . }}-query-frontend-headless.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
    ruler:
      enable_api: true
      rule_path: '/data'
      alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.{{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}/alertmanager
    server:
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
    frontend:
      log_queries_longer_than: 10s
      align_queries_with_step: true
    compactor:
      data_dir: "/data"
    ingester:
      ring:
        final_sleep: 0s
        num_tokens: 512
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    runtime_config:
      file: /var/{{ include "mimir.name" . }}/runtime.yaml
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - {{ include "mimir.fullname" . }}-gossip-ring
    # This configures how the store-gateway synchronizes blocks stored in the bucket. It uses Minio by default for getting started (configured via flags) but this should be changed for production deployments.
    blocks_storage:
      backend: s3
      tsdb:
        dir: /data/tsdb
        wal_compression_enabled: true
        retention_period: 4h
      bucket_store:
        sync_dir: /data/tsdb-sync
        {{- if .Values.memcached.enabled }}
        chunks_cache:
          backend: memcached
          memcached:
            addresses: dns+{{ .Release.Name }}-memcached.{{ .Release.Namespace }}.svc:11211
            max_item_size: {{ .Values.memcached.maxItemMemory }}
        {{- end }}
        {{- if index .Values "memcached-metadata" "enabled" }}
        metadata_cache:
          backend: memcached
          memcached:
            addresses: dns+{{ .Release.Name }}-memcached-metadata.{{ .Release.Namespace }}.svc:11211
            max_item_size: {{ (index .Values "memcached-metadata").maxItemMemory }}
        {{- end }}
        {{- if index .Values "memcached-queries" "enabled" }}
        index_cache:
          backend: memcached
          memcached:
            addresses: dns+{{ .Release.Name }}-memcached-queries.{{ .Release.Namespace }}.svc:11211
            max_item_size: {{ (index .Values "memcached-queries").maxItemMemory }}
        {{- end }}
      s3:
        endpoint: s3.${region}.amazonaws.com
        bucket_name: ${metrics_bucket}
        region: ${region}
    ruler_storage:
      backend: s3
      s3:
        endpoint: s3.${region}.amazonaws.com
        bucket_name: ${ruler_bucket}
        region: ${region}
    {{- if .Values.enterprise.enabled }}
    multitenancy_enabled: true
    admin_api:
      leader_election:
        enabled: true
        ring:
          kvstore:
            store: "memberlist"
    {{- if .Values.minio.enabled }}
    admin_client:
      storage:
        type: s3
        s3:
          endpoint: {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc:9000
          bucket_name: enterprise-metrics-admin
          access_key_id: {{ .Values.minio.accessKey }}
          secret_access_key: {{ .Values.minio.secretKey }}
          insecure: true
    {{- end }}
    auth:
      type: enterprise
    cluster_name: "{{ .Release.Name }}"
    license:
      path: "/license/license.jwt"
    {{- if .Values.gateway.useDefaultProxyURLs }}
    gateway:
      proxy:
        default:
          url: http://{{ template "mimir.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        admin_api:
          url: http://{{ template "mimir.fullname" . }}-admin-api.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        alertmanager:
          url: http://{{ template "mimir.fullname" . }}-alertmanager.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        compactor:
          url: http://{{ template "mimir.fullname" . }}-compactor.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        distributor:
          url: http://{{ template "mimir.fullname" . }}-distributor.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        ingester:
          url: http://{{ template "mimir.fullname" . }}-ingester.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        query_frontend:
          url: http://{{ template "mimir.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        ruler:
          url: http://{{ template "mimir.fullname" . }}-ruler.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
        store_gateway:
          url: http://{{ template "mimir.fullname" . }}-store-gateway.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
    {{- end }}
    instrumentation:
      enabled: true
      distributor_client:
        address: 'dns:///{{ template "mimir.fullname" . }}-distributor.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}'
    {{- end }}
```

Relevant Helm config for Prometheus:
```
    remoteRead:
      - url: http://mimir-query-frontend:8080/prometheus/api/v1/read
    # - url: http://remote1/read

    ## The remote_write spec configuration for Prometheus.
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#remotewritespec
    remoteWrite:
      - url: http://mimir-distributor:8080/api/v1/push
        writeRelabelConfigs:
          - action: drop
            regex: apiserver_request_duration_seconds_bucket
            sourceLabels:
              - __name__
          - action: drop
            regex: etcd_request_duration_seconds_bucket
            sourceLabels:
              - __name__
```

Helm etcd values:
```
nodeSelector:
  role: metrics
tolerations:
  - key: role
    operator: Equal
    value: metrics
    effect: NoSchedule

persistence:
  size: 20Gi

metrics:
  enabled: true
  podMonitor:
    enabled: true
    additionalLabels:
      release: prometheus-stack-1

serviceAccount:
  create: true
  name: etcd-sa

auth:
  rbac:
    allowNoneAuthentication: false
  token:
    ttl: 52560000m  # turned all the way up for debugging
```
