### ISSUE TITLE
Improve `MimirSchedulerQueriesStuck` reliability

### ISSUE THREAD

**Issue by colega** [grafana/mimir#2625]
#### Is your feature request related to a problem? Please describe.

`MimirSchedulerQueriesStuck` alert is currently defined as:

```yaml
  - alert: MimirSchedulerQueriesStuck
    expr: |
      sum by (cluster, namespace, job) (cortex_query_scheduler_queue_length) > 1
    for: 5m
    labels:
      severity: critical
```

Which can be very easily triggered, especially with tight resource planning with autoscaling enabled, especially on the ruler read path where the load is more predictable.

Actually, on the ruler read path, if this alert is not triggered it means that we're most likely wasting resources.

#### Describe the solution you'd like

I would like this alert to check whether queries are stuck or not in some more reliable way, i.e., it should alert if there are old queries queued that are not being recycled.

If there was an "age of the oldest job in the queue" metric, then the alert could look like:

```yaml
    expr: |
      sum by (cluster, namespace, job) (cortex_query_scheduler_queue_length) > 1
      and
      sum by (cluster, namespace, job) (resets(cortex_query_scheduler_oldest_queued_job_age_seconds)) == 0
```

#### Describe alternatives you've considered

On the other hand it would be great to avoid having to add metrics to improve this alert.
We could consider a poor-man's version of the previous suggestion as:

```yaml
    expr: |
      sum by (cluster, namespace, job) (cortex_query_scheduler_queue_length) > 1
      and
      sum by (cluster, namespace, job) (resets(cortex_query_scheduler_queue_length)) == 0
```

This would be more solid, however it would not alert if for some (unlikely?) reason there would be 1 query really stuck.

#### Additional context

Everything said here, also applies to the `MimirFrontendQueriesStuck` counterpart.
