### ISSUE TITLE
Helm default pod anti-affinity rules do not work

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2681]
#### Describe the bug
The chart sets default pod anti-affinity rules that look like this:
```yaml
distributor:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: target
                operator: In
                values:
                  - distributor
          topologyKey: 'kubernetes.io/hostname'
```

But with the latest chart the components don't get a `target` label ([code](https://github.com/grafana/mimir/blob/fd80035656704fa2d1989432a8a8e766fdaa570d/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L213-L239))

#### To Reproduce

1. Set up a small one-node cluster. 
2. Deploy two distributors `distributor: {replicas: 2}`.
3. Both distributors start up, but only one should.
4. If you change the `- key: target` to `-key: app.kubernetes.io/component` then one of the pods cannot be scheduled (which is correct behvaiour on a one-node cluster)
