### ISSUE TITLE
[k8s/mimir-distributed] Overlapping blocks found during reloadBlocks

### ISSUE THREAD

**Issue by qdupuy** [grafana/mimir#2687]
#### Describe the bug
Very often, I get errors `Overlapping blocks found during reloadBlocks` on the injectors

#### To Reproduce

Deploy mimir distributed with the helm charts in its version `mimir-distributed-3.0.0`

#### Expected behavior

I would like to understand the error and correct it. Also, I would like to know if my configuration is correct

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Helm

#### Additional Context

For your information, I’m at 40000 requests/second

Mimir configuration : 
```
config: |
tenant_federation:
  enabled: true

activity_tracker:
  filepath: /data/metrics-activity.log

alertmanager:
  data_dir: /data
  enable_api: true
  external_url: /alertmanager
  fallback_config_file: ""

frontend:
  align_queries_with_step: true
  log_queries_longer_than: 10s
  {{- if index .Values "results-cache" "enabled" }}
  results_cache:
    backend: memcached
    memcached:
      addresses: {{ include "mimir.resultsCacheAddress" . }}
      max_item_size: {{ mul (index .Values "results-cache").maxItemMemory 1024 1024 }}
  cache_results: true
  {{- end }}

frontend_worker:
  frontend_address: {{ template "mimir.fullname" . }}-query-frontend-headless.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}

ingester:
  ring:
    final_sleep: 0s
    num_tokens: 512
    unregister_on_shutdown: true
    replication_factor: 3

limits:
  max_label_names_per_series: 50
  ingestion_tenant_shard_size: 5
  compactor_tenant_shard_size: 2
  compactor_blocks_retention_period: 15m
  out_of_order_time_window: 15m
  max_global_series_per_user: 1000000
  ingestion_burst_size: 400000
  max_global_series_per_metric: 50000
  max_fetched_chunks_per_query: 3000000
  query_sharding_total_shards: 24
  query_sharding_max_sharded_queries: 256
  store_gateway_tenant_shard_size: 2
  compactor_split_and_merge_shards: 2

memberlist:
  abort_if_cluster_join_fails: false
  compression_enabled: false
  join_members:
  - {{ include "mimir.fullname" . }}-gossip-ring
  
ruler:
  alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.{{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}/alertmanager
  enable_api: false
  rule_path: /data

compactor:
  data_dir: "/data"
  block_ranges: [1h0m0s,4h0m0s,12h0m0s]

runtime_config:
  file: /var/{{ include "mimir.name" . }}/runtime.yaml

ingester_client:
  grpc_client_config:
    max_send_msg_size: 67108864
    # max_recv_msg_size: 104857600
    # max_send_msg_size: 104857600

server: 
  # grpc_server_max_recv_msg_size: 104857600
  # grpc_server_max_send_msg_size: 104857600
  # grpc_server_max_concurrent_streams: 1000
  log_level: warn
  
alertmanager_storage:
  backend: azure
  azure:
    container_name: mimir-ruler
    account_name: ${STORAGE_ACCOUNT_NAME}
    account_key: ${STORAGE_ACCOUNT_KEY}

blocks_storage:
  backend: azure
  tsdb:
    dir: /data/tsdb
    retention_period: 2h
    block_ranges_period: [30m,1h,2h]
  bucket_store:
    sync_dir: /data/tsdb-sync
    tenant_sync_concurrency: 20
    block_sync_concurrency: 40
    sync_interval: 10m
    consistency_delay: 10m
    {{- if index .Values "chunks-cache" "enabled" }}
    chunks_cache:
      backend: memcached
      memcached:
        addresses: {{ include "mimir.chunksCacheAddress" . }}
        max_item_size: {{ mul (index .Values "chunks-cache").maxItemMemory 1024 1024 }}
        timeout: 450ms
    {{- end }}
    {{- if index .Values "index-cache" "enabled" }}
    index_cache:
      backend: memcached
      memcached:
        addresses: {{ include "mimir.indexCacheAddress" . }}
        max_item_size: {{ mul (index .Values "index-cache").maxItemMemory 1024 1024 }}
    {{- end }}
    {{- if index .Values "metadata-cache" "enabled" }}
    metadata_cache:
      backend: memcached
      memcached:
        addresses: {{ include "mimir.metadataCacheAddress" . }}
        max_item_size: {{ mul (index .Values "metadata-cache").maxItemMemory 1024 1024 }}
    {{- end }}
  azure:
    container_name: mimir-tsdb
    account_name: ${STORAGE_ACCOUNT_NAME}
    account_key: ${STORAGE_ACCOUNT_KEY}

ruler_storage:
  backend: azure
  azure:
    container_name: mimir-ruler
    account_name: ${STORAGE_ACCOUNT_NAME}
    account_key: ${STORAGE_ACCOUNT_KEY}
```
