### ISSUE TITLE
[Helm] activity_tracker can not be rendered

### ISSUE THREAD

**Issue by aldiserg** [grafana/mimir#2721]
#### Describe the bug
Trying to install mimir-distributed with memcached via helm and got an error:
`Error: execution error at (mimir-distributed/templates/validate.yaml:13:4): The 'activity_tracker.filepath' in 'mimir.config' should be set to a path that is on a writeable volume. For example: '/data/metrics-activity.log'.`

Config already has this option
```
mimir:
  config: |
    activity_tracker:
      filepath: /data/metrics-activity.log
```
Install without memcached is working correctly

#### To Reproduce
enable one of memcached option

#### Expected behavior

starting memcached pod

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm
