### ISSUE TITLE
Add Alertmanager datasource tips 

### ISSUE THREAD

**Issue by seaurching** [grafana/mimir#2738]
When add an datasource for alertmanager, show this message
```
It looks like you have chosen a Mimir or Cortex implementation, but detected a Prometheus endpoint. Please update implementation selection and try again.
```
While use mimirtool show configs,like this
```
./Downloads/mimirtool-darwin-amd64 alertmanager get --id=miyamoto.local --address=http://127.0.0.1:8080
global:
  resolve_timeout: 2m
  #wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'qiyx1@qq.com:587'
```
