### ISSUE TITLE
Alertmanager fallback config not using defaults

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#2806]
### Context 

The [Prometheus alertmanager config](https://prometheus.io/docs/alerting/latest/configuration/#configuration-file) has some sane global defaults. For example
```
global:
  [ telegram_api_url: <string> | default = "https://api.telegram.org" ]
```

Global defaults should apply to all added receivers. So if I add a telegram receiver it should automatically use the `global.telegram_api_url` or its value if I haven't set on.

### Bug

I use this alertmanager config, which I provide via the `alertmanager.fallback_config_file`
```yaml
# The root route on which each incoming alert enters.
# global:
#   telegram_api_url: https://api.telegram.org
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: telegram

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: <redacted>
        chat_id: -1001590945633
        parse_mode: ''
        message: 'author: {{ .CommonLabels.author }}'
```

When I run Alertmanager with the above fallback config, then alertmanager fails to start up. I get this error instead 
```
level=error ts=2022-08-22T16:56:34.321880174Z caller=log.go:60 msg="error running application" err="unable to load fallback config \"/etc/config/am/default.yaml\": missing api_url on\ntelegram_config
error initialising module: alertmanager
github.com/grafana/dskit/modules.(*Manager).initModule
  /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:122
github.com/grafana/dskit/modules.(*Manager).InitModuleServices
  /__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:92
github.com/grafana/mimir/pkg/mimir.(*Mimir).Run
  /__w/mimir/mimir/pkg/mimir/mimir.go:568
main.main
  /__w/mimir/mimir/cmd/mimir/main.go:212
runtime.main
  /usr/local/go/src/runtime/proc.go:250
runtime.goexit
  /usr/local/go/src/runtime/asm_arm64.s:1263"
```

the important part being `missing api_url on\ntelegram_config`

I also tried by setting the `global.telegram_api_url`, but get the exact same error.

### Workaround

Provide the `api_url` for each receiver.
