### ISSUE TITLE
Alertmanager and Ruler in CrashLoopBackOff

### ISSUE THREAD

**Issue by luvpreetsingh** [grafana/mimir#2812]
#### Describe the bug

I have been using mimir since the last 2 weeks. Initially I didn't need the alertmanager and ruler but today I needed those. I enabled them in the helm values yaml file and upgraded the helm release. But the new pods for alertmanager and ruler are in CrashLoopBackOff state. I am using GCS for the storage backend.

#### To Reproduce

Here is the helm yaml config which I added today to enable alertmanager and ruler,

```
mimir:
  config: |
    ...
    ruler_storage:
      backend: gcs
      gcs:
        bucket_name: my-staging-mimir-ruler
    alertmanager_storage:
      backend: gcs
      gcs:
        bucket_name: my-staging-mimir-ruler
    ...

alertmanager:
  enabled: true

  resources:
    requests:
      cpu: 50m
      memory: 100Mi

  persistentVolume:
    size: 10Gi

  # for gcs permission
  extraVolumes:
    - name: gcp-creds
      secret:
        secretName: gcp-credentials

  extraVolumeMounts:
    - name: gcp-creds
      mountPath: /var/secrets/google
      readOnly: true

  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/secrets/google/gcp-credentials.json"


ruler:
  enabled: true

  extraVolumes:
    - name: gcp-creds
      secret:
        secretName: gcp-credentials

  extraVolumeMounts:
    - name: gcp-creds
      mountPath: /var/secrets/google
      readOnly: true

  env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: "/var/secrets/google/gcp-credentials.json"
```

I upgraded the release with these values and the new pods are in CrashLoopBackOff state, with rest of the components working just fine.

1. Mimir helm chart version - mimir-distributed-3.0.0, app version - 2.2.0
2. Perform Operations(Read/Write/Others) - No need, the pods are not even starting

#### Expected behavior

I expected the alertmanager and ruler to start normally.

#### Environment

- Infrastructure: Google Kubernetes Engine - 1.22.10-gke.600
- Deployment tool: helm chart - mimir-distributed-3.0.0, app version - 2.2.0

#### Additional Context

Here are the logs from Alertmanager pod,

```
level=info ts=2022-08-23T11:49:02.685237079Z caller=main.go:202 msg="Starting application" version="(version=2.2.0, branch=HEAD, revision=65344e2)"
level=info ts=2022-08-23T11:49:02.687021409Z caller=server.go:285 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2022-08-23T11:49:02.690779129Z caller=log.go:60 msg="error running application" err="unable to create Alertmanager data directory \"./data-alertmanager/\": mkdir ./data-alertmanager/: read-only file system\nerror initialising module: alertmanager\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:122\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:92\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:438\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:204\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```

Here are the logs from Ruler pod,

```
level=info ts=2022-08-23T11:53:56.693430864Z caller=main.go:202 msg="Starting application" version="(version=2.2.0, branch=HEAD, revision=65344e2)"
level=info ts=2022-08-23T11:53:56.695223684Z caller=server.go:285 http=[::]:8080 grpc=[::]:9095 msg="server listening on addresses"
level=info ts=2022-08-23T11:53:56.698083774Z caller=memberlist_client.go:407 msg="Using memberlist cluster node name" name=mimir-ruler-774d576595-8d4xq-3662f5c4
level=info ts=2022-08-23T11:53:56.699300764Z caller=mapper.go:52 msg="cleaning up mapped rules directory" path=./data-ruler/
level=info ts=2022-08-23T11:53:56.700199784Z caller=module_service.go:82 msg=initialising module=sanity-check
level=info ts=2022-08-23T11:53:56.700253934Z caller=sanity_check.go:33 msg="Checking directories read/write access"
level=error ts=2022-08-23T11:53:56.700309364Z caller=sanity_check.go:35 msg="Unable to access directory" err="ruler: failed to access directory ./data-ruler/: open .check: read-only file system"
level=error ts=2022-08-23T11:53:56.700344064Z caller=mimir.go:483 msg="module failed" module=sanity-check err="invalid service state: Failed, expected: Running, failure: ruler: failed to access directory ./data-ruler/: open .check: read-only file system"
level=error ts=2022-08-23T11:53:56.700370234Z caller=mimir.go:483 msg="module failed" module=ruler err="failed to start ruler, because it depends on module distributor-service, which has failed: context canceled"
level=error ts=2022-08-23T11:53:56.700384744Z caller=mimir.go:483 msg="module failed" module=distributor-service err="failed to start distributor-service, because it depends on module activity-tracker, which has failed: context canceled"
level=error ts=2022-08-23T11:53:56.700399264Z caller=mimir.go:483 msg="module failed" module=store-queryable err="failed to start store-queryable, because it depends on module sanity-check, which has failed: invalid service state: Failed, expected: Running, failure: invalid service state: Failed, expected: Running, failure: ruler: failed to access directory ./data-ruler/: open .check: read-only file system"
level=error ts=2022-08-23T11:53:56.700410234Z caller=mimir.go:483 msg="module failed" module=ring err="failed to start ring, because it depends on module activity-tracker, which has failed: context canceled"
level=error ts=2022-08-23T11:53:56.700423194Z caller=mimir.go:483 msg="module failed" module=server err="failed to start server, because it depends on module activity-tracker, which has failed: context canceled"
level=error ts=2022-08-23T11:53:56.700429894Z caller=mimir.go:483 msg="module failed" module=runtime-config err="failed to start runtime-config, because it depends on module activity-tracker, which has failed: context canceled"
level=error ts=2022-08-23T11:53:56.700442234Z caller=mimir.go:483 msg="module failed" module=memberlist-kv err="failed to start memberlist-kv, because it depends on module activity-tracker, which has failed: context canceled"
level=info ts=2022-08-23T11:53:56.700451204Z caller=module_service.go:82 msg=initialising module=activity-tracker
level=error ts=2022-08-23T11:53:56.700484494Z caller=log.go:60 msg="error running application" err="failed services\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:518\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:204\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"
```
