### ISSUE TITLE
Unable to store the Alertmanager config: mkdir /alertmanager: read-only file system

### ISSUE THREAD

**Issue by z0rc** [grafana/mimir#2859]
#### Describe the bug
Deployed current mimir via helm chart with multitenancy disabled. Trying to upload basic Alertmanager config using mimirtool:

```
mimirtool alertmanager load alertmanager-config.yml --address=https://mimir.example.net --id=anonymous
ERRO[0001] server returned HTTP status 500 Internal Server Error: unable to store the Alertmanager config: mkdir /alertmanager: read-only file system  fields.msg="unable to store the Alertmanager config: mkdir /alertmanager: read-only file system" status="500 Internal Server Error"
mimirtool: error: server returned HTTP status 500 Internal Server Error: unable to store the Alertmanager config: mkdir /alertmanager: read-only file system, try --hel
```

#### To Reproduce

1. Deploy helm chart using following values
```
# ommited most of values, only alertmanager related options mentioned
mimir:
  structuredConfig:
    multitenancy_enabled: false
    alertmanager_storage:
      s3:
        endpoint: s3.us-east-1.amazonaws.com
        region: us-east-1
        bucket_name: sample
alertmanager:
  replicas: 2
  persistentVolume:
    size: 10Gi
```

2. Create dummy alertmanager-config.yml
```
route:
  receiver: "example_receiver"
  group_by: ["example_groupby"]
receivers:
  - name: "example_receiver"
```

3. Try to upload it
```
% mimirtool alertmanager load alertmanager-config.yml --address=https://mimir.example.net --id=anonymous
ERRO[0001] server returned HTTP status 500 Internal Server Error: unable to store the Alertmanager config: mkdir /alertmanager: read-only file system  fields.msg="unable to store the Alertmanager config: mkdir /alertmanager: read-only file system" status="500 Internal Server Error"
mimirtool: error: server returned HTTP status 500 Internal Server Error: unable to store the Alertmanager config: mkdir /alertmanager: read-only file system, try --help
```
Also alertmanager logs:
```
{"caller":"api.go:153","component":"MultiTenantAlertmanager","err":"mkdir /alertmanager: read-only file system","level":"error","msg":"unable to store the Alertmanager config","ts":"2022-08-29T12:05:56.647910375Z","user":"anonymous"}
{"caller":"logging.go:86","level":"warn","msg":"POST /api/v1/alerts (500) 2.795432ms Response: \"unable to store the Alertmanager config: mkdir /alertmanager: read-only file system\\n\" ws: false; Accept-Encoding: gzip; Connection: close; Content-Length: 172; User-Agent: Go-http-client/1.1; X-Forwarded-For: 10.100.0.203; X-Forwarded-Host: mimir.example.net; X-Forwarded-Port: 443; X-Forwarded-Proto: https; X-Forwarded-Server: traefik-private-9868f5f47-jm7b7; X-Real-Ip: 10.100.0.203; X-Scope-Orgid: anonymous; ","traceID":"6d33c9a5a0d773d9","ts":"2022-08-29T12:05:56.647984331Z"}
```

#### Expected behavior

Upload should complete successfuly.

#### Environment

- Infrastructure: EKS 1.23
- Deployment tool: helm

#### Additional Context

I checked generated ConfigMap, it properly sets storage path for alertmanager and ruler:
```
...
alertmanager:
  data_dir: /data
  enable_api: true
  external_url: /alertmanager
...
ruler:
  alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.mimir-alertmanager-headless.mimir.svc.cluster.local/alertmanager
  enable_api: true
  rule_path: /data
...
```
`mkdir /alertmanager` is strange. If I read it correctly, it tries to create directory in root filesystem, which is readonly as expected https://github.com/grafana/mimir/blob/mimir-2.3.0-rc0/operations/helm/charts/mimir-distributed/values.yaml#L409. But it isn't clear why it does so and which option controls this path.

**Comment by z0rc** [comment]
Misconfiguration on my side, sorry for the noise. My ConfigMap was missing following options:
```
alertmanager_storage:
  backend: s3
ruler_storage:
  backend: s3
```
