### ISSUE TITLE
S3 empty directory pruning not taking place after compaction

### ISSUE THREAD

**Issue by zdykstra** [grafana/mimir#2877]
#### Describe the bug
Empty block 'directories' on a `minio` backend are not removed after compaction and block retention periods have removed blocks.  While preparing for a migration from Cortex to Mimir, I've done a single one-way replication of my legacy Cortex data to a new Minio cluster. My existing Cortex configuration was imported, and two additions were made:

```
limits:
    compactor_blocks_retention_period: 180d
    compactor_partial_block_deletion_delay: 4h0m
```

Once `mimir` was started up, it took roughly 6 hours to go back through the ~1.5 years of metrics and prune / compact the blocks down for each tenant. Because this came from Cortex without any retention set, I have/had a significant number of blocks stored on my `minio` backend. For one tenant ID, I have:

```
# mc ls cortex/cortex/c3803 | wc -l
37484
```
However, now that the compaction has taken place, I see that I'm down to 181 blocks recorded in the bucket index for `c3803` (I'm not ingesting any more data to this minio backend, it was a single snapshot of the historical data). Based on the default compaction rules this seems to be accurate.

```
zcat bucket-index.json.gz | jq '.blocks[].block_id' | wc -l
181
```
Unfortunately, the empty fake directories aren't being pruned. This is resulting in a high amount of CPU usage both from `mimir` and `minio` as ~38k empty directories are checked every 15 minutes.  I left the stack running over night, and I can see on CPU graphs when compaction stopped and then spikes every 15 minutes as hundreds of thousands (based on all tenants) of empty directories were inspected repeatedly.  Based on CPU graphs, the check/skip cycle has been taking place for roughly 12 hours.

![image](https://user-images.githubusercontent.com/13874853/187961038-7a505d9e-1832-497d-b5d8-cfbe440063ba.png)

Based on that graph, it looks like after the 4 hour window expired, CPU usage spiked substantially on this node as `mimir` skipped partial blocks that it seems to have forgotten it had seen.

```
level=warn ts=2022-09-01T15:51:01.673596701Z caller=updater.go:113 component=cleaner user=c3803 msg="skipped partial block when updating bucket index" block=01G8QG4D92Z42BBMBG0KE7PCFK
```

Is there a setting I'm missing in either `mimir` or `minio` that will handle this transparently for me?

#### To Reproduce

Apply compaction to legacy Cortex data on a minio S3 backend.

#### Expected behavior

After compaction and the threshold set by `compactor_partial_block_deletion_delay`, empty 'directories' are also deleted.

#### Environment

Bare metal, single process testing.

#### Additional Context

```
activity_tracker:
    filepath: ./active-query-tracker
alertmanager:
    data_dir: data/
alertmanager_storage:
    backend: s3
blocks_storage:
    backend: s3
    bucket_store:
        bucket_index:
            enabled: true
        index_header_lazy_loading_enabled: true
        sync_dir: /tmp/cortex/tsdb-sync
    filesystem:
        dir: ""
    s3:
        access_key_id: redacted
        bucket_name: cortex
        endpoint: minio.test.domain
        insecure: true
        secret_access_key: redacted
    tsdb:
        dir: /tmp/cortex/tsdb
compactor:
    cleanup_interval: 5m0s
    compaction_interval: 15m0s
    compaction_concurrency: 20
    data_dir: /tmp/cortex/compactor
    sharding_ring:
        kvstore:
            store: inmemory
distributor:
    pool:
        health_check_ingesters: true
ingester:
    ring:
        final_sleep: 0s
        kvstore:
            store: inmemory
        min_ready_duration: 0s
        num_tokens: 512
        replication_factor: 1
ingester_client:
    grpc_client_config:
        grpc_compression: gzip
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
multitenancy_enabled: true
ruler:
    enable_api: true
    rule_path: /rules
ruler_storage:
    backend: local
    filesystem:
        dir: ""
    local:
        directory: /tmp/cortex/rules
server:
    grpc_server_max_concurrent_streams: 1000
    grpc_server_max_recv_msg_size: 104857600
    grpc_server_max_send_msg_size: 104857600
    http_listen_port: 9009

limits:
    compactor_blocks_retention_period: 180d
    compactor_partial_block_deletion_delay: 4h0m
```
### mimir version
```
# ./mimir-linux-amd64 -version
Mimir, version 2.3.0 (branch: merge-release-2.3.0-to-main, revision: 2288a4efa)
  go version:       go1.18.4
  platform:         linux/amd64
```

[bucket-index.json.gz](https://github.com/grafana/mimir/files/9471394/bucket-index.json.gz)
