### ISSUE TITLE
Docs feedback: /operators-guide/running-production-environment-with-helm/configuration-with-helm.md

### ISSUE THREAD

**Issue by mrlexor** [grafana/mimir#2886]
Hello,

In the section `Example of configuration managed with Helm` in the point `4. Prepare your custom values file called custom.yaml:` you have a mistake in the structure of `extraEnvFrom`.

Please correct the structure to the following one:
```yaml
global:
  extraEnvFrom:
    - secretRef:
        name: mimir-bucket-secret
  podAnnotations:
    bucketSecretVersion: "0"
```
