### ISSUE TITLE
Unable to set up S3 storage

### ISSUE THREAD

**Issue by pantalones-rojos** [grafana/mimir#2896]
#### Describe the bug
I have been trying to set up S3 storage using the helm chart without success. I have an EKS cluster with IRSA enabled, i have created the proper role for the service account, the S3 bucket exist and it has a policy to allow access to the SA role, my values file look like this:

```
structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-west-1.amazonaws.com
          bucket_name: BUCKET_NAME
          region: eu-west-1
    blocks_storage:
      storage_prefix: blocks

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: ROLE_ARN

minio:
  enabled: false

```

When i run the helm deploy and i look at the pod logs i see this error:
`level=warn ts=2022-09-06T09:12:59.709379757Z caller=sanity_check.go:116 msg="Unable to successfully connect to configured object storage (will retry)" err="2 errors: blocks storage: unable to successfully send a request to object storage: Access Denied; ruler storage: unable to successfully send a request to object storage: Access Denied"`

#### Expected behavior

I expect the components to connect to the S3 bucket without issues.
