### ISSUE TITLE
Docs feedback: /operators-guide/configure/reference-configuration-parameters/index.md

### ISSUE THREAD

**Issue by mrlexor** [grafana/mimir#2911]
Hello,

Please take a look on section `The distributor block configures the distributor.` on the comment about the `ha_tracker.kvstore`.

Here you wrote the following comment:
```yaml
ha_tracker:
  # Backend storage to use for the ring. Please be aware that memberlist is not
  # supported by the HA tracker since gossip propagation is too slow for HA
  # purposes.
  kvstore:
    # Backend storage to use for the ring. Supported values are: consul, etcd,
    # inmemory, memberlist, multi.
    # CLI flag: -distributor.ha-tracker.store
    [store: <string> | default = "consul"]
```

But words `...memberlist is not supported by the HA tracker...` and `Supported values are: ..., memberlist,...` contradict each other.
