### ISSUE TITLE
Error reported using Aliyun OSS object store

### ISSUE THREAD

**Issue by weiya1990** [grafana/mimir#2964]
#### Describe the bug
This is my MIMIR configuration<html>
```
multitenancy_enabled: false
blocks_storage:
  backend: s3
  s3:
    access_key_id: xxxx
    secret_access_key: xxxx
    bucket_name: mimir-data
    endpoint: oss-cn-shanghai-internal.aliyuncs.com 
    insecure: true
  tsdb:
    dir: /data/ingester
```
#### Error message
`level=error ts=2022-09-16T00:59:54.933284229Z caller=shipper.go:160 user=anonymous msg="shipping failed" block=01GD1P4JRQCWM9T5PG0JCZM7PT err="upload chunks: upload file /data/ingester/anonymous/01GD1P4JRQCWM9T5PG0JCZM7PT/chunks/000001 as 01GD1P4JRQCWM9T5PG0JCZM7PT/chunks/000001: upload s3 object: Aws MultiChunkedEncoding is not supported."`
![image](https://user-images.githubusercontent.com/38902618/190534362-adc2d802-e411-460e-8beb-6618eb52b7fd.png)
