### ISSUE TITLE
Configuring Azure Blob Storage causes pods to not start up

### ISSUE THREAD

**Issue by jamunam** [grafana/mimir#2989]
Hi
I'm trying to configure Mimir to use Azure Blob storage in my AKS cluster.
Here is my configuration for blocks_storage in helm values

```
blocks_storage:
      backend: azure
      bucket_store:
        {{- if .Values.memcached.enabled }}
        chunks_cache:
          backend: memcached
          memcached:
            addresses: dns+{{ .Release.Name }}-memcached.{{ .Release.Namespace }}.svc:11211
            max_item_size: {{ .Values.memcached.maxItemMemory }}
            timeout: 450ms
        {{- end }}
        {{- if index .Values "memcached-queries" "enabled" }}
        index_cache:
          backend: memcached
          memcached:
            addresses: dns+{{ .Release.Name }}-memcached-queries.{{ .Release.Namespace }}.svc:11211
            max_item_size: {{ (index .Values "memcached-queries").maxItemMemory }}
        {{- end }}
        {{- if index .Values "memcached-metadata" "enabled" }}
        metadata_cache:
          backend: memcached
          memcached:
            addresses: dns+{{ .Release.Name }}-memcached-metadata.{{ .Release.Namespace }}.svc:11211
            max_item_size: {{ (index .Values "memcached-metadata").maxItemMemory }}
        {{- end }}
        sync_dir: /data/tsdb-sync
      azure: 
        account_key: ''
        account_name: ''
        container_name: ''
        endpoint_suffix: ''
      tsdb:
        dir: /data/tsdb
```

When I configure this, the below pods don't start up. They show as Running but readiness probe shows Failed. There are no errors in the logs for these pods.

mimir-compactor-0                                  0/1     Running     0          7m12s
mimir-ingester-0                                   0/1     Running     0          7m12s
mimir-ingester-1                                   0/1     Running     0          7m12s
mimir-ingester-2                                   0/1     Running     0          7m12s
mimir-mimir-distributed-make-bucket-job--1-h8l7n   0/1     Completed   0          7m12s
mimir-querier-b9d9c54dc-dwpkh                      0/1     Running     0          7m12s
mimir-querier-b9d9c54dc-k6jzp                      0/1     Running     0          7m12s
mimir-query-frontend-849b9f885b-cvl99              0/1     Running     0          7m12s
mimir-ruler-6fccd6c7fc-g76jh                       0/1     Running     0          7m12s
mimir-store-gateway-0                              0/1     Running     0          7m12s

When I switch it back to the default minio configuration, all pods start up as normal.
I can't figure out why this is happening. I have CSI Blob driver enabled in my cluster and I'm able to mount it into a pod
But mimir does not work with it. 
Additional info: The storage account is in a different azure resource group than that of the cluster. Would that cause a problem?
