### ISSUE TITLE
ruler: support explore URL format in the GeneratorURL

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/mimir#2997]
_From original [discussion on slack](https://grafana.slack.com/archives/C039863E8P7/p1663593811472229)_

### Current state
In Prometheus, an alert does have a `GeneratorURL` which points to the graph view of the particular Prometheus which sent it, with the query from the alert already filled in.

With Mimir ruler this is possible the same way: 
Currently, ruler allows configuring the `external_url` and then it generates the `GeneratorURL` using the [Prometheus code](https://github.com/grafana/mimir/blob/main/vendor/github.com/prometheus/prometheus/util/strutil/strconv.go#L36) which means appending `/graph?g0.expr=%s&g0.tab=0 ` to the `external_url`.

### Problem
The issue is that Mimir does not have the Prometheus compatible UI, so there is nowhere to point the URL to. 
Naturally, I'd expect this to be compatible with the Grafana explore since that is the native UI for querying Mimir, but it appears not.

### Suggestion
Add probably 2 new configuration options to the ruler something like 
```yaml
ruler:
  external_url: <Grafana URL>
  # Default prometheus so no breaking change, if set to grafana-explore, generator_datasource_id would be required
  generator_url_format: [prometheus(default),grafana-explore]
  # Explore requires setting the datasource ID in the URL if I'm not mistaken, so it would have to be configurable here
  generator_datasource_id: xyz
```

### Workaround
I found quite easy running only Prometheus react UI pointing to a Mimir. This way I'm capable of doing an "adapter" to make the URL work (and as a side effect give users the classic Prometheus UI which would ease the Migration for them) 

If agreed on the solution, I'd be happy to implement it :)
