### ISSUE TITLE
Allow to configure hash ring via common config block

### ISSUE THREAD

**Issue by pracucci** [grafana/mimir#3031]
I [proposed to deprecated consul and etcd for the KV store ](https://github.com/grafana/mimir/issues/2949) but apparently we're not ready to move everyone to memberlist yet. For the people still using etcd or consul backend, we could simplify their config adding support to configure the hash ring KV store via the common config block.

I propose the following config:

```yaml
common:
  ring:
    kvstore:
      store: <string>
      consul: <consul>
      etcd: <etcd>
    instance_id: <string>
    instance_interface_names: <list of strings>
    instance_port: <int>
    instance_addr: <string>
    heartbeat_period: <duration>
    heartbeat_timeout: <duration>
```

Other fields I intentionally excluded because it's not safe to set the same value everywhere:
- `ring.kvstore.prefix`
- Replication factor

Notes:
- To add `heartbeat_period` to common we need to change all defaults to the same value first
