### ISSUE TITLE
Ruler: pause rule groups

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#3039]
This is a feature request for being able to pause evaluation of rule groups without deleting them.

### Use cases

* as a Mimir end-user I have an incident and my data isn't complete (not everything is getting scraped, some scrapes may report unrealistic data). Some of my recording rules depend on this data. I use these recording rules for some business-critical calculation like for billing my customers. I would rather have no metrics and underbill my customers than have metrics that will lead me to overbilling my customers.
* as a platform engineer/engineering manager, I want a declarative way of managing silences for my org's alerts. The existing alertmanager silences UI doesn't allow me to keep track of all expired silences. Silences in the UI also have no access control or approval mechanism. This means whoever has access to the UI can create any silence they like. If I want to silence an alert, I want this to be part of my GitOps flow and the approvals I have there

### Proposal

Add a `paused` field to alert groups. When `paused: true` the alert group will not evaluate: alerting rule within it will generate no alerts and recording rules within it will produce no series. It will still be visible on the [ruler config API](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#list-prometheus-alerts) and the [prometheus-compatible status API](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#list-prometheus-alerts).

```yaml
name: group_1
interval: 5s
paused: true
rules:
    - alert: Group1Alert
      expr: count_over_time(vector(0)[5m:1m]) > 5
      for: 30s
      labels:
        severity: warning
```

#### Implementation details

Data model: The protobuf descriptor which stores rule groups already has a field for source tenants for federated rules. We can add another `IsPaused` (naming TBD) or use the `Options` field to store additional context about the group. 

https://github.com/grafana/mimir/blob/fe6ee9c8b253e57a7a6335064602f42ba5227762/pkg/ruler/rulespb/rules.pb.go#L42-L47

Behaviour: On rule syncs the ruler already filters out federated rule groups, when that feature is disabled. Pausing can be implemented in a similar fashion. https://github.com/grafana/mimir/blob/27da422ad9225892996dbcd2bbedf64a27dabaaa/pkg/ruler/manager.go#L104-L106

**Comment by dimitarvdimitrov** [comment]
pausing rule groups is possible per tenant via this 

```yaml
limits:
	ruler_alerting_rules_evaluation_enabled: false
	ruler_recording_rules_evaluation_enabled: false
```

pausing individual groups is probably not worth the hassle
