### ISSUE TITLE
Helm: inject node name for GEM pods

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#3069]
### Context 

GEM keeps track of the resources available to it when running in cgroups. These are exported in GEM-specific metrics, e.g. `cortex_quota_cpu_count`. The same metrics also exports the name of the host that the process is running with (`$HOSTNAME`). 

### Description
The problem is that in kubernetes the hostname is the same as the name of the pod, which renders the label fairly useless and makes it more difficult to reason about how much CPU in total the cluster uses (because you can double count pods running on the same node).

_But_ GEM allows to inject the name of the host via an environment  variable - `NODENAME`. Kubernetes supports injecting dynamic environment variables into pods.

### Proposal

I propose to add `NODENAME` with the name of the Kubernetes Node where the pod is running: from [k8s docs](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/) this would looks something like

```yaml
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "sleep", "10"]
      env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```
