### ISSUE TITLE
Invalid ingress nginx config due to newline in prometheusHttpPrefix Helm named templates

### ISSUE THREAD

**Issue by lamida** [grafana/mimir#3086]
#### Describe the bug
Return value from named templates mimir.prometheusHttpPrefix is not trimmed. This will result in an invalid ingress Nginx config generated when `api.prometheus_http_prefix` is set.

#### To Reproduce

Prepare simple mimir-distributed `custom.yaml`.

```
mimir:
  config: |
    activity_tracker:
        filepath: /data/active-query-tracker
    api:
      prometheus_http_prefix: /prometheus
      alertmanager_http_prefix: /alertmanager
```

Install mimir-distributed using above helm values.

That will create the following invalid nginx config:
```
...
   # Rest of 
/prometheus goes to the query frontend
    location 
/prometheus {
      proxy_pass      http://cortex-query-frontend.cortex.svc.cluster.local:8080$request_uri;
    }
...
```

That config will make nginx ingress pod to fail starting with the following error:
```
2022/09/29 11:15:00 [emerg] 1#1: unknown directive "/prometheus" in /etc/nginx/nginx.conf:84
nginx: [emerg] unknown directive "/prometheus" in /etc/nginx/nginx.conf:84
```

#### Expected behavior

The nginx config should be generated properly as follow.

```
   # Rest of /prometheus goes to the query frontend
    location 
/prometheus {
      proxy_pass      http://cortex-query-frontend.cortex.svc.cluster.local:8080$request_uri;
    }
```

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

We can fix this by removing that templated comment `# Rest of /prometheus goes to the query frontend` or to just trim the prometheusHttpPrefix named templates. alertmanagerHttpPrefix template is not giving any issue since it is not used in any comment in nginx config. However, it is good to trim that as well.
