### ISSUE TITLE
Helm: Mention runtime config in "Manage the configuration of Grafana Mimir with Helm"

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#3135]
That article doesn't mention how to manage the runtime config with helm. It's fairly simple, but it's not mentioned anywhere.

```yaml
runtime_config:
  overrides:
    tenant_a:
      ingestion_rate: 123
```

The runbooks also don't mention how to set the tenant overrides config or instante limits in helm. As part of this issue, update the runbooks to link to this article.
