### ISSUE TITLE
tls_enabled param missing from ruler's alertmanager_client config

### ISSUE THREAD

**Issue by mac133k** [grafana/mimir#3220]
#### Describe the bug
Ruler's alertmanager_client config section does not have tls_enabled param. I am not sure if that is a bug, but other config sections with TLS settings do have such param.

#### To Reproduce

In Mimir config add this bit:
```
ruler:
  alertmanager_client:
    tls_ca_path: /etc/mimir/ca.crt
    tls_cert_path: /etc/mimir/client.crt
    tls_enabled: true
    tls_key_path: /etc/mimir/client.key
```

Start Mimir:
```
# mimir -config.file /etc/mimir/mimir-ruler.yml
error loading config from /etc/mimir/mimir-ruler.yml: Error parsing config file: yaml: unmarshal errors:
  line 141: field tls_enabled not found in type ruler.NotifierConfig
```

#### Expected behavior
Alertmanager client config for ruler was expected to have tls_enabled toggle.

#### Environment
```
# mimir --version
Mimir, version 2.3.1 (branch: release-2.3, revision: 64a71a566)
  go version:       go1.18.4
  platform:         linux/amd64

# uname -r
4.18.0-372.13.1.el8_6.x86_64
```

#### Additional Context

Configuration reference doc does not mention tls_enabled in ruler's alertmanager client config either.
