### ISSUE TITLE
'mimirtool alertmanager get' output is invalid and messy

### ISSUE THREAD

**Issue by adeverteuil** [grafana/mimir#3241]
#### Describe the bug

When I run `mimirtool alertmanager get`, the output is not very clean.

Problems:
* The Alertmanager config is at the root of the printed YAML output, along with a `Templates` key.
* The `Templates:` key is capitalized, it should be lowercase, for uniformity.
* The templates data is not indented, this YAML is invalid.
* The Alertmanager config should be under its own key as well.

Requested fixes:
* There should be two root dictionary keys `alertmanager_config` and `template_files`, to be consistent with the POST body requirements.  
  https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#set-alertmanager-configuration
* The output of `mimirtool alertmanager get` should be usable as an input for `mimirtool alertmanager load`.
* Returning the response of the `GET /api/v1/alerts` API call without any processing would be better.

Here is an example of what I get:

```
alex@lgtm-lab-01:~$ mimirtool alertmanager get
global:
    http_config:
        follow_redirects: true
        proxy_url: null
        tls_config:
            insecure_skip_verify: false
    opsgenie_api_url: https://api.opsgenie.com/
    pagerduty_url: https://events.pagerduty.com/v2/enqueue
    resolve_timeout: 5m
    smtp_hello: localhost
    smtp_require_tls: true
    smtp_smarthost: ""
    victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
    wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
receivers:
    - name: no-op
    - name: logger
      webhook_configs:
        - http_config:
            follow_redirects: true
            proxy_url: null
            tls_config:
                insecure_skip_verify: false
          max_alerts: 0
          send_resolved: true
          url: http://localhost:8888/gem-alertmanager
route:
    receiver: logger
    repeat_interval: 5m
templates:
    - test

Templates:
test:
{{ define "test" }}
  asdf
{{ end }}
```

#### To Reproduce

1. Start Mimir v2.2.0 (tested on GEM v2.2.0).
2. Create a tenant with an Alertmanager config.
3. Use `mimirtool alertmanager get` to read the Alertmanager config.

#### Expected behavior

Here is the fixed output I would prefer to see:

```
alertmanager_config: |
    global:
        http_config:
            follow_redirects: true
            proxy_url: null
            tls_config:
                insecure_skip_verify: false
        opsgenie_api_url: https://api.opsgenie.com/
        pagerduty_url: https://events.pagerduty.com/v2/enqueue
        resolve_timeout: 5m
        smtp_hello: localhost
        smtp_require_tls: true
        smtp_smarthost: ""
        victorops_api_url: https://alert.victorops.com/integrations/generic/20131114/alert/
        wechat_api_url: https://qyapi.weixin.qq.com/cgi-bin/
    receivers:
        - name: no-op
        - name: logger
          webhook_configs:
            - http_config:
                follow_redirects: true
                proxy_url: null
                tls_config:
                    insecure_skip_verify: false
              max_alerts: 0
              send_resolved: true
              url: http://localhost:8888/gem-alertmanager
    route:
        receiver: logger
        repeat_interval: 5m
    templates:
        - test

template_files:
    test: |
        {{ define "test" }}
          asdf
        {{ end }}
```

#### Environment

- Infrastructure: Single-node monolithic GEM process on Ubuntu 22.04.
- Deployment tool: Ansible, systemd.

#### Additional Context

n/a
