### ISSUE TITLE
Helm: future improvements

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#3315]
### Opinionated metamonitoring setup

  right now to get a working set of dashboards with the grafana agent you need to enable a few things - the grafana agent, install its operator, enable service monitors, scraping kubernetes, and recording rules; instead we can just enable all of these things with a single toggle; this will make the setup more opinionated and should satisfy most setups

  a similar thing can be done for a use case of the prometheus operator - instead of configuring each of the components of the operator (PrometheusRules, ServiceMonitor, a Prometheus instance that you need to set up), the chart will do these for you at the risk of scraping the same data from mimir multiple times and having it in a separate prometheus instance instead of a central one.

  The idea is to have something to get started with without configuring pretty much anything except for a true/false toggle. Same setup can also provide optional settings so the same setup can be deployed to a small production environment; settings such as namespace for these resources, scrape interval
  
  ```yaml
  metamonitoring:
    prometheusOperatorUseCase:
      enabled: true # required, when true the chart enabled serviceMonitor, prometheusRules with Mimir's default recording & alerting rules, Prometheus instance, and Alertmanager instance
      namespace: monitoring # optional
      scrapeInterval: 15s # optional
      alertmanagerReceiver: '' # alertmanager config so alerts are routed somewhere 
  ```
