### ISSUE TITLE
err-mimir-store-consistency-check-failed

### ISSUE THREAD

**Issue by alfianabdi** [grafana/mimir#3327]
#### Describe the bug
Recently I keep getting error from querier 'err-mimir-store-consistency-check-failed'. 
After looking into store-gateway, the requested block is not there, but the said block exists inside the storage ( S3 ) and inside the index. 
Looking the logs, there is no error. It even says that the synchronization is successful
```
level=info ts=2022-10-28T11:10:49.850096057Z caller=gateway.go:294 msg="successfully synchronized TSDB blocks for all users" reason=periodic
```

#### To Reproduce

1. Start Mimir (SHA or version)
2. Perform Operations(Read/Write/Others)

#### Expected behavior

Store gateway is able to download the required block.

#### Environment

- Infrastructure: Kubernetes ( eks 1.22 )
- Deployment tool: Helm ( helm distributed 3.0.0, migrated from cortex 1.4.0 )

#### Additional Context

Config
```
activity_tracker:
  filepath: /data/mimir/activity/metrics-activity.log
alertmanager:
  data_dir: /data
  external_url: /api/prom/alertmanager
  sharding_ring:
    kvstore:
      store: memberlist
alertmanager_storage:
  backend: s3
  s3:
    bucket_name: <REDACTED>
    endpoint: s3.ap-southeast-1.amazonaws.com
api:
  prometheus_http_prefix: /prometheus
blocks_storage:
  backend: s3
  bucket_store:
    sync_dir: data
  s3:
    bucket_name: <REDACTED>
    endpoint: s3.ap-southeast-1.amazonaws.com
  tsdb:
    dir: /data
compactor:
  data_dir: /data
  sharding_ring:
    kvstore:
      store: memberlist
distributor:
  ha_tracker:
    enable_ha_tracker: true
    kvstore:
      consul:
        acl_token: ${CONSUL_TOKEN}
        host: <REDACTED>
      prefix: cortex/ha-tracker/
      store: consul
  pool:
    health_check_ingesters: true
  ring:
    kvstore:
      store: memberlist
frontend:
  align_queries_with_step: true
  cache_results: false
  grpc_client_config:
    grpc_compression: snappy
  log_queries_longer_than: 10s
  results_cache:
    memcached:
      timeout: 1s
  split_queries_by_interval: 24h0m0s
frontend_worker:
  frontend_address: cortex-query-frontend-headless.monitoring.svc:9095
  grpc_client_config:
    grpc_compression: snappy
ingester:
  ring:
    kvstore:
      store: memberlist
    num_tokens: 512
    replication_factor: 2
ingester_client:
  grpc_client_config:
    grpc_compression: snappy
limits:
  accept_ha_samples: true
  ha_max_clusters: 3
  ingestion_burst_size: 500000
  ingestion_rate: 250000
  max_global_series_per_metric: 200000
  max_global_series_per_user: 0
memberlist:
  join_members:
  - cortex-gossip-ring
multitenancy_enabled: true
no_auth_tenant: fake
querier:
  query_ingesters_within: 8h5m0s
  query_store_after: 8h0m0s
ruler:
  alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.cortex-alertmanager-headless.monitoring.svc.cluster.local/alertmanager
  ring:
    kvstore:
      store: memberlist
  rule_path: /data/rules
ruler_storage:
  backend: s3
  s3:
    bucket_name: <REDACTED>
    endpoint: s3.ap-southeast-1.amazonaws.com
server:
  log_level: info
```
