### ISSUE TITLE
cannot unmarshal !!seq into alertmanager.UserConfig

### ISSUE THREAD

**Issue by tburschka** [grafana/mimir#3338]
#### Describe the bug
I try to get mimir work with [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and configure the chart so that duplicated services like alertmanager existing only once.
Unfortunately, i receive an error message in mimir-alertmanager when prometheus try to send data to alertmanager via mirmir-nginx: 

```
mimir-alertmanager-0 alertmanager level=error ts=2022-10-30T04:30:50.904237086Z caller=api.go:139 component=MultiTenantAlertmanager user=anonymous msg="error marshalling YAML Alertmanager config" err="yaml: unmarshal errors:\n  line 1: cannot unmarshal !!seq into alertmanager.UserConfig"
```

#### To Reproduce

Install  `kube-prometheus-stack`:

```
helm upgrade --install --namespace kube-telemetry prometheus prometheus-community/kube-prometheus-stack --values prometheus.yaml
```

*prometheus.yaml*
```yaml
fullnameOverride: prometheus

cleanPrometheusOperatorObjectNames: true

alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus-node-exporter:
  fullnameOverride: prometheus-node-exporter

prometheus:
  prometheusSpec:
    remoteWrite:
      - url: http://mimir-nginx.kube-telemetry.svc/api/v1/push
    alertingEndpoints:
      - namespace: kube-telemetry
        name: mimir-nginx
        port: http-metric
        pathPrefix: "/"
        apiVersion: v1
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-hostpath
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    additionalScrapeConfigs:
      - job_name: kubernetes-pod-endpoints
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          # annotation 'prometheus.io/scrape' must be set to 'true'
          - action: keep
            regex: true
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          # service cannot be in kube-system or prom namespaces
          - action: drop
            regex: (kube-system|prometheus)
            source_labels: [__meta_kubernetes_namespace]
          # service port name must end with word 'metrics'
          - action: keep
            regex: .*metrics
            source_labels: [__meta_kubernetes_pod_port_name]
          # allow override of http scheme
          - action: replace
            regex: (https?)
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
            target_label: __scheme__
          # allow override of default /metrics path
          - action: replace
            regex: (.+)
            source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            target_label: __metrics_path__
          # allow override of default port
          - action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            target_label: __address__
          - {action: labelmap, regex: __meta_kubernetes_pod_label_(.+)}
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: kubernetes_namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
```

Apply alertmananger fallback config:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-alertmanager-fallback-config
  namespace: kube-telemetry
data:
  alertmanager_fallback_config.yaml: |
    receivers:
      - name: default-receiver
    route:
      receiver: default-receiver
```

Install mimir:

```
helm upgrade --install --namespace kube-telemetry mimir grafana/mimir-distributed --values mimir.yaml
```

*mimir.yaml*

```yaml
fullnameOverride: mimir
mimir:
  structuredConfig:
    multitenancy_enabled: true
    ### START: https://github.com/grafana/mimir/pull/2942/files
    alertmanager:
      fallback_config_file: /configs/alertmanager_fallback_config.yaml
    ### END
    alertmanager_storage:
      backend: s3
      s3:
        access_key_id: mimir
        bucket_name: mimir-ruler
        endpoint: minio.minio.svc:9000
        insecure: true
        secret_access_key: "ABCD"
    blocks_storage:
      backend: s3
      s3:
        access_key_id: mimir
        bucket_name: mimir-tsdb
        endpoint: minio.minio.svc:9000
        insecure: true
        secret_access_key: "ABCD"
    ruler_storage:
      backend: s3
      s3:
        access_key_id: mimir
        bucket_name: mimir-ruler
        endpoint: minio.minio.svc:9000
        insecure: true
        secret_access_key: "ABCD"
alertmanager:
  persistentVolume:
    storageClass: "openebs-hostpath"
### START: https://github.com/grafana/mimir/pull/2942/files
  extraVolumes:
    - name: alertmanager-fallback-config
      configMap:
        name: mimir-alertmanager-fallback-config
  extraVolumeMounts:
    - name: alertmanager-fallback-config
      mountPath: /configs/alertmanager_fallback_config.yaml
      subPath: alertmanager_fallback_config.yaml
### END
ingester:
  replicas: 2 # 3
  persistentVolume:
    storageClass: "openebs-hostpath"
store_gateway:
  persistentVolume:
    storageClass: "openebs-hostpath"
compactor:
  persistentVolume:
    storageClass: "openebs-hostpath"
chunks-cache:
  enabled: true
  allocatedMemory: 1024 # 8192
index-cache:
  enabled: true
  allocatedMemory: 128 # 1024
metadata-cache:
  enabled: true
  allocatedMemory: 64 # 512
results-cache:
  enabled: true
  allocatedMemory: 64 # 512
minio:
  enabled: false
```

Waiting for all coming up

#### Environment

It's my test environment:

* HW: Single-Node-Cluster (4C/16GB/320GB)
* OS: Debian 11
* k3s: v1.24.7+k3s1

**Comment by Logiraptor** [comment]
Hello, I believe the configuration for the alertmanager url should use the `/alertmanager` path prefix.

Like so:

```
prometheus:
  prometheusSpec:
    alertingEndpoints:
      - namespace: kube-telemetry
        name: mimir-nginx
        port: http-metric
        pathPrefix: "/alertmanager"
        apiVersion: v1
...
```
