### ISSUE TITLE
Evaluation delay set per group is not stored or used by Mimir

### ISSUE THREAD

**Issue by pstibrany** [grafana/mimir#3357]
#### Describe the bug

https://github.com/grafana/mimir/pull/1474 introduced ability to set evaluation delay for individual rule groups. Unfortunately this isn't fully working in Mimir yet. While uploading rule group with evaluation delay says that upload succeeded, getting the rule back shows that evaluation delay field was lost.

My group.yaml file:
```
name: testrules
evaluation_delay: "3m"
rules:
    - record: evaluation:timestamp
      expr: time()
    - record: test_metric:sum:rate1m
      expr: sum(rate(test_metric[1m]))
```

Uploading using "/prometheus/config/v1/rules/namespace" endpoint reports:

```console
$ curl -u "$MIMIR_TENANT_ID:$MIMIR_API_KEY" $RULES_ENDPOINT_PREFIX/namespace --data-binary @group.yaml
{"status":"success","data":null,"errorType":"","error":""}%
```

But getting the group back shows no evaluation delay:

```console
$ curl -u "$MIMIR_TENANT_ID:$MIMIR_API_KEY" $RULES_ENDPOINT_PREFIX/namespace
namespace:
    - name: testrules
      rules:
        - record: evaluation:timestamp
          expr: time()
        - record: test_metric:sum:rate1m
          expr: sum(rate(test_metric[1m]))
```

This seems to be caused by the fact that `rulespb.ToProto` [call](https://github.com/grafana/mimir/blob/eb754c60b284168a81da2e9f8d6eb20428f8187f/pkg/ruler/api.go#L507) in `CreateRuleGroup` method doesn't store evaluation delay field to protobuf message: https://github.com/grafana/mimir/blob/fe6ee9c8b253e57a7a6335064602f42ba5227762/pkg/ruler/rulespb/compat.go#L19-L30

(Field doesn't even exist in protobuf message)

Tested against r210 build.
