### ISSUE TITLE
Bucket validation passes when S3 host starts with bucket name

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/mimir#3410]
Mimir works with S3 URLs that cannot contain the bucket name as part of the URL. The [current validation](https://github.com/grafana/mimir/blob/6fef60a44e2f662079a8d0fd1cdee986a7ee1db8/pkg/mimir/sanity_check.go#L164-L170) assumes the config is valid if it manages to send a request to the bucket for a non-existent object and get a "Not Found" error. This approach fails when the URL is structured such that it always yields an HTTP 404

#### incorrect config

```yaml
blocks_storage:
  backend: s3
  s3:
    bucket_name: mimir-blocks
    endpoint: mimir-blocks.s3.eu-central-1.amazonaws.com
    access_key_id: AKIA......................................G
    secret_access_key: d......................................................S
```

validation passed, but then the store-gateway fails to start because it cannot find the bucket index
```
level=info ts=2022-11-07T17:05:35.252927055Z caller=sanity_check.go:44 msg="Object storage config successfully checked"
...
level=warn ts=2022-11-07T17:05:40.325435736Z caller=bucket_stores.go:170 msg="failed to synchronize TSDB blocks" err="The specified key does not exist."
```

#### correct config
```yaml
blocks_storage:
  backend: s3
  s3:
    bucket_name: mimir-blocks
    endpoint: s3.eu-central-1.amazonaws.com
    access_key_id: AKIA......................................G
    secret_access_key: d......................................................S
```

### proposal 1

Improve the validation to also include writing and reading an object to the bucket. The object can be 1-byte long with a different key per component replica (or random), so it doesn't clash between components.

Possible caveat is that these objects may pile up if not cleaned up properly (e.g. component has read/write access, but not delete access).

### proposal 2

Validate that the endpoint hostname is not prefixed with the bucket name.
