### ISSUE TITLE
alertmanager templating fail half of the time

### ISSUE THREAD

**Issue by vaxvms** [grafana/mimir#3591]
#### Describe the bug
Templating fail half of the time.

#### To Reproduce

1. Start Mimir 2.4.0
`./mimir-linux-amd64 -target all,ruler,alertmanager --config.file=./demo.yaml`

2. Load a always on alerting rules
`mimirtool rules load alerts.yml`

3. Load a alertmanager configuration
`mimirtool alertmanager load alertmanager.yml sample.tmpl`

4. Use nc to see notifications
`nc -l 6527`

#### Expected behavior

No templating error reported in log for half of notifications
`level=error ts=2022-11-30T15:55:23.260898571Z caller=dispatch.go:352 component=MultiTenantAlertmanager user=anonymous component=dispatcher insight=true component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="opsgenie-P5/opsgenie[0]: notify retry canceled due to unrecoverable error after 1 attempts: templating error: template: :1:12: executing \"\" at <{{template \"sample\" .}}>: template \"sample\" not defined"`

#### Environment

- Infrastructure: laptop
- Deployment tool: none

#### Additional Context

While looking at data-alertmanager/anonymous/templates/ we can see the file sample.tmpl being deleted and recreated every 15s.
Might be related to https://github.com/cortexproject/cortex/issues/4888 ?

sample.tmpl
```
{{ define "sample" }}This is a sample static template{{ end }}
```

alertmanager.yml
```
global:
  # The API url is wrong on purpose as we want to test templating
  opsgenie_api_url: http://127.0.0.1:6527
  opsgenie_api_key: ABCD

route:
  receiver: opsgenie-P5
  repeat_interval: 30s
  group_interval: 1m
  group_by:
    - alertname

receivers:
- name: opsgenie-P5
  opsgenie_configs:
    - message: '{{ template "sample" . }}'
      priority: P5

templates:
- 'sample.tmpl'
```

alerts.yml
```
namespace: deadmanswitch
groups:
  - name: DeadManSwitch
    rules:
      - alert: DeadMansSwitch
        expr: vector(1)
        labels:
          severity: none
        annotations:
          description: >
            This is a DeadMansSwitch meant to ensure that
            the entire Alerting pipeline is functional.
          summary: Alerting DeadMansSwitch
```

demo.yaml
```
multitenancy_enabled: false

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

ruler:
  alertmanager_url: http://127.0.0.1:8080/alertmanager

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 8080
  log_level: info

store_gateway:
  sharding_ring:
    replication_factor: 1
```

**Comment by pracucci** [comment]
> Might be related to https://github.com/cortexproject/cortex/issues/4888 ?

This Cortex issue (and relative fix) looks related to the `local` storage backend. Given you're not explicitly configuring it in your Mimir config file, the Mimir alertmanager is running with the default `filesystem` backend. However, I'm not seeing you configuring the filesystem location in the `alertmanager_storage` section.

Could you try the following, please?
```
alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/alertmanager
```
