### ISSUE TITLE
[Helm][v4.0.0] Gateway component doesn't have `/metrics` endpoint

### ISSUE THREAD

**Issue by carlosjgp** [grafana/mimir#3833]
#### Describe the bug
After deploying `mimir-distributed` version `4.0.0`

![image](https://user-images.githubusercontent.com/1277613/210088016-58cf1dbf-34d5-440e-a43c-2a27b4901834.png)

#### To Reproduce

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo add grafana https://grafana.github.io/helm-charts
helm repo update

helm upgrade --install prometheus-operator prometheus-community/kube-prometheus-stack
helm fetch --untar grafana/mimir-distributed --version 4.0.0
helm upgrade --install mimir ./mimir-distributed \
  -f ./mimir-distributed/values.yaml \
  -f ./mimir-distributed/large.yaml
```

#### Expected behavior

Either be able to disable the `ServiceMonitor` for the gateway or add the `/metrics` endpoint as expected (see workaround below)

#### Environment

- Infrastructure: AWS EKS
- Deployment tool: Helm

#### Additional Context

My workaround has been to add [`nginx-prometheus-exporter`](https://github.com/nginxinc/nginx-prometheus-exporter) as sidecar

```yaml
gateway:
  enabledNonEnterprise: true
  extraContainers:
  - args:
    - -nginx.retries=5
    - -nginx.scrape-uri=http://127.0.0.1:8080/nginx_status
    - -web.telemetry-path=/metrics
    - -web.listen-address=:9113
    image: nginx/nginx-prometheus-exporter:0.11.0
    name: nginx-exporter
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
  nginx:
    config:
      serverSnippet: |
        location = /metrics {
          proxy_pass http://127.0.0.1:9113$request_uri;
          auth_basic off;
        }
        location = /nginx_status {
          stub_status;
          auth_basic off;
        }
    verboseLogging: false
  podDisruptionBudget:
    maxUnavailable: 50%
  replicas: 5
  resources: {}

```

![image](https://user-images.githubusercontent.com/1277613/210089762-97affdd1-5f2b-4aa7-86a1-722c2dfc9c6a.png)
