### ISSUE TITLE
Docs: OpenShift

### ISSUE THREAD

**Issue by ctml91** [grafana/mimir#4040]
#### Is your documentation request related to a feature? If so, which one?

OpenShift support was added via https://github.com/grafana/mimir/pull/2219 , I cannot find any documentation to go along with but checking the PR it would seem to be enabling it should be pretty straight forward. However enabling SCC and rbac creation still leads to SCC related errors due to seccomp profile being added.

```
rbac:
  create: true
  type: scc
serviceAccount:
  create: true
```

```
FailedCreate            statefulset/mimir-store-gateway-zone-b                       create Pod mimir-store-gateway-zone-b-0 in StatefulSet mimir-store-gateway-zone-b failed error: pods "mimir-store-gateway-zone-b-0" is forbidden: unable to validate against any security context constraint: [pod.metadata.annotations.seccomp.security.alpha.kubernetes.io/pod: Forbidden: seccomp may not be set pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/store-gateway
```

The resultant STS has a security context spec of
```
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
```

Which is the default, but if I must override all 20 components in the helm values to remove seccomProfile from each, it would be good to mention in the docs for OCP or have that happen automatically when setting the rbac type to SCC.

```
$ helm list
NAME 	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART                  	APP VERSION
mimir	mimir    	2       	2023-01-23 00:28:06.209686 -0500 EST	deployed	mimir-distributed-4.0.1	2.5.0


OCP: 4.10.36
Kubernetes Version: v1.23.5
```

#### Describe the solution that you’d like or the expected outcome
Documentation for installing on OCP.
