### ISSUE TITLE
Minio bucket is always  emtpy

### ISSUE THREAD

**Issue by suikast42** [grafana/mimir#4185]
#### Describe the bug
I setup a minio server with pre created bucket for mimir.  With the mimir config 

```yaml
# Test observability.mimir[0]
# Do not use this configuration in production.
# It is for demonstration purposes only.
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter
multitenancy_enabled: false
#bar: observability.mimir[0]
server:
  http_listen_port: 9009
  log_level: debug
  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

common:
  storage:
    backend: s3
    s3:
      endpoint: "minio.service.consul:22375"
      access_key_id: ${MINIO_USER}
      secret_access_key: ${MINIO_PASSWORD}
      insecure: true
      bucket_name: mimir

# Blocks storage requires a prefix when using a common object storage bucket.
blocks_storage:
  backend: s3
  storage_prefix: blocks
  tsdb:
    retention_period: 168h
    dir: /data/ingester

alertmanager_storage:
  backend: s3
  storage_prefix: alarms

ruler_storage:
  backend: s3
  storage_prefix: ruler

compactor:
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1


store_gateway:
  sharding_ring:
    replication_factor: 1

limits:
  max_label_names_per_series: 42
  # Allow ingestion of out-of-order samples up to 5 minutes since the latest received sample for the series.
  out_of_order_time_window: 5m
```

I excpect that mimir saves the TSDB files inside the bucket but the onliy that mirimir saves  in the bucket is  a filed named mimir_cluster_seed.json. 

After restart the container all that is gone ( because I don't mapped this in a volume ).

Did I miss something ?
