### ISSUE TITLE
Couldn't find Distributor status menu on the dashboard

### ISSUE THREAD

**Issue by chupark** [grafana/mimir#4192]
#### Describe the bug
I deploy 2 distributors, but couldn't find that on the dashboard
<img width="809" alt="image" src="https://user-images.githubusercontent.com/32254293/217499073-fe1efced-6f3d-43bc-aff4-02b63848f6d0.png">

However, when I deploy 2 ingesters, it could find on the dashboard

Even though all modules are joined to hash ring, I couldn't find distributor on the dashboard
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/32254293/217499975-710f3144-6711-40ce-9c14-c31002284d05.png">

#### To Reproduce

1. Deploying backend
```yaml
multitenancy_enabled: false
target: backend

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 9009
  log_level: info
```

2. Deploying distributor & ingester
```yaml
# distributor1 ~ 2.yaml
target: distributor

distributor:
  ring:
    kvstore:
      store: memberlist
    instance_id: pcw-dis-1

memberlist:
  node_name: pcw-backend
  join_members: ["10.1.0.16:7946"]
  bind_port: 7947

server:
  http_listen_port: 9010
  grpc_listen_port: 9096
----
# ingester1~2.yaml
target: ingester

ingester:
  ring:
    kvstore:
      store: memberlist
    instance_id: pcw-ing-1

memberlist:
  node_name: pcw-backend
  join_members: ["10.1.0.16:7946"] 
  bind_port: 7950 

server:
  http_listen_port: 9020
  grpc_listen_port: 9100
```

#### Expected behavior

Distributor's status menu is available on the dashboard

#### Environment

- Infrastructure: Ubuntu18, VM
- Deployment tool: binary
