### ISSUE TITLE
Mimir doesn't write to s3 (not an IAM permission issue)

### ISSUE THREAD

**Issue by ofiry-tm** [grafana/mimir#4267]
#### Describe the bug
I configured Mimir storage like this :
```
  minio:
    enabled: false

  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            endpoint: s3.<my-region>.amazonaws.com
            region: <my-region>
      blocks_storage:
        s3:
          bucket_name: <my-mimir-blockes-bucket>
      alertmanager_storage:
        s3:
          bucket_name: <my-mimir-alertmanager-bucket>
      ruler_storage:
        s3:
          bucket_name: <my-mimir-ruler-bucket>
```

I set also the iam access to the buckets with:
s3:Get*
s3:List*
s3:*Object *

(using a service account, that attach the pods to an iam role)

And also I set my Prometheus to write to Mimir (remoteWrite), and when I query the Mimir with Grafana, it shows me what the Prometheus is sending to Mimir.

Now, in the bucket named my-mimir-blockes-bucket, i see only this object: 

```
__mimir_cluster/mimir_cluster_seed.json
```

so that means there is no permissions issue.

But - after 2-3 hours that the prometheus writes to the Mimir, that is still the only object in the s3 blocks bucket, 
and the other 2 buckets, of the ruler and alert manager are totally empty.

is this making any sense?

also, i see that by default, some persistent volumes was created for store_gateway, ingester, alertmanager, and compactor, with sizes of 1GB - 2 GB.
this is something i wouldnt want in production, would you suggest to replace it with EFS ?
and what is the point of having s3 as storage if we also need all of these persistentVolumes ?
btw - all the mimir pods are running, no one is crashing.

#### Expected behavior

Seeing files are written to S3 (to the Mimir blocks bucket at least)
#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm
