### ISSUE TITLE
Ingesters were stopped over and over again with an error

### ISSUE THREAD

**Issue by chupark** [grafana/mimir#4288]
#### Describe the bug
Ingesters are stopped over and over again with an error

#### To Reproduce
 * All components were deployed on single VM

1. start backend
```
## start backend
multitenancy_enabled: false
target: backend

blocks_storage:
  backend: filesystem
  bucket_store:
    sync_dir: /tmp/mimir/tsdb-sync
  filesystem:
    dir: /tmp/mimir/data/tsdb
  tsdb:
    dir: /tmp/mimir/tsdb

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/rules

server:
  http_listen_port: 9009
  log_level: info
```

2. start 3 ingesters 
```
## ingester 1 ~ 3
target: ingester

ingester:
  ring:
    kvstore:
      store: memberlist
    instance_id: pcw-ing-[1 ~ 3]

memberlist:
  node_name: pcw-backend
  join_members: ["10.1.0.16:7946"]
  bind_port: 7950 ~ 7952

server:
  http_listen_port: 9020 ~ 9022
  grpc_listen_port: 9100 ~ 9102
```

3. start 3 distributors
```
## distributor 1 ~ 3
multitenancy_enabled: false
target: distributor

distributor:
  ring:
    kvstore:
      store: memberlist
    instance_id: pcw-dis-1 ~ 3

memberlist:
  node_name: pcw-backend
  join_members: ["10.1.0.16:7946"]
  bind_port: 7947 ~ 9

server:
  http_listen_port: 9010 ~ 9012
  grpc_listen_port: 9096 ~ 9098
```
5. start 1 store-gateway
```
multitenancy_enabled: false
target: store-gateway

server:
  http_listen_port: 9210
  grpc_listen_port: 9310
  log_level: info

store_gateway:
  sharding_ring:
    kvstore:
      store: memberlist

memberlist:
  node_name: pcw-store-gw
  join_members: ["10.1.0.16:7946"]
  bind_port: 7960
```
7. start 1 querier
```
multitenancy_enabled: false
target: querier

server:
  http_listen_port: 9200
  grpc_listen_port: 9300
  log_level: info

memberlist:
  node_name: pcw-querier
  join_members: ["10.1.0.16:7946"]
  bind_port: 7961
```

And few minutes later, the ingester will stop with an error

#### Environment
- Infrastructure: 
   - VM 4vCPU / 8Gb Mem 
   - OS : Ubuntu 18.04, 64bit
- Deployment tool
  - binary

### Error log from ingester
```
ts=2023-02-22T07:34:33.936807328Z caller=memberlist_client.go:543 level=info msg="memberlist fast-join starting" nodes_found=1 to_join=4
ts=2023-02-22T07:34:33.938328503Z caller=memberlist_client.go:563 level=info msg="memberlist fast-join finished" joined_nodes=1 elapsed_time=1.523144ms
ts=2023-02-22T07:34:33.938360397Z caller=memberlist_client.go:576 level=info msg="joining memberlist cluster" join_members=10.1.0.16:7946
ts=2023-02-22T07:34:33.93984342Z caller=memberlist_client.go:595 level=info msg="joining memberlist cluster succeeded" reached_nodes=1 elapsed_time=1.483053ms
ts=2023-02-22T07:34:33.943476498Z caller=head.go:591 level=info user=anonymous storage=persistent msg="Replaying on-disk memory mappable chunks if any"
ts=2023-02-22T07:34:33.944555573Z caller=head.go:635 level=info user=anonymous storage=persistent msg="On-disk memory mappable chunks replay completed" duration=1.044881ms
ts=2023-02-22T07:34:33.944578776Z caller=head.go:641 level=info user=anonymous storage=persistent msg="Replaying WAL, this may take a while"
ts=2023-02-22T07:34:34.036368669Z caller=head.go:677 level=info user=anonymous storage=persistent msg="WAL checkpoint loaded"
ts=2023-02-22T07:34:34.037358955Z caller=head.go:712 level=info user=anonymous storage=persistent msg="WAL segment loaded" segment=30 maxSegment=33
ts=2023-02-22T07:34:34.037889896Z caller=head.go:712 level=info user=anonymous storage=persistent msg="WAL segment loaded" segment=31 maxSegment=33
ts=2023-02-22T07:34:34.03840054Z caller=head.go:712 level=info user=anonymous storage=persistent msg="WAL segment loaded" segment=32 maxSegment=33
ts=2023-02-22T07:34:34.038616918Z caller=head.go:712 level=info user=anonymous storage=persistent msg="WAL segment loaded" segment=33 maxSegment=33
ts=2023-02-22T07:34:34.03869509Z caller=head.go:749 level=info user=anonymous storage=persistent msg="WAL replay completed" checkpoint_replay_duration=91.82845ms wal_replay_duration=2.217453ms wbl_replay_duration=791ns total_replay_duration=95.140549ms
ts=2023-02-22T07:34:34.041002369Z caller=db.go:1746 level=info user=anonymous storage=persistent msg="Compactions disabled"
ts=2023-02-22T07:34:34.041026608Z caller=ingester.go:1791 level=info user=anonymous msg="Running compaction after WAL replay"
ts=2023-02-22T07:34:34.050175809Z caller=compact.go:700 level=info user=anonymous storage=persistent msg="write block resulted in empty block" mint=1675944000000 maxt=1675951200000 duration=9.05505ms
ts=2023-02-22T07:34:34.051851746Z caller=head.go:1246 level=info user=anonymous storage=persistent msg="Head GC completed" caller=truncateMemory duration=1.300544ms
ts=2023-02-22T07:34:34.051938926Z caller=checkpoint.go:100 level=info user=anonymous storage=persistent msg="Creating checkpoint" from_segment=30 to_segment=31 mint=1675951200000
ts=2023-02-22T07:34:34.16341091Z caller=head.go:1218 level=info user=anonymous storage=persistent msg="WAL checkpoint complete" first=30 last=31 duration=111.514881ms
ts=2023-02-22T07:34:34.163934381Z caller=ingester.go:2012 level=info msg="successfully opened existing TSDBs"
ts=2023-02-22T07:34:34.164003358Z caller=lifecycler.go:547 level=info msg="not loading tokens from file, tokens file path is empty"
ts=2023-02-22T07:34:34.164105852Z caller=lifecycler.go:576 level=info msg="instance not found in ring, adding with no tokens" ring=ingester
ts=2023-02-22T07:34:34.164201727Z caller=lifecycler.go:416 level=info msg="auto-joining cluster after timeout" ring=ingester
ts=2023-02-22T07:34:34.16425845Z caller=mimir.go:790 level=info msg="Application started"
panic: expected newly cut file to have sequence:offset 3:8, got 4:8

goroutine 353 [running]:
github.com/prometheus/prometheus/tsdb.handleChunkWriteError({0x2718400?, 0xc0019da2b8?})
        /go/src/github.com/grafana/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_append.go:1501 +0x76
github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).processJob(0xc00084e210, {0x1, 0x1, 0x1867806e744, 0x18678103614, {0x273dd00, 0xc001683260}, 0x300000008, 0x22fbd38})
        /go/src/github.com/grafana/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:138 +0xbf
github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).start.func1()
        /go/src/github.com/grafana/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:126 +0xb5
created by github.com/prometheus/prometheus/tsdb/chunks.(*chunkWriteQueue).start
        /go/src/github.com/grafana/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunks/chunk_write_queue.go:117 +0x6d
```

### slack link
- https://grafana.slack.com/archives/C039863E8P7/p1677051713029129
