### ISSUE TITLE
Querier and ruler fail to start without distributor ha-tracker kv store certificate

### ISSUE THREAD

**Issue by krajorama** [grafana/mimir#4311]
#### Describe the bug

Querier and Ruler fail to start up when Distributor HA tracker is configured with some TLS configuration.
Even though HA tracker is not used in the Querier and Ruler.

#### To Reproduce

1. Create a common YAML configuration with something like:
   ```
   distributor:
      ha_tracker:
        enable_ha_tracker: true
        kvstore:
          store: etcd
          etcd:
            tls_enabled: true
            # tls_insecure_skip_verify: true
            endpoints: [localhost:2379]
            tls_cert_path: "/etc/certs/tls_cert.cert"
            tls_key_path: "/etc/certs/tls_key.key"
            tls_ca_path: "/etc/certs/tls_ca.cert"
   ```
2. Start Querier or Ruler.

#### Expected behavior

Querier and Ruler should start normally.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Helm

#### Additional Context

Root cause: 
[Queryable](https://github.com/grafana/mimir/blob/2a58905e4f522c59969b66cef0f0135903effde7/pkg/mimir/modules.go#L889) and [Ruler](https://github.com/grafana/mimir/blob/2a58905e4f522c59969b66cef0f0135903effde7/pkg/mimir/modules.go#L895) both depend on the DistributorService.

They should not depend on the full service, because that includes the HA tracker.
