### ISSUE TITLE
error: template: mimir-distributed/templates/validate.yaml Fail to deploy mimir-distributed with helm

### ISSUE THREAD

**Issue by LeRaymy** [grafana/mimir#4391]
#### Describe the bug
While trying to install mimir-distributed with helm, an error occurs.
```
Error: template: mimir-distributed/templates/validate.yaml:182:73: executing "mimir-distributed/templates/validate.yaml" at <ne (((($calculatedConfig).store_gateway).sharding_ring).kvstore).prefix "multi-zone/">: error calling ne: incompatible types for comparison
```

#### To Reproduce

1. Write `values.yaml`

<details>
  <summary>values.yaml</summary>

```
minio:
  enabled: false
global:
  dnsService: "coredns"
metaMonitoring:
  serviceMonitor:
    enabled: true
nginx:
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: mimir.example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: mimir-tls
        hosts:
          - mimir.example.com
mimir:
  config: |
    activity_tracker:
      filepath: /data/metrics-activity.log
    alertmanager:
      data_dir: /data
      enable_api: true
      external_url: /alertmanager
    alertmanager_storage:
      backend: s3
      s3:
        access_key_id: myaccesskey
        bucket_name: mybucket
        endpoint: myendpoint
        secret_access_key: mysecretkey

    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data/tsdb-sync
      s3:
        access_key_id: myaccesskey
        bucket_name: mybucket
        endpoint: myendpoint
        secret_access_key: mysecretkey
      tsdb:
        dir: /data/tsdb
    compactor:
      data_dir: "/data"
    frontend:
      align_queries_with_step: true
      log_queries_longer_than: 10s
    frontend_worker:
      frontend_address: {{ template "mimir.fullname" . }}-query-frontend-headless.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
    store_gateway:
      sharding_ring:
        zone_awareness_enabled: true
    ingester:
      ring:
        num_tokens: 512
        zone_awareness_enabled: true
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits: 
      max_global_series_per_user: 10000000
      max_global_series_per_metric: 5000000
      max_label_names_per_series: 120
      ingestion_rate: 100000
      ingestion_burst_size: 2000000
    memberlist:
      compression_enabled: false
      join_members:
      - {{ include "mimir.fullname" . }}-gossip-ring
    ruler:
      alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.{{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}/alertmanager
      enable_api: true
      rule_path: /data
    ruler_storage:
      backend: s3
      s3:
        endpoint: myendpoint
        bucket_name: mybucket
        access_key_id: myaccesskey
        secret_access_key: mysecretkey
    runtime_config:
      file: /var/{{ include "mimir.name" . }}/runtime.yaml
    server:
      grpc_server_max_concurrent_streams: 1000

compactor:
  persistentVolume:
    size: 50Gi

distributor:
  replicas: 10

ingester:
  persistentVolume:
    size: 50Gi
  replicas: 5


chunks-cache:
  enabled: true
  replicas: 5

index-cache:
  enabled: true
  replicas: 5

metadata-cache:
  enabled: true

results-cache:
  enabled: true
  replicas: 4

querier:
  replicas: 5

query_frontend:
  replicas: 3

ruler:
  replicas: 2

store_gateway:
  persistentVolume:
    size: 50Gi
  replicas: 2
```
</details>

2. Launch helm command

```
helm upgrade --install mimir grafana/mimir-distributed -f values.yml
```
#### Expected behavior

Mimir installer on my kubernetes cluster.

#### Environment

- Infrastructure: Kubernetes, v1.24.6
- Deployment tool: helm v3.7.2
