### ISSUE TITLE
Mimirtool: `rules lint` shouldn't merge expression into a one line

### ISSUE THREAD

**Issue by d-mankowski-synerise** [grafana/mimir#4501]
#### Describe the bug
Right now running `mimirtool rules lint` causes all multi-line expression to be "compressed" into a single line, which, sometimes, drastically reduces readability.

#### To Reproduce

1. Create a file that contains an example code from Prometheues [best practices page](https://prometheus.io/docs/practices/rules/#examples):

```yaml
namespace: test-recordings
groups:
    - name: test.rules
      rules:
        - record: instance_path:request_failures_per_requests:ratio_rate5m
          expr: |2
              instance_path:request_failures:rate5m{job="myjob"}
            /
              instance_path:requests:rate5m{job="myjob"}
```

and run `mimirtool rules lint <file>`.

The output is:

```yaml
namespace: test-recordings
groups:
    - name: test.rules
      rules:
        - record: instance_path:request_failures_per_requests:ratio_rate5m
          expr: |-
            instance_path:request_failures:rate5m{job="myjob"} / instance_path:requests:rate5m{job="myjob"}
```

#### Expected behavior

Mimirtool shouldn't change anything.

#### Environment

- Infrastructure: laptop
- Deployment tool: mimirtool 2.7.0
