### ISSUE TITLE
No option to create GKE ingress instead of nginx ingress?

### ISSUE THREAD

**Issue by luvpreetsingh** [grafana/mimir#4505]
#### Describe the bug

I want to create a GKE ingress instead of nginx ingress for mimir-nginx. But I am not able to do so. The main issue is the tls config we have to provide. Check this [line](https://github.com/grafana/mimir/blob/3.0/operations/helm/charts/mimir-distributed/values.yaml#L1446)

I am providing the ssl config using ManagedCertificate from GCP and attaching it using annotations.

```
networking.gke.io/managed-certificates: mimir-cert
```

When I am not providing the tls config, my ingress gets stuck in an error state due to following error
```
  Warning  Sync    47s                   loadbalancer-controller  Error syncing to GCP: error running load balancer syncing routine: error initializing translator env: secrets "loki-nginx-tls" not found
```

#### To Reproduce

Try to launch the ingress without using the ingressClass as nginx.

1. Start Mimir (SHA or version) - Using mimir chart 3.0
2. Perform Operations(Read/Write/Others) - Just enable ingress

#### Expected behavior

I expected my ingress to be created without any issues. Since I am attaching the cert and the static IP using annotations.

#### Environment

- Infrastructure: Kubernetes using GKE
- Deployment tool: helm, chart version 3.0

### Additional Context 
Here is my nginx block,

```
  service:
    type: NodePort
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.global-static-ip-name: staging-mimir
      kubernetes.io/ingress.allow-http: "false"
      networking.gke.io/managed-certificates: mimir-cert
    hosts:
      - host: mimir.xxx.xxx -> redacted full domain name
        paths:
          - path: /api/v1/push
            pathType: ImplementationSpecific
```
