### ISSUE TITLE
Problem with DoBatch: InstancesCount 

### ISSUE THREAD

**Issue by kssrao87** [grafana/mimir#4661]
Configured mimir on kubernetes with backend to s3 by changing values.yaml file under https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml, trying to push data from prometheus to mimir.
Configuration in prometheus:
```
remote_write:
      - url: "http://mimir-distributor:8080/api/v1/push"
        send_exemplars: true
        queue_config:
          max_shards: 1
          max_samples_per_send: 5000
          capacity: 10000
          batch_send_deadline: 60s
        metadata_config:
          send: false
```
Received the below error from prometheus pod:
```
{"caller":"dedupe.go:112","component":"remote","err":"server returned HTTP status 500 Internal Server Error: DoBatch: InstancesCount <= 0","level":"warn","msg":"Failed to send batch, retrying","remote_name":"2715a6","ts":"2023-04-03T14:18:10.382Z","url":"http://mimir-distributor:8080/api/v1/push"}
```

port-forwarded `mimir-distributor` pod:

<img width="1549" alt="image" src="https://user-images.githubusercontent.com/122857484/229825393-74e22c0a-f228-42f5-954e-43dc5ddf7e18.png">

<img width="1550" alt="image" src="https://user-images.githubusercontent.com/122857484/229825220-4630a559-8cd8-4d98-bc90-6088ef016d42.png">

Distributor deployment values from values.yaml:
```
distributor:
  replicas: 1

  service:
    annotations: {}
    labels: {}

  resources:
    requests:
      cpu: 100m
      memory: 512Mi

  # Additional distributor container arguments, e.g. log level (debug, info, warn, error)
  extraArgs:
    log.level: debug

  # Pod Labels
  podLabels:
    egress-istiod: "true"
    egress-k8s-dns: "true"
    istio-egressgateway-access: "true"

  # Pod Annotations
  podAnnotations:
    mhub.istio.io/version: 1.15.5
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: 40m
    sidecar.istio.io/proxyMemory: 80Mi

  # Pod Disruption Budget
  podDisruptionBudget: {}

  # -- The name of the PriorityClass for distributor pods
  priorityClassName: null

  nodeSelector: {}
  affinity: {}

  # -- topologySpreadConstraints allows to customize part of the default topologySpreadConstraints. labelSelectors
  # is generated by the chart using the same selectors as for services.
  topologySpreadConstraints:
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway

  annotations: {}
  persistence:
    subPath:

  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 45

  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault

  # -- The SecurityContext for distributor containers
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ALL]

  strategy:
    type: RollingUpdate

  terminationGracePeriodSeconds: 60

  tolerations: []
  initContainers: []
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  env: []
  extraEnvFrom: []
```
Ingester sts values from values.yaml:
```
ingester:
  # -- Total number of replicas for the ingester across all availability zones
  # If ingester.zoneAwareReplication.enabled=false, this number is taken as is.
  # Otherwise each zone starts `ceil(replicas / number_of_zones)` number of pods.
  #   E.g. if 'replicas' is set to 4 and there are 3 zones, then 4/3=1.33 and after rounding up it means 2 pods per zone are started.
  replicas: 3

  statefulSet:
    enabled: true

  service:
    annotations: {}
    labels: {}

  # -- Optionally set the scheduler for pods of the ingester
  schedulerName: ""

  resources:
    requests:
      cpu: 100m
      memory: 512Mi

  # Additional ingester container arguments, e.g. log level (debug, info, warn, error)
  extraArgs:
    log.level: debug

  # Pod Labels
  podLabels:
    egress-istiod: "true"
    egress-k8s-dns: "true"
    istio-egressgateway-access: "true"

  # Pod Annotations
  podAnnotations:
    mhub.istio.io/version: 1.15.5
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/proxyCPU: 40m
    sidecar.istio.io/proxyMemory: 80Mi
    traffic.sidecar.istio.io/includeInboundPorts: '*'
    traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
  # -- The name of the PriorityClass for ingester pods
  priorityClassName: null

  # -- Pod Disruption Budget for ingester, this will be applied across availability zones to prevent losing redundancy
  podDisruptionBudget:
    maxUnavailable: 1

  podManagementPolicy: Parallel

  # -- NodeSelector to pin ingester pods to certain set of nodes. This is ignored when ingester.zoneAwareReplication.enabled=true.
  nodeSelector: {}
  # -- Pod affinity settings for the ingester. This is ignored when ingester.zoneAwareReplication.enabled=true.
  affinity: {}

  # -- topologySpreadConstraints allows to customize part of the default topologySpreadConstraints. labelSelectors
  # is generated by the chart using the same selectors as for services.
  # It is recommended to replace this with requiredDuringSchedulingIgnoredDuringExecution podAntiAffinity rules when
  # deploying to production.
  topologySpreadConstraints:
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway

  annotations: {}

  persistentVolume:
    # If true and ingester.statefulSet.enabled is true,
    # Ingester will create/use a Persistent Volume Claim
    # If false, use emptyDir
    #
    enabled: false

    # Ingester data Persistent Volume Claim annotations
    #
    annotations: {}

    # Ingester data Persistent Volume access modes
    # Must match those of existing PV or dynamic provisioner
    # Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
    accessModes:
      - ReadWriteOnce

    # Ingester data Persistent Volume size
    size: 2Gi

    # Subdirectory of Ingester data Persistent Volume to mount
    # Useful if the volume's root directory is not empty
    subPath: ''


    # Ingester data Persistent Volume Storage Class
    # If defined, storageClassName: <storageClass>
    # If set to "-", storageClassName: "", which disables dynamic provisioning
    # If undefined (the default) or set to null, no storageClassName spec is
    #   set, choosing the default provisioner.  (gp2 on AWS, standard on
    #   GKE, AWS & OpenStack)
    #
    # storageClass: "-"

  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 60

  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault

  # -- The SecurityContext for ingester containers
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: [ALL]

  # -- updateStrategy of the ingester statefulset. This is ignored when ingester.zoneAwareReplication.enabled=true.
  statefulStrategy:
    type: RollingUpdate

  terminationGracePeriodSeconds: 240

  tolerations: []
  initContainers: []
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  env: []
  extraEnvFrom: []

  # -- Options to configure zone-aware replication for ingester
  # Example configuration with full geographical redundancy:
  # rollout_operator:
  #   enabled: true
  # ingester:
  #   zoneAwareReplication:
  #     enabled: true
  #     topologyKey: 'kubernetes.io/hostname'  # This generates default anti-affinity rules
  #     zones:  # Zone list has to be fully redefined for modification. Update with you actual zones or skip to use logical zones only.
  #     - name: zone-a
  #       nodeSelector:
  #         topology.kubernetes.io/zone: us-central1-a
  #     - name: zone-a
  #       nodeSelector:
  #         topology.kubernetes.io/zone: us-central1-b
  #     - name: zone-c
  #       nodeSelector:
  #         topology.kubernetes.io/zone: us-central1-c
  #
  zoneAwareReplication:
    # -- Enable zone-aware replication for ingester
    enabled: false
    # -- Maximum number of ingesters that can be unavailable per zone during rollout
    maxUnavailable: 25
    # -- topologyKey to use in pod anti-affinity. If unset, no anti-affinity rules are generated. If set, the generated anti-affinity rule makes sure that pods from different zones do not mix.
    # E.g.: topologyKey: 'kubernetes.io/hostname'
    topologyKey: null
    # -- Auxiliary values for migration, see https://grafana.com/docs/mimir/latest/migration-guide/migrating-from-single-zone-with-helm/
    migration:
      # -- Indicate if migration is ongoing for multi zone ingester
      enabled: false
      # -- Exclude default zone on write path
      excludeDefaultZone: false
      # -- Enable zone-awareness, read path only
      readPath: false
      # -- Total number of replicas to start in availability zones when migration is enabled
      replicas: 0
      # -- Scale default zone ingesters to 0
      scaleDownDefaultZone: false
      # -- Enable zone-awareness, write path only
      writePath: false
    # -- Zone definitions for ingester zones. Note: you have to redefine the whole list to change parts as YAML does not allow to modify parts of a list.
    zones:
    # -- Name of the zone, used in labels and selectors. Must follow Kubernetes naming restrictions: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    - name: zone-a
      # -- nodeselector to restrict where pods of this zone can be placed. E.g.:
      # nodeSelector:
      #   topology.kubernetes.io/zone: zone-a
      nodeSelector: null
      # -- extraAffinity adds user defined custom affinity rules (merged with generated rules)
      extraAffinity: {}
    # -- Name of the zone, used in labels and selectors. Must follow Kubernetes naming restrictions: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    - name: zone-b
      # -- nodeselector to restrict where pods of this zone can be placed. E.g.:
      # nodeSelector:
      #   topology.kubernetes.io/zone: zone-b
      nodeSelector: null
      # -- extraAffinity adds user defined custom affinity rules (merged with generated rules)
      extraAffinity: {}
    # -- Name of the zone, used in labels and selectors. Must follow Kubernetes naming restrictions: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
    - name: zone-c
      # -- nodeselector to restrict where pods of this zone can be placed. E.g.:
      # nodeSelector:
      #   topology.kubernetes.io/zone: zone-c
      nodeSelector: null
      # -- extraAffinity adds user defined custom affinity rules (merged with generated rules)
      extraAffinity: {}

```
Please help me what I am missing to make `distributor` to have `InstancesCount > 0`
