### ISSUE TITLE
failed pushing to ingester: rpc error: code = Unavailable desc

### ISSUE THREAD

**Issue by kssrao87** [grafana/mimir#4677]
Configured mimir on kubernetes with backend to s3 by changing values.yaml file under https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml, trying to push data from prometheus to mimir.
Configuration in prometheus:

```
remote_write:
      - url: "http://mimir-distributor:8080/api/v1/push"
        send_exemplars: true
        queue_config:
          max_shards: 1
          max_samples_per_send: 5000
          capacity: 10000
          batch_send_deadline: 60s
        metadata_config:
          send: false
```
I am getting below errors in distributor pod:
```
ts=2023-04-06T10:59:20.115122499Z caller=logging.go:86 level=warn traceID=3a59479d32704c41 msg="POST /api/v1/push (500) 1.025143632s Response: \"failed pushing to ingester: rpc error: code = Unavailable desc = \\n\" ws: false; Content-Encoding: snappy; Content-Length: 191268; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.41.0; X-B3-Sampled: 0; X-B3-Spanid: e9280764f0383de2; X-B3-Traceid: ec00ea61f73f1945e9280764f0383de2; X-Envoy-Attempt-Count: 1; X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/default/sa/mimir;Hash=764146542e7122999e3e9c24821bceebee232d1d85f277d33a2c636d26977e95;Subject=\"\";URI=spiffe://cluster.local/ns/default/sa/prometheus; X-Forwarded-Proto: http; X-Prometheus-Remote-Write-Version: 0.1.0; X-Request-Id: ee523541-8559-42ef-8f99-e0f98d8aa73f; "
ts=2023-04-06T10:59:26.258320074Z caller=logging.go:86 level=warn traceID=359fb19ef292d359 msg="POST /api/v1/push (500) 1.128399928s Response: \"failed pushing to ingester: rpc error: code = Unavailable desc = \\n\" ws: false; Content-Encoding: snappy; Content-Length: 191268; Content-Type: application/x-protobuf; User-Agent: Prometheus/2.41.0; X-B3-Sampled: 0; X-B3-Spanid: ac60ee0a44215292; X-B3-Traceid: 7a1bf02b69a4df05ac60ee0a44215292; X-Envoy-Attempt-Count: 1; X-Forwarded-Client-Cert: By=spiffe://cluster.local/ns/default/sa/mimir;Hash=764146542e7122999e3e9c24821bceebee232d1d85f277d33a2c636d26977e95;Subject=\"\";URI=spiffe://cluster.local/ns/default/sa/prometheus; X-Forwarded-Proto: http; X-Prometheus-Remote-Write-Version: 0.1.0; X-Request-Id: a82c9c60-8001-4bea-afb3-23d04314f1a0; "

```
Please help me to solve the above problem.
