### ISSUE TITLE
Add tenant_id to metric_relabel_configs 

### ISSUE THREAD

**Issue by sepich** [grafana/mimir#4692]
#### Is your feature request related to a problem? Please describe.

Sometimes there is need to enforce label usage per-tenant. For example we have semi-thrust environment where multiple teams push metrics to separate mimir tenants, but reads are global and all metrics are accessible. But at the same time we want to still have separate `team` label (or enforce it's prefix).

#### Describe the solution you'd like

It seems `metric_relabel_configs` is the great place to make such enforcement happen: https://github.com/grafana/mimir/issues/1809
But unfortunately it does not have `userID` passed through:
https://github.com/grafana/mimir/blob/92a468898ed0029d2997af2c58d06778b8989b5c/pkg/distributor/distributor.go#L821
Would be great to have it there as some `__meta_tenant_id` or `__tmp_tenant_id` label:
https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config
> Additional labels prefixed with __meta\_ may be available during the relabeling phase. They are set by the service discovery mechanism that provided the target and vary between mechanisms.
Labels starting with __ will be removed from the label set after target relabeling is completed.
If a relabeling step needs to store a label value only temporarily (as the input to a subsequent relabeling step), use the __tmp label name prefix. This prefix is guaranteed to never be used by Prometheus itself.

Example of enforcing `team` label prefix(so tenant `team-a` cannot push metrics with `team=project-b-1`:
```yaml
metric_relabel_configs:
- source_labels: [__meta_tenant_id, team]
  regex: team-a;project-a-.*|team-b;project-b-.*
  target_label: __tmp_keep
  replacement: true
- action: keep
  source_labels: [__tmp_keep]
  regex: true
```

#### Describe alternatives you've considered

Alternative is to use http-proxy inspecting remote-write labels before mimir, something like 
https://github.com/blind-oracle/cortex-tenant
But that obviously would consume more resources, and add one more point of failure

#### Additional context

I can draft the MR, if it is ok
