### ISSUE TITLE
OpenShift route to service mismatch

### ISSUE THREAD

**Issue by BigGold1310** [grafana/mimir#4727]
#### Describe the bug
Mismatch between OpenShift Route and Service declarations. This mismatch causes the application to be stated as unavailable.

#### To Reproduce

1. Start Mimir (mimir-distributed 4.3.0 helm chart)
2. Values: 
```
        gateway:
          enabledNonEnterprise: true
          replicas: 3
          route:
            enabled: true
            host: mimir01.example.com
          annotations:
            argocd.argoproj.io/sync-wave: "5"
          nginx:
            image:
              registry: docker.io
              repository: nginx
              tag: latest
            config:
              resolver: dns-default.openshift-dns.svc.cluster.local
```
3. Try to access the route mimir01.example.com

#### Expected behavior

A reachable application

#### Environment

- Infrastructure: OpenShift
- Deployment tool: helm
