### ISSUE TITLE
Im receiving repeated data 5 min after the data has stopped.

### ISSUE THREAD

**Issue by David-aylward** [grafana/mimir#4769]
Hi,

I'm using Telegraf to send data to Mimir via the HTTP plugin using the Prometheus remote write option. When the data stops sending from Telegraf I get the last entry repeated 5 times in Mimir (viewed via Grafana) before the data stops.

I expect to see the last data point once in Mimir and not repeated 5 times.

This happens for any metric sent from Telegraf to Mimir.

Data Flow
1. Edge telegraf sends influx line protocol to central telegraf.
2. Data is sent from the central telegraf as Prometheus remote write to Nginx.
3. Nginx load balances to 3 Mimir hosts.
4. The 3 Mimir hosts send to one Minio storage.

[Edge Telegraf's] ----> [Central telegraf] ----> [nginx]   ----> [Mimir] ----> [Minio]

**Telegraf configs:**
```
[global_tags]
[agent]
  interval = "5s"
  round_interval = false
  metric_batch_size = 1000
  metric_buffer_limit = 1000
  flush_interval = "4s"
  precision = ""
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.http]]
  url = "http://data-load-balancer-backend-1:9009/api/v1/push"
  data_format = "prometheusremotewrite"
  username = "*****"
  password = "******"
  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
     X-Scope-OrgID = "****"

[[inputs.influxdb_listener]]
service_address = "0.0.0.0:8086"
  read_timeout = "60s"
  write_timeout = "60s"
  [inputs.influxdb_listener.tags]
     zone = "****"
```
**Mimir Configs:**
```

target: all

blocks_storage:
  backend: s3
  s3:
    endpoint: 10.1*.*.*:9000
    bucket_name: mimir-blocks
    access_key_id: mimir
    secret_access_key: "****"
    insecure: true
  tsdb:
    dir: /data/ingester


memberlist:
  join_members: [ 10.1*.*.*, 10.1*.*.*, 10.1*.*.*]
  tls_enabled: true
  tls_insecure_skip_verify: true
  tls_cert_path: /etc/server.crt
  tls_key_path: /etc/server.key
ruler:
  rule_path: /data/ruler
  alertmanager_url: http://127.0.0.1:8080/alertmanager
  ring:
    heartbeat_period: 5s
    heartbeat_timeout: 15s
  ruler_client:
    tls_enabled: true
    tls_insecure_skip_verify: true

  query_frontend:
    grpc_client_config:
      tls_enabled: true
      tls_insecure_skip_verify: true

ruler_storage:
  backend: s3
  s3:
    endpoint: 10.1*.*.*:9000
    bucket_name: mimir-ruler
    access_key_id: mimir
    secret_access_key: "****"
    insecure: true

alertmanager:
  data_dir: /data/alertmanager
  fallback_config_file: /etc/alertmanager-fallback-config.yaml
  external_url: http://localhost:9009/alertmanager

alertmanager_storage:
  backend: s3
  s3:
    endpoint: 10.1*.*.*:9000
    bucket_name: mimir-alertmanager
    access_key_id: mimir
    secret_access_key: "****"
    insecure: true

ingester:
  ring:
    replication_factor: 2
  instance_limits:
    max_inflight_push_requests: 0

ingester_client:
  grpc_client_config:
    tls_enabled: true
    tls_insecure_skip_verify: true

limits:
  compactor_blocks_retention_period: 360d
  max_global_series_per_metric: 0
  out_of_order_time_window: 4h
  max_global_series_per_user: 0

querier:
  store_gateway_client:
    tls_enabled: true
    tls_insecure_skip_verify: true

frontend:
  grpc_client_config:
    tls_enabled: true
    tls_insecure_skip_verify: true

frontend_worker:
  grpc_client_config:
    tls_enabled: true
    tls_insecure_skip_verify: true

query_scheduler:
  grpc_client_config:
    tls_enabled: true
    tls_insecure_skip_verify: true

server:
  http_listen_port: 9009
  http_listen_address: 127.0.0.1
  log_level: info
  grpc_tls_config:
    cert_file: /etc/server.crt
    key_file: /etc/server.key
    client_auth_type: NoClientCert

```
