### ISSUE TITLE
[Feature request] IRSA for Mimir s3 authentication

### ISSUE THREAD

**Issue by rpartapsing** [grafana/mimir#4914]
Currently the Mimir helm only allows IAM user credentials who have the correct bucket policy. like so:
```
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-west-1.amazonaws.com
          region: eu-west-1
          secret_access_key: "${mimir_aws_secret_access_key}" # This is a secret injected via an environment variable
          access_key_id: "${mimir_aws_access_key}" # This is a secret injected via an environment variable
```

Since we do not allow users in our AWS account, we would like to add a role based authentication method:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

Could you please take this up in your next release?
Will this also have support for the Azure analog then?

Best wishes,
Rakesh

**Comment by dimitarvdimitrov** [comment]
how would role-based authentication look like for the helm chart? In other words, how will you configure it? Is there any environment variable that the chart should pick up?

**Comment by yafanasiev** [comment]
Mimir already supports IRSA. Just omit `secret_access_key` and `access_key_id`, and AWS SDK will pick up any credentials provided. For the official `mimir-distributed` Helm chart you would have following values:

```yaml
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "<role_arn>"
 ```

**Comment by rpartapsing** [comment]
@yafanasiev . That does not work. I tried it already before. Now again:

helm is now
```
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-west-1.amazonaws.com
          region: eu-west-1
```

Sa is defined as:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<my_account>:role/k8s-dev-aws-dsh-mimir_role
    meta.helm.sh/release-name: grafana-mimir
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: grafana-mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.7.1
    helm.sh/chart: mimir-distributed-4.3.0
    helm.toolkit.fluxcd.io/name: grafana-mimir
    helm.toolkit.fluxcd.io/namespace: flux-system
  name: mimir-sa
  namespace: monitoring
```

I restarted the working ruler deployment so that the new config would take effect.
Got error:
```
ts=2023-05-04T09:15:11.007010535Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="2 errors: blocks storage: unable to successfully send a request to object storage: Access Denied; ruler storage: unable to successfully send a request to object storage: Access Denied"
```

**Comment by rpartapsing** [comment]
![Capture](https://user-images.githubusercontent.com/59692703/236163340-cfb1e123-f2c8-4040-832e-bf6168fad9a7.JPG)
here is a screenshot of the role

**Comment by yafanasiev** [comment]
@rpartapsing IRSA itself certainly works, we are using it in our setup without any issues. Most likely there are some issues with your configs. Make sure your Helm values are at least 

```yaml
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.us-east-1.amazonaws.com
          region: us-east-1
          bucket_name: "<bucket_name>"
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "<role_arn>"
```

changing region accordingly. In your values  `bucket_name` is missing. Also, if you are looking to use S3 with ruler, it is configured separately via https://grafana.com/docs/mimir/v2.7.x/references/configuration-parameters/#ruler_storage. I would also recommend checking if IRSA is configured correctly and Mimir pods are injected with required AWS environment variables and volumes.

**Comment by rpartapsing** [comment]
@yafanasiev thank you for your help so far.

I didnt post the complete block sorry (also now with `bucket_name` included):
```
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-west-1.amazonaws.com
          region: eu-west-1
          bucket_name: mimir-k8s-dev-aws-dsh
    blocks_storage:
      s3:
        endpoint: s3.eu-west-1.amazonaws.com
        region: eu-west-1
        bucket_name: mimir-k8s-dev-aws-dsh
    alertmanager_storage:
      storage_prefix: alertmanager
      s3:
        bucket_name: mimir-k8s-dev-aws-dsh
    ruler_storage:
      storage_prefix: ruler
      s3:
        endpoint: s3.eu-west-1.amazonaws.com
        region: eu-west-1
        bucket_name: mimir-k8s-dev-aws-dsh
```

Which container to check best if the the structuredConfig has taken affect? I guess the store-gateway ones?
For all the pods I could see injection like:
```
    Environment:
      AWS_STS_REGIONAL_ENDPOINTS:   regional
      AWS_DEFAULT_REGION:           eu-west-1
      AWS_REGION:                   eu-west-1
      AWS_ROLE_ARN:                 arn:aws:iam::<my_account>:role/k8s-dev-aws-dsh-mimir_role
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /active-query-tracker from active-queries (rw)
      /data from storage (rw)
      /etc/mimir from config (rw)
      /var/mimir from runtime-config (rw)
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-s4frb (ro)
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400

```
However I would also have expected AWS_ACCESS_KEY_ID in there with the non-role-based setup?
Do you notice any peculiar settings with respect to yours? 

w.r.t to Sa settings in helm I have:
```
serviceAccount:
  # -- Whether to create a service account or not. In case 'create' is false, do set 'name' to an existing service account name.
  create: true
  # -- Override for the generated service account name.
  name: mimir-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${PlatformAwsAccountId}:role/${platformName}-mimir_role
```
Which resulted in the above sa which points to the above role in the screenshot.
Restarted the ruler and store gateways, still not working unfortunately.
