### ISSUE TITLE
values.yaml not being read by mimir-distributed

### ISSUE THREAD

**Issue by LSparkzwz** [grafana/mimir#4952]
Hello, I'm trying to install mimir-distributed as a dependency through helm install:
`helm install [main chart name] [path] -n [namespace] -f values.yaml`

But the configurations given in the values.yaml are not reflected into the helm install.
In particular I have this in my values.yaml:

```
minio:
  enabled: false

mimir:
  structuredConfig: ...
```

But when I install/upgrade I still see minio getting deployed and the mimir configuration doesn't change either (I'm trying to point it towards an s3 object storage).

Other helm chart dependencies that use that same values.yaml (for example Prometheus) manage to probably get their respective values.
What am I doing wrong?

**Comment by LSparkzwz** [comment]
I just made a test with only mimir-distributed in the chart dependencies:
```
apiVersion: v2
name: testname
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: 0.1.0

dependencies:
- name: mimir-distributed
  version: "4.3.1"
  repository: "@grafana"
```

Using the small.yaml values file found in this repository except I added this:
```
global:
  env: envtest
```

I still see minio getting deployed despite the small.yaml having it disabled.
I hope this gives more info on the nature of the problem.

**Comment by dimitarvdimitrov** [comment]
When you are using mimir as a subchart you should also nest all its values under `mimir-distributed` (the `name` of the dependency in the Chart.yaml). Can you confirm that with values below minio still installs?

```yaml
mimir-distributed:
  minio:
    enabled: false
```
