### ISSUE TITLE
Grafana datasource unable to read metrics when using an Object Storage

### ISSUE THREAD

**Issue by LSparkzwz** [grafana/mimir#4961]
Hello,
my Mimir is currently connected to a s3 object storage and writing on it seems to work:
I have two different Prometheus that write to Mimir through these remote writes:
```
      remoteWrite:
      - url: http://[testname]-mimir-nginx.[testname].svc:80/api/v1/push
        headers:
          X-Scope-OrgID: [env1 for Prom 1, env2 for Prom 2]
```
So Mimir writes on the object storage like this:
![image](https://github.com/grafana/mimir/assets/48359499/4a3f1b45-8595-485a-b121-77a34e29d14d)

My problem is that my dashboard metrics on Grafana are empty despite despite being visible if I use Prometheus directly as datasource (so I assume this is not a Prometheus/Exporter/Dashboard issue).

My data sources for Mimir are like this:
`http://[testname]-mimir-nginx.[testname].svc:80/prometheus`
With custom header X-Scope-OrgID with either values env1 or env2.

Besides setting up the object storage and disabling minio like described in the documentation I haven't changed the default Mimir configurations.
The query frontend logs show me that they're receiving Grafana's query but returning nothing.

What am I doing wrong here?
