### ISSUE TITLE
Querier don't query correct storage or ingerster.

### ISSUE THREAD

**Issue by intelroman** [grafana/mimir#4972]
#### Describe the bug
Missing data when query ingerster and storage however data reaper after 10 - 12h .
No error in compactor/ ingerster / distributors or querier.

#### To Reproduce
Deploy via docker compose mimir: https://github.com/grafana/mimir/tree/main/development/mimir-microservices-mode

.config/mimir.yaml  config diff from http://localhost:8007/config?mode=diff
```
activity_tracker:
    filepath: /activity/query-frontend-8007
alertmanager:
    fallback_config_file: ./config/alertmanager.yaml
    sharding_ring:
        heartbeat_period: 5s
        heartbeat_timeout: 15s
        kvstore:
            consul:
                host: consul:8500
alertmanager_storage:
    backend: s3
    s3:
        access_key_id: '********'
        bucket_name: mimir-alertmanager
        endpoint: '********'
        http:
            insecure_skip_verify: true
        secret_access_key: '********'
blocks_storage:
    backend: s3
    bucket_store:
        chunks_cache:
            backend: memcached
            memcached:
                addresses: dns+memcached:11211
        consistency_delay: 5s
        index_cache:
            backend: memcached
            memcached:
                addresses: dns+memcached:11211
        metadata_cache:
            backend: memcached
            memcached:
                addresses: dns+memcached:11211
        sync_dir: /tmp/mimir-tsdb-querier
        sync_interval: 1m0s
    s3:
        access_key_id: '********'
        bucket_name: mimir-tsdb
        endpoint: '********'
        http:
            insecure_skip_verify: true
        secret_access_key: '********'
    tsdb:
        dir: /tmp/mimir-tsdb-ingester
        retention_period: 3h0m0s
compactor:
    cleanup_interval: 1m0s
    compaction_concurrency: 12
    compaction_interval: 30s
    consistency_delay: 1m0s
    data_dir: /tmp/mimir-compactor
    sharding_ring:
        kvstore:
            consul:
                host: consul:8500
    tenant_cleanup_delay: 1m0s
distributor:
    ring:
        kvstore:
            consul:
                host: consul:8500
frontend:
    align_queries_with_step: true
    cache_results: true
    max_outstanding_per_tenant: 100000
    parallelize_shardable_queries: true
    results_cache:
        backend: memcached
        compression: snappy
        memcached:
            addresses: dns+memcached:11211
    scheduler_address: query-scheduler:9011
ingester:
    instance_limits:
        max_inflight_push_requests: 0
    ring:
        kvstore:
            consul:
                host: consul:8500
        num_tokens: 512
        replication_factor: 1
ingester_client:
    grpc_client_config:
        grpc_compression: gzip
limits:
    compactor_block_upload_enabled: true
    compactor_partial_block_deletion_delay: 4h
    compactor_split_and_merge_shards: 6
    compactor_split_groups: 4
    ingestion_rate: 2.5e+06
    max_global_exemplars_per_user: 150000
    max_global_series_per_user: 500000
    max_total_query_length: 1y
    out_of_order_time_window: 5m
    query_sharding_max_sharded_queries: 12
    query_sharding_total_shards: 8
memberlist:
    bind_port: 10007
    join_members:
        - distributor-1:10000
    message_history_buffer_bytes: 1024000
    node_name: query-frontend
    rejoin_interval: 10s
multitenancy_enabled: false
querier:
    query_ingesters_within: 24h0m0s
query_scheduler:
    service_discovery_mode: ring
ruler:
    alertmanager_url: http://alertmanager-1:8031/alertmanager,http://alertmanager-2:8032/alertmanager,http://alertmanager-3:8033/alertmanager
    ring:
        heartbeat_period: 5s
        heartbeat_timeout: 15s
        kvstore:
            consul:
                host: consul:8500
ruler_storage:
    backend: s3
    s3:
        access_key_id: '********'
        bucket_name: mimir-ruler
        endpoint: '********'
        http:
            insecure_skip_verify: true
        secret_access_key: '********'
runtime_config:
    file: ./config/runtime.yaml
server:
    grpc_listen_port: 9007
    http_listen_port: 8007
store_gateway:
    sharding_ring:
        heartbeat_period: 5s
        heartbeat_timeout: 15s
        kvstore:
            consul:
                host: consul:8500
        replication_factor: 1
target: query-frontend
```

1. Start Mimir: Mimir, version 2.8.0 (branch: release-2.8, revision: f917e084d)
2. Perform Operations(Read/Write/Others)

#### Expected behavior

When i query with grafana i miss some data in past 1-2 days .. but after 1 day they appear . 
Example 1 day:
![image](https://github.com/grafana/mimir/assets/4648689/2ad3f0b2-7938-45c7-9a71-749b00e20d61)

Example: 7 days is populated the data
![image](https://github.com/grafana/mimir/assets/4648689/4b551f43-1e2f-4c4d-a058-27e33487077b)

#### Environment

- Infrastructure: docker compose
- Deployment tool: docker compose

#### Additional Context

It looks like composer compacted some earlier data but some data are on ingester ... 
If i modify querier config it can find data but frontend is starting do funky stuff if I pick a range  bigger than 2 days
```
querier:
    query_ingesters_within: 13h0m0s
    query_store_after: 7h0m0s
```

Any idea or hint . 
I have similar Proof of Concept with mimir monolithic mode and I don't see this issue.
