### ISSUE TITLE
app.kubernetes.io/component label wrong for zone aware deployment.

### ISSUE THREAD

**Issue by alex5517** [grafana/mimir#5018]
#### Describe the bug
When deploying Mimir distributed using the helm chart, and enabling zone awareness for ingester, it seems that the `app.kubernetes.io/component:` label is wrong in regards to the Anti affinity set on the pods.

The label set for the ingesters are: `app.kubernetes.io/component: {{ .component }}`

And the affinity is:

```yaml
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
          - key: rollout-group
            operator: In
            values:
              - {{ .component }}
          - key: app.kubernetes.io/component
            operator: NotIn
            values:
              - {{ .component }}-{{ .rolloutZoneName }}
      topologyKey: {{ .topologyKey | quote }}
```
I would have expected the label to be `app.kubernetes.io/component: {{ .component }}-{{ .rolloutZoneName }}` so that you could run ingesters on in the same zone on the same node.

Am i missing something?
If not i can create a PR.
