### ISSUE TITLE
`mimir-distributed` helm chart on GKE Autopilot - query-frontend component: `"error contacting scheduler"`

### ISSUE THREAD

**Issue by dorkamotorka** [grafana/mimir#5268]
#### Describe the bug

I'm deploying a `mimir-distributed` helm chart on the GKE Autopilot and I'm unable to get data to the Grafana dashboard. I think the issue lies in `querier` and `query-frontend` component, because they are unable to connect to the `query-scheduler`. 

- Output of `kubectl logs mimir-querier-*`:
```
ts=2023-06-17T10:52:40.448891324Z caller=scheduler_processor.go:115 level=warn msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.10.23.52:9095: i/o timeout\"" addr=10.10.23.52:9095
```

- Output of `kubectl logs mimir-query-frontend-*`:
```
ts=2023-06-17T10:53:00.15449557Z caller=frontend_scheduler_worker.go:276 level=error msg="error contacting scheduler" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.10.23.52:9095: i/o timeout\"" addr=10.10.23.52:9095
```

Although looking at the output of the `kubectl get svc` I'm able to see the `mimir-query-scheduler` service:
```
mimir-alertmanager                              ClusterIP   10.10.21.30    <none>        8080/TCP,9095/TCP                               46m
mimir-alertmanager-headless                     ClusterIP   None           <none>        8080/TCP,9095/TCP,9094/TCP                      46m
mimir-compactor                                 ClusterIP   10.10.26.101   <none>        8080/TCP,9095/TCP                               46m
mimir-distributor                               ClusterIP   10.10.25.218   <none>        8080/TCP,9095/TCP                               46m
mimir-distributor-headless                      ClusterIP   None           <none>        8080/TCP,9095/TCP                               46m
mimir-gossip-ring                               ClusterIP   None           <none>        7946/TCP                                        46m
mimir-ingester                                  ClusterIP   10.10.27.194   <none>        8080/TCP,9095/TCP                               46m
mimir-ingester-headless                         ClusterIP   None           <none>        8080/TCP,9095/TCP                               46m
mimir-querier                                   ClusterIP   10.10.18.20    <none>        8080/TCP,9095/TCP                               46m
mimir-query-frontend                            ClusterIP   10.10.28.236   <none>        8080/TCP,9095/TCP                               46m
mimir-query-scheduler                           ClusterIP   10.10.23.52    <none>        8080/TCP,9095/TCP                               46m
mimir-query-scheduler-headless                  ClusterIP   None           <none>        8080/TCP,9095/TCP                               46m
mimir-ruler                                     ClusterIP   10.10.26.179   <none>        8080/TCP                                        46m
mimir-store-gateway                             ClusterIP   10.10.29.66    <none>        8080/TCP,9095/TCP                               46m
mimir-store-gateway-headless                    ClusterIP   None           <none>        8080/TCP,9095/TCP                               46m
```

Since the `query-scheduler` component is optional I also tried, disabling it, but then I'm getting this error on the `query-frontend`:
```
Query Frontend not ready: not ready: number of queriers connected to query-frontend is 0
Query Frontend not ready: not ready: number of queriers connected to query-frontend is 0
Query Frontend not ready: not ready: number of queriers connected to query-frontend is 0
...
```

Here is my config for `Mimir-distributed` helm chart:
```
mimir:
  config: |
    usage_stats:
      installation_mode: helm

    activity_tracker:
      filepath: /active-query-tracker/activity.log

    common:
      storage:
        backend: gcs

    # Check https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend when modifying
    frontend:
      scheduler_address: mimir-query-scheduler.grafana-stack.svc:9095

    # Check https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend_worker when modifying
    frontend_worker:
      scheduler_address: mimir-query-scheduler.grafana-stack.svc:9095

    blocks_storage:
      gcs:
        bucket_name: {{ .Values.blocks_bucket_name }}

    alertmanager_storage:
      gcs:
        bucket_name: {{ .Values.alert_bucket_name }}

    ruler_storage:
      gcs:
        bucket_name: {{ .Values.ruler_bucket_name }}

minio:
  enabled: false

query_frontend:
  replicas: 1

query_scheduler:
  enabled: true
  replicas: 1

querier:
  replicas: 3

overrides_exporter:
  enabled: false

nginx:
  enabled: false
```

#### To Reproduce

1. Deploy `mimir-distributed` helm chart to GKE Autopilot

#### Expected behavior

I expect this to work, but probably there's some additional configuration that needs to be done for GKE Autopilot that is not documented or even supported.

#### Environment

- Infrastructure: GKE Autopilot Kubernetes
- Deployment tool: helm

**Comment by dorkamotorka** [comment]
NOTE: I'm deploying this helm chart using Terraform, that's why some variables like `bucket names` expect some input.

**Comment by dorkamotorka** [comment]
I've managed to push this further and resolve this issue, using this configuration:
```
mimir:
  config: |
    usage_stats:
      installation_mode: helm

    activity_tracker:
      filepath: /active-query-tracker/activity.log

    server:
      log_format: "logfmt"
      log_level: "debug"

    common:
      storage:
        backend: gcs

    multitenancy_enabled: true

    # Check https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend when modifying
    frontend:
      {{- if .Values.query_scheduler.enabled }}
      scheduler_address: {{ template "mimir.fullname" . }}-query-scheduler.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
      {{- end }}
      # Downstream URL of Mimir Querier, because some API calls just directly go to the downstream Querier
      downstream_url: http://{{ template "mimir.fullname" . }}-querier.{{ .Release.Namespace }}.svc:{{ include "mimir.serverHttpListenPort" . }}
      address: {{ template "mimir.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc
      port: {{ include "mimir.serverGrpcListenPort" . }}

    # Check https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend_worker when modifying
    frontend_worker:
      {{- if .Values.query_scheduler.enabled }}
      scheduler_address: {{ template "mimir.fullname" . }}-query-scheduler.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
      {{- else }}
      frontend_address: {{ template "mimir.fullname" . }}-query-frontend.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
      {{- end }}

    query_scheduler:
      service_discovery_mode: "dns"

    blocks_storage:
      gcs:
        bucket_name: {{ .Values.blocks_bucket_name }}

    alertmanager_storage:
      gcs:
        bucket_name: {{ .Values.alert_bucket_name }}

    ruler_storage:
      gcs:
        bucket_name: {{ .Values.ruler_bucket_name }}

minio:
  enabled: false

query_frontend:
  replicas: 1

query_scheduler:
  enabled: true
  replicas: 1

querier:
  replicas: 3

overrides_exporter:
  enabled: false

# No need for LB in front of the containers, because the Kubernetes service object itself already acts as one
nginx:
  enabled: false
```

But now I'm getting Error on the dashboard when it is querying for labels:

<img width="1512" alt="Screenshot 2023-06-18 at 2 33 02 PM" src="https://github.com/grafana/mimir/assets/48418580/549420f8-5d24-44dc-a8fe-7bcd0d26c5e2">

Also looking at the debug logs of the `query-frontend` I can see `422 HTTP error`:
```
ts=2023-06-18T12:32:59.416666612Z caller=logging.go:76 level=debug traceID=1fdcdcec4dd46123 msg="GET /prometheus/api/v1/label/__name__/values?start=1687087980&end=1687091580 (422)
```
