### ISSUE TITLE
Docs: A basic deployment to k8s that combines 2 prometheuses 

### ISSUE THREAD

**Issue by bulmust** [grafana/mimir#5428]
Thank you for your whole documentation. I have done [get-started](https://grafana.com/docs/mimir/latest/get-started/)  as a monolith system. I am newbie for micro-services and it would be great if you can add a documentation for kubernetes.

Here is my trying of mimir installation to kind without ngnix, minio etc. I have written yaml files, but probably I can not combine prometheuses into mimir.

Summary:
1. Prometheus-1 - namespace: monitoring-test1
1. Echo-server hashicorp/http-echo  - namespace: monitoring-test1 => For prometheus-1
1. Grafana - namespace: monitoring-test1
1. Prometheus-2 (namespace: monitoring-test2)
1. Echo-server hashicorp/http-echo  - namespace: monitoring-test2 => For prometheus-2
1. Mimir -  namespace: monitoring-test1

-  [This file](https://gist.github.com/bulmust/938629f4d41d3b767482ea000a24e20c) installs 1, 2, 3
- [This file](https://gist.github.com/bulmust/8e0807da365296f23376a1eb04c7befe) installs 4, 5
- Mimir installation is following:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: monitoring-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.8.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: mimir-config
              mountPath: /etc/mimir
      volumes:
      - name: mimir-config
        configMap:
          name: mimir-config
         
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: monitoring-test-1
data:
  mimir.yml: |
    mimir:
      prometheuses:
        - name: prometheus-1
          url: http://prometheus-1:9090/
        - name: prometheus-2
          url: http://prometheus-2:9090/
      merge:
        - match:
            metric: "*"
          sources: ["prometheus-1", "prometheus-2"]
---
apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: monitoring-test-1
spec:
  selector:
    app: mimir
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31113
```

**Comment by dimitarvdimitrov** [comment]
Thanks for opening this issue. Have you seen the mimir-distributed getting started article? https://grafana.com/docs/helm-charts/mimir-distributed/latest/get-started-helm-charts/ It aims to get a similar setup, but without the scraping prometheis. We may be able to extend the helm tutorial to be more complete if it's missing something.

**Comment by bulmust** [comment]
Yes. I know helm charts and it works great with various features thank you. The only thing that I want is the scraping prometheis from Mimir. As you can see my Mimir configuration, I struggle to create ingesters. Also, as I understand that prometheus should remote write to Mimir.

**Comment by bulmust** [comment]
Okay, I solved the problem using prometheus remoteWrite option.

1. Create following overriding `values.yaml`.

```yaml
prometheus:
  service:
    nodePort: 30110
    type: NodePort
  prometheusSpec:
    enableRemoteWriteReceiver: false
    remoteWrite:
      - url: http://mimir-nginx.monitoring.svc:80/api/v1/push
        headers:
          X-Scope-OrgID: cluster1

grafana:
  additionalDataSources:
    - name: Mimir
      type: prometheus
      access: proxy
      orgId: 1
      url: http://mimir-nginx.monitoring.svc:80/prometheus
      editable: true
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
      secureJsonData:
        httpHeaderValue1: "cluster1"
  defaultDashboardsTimezone: Asia/Istanbul
  adminPassword: prom-operator
  service:
    nodePort: 30111
    type: NodePort
```

1. Install this it with using helm: `helm install prom-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace -f values.yaml`
2. Install Mimir using helm: `helm install mimir grafana/mimir-distributed -n monitoring`
3. Patch mimir-distributor service as a NodePort service: `kubectl patch svc mimir-distributor -n monitoring -p '{"spec": {"type": "NodePort"}}'`
3. Check port: `kubectl get svc -n monitoring | grep mimir-distributor`
4. Browse mimir-distrubtor users: [http://[node-ip]:[mimir-distributor-port]/distributor/all_user_stats](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport)
5. You will see that prometheus is sending metrics to mimir.
6. If you navigate Grafana datasources, you can see metrics in Mimir.
7. After some time, You can see metrics in mimir-console.
