### ISSUE TITLE
Alertmanager CPU consumption

### ISSUE THREAD

**Issue by kelt1k** [grafana/mimir#5497]
#### Describe the bug
We are using mimir Alertmanager as central alerting system for few k8s clusters (for now it's about 8 clusters)
We are running it in distributed mode with 3 replicas using zone-awarnes 
Alertmanager connected to grafana as datasource and during requesting Alerting->Groups Alertmanager returns an error 
```
Error loading notifications
Failed to process the request to the alertmanager
```
alertmanager instance logs look like this 
```
ts=2023-07-13T18:01:31.379225857Z caller=logging.go:111 level=warn traceID=19fba9cdefa2d844 msg="GET /alertmanager/api/v2/alerts/groups (500) 2.001202777s Response: \"Failed to process the request to the alertmanager\\n\" ws: false; Accept-Encoding: gzip; Connection: close; User-Agent: Grafana/9.5.1; X-Grafana-Referer: ; X-Scope-Orgid: anonymous; "
```
at the same time CPU load on all instances look like this 

```
Every 2.0s: kubectl top pods | grep alert                                 MBP-Maksym-Babenko.local: Thu Jul 13 21:03:18 2023

mimir-distributed-alertmanager-zone-a-0                 2217m        440Mi
mimir-distributed-alertmanager-zone-b-0                 2355m        472Mi
mimir-distributed-alertmanager-zone-c-0                 4057m        514Mi
``` 

Current config: 

``` 
alertmanager:
    data_dir: /data
    retention: 120h0m0s
    external_url: /alertmanager
    poll_interval: 15s
    max_recv_msg_size: 1048576000
    sharding_ring:
        kvstore:
            store: memberlist
            prefix: alertmanagers/
            consul:
                host: localhost:8500
                acl_token: ""
                http_client_timeout: 20s
                consistent_reads: false
                watch_rate_limit: 1
                watch_burst_size: 1
                cas_retry_delay: 1s
            etcd:
                endpoints: []
                dial_timeout: 10s
                max_retries: 10
                tls_enabled: false
                tls_cert_path: ""
                tls_key_path: ""
                tls_ca_path: ""
                tls_server_name: ""
                tls_insecure_skip_verify: false
                tls_cipher_suites: ""
                tls_min_version: ""
                username: ""
                password: ""
            multi:
                primary: ""
                secondary: ""
                mirror_enabled: false
                mirror_timeout: 2s
        heartbeat_period: 15s
        heartbeat_timeout: 1m0s
        instance_id: mimir-distributed-alertmanager-zone-a-0
        instance_interface_names:
            - eth0
        instance_port: 0
        instance_addr: ""
        instance_enable_ipv6: false
        replication_factor: 3
        zone_awareness_enabled: true
        instance_availability_zone: zone-a
    fallback_config_file: /configs/alertmanager_fallback_config.yaml
    peer_timeout: 15s
    enable_api: true
    max_concurrent_get_requests_per_tenant: 0
    alertmanager_client:
        remote_timeout: 2s
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: ""
        rate_limit: 0
        rate_limit_burst: 0
        backoff_on_ratelimits: false
        backoff_config:
            min_period: 100ms
            max_period: 10s
            max_retries: 10
        tls_enabled: false
        tls_cert_path: ""
        tls_key_path: ""
        tls_ca_path: ""
        tls_server_name: ""
        tls_insecure_skip_verify: false
        tls_cipher_suites: ""
        tls_min_version: ""
    persist_interval: 15m0s
    enable_state_cleanup: true
``` 

#### To Reproduce

1. Start Mimir (grafana/mimir:2.9.0)
2. Perform Operations(Read/Write/Others)

#### Expected behavior

return alerts list 

#### Environment

- Infrastructure: [e.g., Kubernetes]
- Deployment tool: [e.g., helm + kustomize]
