### ISSUE TITLE
panic: runtime error: index out of range in the ingester with native histograms

### ISSUE THREAD

**Issue by aptomaKetil** [grafana/mimir#5576]
#### Describe the bug
Ingesting native histograms can cause a panic in `counterResetInAnyBucket` which then corrupts the WAL.

#### To Reproduce

1. Start Mimir ([r248-c7fbeb7](https://hub.docker.com/layers/grafana/mimir/r248-c7fbeb7/images/sha256-2b0466138fad258a445bb8a7cd271e5df3088afefdc87f5d0bfaa7b14f50fb75?context=explore))
2. Start OTEL Collector ([8a4348cb009d1448dc647f2bdad27304b8ce53d3](https://hub.docker.com/layers/otel/opentelemetry-collector-contrib-dev/8a4348cb009d1448dc647f2bdad27304b8ce53d3/images/sha256-f086dafb0545da52d8ede77d5a355dafb63c2bb1ad9ff801245abca672d6fe66?context=explore))
3. Generate exponential histograms via OTEL client libs, push these to the collector and have the collector write them to Mimir via the `prometheusremotewrite` exporter as native histograms.

#### Expected behavior

No panics.

#### Environment

- Infrastructure: kubernetes
- Deployment tool: helm

#### Additional Context

I decided to kick the tires on the histogram downsampling (from https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/24026), as we'd like to start using these from the OTEL libs. Reconfiguring the collector to write downsampled native histograms immediately led to the below error in the mimir ingesters. After restarting I then got the same error during WAL replay. Ended up having to wipe the WALs completely. I see there has been a previous PR for `counterResetInAnyBucket` which looks very similar in https://github.com/prometheus/prometheus/pull/12357.

Logs:

```
2023-07-24 10:37:12	panic: runtime error: index out of range [2] with length 2
2023-07-24 10:37:12
2023-07-24 10:37:12	goroutine 1212 [running]:
2023-07-24 10:37:12	github.com/prometheus/prometheus/tsdb/chunkenc.counterResetInAnyBucket({0x405595bd20?, 0xa624e0?, 0x4000e9bc48?}, {0x40584a9330?, 0x40584acd00?, 0x1898705c49c?}, {0x405595bd10?, 0x26e6ca0?, 0x400138e000?}, {0x40584a4558?, ...})
2023-07-24 10:37:12		/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go:423 +0x130
2023-07-24 10:37:12	github.com/prometheus/prometheus/tsdb/chunkenc.(*HistogramAppender).Appendable(0x4056129c20, 0x40584d65a0)
2023-07-24 10:37:12		/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/histogram.go:309 +0x1c4
2023-07-24 10:37:12	github.com/prometheus/prometheus/tsdb.(*memSeries).appendHistogram(0x4055e5aea0, 0x1898705c49c, 0x40584d65a0, 0x0, {{0x26e6ca0?, 0x400138e000?}, 0x0?, 0x0?})
2023-07-24 10:37:12		/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_append.go:1197 +0x1d4
2023-07-24 10:37:12	github.com/prometheus/prometheus/tsdb.(*walSubsetProcessor).processWALSamples(0x40051ba158, 0x4000d6f000, 0x0?, 0x0?)
2023-07-24 10:37:12		/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_wal.go:627 +0x4e0
2023-07-24 10:37:12	github.com/prometheus/prometheus/tsdb.(*Head).loadWAL.func2(0x403ebf2d88?)
2023-07-24 10:37:12		/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_wal.go:106 +0x48
2023-07-24 10:37:12	created by github.com/prometheus/prometheus/tsdb.(*Head).loadWAL
2023-07-24 10:37:12		/__w/mimir/mimir/vendor/github.com/prometheus/prometheus/tsdb/head_wal.go:105 +0x23c
```

**Comment by aptomaKetil** [comment]
Can confirm that this also happens with mimir v2.9.0 and otel collector v0.82.0. Pushing downsampled native histograms to mimir eventually triggers this error, which causes the ingester to crash. It will then continue to crash on startup until the WAL is wiped. Every time I've tried upgrading to collector v0.82.0 to make use of the downscaling, this issue appears within 24hrs. We're producing native histograms via OTEL client libs (js/node), and the spanmetrics connector in the otel collector.

**Comment by krajorama** [comment]
Hi, I've started to work on reproduction, is a very basic otel collector configuration such as the one in https://github.com/grafana/mimir/pull/5968/files sufficient? (I'll keep working at it, but don't want to go down the wrong path.)

**Comment by krajorama** [comment]
@aptomaKetil Hi, do you still have this problem? Is there any chance you could share a corrupt WAL I could analyze? I've got a simple setup going with random observations generator 0m - 5m observing into a scale 20 exponential histogram -> otel collector -> remote write -> mimir 2.9. But so far nothing.

**Comment by aptomaKetil** [comment]
Hi @krajorama I'll fire up a dev-cluster on 2.9 and see if I can still reproduce.

**Comment by aptomaKetil** [comment]
I can still reproduce with 2.9 and collector 0.84. I've kept the broken WAL (~135MB zipped), and can share it in private if you can suggest a sensible way of doing so. Pasting my collector config, I've removed all trace-stuff for brevity:

```yaml
exporters:
  prometheusremotewrite:
    auth:
      authenticator: basicauth/mimir
    endpoint: <snip>
    target_info:
      enabled: false
extensions:
  basicauth/mimir:
    client_auth:
      password: ${mimir_password}
      username: ${mimir_username}
  health_check: {}
  memory_ballast:
    size_in_percentage: 40
processors:
  batch: {}
  filter:
    error_mode: ignore
    metrics:
      metric:
      - Len(data_points) == 0
  k8sattributes:
    extract:
      labels:
      - from: pod
        key: app.kubernetes.io/name
        tag_name: __app
      - from: pod
        key: app
        tag_name: __app
      - from: pod
        key: k8s-app
        tag_name: __app
      - from: pod
        key: app.kubernetes.io/version
        tag_name: __version
      metadata:
      - k8s.namespace.name
      - k8s.pod.name
      - k8s.node.name
    pod_association:
    - sources:
      - from: connection
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resource:
    attributes:
    - action: upsert
      from_attribute: __app
      key: service.name
    - action: upsert
      from_attribute: __version
      key: service.version
    - action: insert
      from_attribute: k8s.pod.name
      key: service.instance.id
    - action: insert
      from_attribute: k8s.namespace.name
      key: service.namespace
    - action: insert
      from_attribute: k8s.node.name
      key: host.name
  transform:
    error_mode: ignore
    metric_statements:
    - context: datapoint
      statements:
      - set(attributes["cluster"], resource.attributes["deployment.environment"])
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
service:
  extensions:
  - health_check
  - basicauth/mimir
  pipelines:
    metrics:
      exporters:
      - prometheusremotewrite
      processors:
      - memory_limiter
      - filter
      - k8sattributes
      - resource
      - transform
      - batch
      receivers:
      - otlp

```
