### ISSUE TITLE
Support default authentication methods of the AWS SDK

### ISSUE THREAD

**Issue by AljoschaP** [grafana/mimir#5613]
#### Is your feature request related to a problem? Please describe.

In order to be able to use [cross-account IRSA with chained AssumeRole](https://docs.aws.amazon.com/eks/latest/userguide/cross-account-access.html), I need to possibility to set the AWS profile via AWS_PROFILE environment variable. I can inject the AWS configuration but it will not be picked up even if I set the correct profile name. I assume that the `aws_sdk_auth` field of the used thanos.io/objstore library is set to false by default and there is currently no way to set it to true.

#### Describe the solution you'd like

I would love to set the aws_sdk_auth field via configuration. For example:
````
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-central-1.amazonaws.com
          region: eu-central-1
          aws_sdk_auth: true
    blocks_storage:
      s3:
        bucket_name: s3bucket

````

#### Additional context

https://github.com/thanos-io/objstore#s3
https://github.com/thanos-io/objstore/blob/d0c43443ecda0d8cffbd4d215569a0dba9ba39ec/providers/s3/s3.go#L226
https://docs.aws.amazon.com/sdk-for-go/api/aws/session/
