### ISSUE TITLE
Docs feedback: /docs/sources/mimir/operators-guide/monitor-grafana-mimir/requirements.md

### ISSUE THREAD

**Issue by johnheywardobrien** [grafana/mimir#5614]
To make sure your pod and job labels are what we expect, you could add something like:
```
          relabel_configs:
            - source_labels: ['__address__']
              target_label: 'pod'
              regex: '([^:]+)(:[0-9]+)?'
              replacement: '${1}'
            - source_labels: ['namespace', 'pod']
              target_label: 'job'
              separator: '/'
              regex: '(.+?)(-\d+)?'
              replacement: '${1}'
```
