### ISSUE TITLE
Empty results when querying metrics

### ISSUE THREAD

**Issue by CyberHippo** [grafana/mimir#5767]
#### Describe the bug
Hi, I got empty results whenever I try to retrieve data from Mimir. I can see that Prometheus correctly remote writes to Mimir and that Mimir stores its blocks on GCS. However I cannot get metrics from Mimir. I always get empty results.

I can see some errors in the querier logs:
```json
{"address":"xx.xx.xx.xx:9095","caller":"frontend_processor.go:87","err":"rpc error: code = Unavailable desc = closing transport due to: connection error: desc = \"error reading from server: EOF\", received prior goaway: code: NO_ERROR","level":"error","msg":"error processing requests","ts":"2023-08-17T09:36:28.972138358Z"}
```
But the query-frontend logs seems fine:
```json
{"caller":"handler.go:314","component":"query-frontend","estimated_series_count":0,"fetched_chunk_bytes":0,"fetched_chunks_count":0,"fetched_index_bytes":0,"fetched_series_count":0,"level":"info","method":"GET","msg":"query stats","path":"/prometheus/api/v1/metadata","query_wall_time_seconds":0.001458609,"response_time":"2.423617ms","sharded_queries":0,"split_queries":0,"status":"success","ts":"2023-08-17T09:48:29.292462799Z","user":"anonymous","user_agent":"Grafana/10.0.3"}
```

All mimir components are up and running : 
```
NAME                                    READY   STATUS    RESTARTS   AGE
mimir-compactor-0                       1/1     Running   0          68m
mimir-distributor-6f87c9c4fd-4spln      1/1     Running   0          66m
mimir-distributor-6f87c9c4fd-kxbjr      1/1     Running   0          68m
mimir-ingester-0                        1/1     Running   0          66m
mimir-ingester-1                        1/1     Running   0          68m
mimir-metadata-cache-0                  2/2     Running   0          84m
mimir-nginx-79fd9db579-5t5tg            1/1     Running   0          2d18h
mimir-nginx-79fd9db579-zssf4            1/1     Running   0          70m
mimir-querier-5449d78fc6-7sdpd          1/1     Running   0          29m
mimir-querier-5449d78fc6-rskwm          1/1     Running   0          28m
mimir-query-frontend-6b5bdb5d8b-fwnq8   1/1     Running   0          25m
mimir-query-frontend-6b5bdb5d8b-wn6t6   1/1     Running   0          24m
mimir-store-gateway-0                   1/1     Running   0          66m
mimir-store-gateway-1                   1/1     Running   0          68m
```

I used the following helm values:

```yaml
mimir:
  structuredConfig:
    server:
      log_format: json
    blocks_storage:
      backend: gcs
      gcs:
        bucket_name: <redacted>
    limits:
      max_global_series_per_user: 1000000
      ingestion_rate: 100000
      ingestion_burst_size: 150000
      compactor_blocks_retention_period: 180d
    ingester:
      ring:
        replication_factor: 1

metaMonitoring:
  dashboards:
    enabled: false
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true

compactor:
  persistentVolume:
    size: 20Gi

distributor:
  replicas: 2

ingester:
  persistentVolume:
    size: 50Gi
  replicas: 2
  rollout_operator:
    enabled: false
  zoneAwareReplication:
    enabled: false

querier:
  replicas: 2

query_frontend:
  replicas: 2

store_gateway:
  persistentVolume:
    size: 10Gi
  replicas: 2
  rollout_operator:
    enabled: false
  zoneAwareReplication:
    enabled: false

nginx:
  replicas: 2
  ingress:
    enabled: true
    [...]

gateway:
  replicas: 2

rollout_operator:
  enabled: false

overrides_exporter:
  enabled: false

admin-cache:
  enabled: false

chunks-cache:
  enabled: false

index-cache:
  enabled: false

metadata-cache:
  enabled: true

results-cache:
  enabled: false

minio:
  enabled: false

ruler:
  enabled: false

query_scheduler:
  enabled: false

alertmanager:
  enabled: false
```

Am I missing something obvious here?

#### To Reproduce

1. Start Mimir `2.9.0`
2. Perform Operations

- Get data from Mimir either via cURL or Grafana.
```bash
curl "https://<mimir-url>/prometheus/api/v1/query_range?end=1692264360&query=container_memory_usage_bytes%0A&start=1692262560&step=15"
{"status":"success","data":{"resultType":"matrix","result":[]}}
```

#### Expected behavior

I expect Mimir to return the results of my query.

#### Environment

- Infrastructure: GKE
- Deployment tool: helm

#### Additional Context

Thanks for your help.
