### ISSUE TITLE
Ruler cannot read labels defined on ALERT RULE when rendering ALERT RULE annotation template

### ISSUE THREAD

**Issue by chanjarster** [grafana/mimir#5828]
#### Describe the bug

Ruler cannot read labels defined on ALERT RULE when rendering alert rule annotation template.

#### To Reproduce

1. Start Mimir (2.9.0), enable ruler
2. Start Grafana, create an Mimir source and create an ALERT RULE

```yaml
name: test-annotation-template
labels:
  - key: nickname
    value: foo
annotations:
  - value: |-
      Render value: {{ $value }}
      Render query result label: {{ .Labels.name }}
      Render rule label: {{ .Labels.nickname }}
    key: summary
dataSourceName: mon_prometheus
type: cloud-alerting
group: test
folder: null
queries: []
condition: ''
noDataState: NoData
execErrState: Alerting
evaluateEvery: 1m
evaluateFor: 5m
namespace: test-annotation-template
expression: absent(alien{name="jack"})
forTime: 1
forTimeUnit: m
```

3. Wait for the rule trigger an alert
4. See the summary annotation, `{{ .Labels.nickname }}` renders to empty string.

![grafana-screenshot](https://github.com/grafana/mimir/assets/612413/96585132-52cb-4abb-8ad9-3465a3e1e4f9)

#### Expected behavior

Ruler can read labels defined on alert rule when trying to render annotation template

**Comment by chanjarster** [comment]
I found that this maybe is a Prometheus issue, providing the rule below directly to prometheus, will get the same result:

```yaml
groups:
- name: example
  rules:
  - alert: foo
    expr: absent(alien{name="jack"})
    for: 1s
    labels:
      name: rose
      nickname: foo
    annotations:
      summary: |-
        value: {{ .Value }}
        sample label: {{ .Labels.name }}
        rule label: {{ .Labels.nickname }}
```

As Prometheus doc says:

> Prometheus supports templating in the annotations and labels of alerts ...

but it only use sample data.
