### ISSUE TITLE
Configuring Ruler external endpoint

### ISSUE THREAD

**Issue by andreimiclea99** [grafana/mimir#5868]
#### Describe the bug
I deployed the Mimir(v. 2.7.1) stack using the helm chart on GKE 1.25, the ruler and alertmanager are working fine and alerts are sent to slack and email. However when trying GET the rules via:

"GET /ruler/rule_groups" - I receive "404 Not Found",

and the same is for:

"GET <prometheus-http-prefix>/api/v1/rules" - I receive "{"status":"success","data":{"groups":[]}}"

The ruler configs are:
```
    ruler:
      alertmanager_url: http://mimir-nginx.com/alertmanager
      enable_api: true
      rule_path: /data
```
When it comes to the "external_url" I tried set it but with same result or maybe i didn't understand how it should be configured.

The logs of ruler look ok and the communication with the alertmanager is working fine.
