### ISSUE TITLE
[Mimir-distributed] Meta Monitoring Grafana Agent doesn't allow readOnlyRootFilesystem

### ISSUE THREAD

**Issue by j-sokol** [grafana/mimir#5912]
#### Describe the bug
When enabling `readOnlyRootFilesystem` on the Meta monitoring Grafana Agent, pod fails with error
```
grafana-agent ts=2023-09-04T09:48:42.457808398Z caller=reporter.go:106 level=info msg="failed to init seed" err="open /tmp/agent_seed.json: read-only file system"                      
grafana-agent ts=2023-09-04T09:48:42.4579028Z caller=gokit.go:72 level=info msg="=== Handler.Stop()'d ==="                                                                              
grafana-agent ts=2023-09-04T09:48:42.458234809Z caller=main.go:77 level=error msg="error running agent" err="open /tmp/agent_seed.json: read-only file system"                          
```

#### To Reproduce

1. Start Mimir (5.1.0-weekly.253)
2. Add 
``` 
      containerSecurityContext:
        readOnlyRootFilesystem: true

```
to https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml#L3008

#### Expected behavior

Grafana Agent should run successfully

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

Helm chart doesn't allow adding extraVolumes / extraVolumeMounts, using which adding a emptyDir{} mounted to /tmp whould fix the issue. Example:
``` 
apiVersion: monitoring.grafana.com/v1alpha1
kind: GrafanaAgent
spec:
  containers:
  - name: config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
  - image: docker.io/grafana/agent:v0.31.2
    name: grafana-agent
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  enableConfigReadAPI: false
  logs:
    instanceSelector:
      matchLabels:
        app.kubernetes.io/component: meta-monitoring
        app.kubernetes.io/instance: metrics
        app.kubernetes.io/name: mimir
  metrics:
    externalLabels:
      cluster: metrics
    instanceSelector:
      matchLabels:
        app.kubernetes.io/component: meta-monitoring
        app.kubernetes.io/instance: metrics
        app.kubernetes.io/name: mimir
    scrapeInterval: 60s
  serviceAccountName: metrics-mimir
  volumes:
  - emptyDir: {}
    name: tmp
```
with example above the agent runs successfully with `readOnlyRootFilesystem` enabled.

**Comment by dimitarvdimitrov** [comment]
this may be solved by #5860

**Comment by SanthoshKumar18245** [comment]
can anyone tell me how to connect the grafana-agent to mimir because i tried i couldn't do it by documentation and there is no videos about grafana mimir configuration and grafana agent .. i have installed the agent in static mode and grafana mimir in my aws ubuntu instance (in same machine)

agent.yaml

server:
log_level: info

metrics:
wal_directory: /tmp/agent
global:
scrape_interval: 60s
remote_write:
- url: http://127.0.0.1:9009/api/v1/push

integrations:
node_exporter:
enabled: true

please help me i have been trying to connect almost five days );
<img width="932" alt="git" src="https://github.com/grafana/mimir/assets/133011171/2883fc58-45a1-4bc7-8529-014be7020d1d">

**Comment by dimitarvdimitrov** [comment]
@SanthoshKumar18245 I think this question is unrelated to the issue, but try adding a tenant to the remote-write spec

```yaml
remote_write:
- url: http://127.0.0.1:9009/api/v1/push
  headers:
    X-Scope-OrgID: monitoring
```
