### ISSUE TITLE
Having the possibility to add an Opentelemetry label to Mimir metrics

### ISSUE THREAD

**Issue by MarcBostMich** [grafana/mimir#5926]
#### Is your feature request related to a problem? Please describe.

Hi guys, I have installed and set up a Grafana, Loki, Mimir and Tempo in my company with a whole data collect layer using Opentelemetry Collector.

It's been several weeks that I'm trying to find a solution for labels ingestion in Mimir but I'm still struggling with. Is there any chance that we can ingest metrics (other than target_info) with other labels than service.namespace, service.name and service.instance.id ? For example, it would be so nice if I could also have a label deployment.environment for my metrics.

In comparison, I don't have any issues with Tempo (you can create any custom label you want and it will be created on Tempo side) and for Loki I needed to use loki.resource.labels attribute processor (combined with loki exporter) to fix it. So both Tempo and Loki and working fine in adding a new label to logs and traces. For information, I'm using otlphttp exporter for Mimir.

Since now, I tried to map this deployment.environment using attribute and resource processor in OTEL without any success. I also tried to use metricstransform processor with the same result. Finally, I tried to build a metric relabel on Mimir side without more success.

#### Describe the solution you'd like

I would like to be able to add a deployment.environment label (for example) into my metrics, like it is exposed on Grafana doc:

![image](https://github.com/grafana/mimir/assets/144110875/ba0ae2af-f63f-41f7-9f67-5fd40bf3701b)

#### Describe alternatives you've considered

I tried to consider not using more labels than service ones, but some users have special needs that can't be done with only 3 labels.

#### Additional context

N/A, don't hesitate to ask if I'm not clear enough !

**Comment by mxab** [comment]
Hi,
I think I stumbled on the same issue.

After researching I think this is intentionally.
https://opentelemetry.io/docs/specs/otel/compatibility/prometheus_and_openmetrics/#info

This blog post here lines out two solutions
https://grafana.com/blog/2023/07/20/a-practical-guide-to-data-collection-with-opentelemetry-and-prometheus/#2-copy-common-resource-attributes

Either do a funky join with the target_info metric or attach them in the otel collector processing step

The only issue I had in that blog post is that in the transform part the `context` should be `datapoint` otherwise the `attributes`  are not available


If you're using grafana's agent in flow mode it kind of looks like this

```hcl
otelcol.processor.transform "prometheus" {
	
	metric_statements  {
		context = "datapoint"

		statements = [
			"set(attributes[\"deployment_environment\"], resource.attributes[\"deployment.environment\"])",
		]
	}
	output {
		metrics = [otelcol.exporter.prometheus.default.input]
	}
}
```

hope this helps

**Comment by MarcBostMich** [comment]
Hi @mxab, thank you so much for your post, this finally gave me the possibility to filter on these custom labels in Mimir !!

Till today, the workaround we had was only for SpringBoot application for which we were implementing a specific code part that was forcing Mimir to ingest these labels but we didn't have it for other applications.

For one who will wonder in the future, we are collection data through a data collection layer built with OpenTelemetry Collector. We have this Opentelemetry Collector installed as an agent on remote servers or applications and we aggregate these data into multiple gateways on which we put specific configuration.
I added the configuration you suggested in previous post in the metrics specific Opentelemetry Collector Gateway, which is the last OTEL part of the chain before reaching Mimir. Here is the configuration I made, according to what you said:

```
    processors:
       transform:
         metric_statements:
           - context: datapoint
             statements:
               - set(attributes["environment"], resource.attributes["environment"])
               - set(attributes["net_k8s_name"], resource.attributes["net.k8s.name"])
               - set(attributes["k8s_namespace_name"], resource.attributes["k8s_namespace_name"])
               - set(attributes["k8s_container_name"], resource.attributes["k8s.container.name"])
               - set(attributes["k8s_pod_name"], resource.attributes["k8s.pod.name"])
               - set(attributes["k8s_cluster_name"], resource.attributes["k8s.cluster.name"])

```

This unlocked the situation and I now have more than taret_info metrics accessible when I filter on net_k8s_name label for example.

Thank you again @mxab !!
