### ISSUE TITLE
Getting metrics with duplicated labels, one set including __replica__, but no HA configuration has been enabled.

### ISSUE THREAD

**Issue by wltbenade** [grafana/mimir#5928]
### Discussed in https://github.com/grafana/mimir/discussions/5920

Originally posted by **wltbenade** September  4, 2023

> Hey all,
> 
> I've come across from weird behaviour that I hope someone can explain to me.
> 
> I've set up Mimir using the helm-distributed Helm chart, altering nothing except structuredConfig to S3 storage, and some persistent storage parameters for the various components.
> 
> I'm making use of GrafanaAgent CRs to control my ingestion, with an additionalScrapeConfig, running 3 scrape_jobs, defined on a single MetricsInstance to federate metrics from ClusterControl, and an Integration attached to the same MetricsInstance.
> 
> What's curious is that my config seems to be producing 2 sets of metrics for everything (one with a __replica__ label, one without), EXCEPT the Integration:
> PostgreSQL coming from additionalScrapeConfig
> ```
> pg_up{__replica__="replica-0", cluster="monitoring-system/grafana-agent", clusterid="[REDACTED]", instance="[REDACTED]", job="postgres", source="clustercontrol"}
> pg_up{cluster="monitoring-system/grafana-agent", clusterid="[REDACTED]", instance="[REDACTED]", job="postgres", source="clustercontrol"}
> ```
> 
> MSSQL coming from Integration:
> ```
> mssql_build_info{agent_hostname="[REDACTED]", cluster="monitoring-system/grafana-agent", instance="[REDACTED]", job="integrations/mssql", branch="HEAD", goarch="amd64", goos="linux", goversion="go1.20.6", revision="7ff76ca4", tags="netgo,builtinassets,promtail_journal_enabled", version="v0.35.3"}
> ```
> 
> I know it's something to do with my Mimir config, as I've check the metrics/target API, and all seems well there. I should mention that I'm running with HA deduplication off, as I'm still evaluating the stack, so it's single instances all the way.
> 
> If anyone has any idea what I'm doing wrong, I would be highly appreciative!
> 
> Cheers

The more I look at the HA deduplication documentation, the more I believe this to be a bug. I have no HA deduplication configuration active, although I do have zone replication enabled on alertmanager, ingester, and store-gateway. Not sure if that's relevant, but thought I would mention it.

**Comment by wltbenade** [comment]
Adding to this, I've now redeployed Mimir-distributed with zone-aware replication completely disabled, but still finding the __replica__ label, duplicating metrics.

I've had to resort to working around this by prefacing all my queries with `{__replica__=""}` until I can find a solution. The problem still stands, as I believe this means that I'm storing double the amount of samples from my scrape_configs, because of this bug.

**Comment by 56quarters** [comment]
This doesn't sound like a Mimir bug to me. Mimir will _remove_ the `__replica__` label if HA deduplication is enabled but it won't add that label. If the label is on the series, seems like it's getting added by the Agent.

**Comment by wltbenade** [comment]
Hi @56quarters,

Thanks for your inputs. Just to confirm your theory, I've tried the following:

- Manually inspected the metrics coming in from the federated endpoints, but there's no sign of the __replica__ label on any of them.
- Disabled the following relabeling configs on the scrape_config, in case it may have an impact:
```yaml
      # relabel_configs:
        # - action: hashmod
        #   modulus: $(SHARDS)
        #   source_labels:
        #   - __address__
        #   target_label: __tmp_hash
        # - action: keep
        #   regex: $(SHARD)
        #   source_labels:
        #   - __tmp_hash
```

I'm still picking up the __replica__ label, though.

**Comment by dimitarvdimitrov** [comment]
perhaps some things to check for are 
* that HA deduplication has been enabled for that tenant (`accept_ha_samples`)
* that there is not relabelling config on the distributor configuration (could have been set per tenant as well)
* using [trafficdump](https://github.com/grafana/mimir/blob/03c4844b859d89c167ea1a04736e42679786555c/docs/internal/tools/trafficdump.md#L2-L1) to inspect the incoming TCP requests and parse them as remote-write so you can see what mimir actually receives on the wire

**Comment by wltbenade** [comment]
Hi @dimitarvdimitrov,

Thanks for the points to try.

I'm not aware of any per-tenant configs made, but I'm including a sanitised copy of my entire config, in case I've made a fundamental mistake:
```yaml
activity_tracker:
      filepath: /active-query-tracker/activity.log
    alertmanager:
      data_dir: /data
      enable_api: true
      external_url: /alertmanager
      fallback_config_file: /configs/alertmanager_fallback_config.yaml
    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager
    blocks_storage:
      backend: s3
      bucket_store:
        max_chunk_pool_bytes: 12884901888
        sync_dir: /data/tsdb-sync
      s3:
        bucket_name: mimir-blocks
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
    common:
      storage:
        backend: s3
        s3:
          access_key_id: [REDACTED]
          endpoint: mimir-s3-store-hl.mimir.svc.cluster.local:9000
          insecure: true
          secret_access_key: [REDACTED]
    compactor:
      compaction_interval: 30m
      data_dir: /data
      deletion_delay: 2h
      first_level_compaction_wait_period: 25m
      max_closing_blocks_concurrency: 2
      max_opening_blocks_concurrency: 4
      sharding_ring:
        wait_stability_min_duration: 1m
      symbols_flushers_concurrency: 4
    frontend:
      parallelize_shardable_queries: true
      scheduler_address: mimir-query-scheduler-headless.mimir.svc:9095
    frontend_worker:
      grpc_client_config:
        max_send_msg_size: 419430400
      scheduler_address: mimir-query-scheduler-headless.mimir.svc:9095
    ingester:
      ring:
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
    limits:
      ingestion_burst_size: 500000
      ingestion_rate: 100000
      max_cache_freshness: 10m
      max_global_series_per_user: 0
      max_query_parallelism: 240
      max_total_query_length: 8760h
      out_of_order_time_window: 5m
    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - dns+mimir-gossip-ring.mimir.svc.cluster.local:7946
    querier:
      max_concurrent: 16
    query_scheduler:
      max_outstanding_requests_per_tenant: 800
    ruler:
      alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.mimir-alertmanager-headless.mimir.svc.cluster.local/alertmanager
      enable_api: true
      rule_path: /data
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
    runtime_config:
      file: /var/mimir/runtime.yaml
    server:
      grpc_server_max_concurrent_streams: 1000
      grpc_server_max_connection_age: 2m
      grpc_server_max_connection_age_grace: 5m
      grpc_server_max_connection_idle: 1m
    store_gateway:
      sharding_ring:
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
        wait_stability_min_duration: 1m
    usage_stats:
      installation_mode: helm
```

I'll try and see if I can sniff the traffic coming in to see if I can pick up anything on that end.

Cheers!
