### ISSUE TITLE
bucket{le="+Inf"} and count metrics contain not equal data

### ISSUE THREAD

**Issue by misternobody** [grafana/mimir#6058]
#### Describe the bug

The metric values for request_duration_seconds_bucket{le="+Inf"} and request_duration_seconds_count differ, whereas the documentation indicates that they should be identical:

`The final bucket captures all of the measurements that were captured by the preceding bucket and any measurements that exceed the preceding bucket. The count for the +Inf <metric_name>_bucket should be equivalent to the value of the <metric_name>_count field. Both fields provide a count of all of the measurements categorized by the histogram data point as of the histogram's timestamp.`

#### To Reproduce

Compare values of 2 metrics: **<metric_name>_bucket{le="+Inf"}** and **<metric_name>_count**

For example: **sum(cortex_request_duration_seconds_bucket{le="+Inf", service="grafana-mimir-ingester", status_code="success"}) - sum(cortex_request_duration_seconds_count{status_code="success", service="grafana-mimir-ingester"}) != 0**

We did not encounter this behavior when using Victoria Metrics and Prometheus prior to migrating to the Grafana stack.

<img width="1703" alt="image" src="https://github.com/grafana/mimir/assets/1763054/d5c84384-157f-414d-9198-c8312146a267">

<img width="1685" alt="image" src="https://github.com/grafana/mimir/assets/1763054/e9ec5004-af9a-4304-9f56-65929a2d3fd2">

#### Expected behavior

The difference between `<metric_name>_bucket{le="+Inf"}` and `<metric_name>_count` values must be 0.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: Distributed Helm chart (mimir-distributed-5.1.0-weekly.248)
- Mimir Docker image: r248-c7fbeb7

#### Additional Context

There were nothing interesting in Mimir or Grafana agent logs. 

Used configuration:
```
  mimir:
    structuredConfig:
      server:
        http_server_write_timeout: 300s
        http_server_read_timeout: 300s
        http_server_idle_timeout: 300s
        grpc_server_max_recv_msg_size: 209715200
        grpc_server_max_send_msg_size: 209715200
      common:
        storage:
          backend: s3
          s3:
            region: some_aws_region
            endpoint: s3.some_aws_region.amazonaws.com
      blocks_storage:
        s3:
          bucket_name: some_aws_bucket
        bucket_store:
          max_concurrent: 10000
          index_cache:
            backend: memcached
            memcached:
              timeout: 60s
              connect_timeout: 60s
              max_idle_connections: 750
              max_async_concurrency: 100
              max_async_buffer_size: 10000000
              max_get_multi_concurrency: 750
              max_get_multi_batch_size: 1000
              max_item_size: 16777216 # 16Mb
          chunks_cache:
            backend: memcached
            memcached:
              timeout: 60s
              connect_timeout: 60s
              max_idle_connections: 750
              max_async_concurrency: 100
              max_async_buffer_size: 10000000
              max_get_multi_concurrency: 750
              max_get_multi_batch_size: 1000
              max_item_size: 16777216 # 16Mb
          metadata_cache:
            backend: memcached
            memcached:
              timeout: 60s
              connect_timeout: 60s
              max_idle_connections: 750
              max_async_concurrency: 100
              max_async_buffer_size: 10000000
              max_get_multi_concurrency: 750
              max_get_multi_batch_size: 1000
              max_item_size: 16777216 # 16Mb
      memberlist:
        cluster_label_verification_disabled: true
        cluster_label: "mimir"
      ruler_storage:
        s3:
          bucket_name: some_aws_bucket
      limits:
        ruler_max_rules_per_rule_group: 10000000
        ruler_max_rule_groups_per_tenant: 1000000
        max_global_exemplars_per_user: 1000000
        max_global_series_per_user: 0
        max_global_series_per_metric: 0
        out_of_order_time_window: 15s
        max_query_parallelism: 240
        max_cache_freshness: 10m
        max_total_query_length: 30240h
        max_fetched_chunks_per_query: 0
        ingestion_rate: 200000000
        ingestion_burst_size: 200000
        compactor_blocks_retention_period: 720h
        accept_ha_samples: true
        ha_cluster_label: cluster
        ha_replica_label: __replica__
        query_sharding_total_shards: 16
        query_sharding_max_sharded_queries: 128
        label_names_and_values_results_max_size_bytes: 419430400
        cardinality_analysis_enabled: true
        label_names_and_values_results_max_size_bytes: 512000000
      alertmanager:
        max_recv_msg_size: 209715200
        alertmanager_client:
          max_recv_msg_size: 209715200
          max_send_msg_size: 209715200
      ingester:
        ring:
          unregister_on_shutdown: false
          min_ready_duration: 120s
      store_gateway:
        sharding_ring:
          unregister_on_shutdown: false
      alertmanager_storage:
        backend: s3
        s3:
          bucket_name: some_aws_bucket
          endpoint: s3.some_aws_region.amazonaws.com
      distributor:
        max_recv_msg_size: 209715200
        ha_tracker:
          enable_ha_tracker: true
          kvstore:
            store: consul
            consul:
              host: http://consul:8500
      compactor:
        compaction_interval: 1h
        deletion_delay: 1h
      frontend:
        parallelize_shardable_queries: true
        split_queries_by_interval: 24h
        align_queries_with_step: true
        log_queries_longer_than: 10s
        max_outstanding_per_tenant: 10000
        cache_results: true
        cache_unaligned_requests: true
        grpc_client_config:
          grpc_compression: snappy
        results_cache:
          memcached:
            timeout: 60s
            connect_timeout: 60s
            max_idle_connections: 750
            max_async_concurrency: 100
            max_async_buffer_size: 10000000
            max_get_multi_concurrency: 750
            max_get_multi_batch_size: 1000
            max_item_size: 16777216
      frontend_worker:
        grpc_client_config:
          max_send_msg_size: 512000000
          grpc_compression: snappy
      query_scheduler:
        max_outstanding_requests_per_tenant: 10000
      querier:
        timeout: 280s
        max_concurrent: 16
```

The configuration of the Grafana agent is fairly standard, with minimal customizations.
