### ISSUE TITLE
Mimir distributed chart does not support minDomains for topologySpreadConstraints

### ISSUE THREAD

**Issue by eric-engberg** [grafana/mimir#6140]
#### Describe the bug
The mimir distributed chart does not support the minDomains field

#### To Reproduce

1. Add minDomains to a topologySpreadConstraint in mimir distributed helm chart
2. Template the output and see that the topologySpreadConstraint does not have minDomains in it.

#### Expected behavior

I expect the minDomains field to be present in the topologySpreadConstraint field

#### Environment

- EKS
- HELM
-

**Comment by dimitarvdimitrov** [comment]
i think we can add this field. It's in beta since v1.25 and requires enabling a feature gate to use it, so the default value we add to the helm chart shouldn't break deployments that don't have the feature gate enabled.

I think having a `null` or simply unset YAML value will do the trick with the [TSC template in the helm chart](https://github.com/grafana/mimir/blob/18f1dd062f141dbf21772930380e4fa77fa4bb69/operations/helm/charts/mimir-distributed/templates/lib/topologySpreadConstraints.tpl#L1-L21).

I think simply doing it in the template will bring the change to all components that use TSCs

**Comment by jrab66** [comment]
@dimitarvdimitrov I add the changes to support the `minDomains` optional field over the **topologySpreadContraints** on the values.yaml, can you help me regarding with that PR :) 


@eric-engberg enjoy!


PR: https://github.com/grafana/mimir/pull/6375

example for any component:
```
  topologySpreadConstraints:
    maxSkew: 12
    minDomains: 10 #optional 
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
```


helm template with `minDomains` :

```
      topologySpreadConstraints:
      - maxSkew: 12
        minDomains: 10
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: mimir
            app.kubernetes.io/instance: release-name
            app.kubernetes.io/component: alertmanager
```

helm template without `minDomains`: 
```
      topologySpreadConstraints:
      - maxSkew: 12
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: mimir
            app.kubernetes.io/instance: release-name
            app.kubernetes.io/component: alertmanager
```
