### ISSUE TITLE
Mimir helm  - Gateway fails when using extraArgs

### ISSUE THREAD

**Issue by wonderphil** [grafana/mimir#6243]
#### Describe the bug
when deploying Mimir and setting up a gateway, if you have `extraArgs` in the helm config, Mimir gateway fails to start with the following error:

```
/docker-entrypoint.sh: exec: line 47: illegal option -0
```

#### To Reproduce

1. Mimir Version: `grafana/mimir:2.10.0` Gateway version: `docker.io/nginxinc/nginx-unprivileged:1.24-alpine`
2. have the following config in the values file:

```
gateway:
    enabledNonEnterprise: true
    extraArgs:
      - -config.expand-env=true
    extraEnvFrom:
      - secretRef:
          name: secret-grafana
```

#### Expected behavior

For pod to start and environment vars available 

#### Environment

- Infrastructure:  Kubernetes v1.28, bare-metal
- Deployment tool: helm with argocd
