### ISSUE TITLE
store-gateway keep Killed by OOM Error

### ISSUE THREAD

**Issue by kadhamecha-conga** [grafana/mimir#6284]
hi team,

We are running Mimir 2.3.1 in AWS EKS, we have observed store-gateway and query frontend are keep killed by OOM.
we are running with 5 replicas of store-gateway with each level of cache ( result, metadata, index and chunk ). I don't see any issue on loading index for block from backend storage. Iet me know, if it needs some tuning of resources and config. also suggest parameter tunning of memcache to improve query performance ?
store-gw is currently running with 24 Gb. 

we do have some queries which perform operation on 30 days data .

```
blocks_storage:
  backend: s3
  bucket_store:
    chunks_cache:
      backend: memcached
      memcached:
        addresses: dns+cortex-chunks-cache.test.svc:11211
        max_item_size: 1048576
        timeout: 450ms
    ignore_deletion_mark_delay: 1h0m0s
    index_cache:
      backend: memcached
      memcached:
        addresses: dns+cortex-index-cache.test.svc:11211
        max_item_size: 15728640
    metadata_cache:
      backend: memcached
      memcached:
        addresses: dns+cortex-metadata-cache.test.svc:11211
        max_item_size: 1048576
    sync_dir: /data/tsdb-sync
  filesystem:
    dir: ""
  s3:
    bucket_name: xxxx
    endpoint: s3.dualstack.us-west-2.amazonaws.com
    region: us-west-2
  tsdb:
    dir: /data/tsdb
    retention_period: 7h0m0s
compactor:
  data_dir: ./data
distributor:
  remote_timeout: 5s
frontend:
  align_queries_with_step: true
  cache_results: true
  log_queries_longer_than: 5s
  parallelize_shardable_queries: true
  query_stats_enabled: true
  results_cache:
    backend: memcached
    memcached:
      addresses: dns+cortex-results-cache.test.svc:11211
      max_item_size: 1048576
  scheduler_address: cortex-query-scheduler-headless.test.svc:9095
  split_queries_by_interval: 24h0m0s
frontend_worker:
  scheduler_address: cortex-query-scheduler-headless.test.svc:9095
ingester:
  ring:
    final_sleep: 0s
    num_tokens: 512
    replication_factor: 1
    tokens_file_path: /data/tokens
    unregister_on_shutdown: false
ingester_client:
  grpc_client_config:
    max_recv_msg_size: 209715200
    max_send_msg_size: 209715200
limits:
  ingestion_burst_size: 2000000
  ingestion_rate: 1500000
  max_fetched_chunks_per_query: 0
  max_fetched_series_per_query: 0
  max_global_series_per_user: 0
  max_label_names_per_series: 100
  max_query_parallelism: 224
memberlist:
  abort_if_cluster_join_fails: false
  compression_enabled: false
  join_members:
  - dns+cortex-gossip-ring.test.svc.cluster.local:7946
no_auth_tenant: fake
querier:
  max_concurrent: 16
query_scheduler:
  max_outstanding_requests_per_tenant: 1600
runtime_config:
  file: /var/cortex/runtime.yaml
server:
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_connection_age: 2m
  grpc_server_max_connection_age_grace: 5m
  grpc_server_max_connection_idle: 1m
  grpc_server_max_recv_msg_size: 10000000
  grpc_server_max_send_msg_size: 10000000
  http_listen_port: 7900
  http_server_read_timeout: 1m0s
  http_server_write_timeout: 1m0s
store_gateway:
  sharding_ring:
    kvstore:
      store: memberlist
    replication_factor: 1
    tokens_file_path: /data/tokens
```
