### ISSUE TITLE
Wrong 200 status code for large query

### ISSUE THREAD

**Issue by BogdanIonesq** [grafana/mimir#6415]
#### Summary
When doing large queries (through Grafana, in this case), Mimir wrongly returns 200 and no data, instead of returning an error.

#### To Reproduce
I have the following query:
```
max(burrow_kafka_consumer_status) by (consumer_group)
```

If I execute it against a Mimir datasource, for the last 5 minutes, for example, everything is alright - data is returned, and displayed in Grafana.
<img width="1523" alt="Screenshot 2023-10-18 at 11 37 25" src="https://github.com/grafana/mimir/assets/14040788/b614e1a6-1bd3-47a2-beec-175f51973fe2">

As shown above, this is a pretty expensive query, as the cardinality of `consumer_group` is high.

If I increase the timeframe to 6 hours, Mimir returns 200 and no data, and Grafana shows `No data`.
<img width="1012" alt="Screenshot 2023-10-18 at 11 40 05" src="https://github.com/grafana/mimir/assets/14040788/e5b9781e-8d47-467d-a163-072fea8888b1">

No error is reported by Mimir, either in the query frontend, query scheduler or the querier. I sometimes noticed that the query-frontends is killed due to OOM, but in either case, returning 200 (which is interpreted as success) should not be returned by Mimir - this might mistakenly lead to think that data indeed does not exist in Mimir (although it does).

Mimir version: 2.10.0
Mimir Helm chart version: 5.1.0

#### Expected behaviour

When a query fails, due to high cardinality, or other limits, 200 should not be returned.

#### Environment

- Infrastructure: Kubernetes (AWS EKS)
- Deployment tool: Helm

#### Additional Context
Mimir config:
```
  mimir:
    structuredConfig:
      tenant_federation:
        enabled: true
      server:
        log_level: warn
        http_server_read_timeout: 2m
        http_server_write_timeout: 2m
      ingester_client:
        grpc_client_config:
          grpc_compression: snappy
      blocks_storage:
        backend: s3
        s3:
          bucket_name: <redacted>
          endpoint: <redacted>
          region: eu-central-1
          sse:
            type: "SSE-S3"
        bucket_store:
          index_cache:
            backend: "memcached"
            memcached:
              addresses: "<redacted>"
          chunks_cache:
            backend: "memcached"
            memcached:
              addresses: "<redacted>"
          metadata_cache:
            backend: "memcached"
            memcached:
              addresses: "<redacted>"
      querier:
        max_concurrent: 32
        timeout: 2m
        prefer_streaming_chunks_from_ingesters: true
        prefer_streaming_chunks_from_store_gateways: true
      frontend:
        max_outstanding_per_tenant: 2048 # defaults to 100
        align_queries_with_step: true
        query_sharding_target_series_per_shard: 0
        log_queries_longer_than: 10s
        scheduler_worker_concurrency: 32 # should be aligned with querier.max_concurrent
        grpc_client_config:
          grpc_compression: snappy
        cache_results: true
        results_cache:
          backend: "memcached"
          compression: "snappy"
          memcached:
            addresses: "<redacted>"
            timeout: 1s
      distributor:
        ha_tracker:
          enable_ha_tracker: true
          kvstore:
            store: consul
            consul:
              host: mimir-consul-headless:8500
      query_scheduler:
        max_outstanding_requests_per_tenant: 2048 # defaults to 100
        grpc_client_config:
          grpc_compression: snappy
      frontend_worker:
        grpc_client_config:
          grpc_compression: snappy
          max_send_msg_size: 104857600
      limits:
        # deduplication settings
        accept_ha_samples: true
        ha_cluster_label: mimir_tenant
        ha_replica_label: prometheus_replica
        compactor_blocks_retention_period: 1y
        max_label_names_per_series: 40
        max_global_series_per_user: 0
        ingestion_rate: 200000
        ingestion_burst_size: 500000
        # limit queries to 3 months
        max_total_query_length: 90d
        max_query_parallelism: 960
        query_sharding_max_sharded_queries: 0
        max_fetched_chunks_per_query: 5000000
      ruler:
        ruler_client:
          grpc_compression: snappy
        query_frontend:
          address: "dns:///mimir-query-frontend.mimir:9095"
          grpc_client_config:
            grpc_compression: snappy
        tenant_federation:
          enabled: true
      ruler_storage:
        backend: local
        local:
          directory: /tmp/rules
      alertmanager_storage:
        backend: s3
        s3:
          bucket_name: <redacted>
          endpoint: <redacted>
          region: eu-central-1
          sse:
            type: "SSE-S3"

```
