### ISSUE TITLE
helm: mimir-distributed helm chart missing components when enabling zone-aware-replication

### ISSUE THREAD

**Issue by NickAhold** [grafana/mimir#6514]
#### Describe the bug
When you enable zone-aware-replication for the ingester and store-gateway you only get one pdb and one servicemonitor for the 3 statefullsets it creates per zone. 

#### To Reproduce

Deploy the mimir-distributed helm chart with the following values for the store-gateway and ingester. 

```
  zoneAwareReplication:
    enabled: true
    maxUnavailable: "1"
    topologyKey: 'kubernetes.io/hostname'
    zones:
    - name: zone-1
      nodeSelector:
        topology.kubernetes.io/zone: westeurope-1
      storageClass: null
    - name: zone-2
      nodeSelector:
        topology.kubernetes.io/zone: westeurope-2
      storageClass: null
    - name: zone-3
      nodeSelector:
        topology.kubernetes.io/zone: westeurope-3
      storageClass: null


```

#### Expected behavior

When deploying these mimir components in zone-aware mode the helm chart should create a pdb and servicemonitor for each of the statefullsets created. for the example configuration above we should get the following statefullsets. 

```
mimir-ingester-zone-1
mimir-ingester-zone-2
mimir-ingester-zone-3
```

These statefullsets should have their own pdb and servicemonitor. 

#### Environment

- Infrastructure:  Kubernetes
- Deployment tool:  helm

#### Additional Context

n/a
