### ISSUE TITLE
Alertmanager should always return 404 when user config have been deleted

### ISSUE THREAD

**Issue by fgouteroux** [grafana/mimir#6599]
#### Describe the bug
When a user alertmanager config is deleted, the GET api return a 404 and one minuter later a 200.

#### To Reproduce

1. Start Mimir (2.10.3)
2. Delete an existing user alertmanager config
```
$ curl -H "X-Scope-OrgID: test" https://prom-alert.example.com/api/v1/alerts -X DELETE
```
3. Read the deleted user alertmanager config
```
$ curl -H "X-Scope-OrgID: test" https://prom-alert.example.com/api/v1/alerts
alertmanager storage object not found
```

4, One minute later, read again the deleted user alertmanager config
```
$ curl -H "X-Scope-OrgID: test" https://prom-alert.example.com/api/v1/alerts
template_files: {}
alertmanager_config: ""
```

#### Expected behavior

I expect to always have a 404 api response code when an existing user alertmanager config have been deleted.

#### Environment

- 3 alertmanagers peers
- 97 Alertmanager tenants
- s3 object storage used (netapp)
- Infrastructure: [bare-metal]
- Deployment tool: [puppet, [terraform-provider-mimir](https://registry.terraform.io/providers/fgouteroux/mimir/0.2.3)]

**Comment by dimitarvdimitrov** [comment]
this looks similar to https://github.com/prometheus/alertmanager/issues/1377. That was solve with some sticky sessions on the load-balancer in front of the alertmanagers. Perhaps @grafana/mimir-ruler-and-alertmanager-maintainers can pitch in to say whether this is expected

**Comment by fgouteroux** [comment]
It doesn't happen with local filesystem storage directory.

**Comment by stevesg** [comment]
Hi @fgouteroux - could you post your Mimir Alertmanger configuration? I'm primarily interested in if you have a fallback configuration specified (`-alertmanager.configs.fallback`). If so, then any other API rquest made will cause the second request is likely uploading a stub configuration

**Comment by fgouteroux** [comment]
> > It doesn't happen with local filesystem storage directory.
> 
> what do you mean, do you always gets a 200 and a yaml response?
> 
> Also what happens with the local fs storage if you request a non-existent tenant? Do you still get a 404? (sorry about the basic questions, but I'm exploring this along with you)

Yes, I get a 404 for a non-existent tenant.

**Comment by fgouteroux** [comment]
> Hi @fgouteroux - could you post your Mimir Alertmanger configuration? I'm primarily interested in if you have a fallback configuration specified (`-alertmanager.configs.fallback`). If so, then any other API request made will cause a stub configuration file to be uploaded.
> 
> If you could post a snippet of your logs, that would also be helpful.

I have no fallback configuration specified. 
```
alertmanager:
    data_dir: /var/lib/mimir/data-alertmanager
    retention: 120h0m0s
    external_url: http://localhost:8080/alertmanager
    poll_interval: 15s
    max_recv_msg_size: 104857600
    sharding_ring:
        kvstore:
            store: memberlist
            prefix: alertmanagers/
            consul:
                host: localhost:8500
                acl_token: ""
                http_client_timeout: 20s
                consistent_reads: false
                watch_rate_limit: 1
                watch_burst_size: 1
                cas_retry_delay: 1s
            etcd:
                endpoints: []
                dial_timeout: 10s
                max_retries: 10
                tls_enabled: false
                tls_cert_path: ""
                tls_key_path: ""
                tls_ca_path: ""
                tls_server_name: ""
                tls_insecure_skip_verify: false
                tls_cipher_suites: ""
                tls_min_version: ""
                username: ""
                password: ""
            multi:
                primary: ""
                secondary: ""
                mirror_enabled: false
                mirror_timeout: 2s
        heartbeat_period: 15s
        heartbeat_timeout: 1m0s
        instance_id: mimiralert0101e1.example.com
        instance_interface_names:
            - ens160
        instance_port: 0
        instance_addr: 10.XX.XX.XX
        instance_enable_ipv6: false
        replication_factor: 3
        zone_awareness_enabled: true
        instance_availability_zone: e1
    fallback_config_file: ""
    peer_timeout: 15s
    enable_api: true
    max_concurrent_get_requests_per_tenant: 0
    alertmanager_client:
        remote_timeout: 2s
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600
        grpc_compression: ""
        rate_limit: 0
        rate_limit_burst: 0
        backoff_on_ratelimits: false
        backoff_config:
            min_period: 100ms
            max_period: 10s
            max_retries: 10
        initial_stream_window_size: 63KiB1023B
        initial_connection_window_size: 63KiB1023B
        tls_enabled: true
        tls_cert_path: /etc/mimir/ssl/cert.pem
        tls_key_path: /etc/mimir/ssl/key.pem
        tls_ca_path: /etc/mimir/ssl/ca.pem
        tls_server_name: ""
        tls_insecure_skip_verify: false
        tls_cipher_suites: ""
        tls_min_version: ""
        connect_timeout: 5s
        connect_backoff_base_delay: 1s
        connect_backoff_max_delay: 5s
    persist_interval: 15m0s
    enable_state_cleanup: true
alertmanager_storage:
    backend: s3
    s3:
        endpoint: s3.example.com
        region: default
        bucket_name: mimir-alertmanager-sandbox
        secret_access_key: '********'
        access_key_id: XXXXXX
        insecure: false
        signature_version: v4
        list_objects_version: ""
        storage_class: ""
        native_aws_auth_enabled: false
        sse:
            type: ""
            kms_key_id: ""
            kms_encryption_context: ""
        http:
            idle_conn_timeout: 1m30s
            response_header_timeout: 2m0s
            insecure_skip_verify: false
            tls_handshake_timeout: 10s
            expect_continue_timeout: 1s
            max_idle_connections: 100
            max_idle_connections_per_host: 100
            max_connections_per_host: 0
```
No errors/infos in logs. I will try to reproduce it in debug mode.
