### ISSUE TITLE
Unruly store gateway rollout

### ISSUE THREAD

**Issue by LasseHels** [grafana/mimir#6678]
**Context**
---
A rollout of store gateways in our cluster started at 09:23:14 UTC November 16th 2023. Immediately, p99 latency of our Mimir read path shot up from ~1s to ~40s:
![Screenshot 2023-11-17 at 10 39 46](https://github.com/grafana/mimir/assets/121869045/c03918b0-721a-4912-a7dc-e95bd611ae88)

We run a total of 63 store gateways across three zones (21 per zone). Our Mimir setup runs in a dedicated AKS cluster and ingests 12m metrics per second as well as serving ~200 instant queries per second and ~85 range queries per second.

The change that triggered the rollout was this:
```diff
-       - -blocks-storage.bucket-store.chunks-cache.memcached.max-async-concurrency=50
-       - -blocks-storage.bucket-store.chunks-cache.memcached.max-get-multi-concurrency=100
-       - -blocks-storage.bucket-store.chunks-cache.memcached.max-idle-connections=150
+       - -blocks-storage.bucket-store.chunks-cache.memcached.max-async-buffer-size=10000
+       - -blocks-storage.bucket-store.chunks-cache.memcached.max-async-concurrency=200
+       - -blocks-storage.bucket-store.chunks-cache.memcached.max-get-multi-batch-size=1000
+       - -blocks-storage.bucket-store.chunks-cache.memcached.max-get-multi-concurrency=200
+       - -blocks-storage.bucket-store.chunks-cache.memcached.max-idle-connections=500
```

<details>
  <summary>Full store gateway configuration</summary>

```yaml
      containers:
      - args:
        - -auth.multitenancy-enabled=false
        - -auth.no-auth-tenant=fake
        - -blocks-storage.azure.container-name=mimir
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=dnssrvnoa+memcached.mimir.svc.cluster.local:11211
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-async-buffer-size=10000
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-async-concurrency=200
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-get-multi-batch-size=1000
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-get-multi-concurrency=200
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-idle-connections=150
        - -blocks-storage.bucket-store.chunks-cache.memcached.max-item-size=1048576
        - -blocks-storage.bucket-store.chunks-cache.memcached.timeout=450ms
        - -blocks-storage.bucket-store.ignore-blocks-within=10h
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=dnssrvnoa+memcached-index-queries.mimir.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.memcached.max-async-concurrency=50
        - -blocks-storage.bucket-store.index-cache.memcached.max-get-multi-concurrency=100
        - -blocks-storage.bucket-store.index-cache.memcached.max-idle-connections=150
        - -blocks-storage.bucket-store.index-cache.memcached.max-item-size=5242880
        - -blocks-storage.bucket-store.index-cache.memcached.timeout=300ms
        - -blocks-storage.bucket-store.index-header-lazy-loading-enabled=true
        - -blocks-storage.bucket-store.index-header-lazy-loading-idle-timeout=60m
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=dnssrvnoa+memcached-metadata.mimir.svc.cluster.local:11211
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-async-concurrency=50
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-get-multi-concurrency=100
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-idle-connections=150
        - -blocks-storage.bucket-store.metadata-cache.memcached.max-item-size=1048576
        - -blocks-storage.bucket-store.metadata-cache.memcached.timeout=500ms
        - -blocks-storage.bucket-store.sync-dir=/data/tsdb
        - -blocks-storage.bucket-store.sync-interval=15m
        - -common.storage.azure.account-name=pensievemimirprodwe01
        - -common.storage.backend=azure
        - -config.expand-env=true
        - -config.file=/etc/mimir/config/mimir.yaml
        - -memberlist.bind-port=7947
        - -memberlist.join=gossip-ring.mimir.svc.cluster.local:7947
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -store-gateway.sharding-ring.heartbeat-timeout=2m
        - -store-gateway.sharding-ring.instance-availability-zone=zone-a
        - -store-gateway.sharding-ring.prefix=multi-zone/
        - -store-gateway.sharding-ring.replication-factor=3
        - -store-gateway.sharding-ring.store=memberlist
        - -store-gateway.sharding-ring.tokens-file-path=/data/tokens
        - -store-gateway.sharding-ring.unregister-on-shutdown=true
        - -store-gateway.sharding-ring.wait-stability-min-duration=1m
        - -store-gateway.sharding-ring.zone-awareness-enabled=true
        - -target=store-gateway
```
</details>

The same commit also triggered a rollout of our memcached instances with this change:
```diff
-       - -oext_path=/data/ephemeral:200G,ext_wbuf_size=8,ext_item_age=30,ext_max_sleep=10000
+       - -oext_path=/data/ephemeral:200G,ext_wbuf_size=32,ext_item_age=30,ext_max_sleep=10000,ext_recache_rate=0,slab_automove_freeratio=0.10
```

We use Grafana's [rollout-operator](https://github.com/grafana/rollout-operator) component to manage rollout of store gateways. The operator is configured to leave a maximum of two store gateways unavailable in a zone during the rollout. 
Rollout operator logs from `2023-11-16 09:23:14` UTC to `2023-11-16 10:20:15` UTC: [rollout-operator-logs.txt](https://github.com/grafana/mimir/files/13390230/rollout-operator-logs.txt)

The rollout of memcached instances is not managed by the rollout-operator. Timestamps for memcached rollout can be seen directly in Kubernetes events. The rollout of memcached instances took only a couple of minutes: [kubernetes-events.txt](https://github.com/grafana/mimir/files/13390275/kubernetes-events.txt)

**Analysis**
---
This is not the first time we've seen unruly store gateway rollouts, but it _is_ the first time that our read path has been impacted.

While we're not sure, we believe the crux of the issue lies in the combined rollout of store gateways and memcached instances at the same time. Anecdotal queries run during the rollout showed that it was primarily queries going back more than 24 hours that were affected. We suspect this is because querying fresh data bypasses store gateways altogether in favour of ingesters (which were unaffected).

Reads dashboard memcached panels:
![Screenshot 2023-11-17 at 10 57 46](https://github.com/grafana/mimir/assets/121869045/5bfaa897-2be5-4ae7-9054-e1dad8ff4b57)

Looking at these panels shows a clear change in behaviour when the rollout starts. Similarly, our memcached dashboards shows practically zero reads after the rollout starts:
![Screenshot 2023-11-17 at 11 02 00](https://github.com/grafana/mimir/assets/121869045/c6cd9a8e-7b93-4b3b-a4c3-bb9392097fb6)

Store gateway block store accesses:
![Screenshot 2023-11-17 at 11 06 49](https://github.com/grafana/mimir/assets/121869045/2e9250cc-ccb3-4a4b-8cac-29426ea21c3e)

Store gateway resource consumption looks nominal during the rollout:
![Screenshot 2023-11-17 at 11 03 07](https://github.com/grafana/mimir/assets/121869045/f9e9883b-2914-4eac-9bcb-2144ae8e13a3)

Store gateway PVC usage swings wildly during the rollout:
![Screenshot 2023-11-17 at 11 04 12](https://github.com/grafana/mimir/assets/121869045/402def94-1fea-4906-bf44-234f1edca90d)

The PVC of gateway 13 and 18 maxed out:
![Screenshot 2023-11-17 at 11 05 16](https://github.com/grafana/mimir/assets/121869045/86c9de7d-0892-4b04-afde-dbd2860cbdd2)

Here's the full log output of three of the store gateways from when they were terminated:
* [store-gateway-a-0.txt](https://github.com/grafana/mimir/files/13390383/store-gateway-a-0.txt).
* [store-gateway-a-5.txt](https://github.com/grafana/mimir/files/13390385/store-gateway-a-5.txt).
* [store-gateway-a-15.txt](https://github.com/grafana/mimir/files/13390387/store-gateway-a-15.txt).

A common trend we observe (both in this rollout and others) is that it takes a _long_ time for gateways to start, typically around five minutes. This combined with a max unavailable count of two leads to prolonged rollouts that last for hours.

From what we understand, store gateways distribute blocks between them. As such, when a gateway is terminated, it must distribute its blocks amongst the other gateways in the ring. We're unsure of how this works in detail, as well as how expensive it is, but it seems that ring changes strongly correlate with the observed degradation in read latency.

Looking at the logs, it seems like terminating pods in zone A leads to ring changes (and thus a block synchronisation) in zones B and C as well:
![Screenshot 2023-11-17 at 11 22 42](https://github.com/grafana/mimir/assets/121869045/e5b03fc9-a9b0-45fe-9b93-736e6099fa3a)

At this time, we're left with a couple of questions:
1. Why does it take several minutes for a store gateway to start?
2. Why do store gateway PVCs fill up during a rollout?
3. What was the root cause of the degradation in latency during the rollout? Our naive take is that it has to do with how the gateways interact with memcached during the rollout, but we are unable to pin down the root cause further.
4. Is there a faster (and more stable) way of rolling out store gateways? We've experimented with bringing down **all** store gateway pods in a zone at once, and this seems - somewhat ironically - to be more stable than rolling out gradually.

We're still looking into this, but are hampered by our novice understanding of store gateways; we'd be most appreciative of assistance from the Mimir team. We're happy to provide any additional information required.

Thanks!
