### ISSUE TITLE
Ingester disk read activity

### ISSUE THREAD

**Issue by LasseHels** [grafana/mimir#6730]
**Context**
---
We run 110 ingesters in each of three availability zones for a total of 330 ingesters. Our Mimir setup runs on Azure Kubernetes Service. Each ingester has an attached PVC of 150GiB (which is a P15 Azure disk behind the scenes).

On November 14th at 10:10 UTC, a node image upgrade was started on our cluster, requiring a restart of all nodes in our cluster. This rollout eventually triggered an incident in our platform.

<details>
  <summary>Mimir ingester configuration</summary>

```yaml
      containers:
      - args:
        - -auth.multitenancy-enabled=false
        - -auth.no-auth-tenant=fake
        - -blocks-storage.azure.container-name=mimir
        - -blocks-storage.tsdb.block-ranges-period=2h
        - -blocks-storage.tsdb.dir=/data/tsdb
        - -blocks-storage.tsdb.head-compaction-interval=15m
        - -blocks-storage.tsdb.ship-interval=1m
        - -blocks-storage.tsdb.wal-replay-concurrency=14
        - -common.storage.azure.account-name=REDACTED
        - -common.storage.backend=azure
        - -config.expand-env=true
        - -config.file=/etc/mimir/config/mimir.yaml
        - -distributor.health-check-ingesters=true
        - -ingester.instance-limits.max-inflight-push-requests=90000
        - -ingester.max-global-exemplars-per-user=100000
        - -ingester.max-global-metadata-per-metric=0
        - -ingester.max-global-metadata-per-user=0
        - -ingester.max-global-series-per-user=0
        - -ingester.out-of-order-time-window=0s
        - -ingester.ring.heartbeat-timeout=10m
        - -ingester.ring.instance-availability-zone=zone-a
        - -ingester.ring.num-tokens=512
        - -ingester.ring.prefix=
        - -ingester.ring.replication-factor=3
        - -ingester.ring.store=memberlist
        - -ingester.ring.tokens-file-path=/data/tokens
        - -ingester.ring.unregister-on-shutdown=true
        - -ingester.ring.zone-awareness-enabled=true
        - -memberlist.bind-port=7947
        - -memberlist.join=gossip-ring.mimir.svc.cluster.local:7947
        - -runtime-config.file=/etc/mimir/overrides.yaml
        - -server.grpc-max-concurrent-streams=10000
        - -server.grpc.keepalive.min-time-between-pings=10s
        - -server.grpc.keepalive.ping-without-stream-allowed=true
        - -server.http-listen-port=8080
        - -target=ingester
        - -validation.max-label-names-per-series=40
```
</details>

Note `-ingester.ring.unregister-on-shutdown=true`. We're unsure if this has any impact on the issues mentioned below.

**Analysis**
---

Our theory as to what happened is:
1. Ingester commit duration increased.
2. The increase in commit duration meant that ingesters could no longer process requests as fast as before, leading to a buildup of inflight push requests.
3. The increase of inflight push requests translated to increased memory usage. We assume that each inflight push request takes up some amount of memory.
4. Ingesters are eventually OOMKilled, triggering the incident.

Disk commit duration:
![Screenshot 2023-11-24 at 11 45 04](https://github.com/grafana/mimir/assets/121869045/280a9203-73fb-4fd7-b5f9-c21c626dc231)

Inflight push requests:
![Screenshot 2023-11-24 at 11 45 41](https://github.com/grafana/mimir/assets/121869045/b15a551b-77f2-4f54-9abe-ff8172b30749)

Memory usage (in thousands of gigabytes):
![Screenshot 2023-11-24 at 11 45 59](https://github.com/grafana/mimir/assets/121869045/5d5be4dd-a7cb-4e00-bd1b-846904838417)

We're yet to explain the increase in commit duration. From what we can see, the only thing a commit involves is writing data to disk, so our assumption is that the cause of commit latency will be some sort of degradation and/or throttling of the underlying disk.

We're currently chasing two theories:
1. Disk failure in Azure. This seems rather unlikely, and would be an extraordinary coincidence to have happen while we're doing a node rollout.
2. Disk throttling. This seems more likely, and is our leading theory.

While looking into disk throttling, we noticed some curious ingester IO patterns.

During the rollout of zone A, ingester read activity increases slightly:
![Screenshot 2023-11-24 at 11 51 36](https://github.com/grafana/mimir/assets/121869045/01013a53-db20-4277-948f-0b6684c4d3c9)

This makes intuitive sense to us; ingesters are re-placed as their node is drained, and must replay WAL upon startup (causing disk reads). The read activity lasts for a couple of minutes (the time it takes an ingester to replay its WAL) and typically hovers around ~100 reads/s.

However, starting at 12:00 UTC, we see some concerning behaviour:
![Screenshot 2023-11-24 at 11 54 29](https://github.com/grafana/mimir/assets/121869045/36516483-7c3e-479f-828e-d12196421f4b)

Zooming in on the initial spike, we see ingesters doing several thousand reads/s for a couple of minutes:
![Screenshot 2023-11-24 at 11 55 41](https://github.com/grafana/mimir/assets/121869045/bd86ba56-c2d0-43af-b87a-8d3b75eb1b12)

None of the eager ingesters were replaying WAL during these minutes:
![Screenshot 2023-11-24 at 11 58 10](https://github.com/grafana/mimir/assets/121869045/466f00e3-bcf4-4625-8754-491f8a770512)

We initially theorised that the disk read activity was caused by read requests to the ingester, but this wouldn't make sense as ingester data is served directly from memory(?) and not from disk. Under normal circumstances (where we get a _lot_ of read requests), ingester disk read activity is near-zero:
![Screenshot 2023-11-24 at 12 08 15](https://github.com/grafana/mimir/assets/121869045/9a84aa50-469f-4cd0-be25-aacb202c4363)

Thus, we're left with the question: **what could be the cause of this dramatic increase of ingester disk read activity we see during the rollout?**

Thanks!
