### ISSUE TITLE
Connectivity fails with R2, B2 and Wasabi

### ISSUE THREAD

**Issue by cyclingwithelephants** [grafana/mimir#6739]
#### Describe the bug
Mimir cannot connect to Cloudflare R2, Backblaze B2 or Wasabi S3. I'd normally assume the issue is with the bucket provider but they all fail so I'm not really sure what to think.

Totally appreciate this could be problems with s3 API compatibility from all of the above providers, and am hoping to understand this a bit more to see if it's possible to work around.

#### To Reproduce (generic)
All buckets are made with default settings, and API keys are configured with read/write access on the buckets

Log outputs are from the pod `mimir-store-gateway-zone-a-0`

#### To Reproduce (R2)

1. Start Mimir using helm chart with following values:
```yaml
minio:
  enabled: false

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: {cloudflare_account_id}.r2.cloudflarestorage.com
          region: weur # have also tried 'auto' - I'm in western europe
          secret_access_key: "${BUCKET_SECRET_ACCESS_KEY}" # This is a secret injected via an environment variable
          access_key_id: "${BUCKET_ACCESS_KEY_ID}"                  # This is a secret injected via an environment variable

    blocks_storage:
      s3:
        bucket_name: {bucket_prefix}-mimir-blocks
    alertmanager_storage:
      s3:
        bucket_name: {bucket_prefix}-mimir-alertmanager
    ruler_storage:
      s3:
        bucket_name: {bucket_prefix}-mimir-ruler
```
2. Deploy corresponding secret for cloudflare token with read/write permission on buckets
```yaml
apiVersion: v1
stringData:
  BUCKET_ACCESS_KEY_ID: <redacted>
  BUCKET_SECRET_ACCESS_KEY: <redacted>
kind: Secret
metadata:
  name: mimir-bucket
  namespace: monitoring
type: Opaque
```
4. no components in mimir are able to connect R2 
```
ts=2023-11-26T23:27:47.869977534Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="blocks storage: unable to successfully send a request to object storage: Invalid Argument: Authorization"
```

I do note that I did find [this issue](https://community.cloudflare.com/t/r2-storage-unable-to-upload-using-pre-signed-url-getting-invalid-argument-authorization/396502) which suggests that the issue is due to presigned URLs. I tried giving the buckets public URLs but that doesn't solve the problem. I'm new to R2 so am not confident I did this correctly.

#### To Reproduce (B2)
Same process, changing values.yaml as
```
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.us-west-004.backblazeb2.com
          region: us-west-004
```
API token has read/write permissions on all buckets in the account, and I appropriately changed the secret and re-applied the yaml (deleting first)

which returns an error like
```
ts=2023-11-26T23:49:00.135501318Z caller=sanity_check.go:115 level=warn msg="Unable to successfully connect to configured object storage (will retry)" err="blocks storage: unable to successfully send a request to object storage: bucket is not authorized: {bucket_prefix}-mimir-blocks"
```
I did note [this similar issue](https://github.com/Backblaze/b2-sdk-python/issues/136#issuecomment-843670655) but am already specifying the region as is suggested in the issue.

*Changing the buckets to public fixes this issue for B2, however returns a new error*
```
ts=2023-11-27T00:24:40.914711567Z caller=mimir.go:850 level=error msg="module failed" module=store-gateway err="invalid service state: Failed, expected: Running, failure: initial blocks synchronization: Unauthenticated requests are not allowed for this api"
```

#### To Reproduce (Wasabi)
Same process, changing values.yaml to
```
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-central-1.wasabisys.com
          region: eu-central-1
```
(and changing the secrets as appropriate)

Which produces the error
```
ts=2023-11-27T00:04:48.374211946Z caller=seed.go:127 level=warn msg="failed to read cluster seed file from object storage" err="Public use of objects is not allowed by this account. Please contact Wasabi Support at support@wasabi.com for assistance."
``` 

This suggests again to me that this is some kind of issue around URL signing. I've gotten in touch to activate public objects with Wasabi, but they haven't gotten back to me. Based on my experience with B2 I'd expect setting the buckets to public would behave similarly

#### Expected behavior

I would not have to set buckets to public in order for Mimir to connect.

#### Environment

- Infrastructure: kubernetes
- Deployment tool: helm
