### ISSUE TITLE
Mimirtool multiple files with same namespace are not allowed

### ISSUE THREAD

**Issue by andres32168** [grafana/mimir#6748]
#### Describe the bug

Mimirtool does not allow to load or sync multiple files within the same namespace
For example `alerts.yaml` and `rules.yaml` from the mimir-mixin-compiled are not allowed to be deployed to the same namespace:
Adding a namespace to `alerts.yaml`
```yaml
namespace: mimir
groups:
- name: mimir_alerts
  rules:
  - alert: MimirIngesterUnhealthy
 {...}
```

```yaml
namespace: mimir
groups:
- name: mimir_api_1
  rules:
  - expr: histogram_quantile(0.99, sum(rate(cortex_request_duration_seconds_bucket[1m]))
{...}
```

In my opinion both , rules and alerts, belong to mimir which should be only 1 namespace and not 2.

Of course, it would be possible to have 2 different namespaces for example `mimir-rules` and `mimir-alerts` but both belong to mimir and it should be possible to load both into the same namespace.

#### To Reproduce

1. Add the same `namespace` to multiple files (see above)
2. Run following commands:
```shell
./mimirtool rules sync --rule-dirs=./rules/
ERRO[0001] repeated namespace attempted to be loaded     file=rules/rules.yaml namespace=mimir
mimirtool: error: sync operation unsuccessful, unable to parse rules files: file read error, try --help
```
or
```shell
./mimirtool rules load rules/alerts.yaml rules/rules.yaml
ERRO[0001] repeated namespace attempted to be loaded     file=rules/rules.yaml namespace=mimir
mimirtool: error: load operation unsuccessful, unable to parse rules files: file read error, try --help
```

#### Expected behavior

Multiple files could take the same namespace

#### Environment

Mimirtool, version 2.10.4 (branch: release-2.10, revision: https://github.com/grafana/mimir/commit/d1f4f1291001db7384ba66ca90b4f753309f262d)
