### ISSUE TITLE
msg="unknown message type" msgType=G

### ISSUE THREAD

**Issue by max107** [grafana/mimir#7056]
#### Describe the bug

```
ts=2024-01-05T14:04:26.889666454Z caller=tcp_transport.go:319 level=error component="memberlist TCPTransport" msg="unknown message type" msgType=G remote=10.244.111.238:36404
```

#### To Reproduce

add limits to helm chart values

```
mimir:
  structuredConfig:
    multitenancy_enabled: false
    limits:
      max_global_series_per_user: 1000000
```

#### Expected behavior

no `unknown message type` error and distributor accept metrics

#### Environment

kubernetes, helm

#### Additional Context

runtimeConfig not help override max_global_series_per_user
```
ts=2024-01-05T12:49:21.416198Z caller=push.go:130 level=error user=anonymous msg="push error"
err="rpc error: code = Code(400) desc = failed pushing to ingester: user=anonymous: per-user series
limit of 150000 exceeded (err-mimir-max-series-per-user). To adjust the related per-tenant limit,
configure -ingester.max-global-series-per-user, or contact your service administrator."
```
