### ISSUE TITLE
Can't set annotations for create-bucket-job

### ISSUE THREAD

**Issue by adberger** [grafana/mimir#7060]
#### Describe the bug

There is an option to set annotations for the create-bucket-job in mimir-ditributed, but its missing the `annotations` key:
https://github.com/grafana/mimir/blob/146af07f02f8255b719c00af3687cd98814902a3/operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml#L18-L20

#### To Reproduce

Add the following to the `values.yaml`:
```
minio:
  makeBucketJob:
    annotations:
      argocd.argoproj.io/hook: PostSync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

Output will be:
```
kind: Job
metadata:
  name: release-name-mimir-make-minio-buckets-5.0.14
  namespace: "default"
  labels:
    app: mimir-distributed-make-bucket-job
    chart: mimir-distributed-5.2.0-weekly.271
    release: release-name
    heritage: Helm
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

#### Expected behavior

```
kind: Job
metadata:
  name: release-name-mimir-make-minio-buckets-5.0.14
  namespace: "default"
  labels:
    app: mimir-distributed-make-bucket-job
    chart: mimir-distributed-5.2.0-weekly.271
    release: release-name
    heritage: Helm
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
```

#### Environment

- Infrastructure: laptop
- Deployment tool: helm

#### Additional context

Installing this helm chart spawns 2 jobs, one from the minio sub chart and the one from the mimir-distributed (https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/minio/create-bucket-job.yaml).

Related issued: https://github.com/grafana/mimir/issues/2464
