### ISSUE TITLE
No data on mimir/reads dashboard

### ISSUE THREAD

**Issue by rosh0450** [grafana/mimir#7080]
I have enabled meta monitoring for my grafana mimir:

values.yaml 
```
metaMonitoring:
  dashboards:
    enabled: false

  serviceMonitor:
    enabled: true

  grafanaAgent:
    enabled: true

    metrics:
      enabled: true
      remote:
        url: "http://mimir-nginx.mimir.svc:80/api/v1/push"

      scrapeK8s:
        enabled: true
```

and i am able to see components specific metrics like cortex_ingester_active_series, cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds and others.

But when i imported the mimir/reads dashboard, it is completely empty.
![image](https://github.com/grafana/mimir/assets/59838688/fce6dbb4-2978-46b0-b54b-6ae3f590fb14)

Same is the case with other dashboards like mimir/write and others.

What can be the reason ?

Thanks.
