### ISSUE TITLE
Helm : structuredConfig field not working as intended

### ISSUE THREAD

**Issue by QuantumEnigmaa** [grafana/mimir#7225]
#### Describe the bug

When using the `structuredConfig` in my values file, its content is not passed correctly to the `mimir-config` configmap. I'm using the following field in my values : 
```
structuredConfig:
  blocks_storage:
    bucket_store:
      max_chunk_pool_bytes: 12884901888
      sync_dir: /data/tsdb-sync
    s3:
      bucket_name: <my_bucket>
  common:
    storage:
      backend: s3
      s3:
        endpoint: <my_endpoint>
        region: <my_region>
```

The resulting `mimir-config` is as follows (when templating or deploying the chart) : 
```
    blocks_storage:
      backend: s3
      bucket_store:
        sync_dir: /data/tsdb-sync
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
```

The `common` field has disappeared as well as the `blocks_storage.s3.bucket_name` one and the `blocks_storage.backend` field has been added. This result in `ingester` pods not being able to send their stored metrics to S3. 

To fix this, I had to manually edit the `mimir-config` configmap so that it looks as such : 
```
    blocks_storage:
      bucket_store:
        sync_dir: /data/tsdb-sync
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
      s3:
        bucket_name: <my_bucket>
    common:
      storage:
        backend: s3
        s3:
          endpoint: <my_endpoint>
          region: <my_region>
```

But this is not a long term solution as the configmap's content get overriden every time the chart is redeployed. So I was wondering where this issue might be coming from.

#### To Reproduce

1. Have a values with the content shared above
2. Template chart (`helm template -f /path/to/values /path/to/chart`) or deploy it

#### Expected behavior

The mimir config from the `mimir-config` configmap should match what's written in the `structuredConfig` field from the values.

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
- Deployment tool: [e.g., helm, jsonnet]

**Comment by rknightion** [comment]
In structuredConfig some levels (like common) appear to be not needed. 

here's a segment from one of ours for example that works:
```
mimir:
  structuredConfig:
    alertmanager_storage:
      backend: s3
      s3:
        bucket_name: pop-mimir-alertmanager
        endpoint: s3.us-east-1.amazonaws.com
        region: us-east-1
        sse:
          type: "SSE-S3"

    blocks_storage:
      tsdb:
        retention_period: 13h
      backend: s3
      s3:
        bucket_name: pop-mimir-blocks
        endpoint: s3.us-east-1.amazonaws.com
        region: us-east-1
        sse:
          type: "SSE-S3"
      bucket_store:
        ignore_blocks_within: 10h
        max_concurrent: 250
        block_sync_concurrency: 20
        meta_sync_concurrency: 20
        index_header_lazy_loading_idle_timeout: 6h
        index_header:
          eager_loading_startup_enabled: true
          sparse_persistence_enabled: true
```
No common needed as structuredConfig isn't a direct "put this in the configmap" it runs everything through the template/tpl rendering. It takes a bit of getting used to!

**Comment by narqo** [comment]
Note that `mimir.structuredConfig` is to **amend** the base config from `mimir.confg` with extra data. I.e. the resulting config is a deep-merge of two structures. IIRC, to unset a parameter on the leaf of a structure, one has to set the field to its corresponding empty value, e.g.

```
mimir:
  structuredConfig:
    blocks_storage:
      backend: ''
```

Although this is not always obvious, this explains why the resulting config included the `blocks_storage.backend` field. This part works as intended.

> The common field has disappeared as well as the blocks_storage.s3.bucket_name

I cannot reproduce this part using `helm v3.14.0` and the latest Helm chart (see the detailed steps below).

<details>

```
% cat gh7225-values-mimir.yaml
mimir:
  structuredConfig:
    blocks_storage:
      bucket_store:
        max_chunk_pool_bytes: 12884901888
        sync_dir: /data/tsdb-sync
      s3:
        bucket_name: my_bucket
    common:
      storage:
        backend: s3
      s3:
        endpoint: my_endpoint
        region: my_region

% helm template grafana/mimir-distributed -f ./gh7225-values-mimir.yaml > gh7225-k8s-1.yaml

% cat gh7225-k8s-1.yaml
···
data:
  mimir.yaml: |
    ···
    blocks_storage:
      backend: s3
      bucket_store:
        max_chunk_pool_bytes: 12884901888
        sync_dir: /data/tsdb-sync
      s3:
        access_key_id: grafana-mimir
        bucket_name: my_bucket
        endpoint: release-name-minio.default.svc:9000
        insecure: true
        secret_access_key: supersecret
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 15m
        wal_replay_concurrency: 3
    common:
      s3:
        endpoint: my_endpoint
        region: my_region
      storage:
        backend: s3
```

</details>

@QuantumEnigmaa could you provide more details? Maybe the `values.yaml` file also has `mimir.config`, which, when merged with `mimir.structuredConfig`, renders into an unexpected result.
