### ISSUE TITLE
Bug: upload s3 object to Backblaze B2 S3 storage fails: Unsupported header 'x-amz-checksum-algorithm'

### ISSUE THREAD

**Issue by cedi** [grafana/mimir#7270]
#### Describe the bug
I use Backblaze B2 as my S3 storage backend for Mimir.
After updating to mimir-distributed v5.2.0 Mimir fails to upload blocks to S3:

```
=2024-02-01T15:21:15.438490917Z caller=shipper.go:162 level=error user=<redacted> msg="uploading new block to long-term storage failed" block=<redacted> err="upload chunks: upload file /data/tsdb/<redacted>/<redacted>/chunks/000001 as <redacted>/chunks/000001: upload s3 object: Unsupported header 'x-amz-checksum-algorithm' received for this API call."
```

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context

This also affects Temp: https://github.com/grafana/tempo/issues/2910

Related to that is probably the following change in minio-go: https://github.com/minio/minio-go/issues/1791

**Comment by andyasp** [comment]
A `send_content_md5` configuration option was added for the `s3` backend in Mimir 2.11.0 that you can set to `true` that should be an escape hatch to that situation:
> (experimental) If enabled, a Content-MD5 header is sent with S3 Put Object
> requests. Consumes more resources to compute the MD5, but may improve
> compatibility with object storage services that do not support checksums.
> CLI flag: -(prefix).s3.send-content-md5

There are various ways to set object storage configuration in Helm, so modify as needed for your situation, but it would look something like
```
   structuredConfig:
     common:
       storage:
         backend: s3
         s3:
           send_content_md5: true
```

**Comment by cedi** [comment]
Thanks a bunch! This is super helpful!
I will give it a try tomorrow and report back/close the issue if I can confirm it's working.

**Comment by cedi** [comment]
This appears to be not working for me:

```
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: s3.eu-central-003.backblazeb2.com
			// ...
          send_content_md5: true
```

results in 

```
error loading config from /etc/mimir/mimir.yaml: Error parsing config file: yaml: unmarshal errors:
  line 37: field send_content_md5 not found in type s3.Config
```

using `image: grafana/mimir:2.11.0`:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: store-gateway
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/part-of: memberlist
    app.kubernetes.io/version: 2.11.0
    argocd.argoproj.io/instance: grafana-mimir
    helm.sh/chart: mimir-distributed-5.2.0
    name: store-gateway-nbg
    rollout-group: store-gateway
    zone: nbg
  name: mimir-store-gateway-nbg
  namespace: observability
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: store-gateway
      app.kubernetes.io/instance: mimir
      app.kubernetes.io/name: mimir
      rollout-group: store-gateway
      zone: nbg
  serviceName: mimir-store-gateway-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/component: store-gateway
        app.kubernetes.io/instance: mimir
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: mimir
        app.kubernetes.io/part-of: memberlist
        app.kubernetes.io/version: 2.11.0
        helm.sh/chart: mimir-distributed-5.2.0
        name: store-gateway-nbg
        rollout-group: store-gateway
        zone: nbg
      namespace: observability
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: rollout-group
                    operator: In
                    values:
                      - store-gateway
                  - key: zone
                    operator: NotIn
                    values:
                      - nbg
              topologyKey: topology.kubernetes.io/region
      containers:
        - args:
            - -target=store-gateway
            - -config.expand-env=true
            - -config.file=/etc/mimir/mimir.yaml
            - -store-gateway.sharding-ring.instance-availability-zone=nbg
          env:
            - name: JAEGER_AGENT_HOST
              value: tempo-distributor.observability.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: JAEGER_SAMPLER_TYPE
              value: const
            - name: JAEGER_DISABLED
              value: "false"
            - name: JAEGER_SERVICE_NAME
              value: mimir
            - name: GOMAXPROCS
              value: "5"
            - name: GOMEMLIMIT
              value: "483393536"
          envFrom:
            - secretRef:
                name: mimir-s3-secret
          image: grafana/mimir:2.11.0
          imagePullPolicy: IfNotPresent
          name: store-gateway
          ports:
            - containerPort: 8080
              name: http-metrics
              protocol: TCP
            - containerPort: 9095
              name: grpc
              protocol: TCP
            - containerPort: 7946
              name: memberlist
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ready
              port: http-metrics
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 461Mi
            requests:
              cpu: 48m
              memory: 461Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/mimir
              name: config
            - mountPath: /var/mimir
              name: runtime-config
            - mountPath: /data
              name: storage
            - mountPath: /active-query-tracker
              name: active-queries
      dnsPolicy: ClusterFirst
      nodeSelector:
        topology.kubernetes.io/region: nbg1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: mimir
      serviceAccountName: mimir
      terminationGracePeriodSeconds: 240
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/component: store-gateway
              app.kubernetes.io/instance: mimir
              app.kubernetes.io/name: mimir
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      volumes:
        - configMap:
            defaultMode: 420
            items:
              - key: mimir.yaml
                path: mimir.yaml
            name: mimir-config
          name: config
        - configMap:
            defaultMode: 420
            name: mimir-runtime
          name: runtime-config
        - emptyDir: {}
          name: active-queries
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
```

**Comment by andyasp** [comment]
I can't reproduce that error. That would be expected if that pod was still running an older image. Double check the pod itself with `kubectl`.

To verify it for myself, I wrote a `test-values.yaml` file containing only:
```yaml
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          send_content_md5: true
```
Then ran `helm install -n mimir-test mimir grafana/mimir-distributed --version 5.2.0 -f test-values.yaml`. It all came up as expected. To triple check I port forwarded with `kubectl -n mimir-test port-forward pod/mimir-store-gateway-zone-a-0 8080:8080` then `curl localhost:8080/config | rg send_content_md5` showed it set.
