### ISSUE TITLE
Logs cluster label cannot be customized in helm chart

### ISSUE THREAD

**Issue by ian-lmcb** [grafana/mimir#7412]
#### Describe the bug
The mimir helm chart templates for metamonitoring logs uses `"mimir.clusterName"` for the `cluster` label which resolves to the `.Release.name` value in non-GEM installs afaict and thus the `cluster` label cannot be configured it appears.

Looks like this same issue used to affect metrics per #2084 (and https://github.com/grafana/helm-charts/issues/1387) and was resolved by adding `metaMonitoring.serviceMonitor.clusterLabel` in `values.yaml` and using it in the `ServiceMonitor` templates per #2125 and #4126.

#### To Reproduce

1. Write a helm chart values config with meta monitoring enabled
2. Include metrics and logs for comparison
3. Specify `metaMonitoring.serviceMonitor.clusterLabel` with a name different from name to be used in the helm release install, e.g. `"my-mimir-cluster"`
4. Install mimir via helm with a release name different from the `clusterLabel`, e.g. `my-mimir-helm-release`

```yaml
# ... other mimir helm chart config

metaMonitoring:
  serviceMonitor:
    enabled: true
    clusterLabel: "my-mimir-cluster"
  grafanaAgent:
    enabled: true
    installOperator: true
    logs:
      remote:
        url: "http://my-loki:3100/loki/api/v1/push"
```

```shell
helm -n my-mimir-namespace install my-mimir-helm-release grafana/mimir-distributed
```

5. Observe metrics are labeled with `cluster="my-mimir-cluster"` while logs are labeled with `cluster="my-mimir-helm-release"`

#### Expected behavior

Either the helm innstall also uses the `metaMonitoring.serviceMonitor.clusterLabel` for the cluster label on logging in addition to metrics or the `values.yaml` provides another mechanism for customizing the `cluster` label on logs similar to `serviceMonitor`.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm
