### ISSUE TITLE
Ruler APIs not working when configured with S3 storage

### ISSUE THREAD

**Issue by jseparovic** [grafana/mimir#7434]
#### Describe the bug
After configuring ruler with S3 storage, I expected all of the documented ruler APIs to work.
I have auth enabled and am passing in the X-Scope-OrgID header.

However, only the rule_groups API works, the rest return 404. (/api/v1/alerts works fine)

Works: 
`GET /ruler/rule_groups` (headers: "X-Scope-OrgID: myOrg")

Doesn't Work (404):
`GET /api/v1/rules` (headers: "X-Scope-OrgID: myOrg")
`GET /config/v1/rules` (headers: "X-Scope-OrgID: myOrg")
`POST /config/v1/rules/{namespace}` (headers: "X-Scope-OrgID: myOrg")
![image](https://github.com/grafana/mimir/assets/4665758/bc65727b-d201-4155-958c-c63e321c58d4)

#### To Reproduce

1. Start Mimir (SHA or version)
2. Perform Operations(Read/Write/Others)

#### Expected behavior

Expected APIs to be there.

#### Environment

Mimir Config File: note jinja2 variables below are replaced prior to bring up the containers:
```
# Run Mimir in single process mode, with all components running in 1 process.
target: all,alertmanager,overrides-exporter

multitenancy_enabled: true

# Configure Mimir to use Minio as object storage backend.
common:
  storage:
    backend: s3
    s3:
      endpoint: {{ minio.host }}:9000
      access_key_id: {{ minio.user }}
      secret_access_key: {{ minio.password }}
      insecure: true
      bucket_name: mimir

blocks_storage:
  tsdb:
    dir: /data/mimir/tsdb

  bucket_store:
    sync_dir: /data/mimir/tsdb-sync

  backend: s3 
  
  #filesystem:
  #  dir: /data/tsdb

compactor:
  data_dir: /data/mimir/compactor
  sharding_ring:
    kvstore:
      store: inmemory

ruler:
  enable_api: true
  alertmanager_url: http://127.0.0.1/alertmanager

ruler_storage:
  backend: s3
  s3:
    bucket_name: mimir-ruler

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

store_gateway:
  sharding_ring:
    replication_factor: 1

server:
  http_listen_port: 80
  log_level: debug

limits:
  out_of_order_time_window: 24h
  max_label_names_per_series: 100

alertmanager:
  enable_api: true
  data_dir: /data/mimir/alertmanager
  fallback_config_file: /etc/alertmanager.yaml
  external_url: https://alertmanager.admin.{{ common.fqdn }}

alertmanager_storage:
  backend: filesystem


```

#### Additional Context

Docker Compose file:
```
version: '3.7'
name: cloud-prometheus

services:
  cloud-minio:
    container_name: cloud-minio
    hostname: cloud-minio
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - cloud_minio_data:/data
    networks:
      - cloud
        
  cloud-minio-setup:
    container_name: cloud-minio-setup
    hostname: cloud-minio-setup
    image: minio/minio
    depends_on:
      - cloud-minio
    entrypoint: >
      /bin/sh -x -c "
      /usr/bin/mc alias set myminio http://cloud-minio:9000 minio minio123;
      /usr/bin/mc mb myminio/mimir-ruler;
      /usr/bin/mc policy set public myminio/mimir-ruler;
      sleep 60;
      exit 0
      "
    networks:
      - cloud

  cloud-mimir:
    container_name: cloud-mimir
    hostname: cloud-mimir
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    depends_on:
      - cloud-minio
    volumes:
      - ./mimir/mimir.yaml:/etc/mimir.yaml
      - ./mimir/alertmanager.yaml:/etc/alertmanager.yaml
      - cloud_mimir_data:/data
    networks:
      - cloud

  cloud-prometheus:
    container_name: cloud-prometheus
    hostname: cloud-prometheus
    image: prom/prometheus:v2.49.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - cloud_prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
    links:
      - cloud-cadvisor:cloud-cadvisor
    depends_on:
      - cloud-cadvisor
    networks:
      - cloud
    restart: always

  cloud-node-exporter:
    container_name: cloud-node-exporter
    hostname: cloud-node-exporter
    image: quay.io/prometheus/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - cloud
    restart: always
    deploy:
      mode: global

  cloud-cadvisor:
    container_name: cloud-cadvisor
    hostname: cloud-cadvisor
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - cloud
    restart: always
    deploy:
      mode: global

  cloud-grafana:
    container_name: cloud-grafana
    hostname: cloud-grafana
    image: grafana/grafana
    user: "472"
    depends_on:
      - cloud-prometheus
    volumes:
      - cloud_grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    networks:
      - cloud
    restart: always

networks:
  cloud:
    name: cloud
    driver: bridge

volumes:
  cloud_minio_data:
    external: true
  cloud_mimir_data:
    external: true
  cloud_prometheus_data:
    external: true
  cloud_grafana_data:
    external: true
```

Log doesn't indicate what's wrong:
```
cloud-mimir  | ts=2024-02-21T09:11:26.756691678Z caller=logging.go:122 level=debug traceID=3a8cc21b85a60bbe msg="POST /config/v1/rules/MyGroupName (404) 106.711µs"
cloud-mimir  | ts=2024-02-21T09:11:29.460488797Z caller=logging.go:122 level=debug traceID=67f8242b5facb010 msg="GET /config/v1/rules (404) 76.484µs"
cloud-mimir  | ts=2024-02-21T09:11:34.379549836Z caller=logging.go:122 level=debug traceID=4c6eb5a212fe2290 msg="GET /api/v1/rules (404) 82.125µs"

```

![image](https://github.com/grafana/mimir/assets/4665758/2c858623-43dc-4521-bd42-7254abf6ca44)
