### ISSUE TITLE
Azure Workload Identity not working for mimir

### ISSUE THREAD

**Issue by jiragrid** [grafana/mimir#7447]
#### Describe the bug
I've implemented federated identity and configured Mimir to utilize Azure workload identity. Everything seems to be set up correctly in the environment. However, the pods are crashing due to authentication issues with the identity. I'm utilizing this setup to connect to a storage account. I can confirm that the Storage account and Managed Identity are still present. The Managed Identity is assigned the Contributor role for the Storage Account.

#### To Reproduce

1. Deploy Mimir by helm.

#### Expected behavior

All pods can running
#### Environment

- Infrastructure: AKS, Storage account, Manage Identity
- Deployment tool: helm

#### Additional Context
Mimir version : 2.11
AKS version: v1.26

<img width="1440" alt="image" src="https://github.com/grafana/mimir/assets/32784982/b1d8c69f-d600-4186-9646-9f79ff43aa07">

<img width="815" alt="image" src="https://github.com/grafana/mimir/assets/32784982/01921eaf-dc68-4647-a404-d1c575bd6071">

**Comment by etiennetremel** [comment]
@jiragrid from the logs, I do see it tries to call the system assigned identity endpoint.

Could it be that the client id is defined in your config? for workload identity, the client id should be omitted.

Below is the config I'm using with the mimir-distributed Helm chart, replace client id and account name with yours:

```yaml
global:
  podLabels:
    azure.workload.identity/use: "true"
serviceAccount:
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "00000000-0000-0000-0000-000000000000"
mimir:
  structuredConfig:
    common:
      storage:
        backend: azure
        azure:
          account_name: my-storage-account
          endpoint_suffix: blob.core.windows.net
    blocks_storage:
      backend: azure
      azure:
        container_name: mimir-blocks
    alertmanager_storage:
      azure:
        container_name: mimir-alertmanager
    ruler_storage:
      azure:
        container_name: mimir-ruler
```
