### ISSUE TITLE
The bucket you are attempting to access must be addressed using COS virtual-styled domain

### ISSUE THREAD

**Issue by east4ming** [grafana/mimir#7512]
#### Describe the bug
I use Tencent Cloud COS(S3 compatible storage) as the storage backend, configured as follows:

```yaml
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: cos.ap-shanghai.myqcloud.com
          region: ap-shanghai
          secret_access_key: 'xxxxx' # This is a secret injected via an environment variable
          access_key_id: 'xxxxx' # This is a secret injected via an environment variable

    blocks_storage:
      s3:
        bucket_name: mimir-blocks-xxxxx
    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager-xxxxx
    ruler_storage:
      s3:
        bucket_name: mimir-ruler-xxxxx

```

After startup, the error is reported as follows:

```log
ts=2024-03-01T06:41:37.611006741Z caller=sanity_check.go:41 level=error msg="Unable to successfully connect to configured object storage" err="alertmanager storage: unable to successfully send a request to object storage: The bucket you are attempting to access must be addressed using COS virtual-styled domain"
```

#### To Reproduce

1. Config Mimir Helm , using Tencent Cloud COS(S3 compatible storage) ,like above
2. Helm install
3. pod CrashLoopBackOff/Error

#### Expected behavior

Support virtual-style s3 config.
Or can my configuration be modified to fix this problem?

#### Environment

- Infrastructure: 
  - S3: Tencent Cloud COS
- Helm

#### Additional Context

 [Domain name compliance issues | COS | TencentCloud](https://cloud.tencent.com/document/faq/436/102489)

On this page, there is the following description:

> # path-style domain name related issues
> 
> ## 1. Does COS bucket support path-style domain names?
> 
> To ensure the security and stability of the overall service, path-style domain names are not supported for buckets created after January 1, 2024. Buckets created before January 1, 2024 will not be affected. Path-style domain names are supported, but virtual-hosted-style domain names are recommended to be used first.

And, I created these buckets after January 1, 2024.
