### ISSUE TITLE
Meta-monitoring grafana agent crashing: no such file or directory

### ISSUE THREAD

**Issue by nosalan** [grafana/mimir#7531]
#### Describe the bug
A statefulset pod named `mimir-meta-monitoring-0`, which is probably created by the grafana agent operator, is crashing with the following error: 
`error loading config file /var/lib/grafana-agent/config/agent.yml: error reading config file open /var/lib/grafana-agent/config/agent.yml: no such file or directory`

Other pods are running:
![image](https://github.com/grafana/mimir/assets/2273250/19bab6d8-012b-4768-a071-bea458e701b6)

#### To Reproduce
1. Installed the latest helm release `mimir-distributed-5.2.1`
2. Configured the meta monitoring in helm chart:
```
  metaMonitoring:
    serviceMonitor:
      enabled: true
    grafanaAgent:
      enabled: true
      installOperator: true
      logs:
        enabled: false
      metrics:
        enabled: true
      imageRepo:
        # Due to bad mimir chart design, I had to put whole configs below in order to overwrite JUST the container registry.
        configReloader:
          repo: quay.io # updated at runtime
          image: prometheus-operator/prometheus-config-reloader
          tag: v0.47.0
        grafanaAgent:
          repo: docker.io # updated at runtime
          image: grafana/agent
          tag: v0.29.0
```
other helm values are pretty standard.

#### Expected behavior

Service is running, mimir charts are working

#### Environment

- Infrastructure: Kubernetes, bare-metal, laptop
- Deployment tool: helm
