### ISSUE TITLE
Mimir Read Latency Errors (MimirCacheRequestErrors & MimirRequestLatency)

### ISSUE THREAD

**Issue by james3cardenas** [grafana/mimir#7652]
#### Describe the bug
I'm trying to understand how best to improve our Mimir read request latency and have been unable to make much progress on resolving the following error alerts for long range queries (ex. 30 days). 

Details below (any additional details available upon request): 

**_MimirCacheRequestErrors_**
The cache index-cache used by Mimir grafana-mimir/devops-prod is experiencing 7.79% errors for getmulti operation.
The cache chunks-cache used by Mimir grafana-mimir is experiencing 97.13% errors for getmulti operation.
The cache chunks-cache used by Mimir grafana-mimir is experiencing 66.55% errors for set operation.

Scaling the memcached cluster doesn't seem to resolve the timeouts. The timeouts are reduced if I increase the store-gateway's memcached client timeout, however memcached get/set latency seems to scale proportionally with this configuration, so adjusting this to something larger then 450ms seems unreasonable.  

**_MimirRequestLatency_**
querier prometheus_api_v1_query_range is experiencing 24.69s 99th percentile latency.
store-gateway /gatewaypb.StoreGateway/Series is experiencing 46.06s 99th percentile latency.

It's unclear to me whether fixing the memcached timeouts will help resolve this alert. I can sometimes see the Queue length panel suggesting we have queries that are waiting in queue due to busy queriers, and have considered scaling the queriers up but I want to be sure that this doesn't cause further issues downstream (ex. causing higher load on store-gateways, ingesters, and/or query frontend).

#### To Reproduce

1. Start Mimir 2.10.5
2. Perform Operations Read Operations

#### Expected behavior

I expect the MimirCacheRequestErrors & MimirRequestLatency not to trigger.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

#### Additional Context
values.yaml
```yaml
image:
  repository: grafana/mimir
  tag: 2.10.5

memcached:
  image:
    repository: memcached
    tag: 1.6.19-alpine

chunks-cache:
  replicas: 4
  port: 11211
  allocatedMemory: 8192
  maxItemMemory: 1

index-cache:
  replicas: 4
  port: 11211
  allocatedMemory: 2048
  maxItemMemory: 5

metadata-cache:
  replicas: 1
  port: 11211
  allocatedMemory: 512
  maxItemMemory: 1

results-cache:
  replicas: 4
  port: 11211
  allocatedMemory: 1024
  maxItemMemory: 5

store_gateway:
  replicas: 6
  resources:
    limits:
      memory: 8.5Gi
    requests:
      cpu: 1
      memory: 6Gi

ingester:
  replicas: 15
  resources:
    limits:
      cpu: 5
      memory: 12Gi
    requests:
      cpu: 3.5
      memory: 8Gi

querier:
  replicas: 4
  resources:
    limits:
      cpu: 2
      memory: 12Gi
    requests:
      cpu: 2
      memory: 8Gi

query_frontend:
  replicas: 3
  resources:
    limits:
      cpu: 2
      memory: 2.8Gi
    requests:
      cpu: 2
      memory: 2Gi

query_scheduler:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
```
mimir.yaml
```yaml

blocks_storage:
  backend: s3
  bucket_store:
    chunks_cache:
      backend: memcached
      memcached:
        addresses: dns+grafana-mimir-chunks-cache.prod.svc:11211
        max_idle_connections: 150
        max_item_size: 1048576
        timeout: 450ms
        tls_enabled: true
    index_cache:
      backend: memcached
      memcached:
        addresses: dns+grafana-mimir-index-cache.prod.svc:11211
        max_idle_connections: 150
        max_item_size: 5242880
        timeout: 450ms
        tls_enabled: true
    metadata_cache:
      backend: memcached
      memcached:
        addresses: dns+grafana-mimir-metadata-cache.prod.svc:11211
        max_idle_connections: 150
        max_item_size: 1048576
        tls_enabled: true
  
common:
  storage:
    backend: s3

frontend:
  cache_results: true
  grpc_client_config:
    tls_enabled: true
  parallelize_shardable_queries: true
  query_result_response_format: protobuf
  query_sharding_target_series_per_shard: 2500
  
  results_cache:
    backend: memcached
    memcached:
      addresses: dns+grafana-mimir-results-cache.prod.svc:11211
      max_item_size: 1048576
      timeout: 500ms
      tls_enabled: true
  scheduler_address: grafana-mimir-query-scheduler-headless.prod.svc:9095
frontend_worker:
  grpc_client_config:
    max_send_msg_size: 419430400
    tls_enabled: true
  scheduler_address: grafana-mimir-query-scheduler-headless.prod.svc:9095

limits:
  cardinality_analysis_enabled: true
  max_cache_freshness: 10m
  max_query_parallelism: 240
  max_total_query_length: 12000h
  native_histograms_ingestion_enabled: true

querier:
  max_concurrent: 16
  store_gateway_client:
    tls_enabled: true

query_scheduler:
  grpc_client_config:
    tls_enabled: true
  max_outstanding_requests_per_tenant: 800


server:
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_connection_age: 2m
  grpc_server_max_connection_age_grace: 5m
  grpc_server_max_connection_idle: 1m
  
usage_stats:
  enabled: false
  installation_mode: helm
```
![Screen Shot 2024-03-18 at 3 02 10 PM](https://github.com/grafana/mimir/assets/5607302/9f5d3cbc-b7d3-4fc4-b087-188afd72e930)
![Screen Shot 2024-03-18 at 3 07 17 PM](https://github.com/grafana/mimir/assets/5607302/f9981d5a-1b1e-414a-8309-2da1b2dfa2db)
![Screen Shot 2024-03-18 at 3 10 36 PM](https://github.com/grafana/mimir/assets/5607302/99942e70-e248-4407-b1c8-29f86f2a3420)
![Screen Shot 2024-03-18 at 3 04 21 PM](https://github.com/grafana/mimir/assets/5607302/43d9e62f-87bc-41e7-90b4-47399f466590)
![Screen Shot 2024-03-18 at 3 04 37 PM](https://github.com/grafana/mimir/assets/5607302/d2c44798-6f0e-4124-a720-5df2c8767809)
![Screen Shot 2024-03-18 at 3 05 13 PM](https://github.com/grafana/mimir/assets/5607302/d021c2c1-2bb4-4d93-a92d-e85bbf89d984)

**Comment by 56quarters** [comment]
> **_MimirCacheRequestErrors_** The cache index-cache used by Mimir grafana-mimir/devops-prod is experiencing 7.79% errors for getmulti operation. The cache chunks-cache used by Mimir grafana-mimir is experiencing 97.13% errors for getmulti operation. The cache chunks-cache used by Mimir grafana-mimir is experiencing 66.55% errors for set operation.
> 

Internally at Grafana, we use `750ms` for both the index cache and chunks cache (these are the highest traffic caches). I've been meaning to change the values in the OSS jsonnet and Helm chart.

> Scaling the memcached cluster doesn't seem to resolve the timeouts. The timeouts are reduced if I increase the store-gateway's memcached client timeout, however memcached get/set latency seems to scale proportionally with this configuration, so adjusting this to something larger then 450ms seems unreasonable. 

To me this seems to indicate that timeout is too short and so you're continuing to hit it at the p99 and will until you set it to something larger than however long the operations are taking. 

I notice that you have TLS enabled for the cache connections. The default values are picked with plaintext connections in mind, assuming that creating a new connection is basically "free".

With TLS, you'll likely need to:
* Increase the connection timeouts to something like `1s` (this is what the [Jsonnet](https://github.com/grafana/mimir/blob/8f05c1cedf041bf47b2a33f8ef2a4fbdcf69a427/operations/mimir/config.libsonnet#L703-L711) does): `memcached.connect_timeout: 1s`
* Give Memcached more CPU (default is 0.5 cores)
* Give the store-gateways more CPU

**Comment by james3cardenas** [comment]
Much appreciated for the response @56quarters!

I made the following adjustments based on your suggestions (starting at 12:15 in the graphs below):
```yaml
    blocks_storage:
      bucket_store:
        chunks_cache:
          memcached:
            timeout: 750ms
            connect_timeout: 1s
        index_cache:
          memcached:
            timeout: 750ms
            connect_timeout: 1s
```
This seems to have helped a bit — more so for the index-cache. We don't currently have a CPU limit set on our chunks-cache — you can see from the graphs some pods use upward of 2-3 CPUs under heavy load.  Still, the MimirCacheRequestErrors is triggering often, predominately for getmulti operations it seems. **The getmulti p99 seems to be hitting an upperbound still, perhaps indicating the timeout needs to be increased further to facilitate the longer read i/o ops?**

```
The cache chunks-cache used by Mimir grafana-mimir/devops-stg is experiencing 65.21% errors for getmulti operation.
```
![Screen Shot 2024-03-19 at 4 10 21 PM](https://github.com/grafana/mimir/assets/5607302/81f53d61-7c8c-4a0e-ad7e-5890ec077f9d)
![Screen Shot 2024-03-19 at 3 12 52 PM](https://github.com/grafana/mimir/assets/5607302/78f30e5d-f3c6-44af-a238-212a58da0249)
![Screen Shot 2024-03-19 at 3 18 13 PM](https://github.com/grafana/mimir/assets/5607302/3578bd30-820c-4b85-9e96-36186d6df901)

In addition to the timeout configs, increasing store-gateway CPU resource request from 1 -> 2 (starting at 15:00 in the graphs below) doesn't seem to have much impact.

Logs from the store-gateway more frequently display the following with or without the additional CPU power:
```
caller=client.go:144 level=debug msg="failed to store item to cache because the async buffer is full" err="the async queue is full" size=25000
caller=client.go:129 level=debug msg="failed to store item to cache" key=subrange:prod/01HQEZC3CD5XD6NRYXKAV5B9ST/chunks/000001:19024000:19040000 sizeBytes=16000 err="read tcp 10.42.34.219:33812->10.42.34.214:11211: i/o timeout"
```

**What are the possible implications of increasing ```max_async_buffer_size```, should we consider increasing this? My guess is that this would only exacerbate our Memcached timeout issues.** 

![Screen Shot 2024-03-19 at 4 06 44 PM](https://github.com/grafana/mimir/assets/5607302/8376e161-0894-4cca-a0d8-c985a1cfce51)
![Screen Shot 2024-03-19 at 4 06 32 PM](https://github.com/grafana/mimir/assets/5607302/cff5fbd2-4b9e-4ea7-a351-8c4a4b1ada90)

**On occasion I do see MimirSchedulerQueriesStuck getting trigger, an issue I'm assuming we can easily solve by scaling up our querier replicas?**
