### ISSUE TITLE
per-tenant `max_total_query_length` not overriding global limit

### ISSUE THREAD

**Issue by alexanderldavis** [grafana/mimir#7686]
#### Describe the bug

When trying to override the total query time range limit on a per-tenant basis, we continue to get the error

`bad_data: the total query time range exceeds the limit (query length: 43848h0m0s, limit: 6144h0m0s) (err-mimir-max-total-query-length). To adjust the related per-tenant limit, configure -query-frontend.max-total-query-length, or contact your service administrator.`

#### To Reproduce

1. In our case, the global limit on the Mimir datasource is 256d (6144h0m0s):

```yaml
mimir:
  structuredConfig:
    limits:
      max_total_query_length: 256d
```

and we are configuring the per-tenant override set to 10y:

```yaml
runtimeConfig:
  overrides:
    specialTenant:
      max_total_query_length: 3650d
```

2. When looking at the query frontend config that is deployed, we see the `max_total_query_length` override is being set correctly.
3. Run a query over 5 years of data. The `bad_data: the total query time range exceeds the limit` will appear.

#### Expected behavior

`max_total_query_length` should be configurable on a per-tenant basis, so that certain tenants allow for longer query windows than the global limit.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

On Grafana Mimir v2.10.x
