### ISSUE TITLE
Support podAnnotations for minio pods

### ISSUE THREAD

**Issue by bilsch-nice** [grafana/mimir#7703]
#### Is your feature request related to a problem? Please describe.

I'm trying to run mimir-distributed with istio and mutual tls enabled. The minio pods are failing to start up so I wanted to disable the sidecar injection via an annotation however there is no option to do so.

with mutual tls enabled I have the following for get pods:

```
❯ kubectl get pods -n mimir
NAME                                        READY   STATUS     RESTARTS   AGE
mimir-alertmanager-0                        2/2     Running    0          11m
mimir-compactor-0                           2/2     Running    0          11m
mimir-distributor-547b984dd-l2x49           2/2     Running    0          11m
mimir-ingester-zone-a-0                     2/2     Running    0          11m
mimir-ingester-zone-b-0                     2/2     Running    0          11m
mimir-ingester-zone-c-0                     2/2     Running    0          11m
mimir-make-minio-buckets-5.0.14-4xbpz       1/2     NotReady   0          11m
mimir-minio-c7ff58477-k486l                 2/2     Running    0          11m
mimir-minio-post-job-lzgtr                  1/3     NotReady   0          11m
mimir-nginx-6b7668cbdb-b8kz4                2/2     Running    0          11m
mimir-overrides-exporter-74877c8585-v85xz   2/2     Running    0          11m
mimir-querier-75675d56db-dbrx4              2/2     Running    0          11m
mimir-querier-75675d56db-vp45l              2/2     Running    0          11m
mimir-query-frontend-547c4dcf5f-8kxbs       2/2     Running    0          11m
mimir-query-scheduler-965567cf4-mzqfs       2/2     Running    0          11m
mimir-query-scheduler-965567cf4-qq69d       2/2     Running    0          11m
mimir-rollout-operator-5675df6d94-tjl42     2/2     Running    0          11m
mimir-ruler-f56868948-k4v99                 2/2     Running    0          11m
mimir-store-gateway-zone-a-0                2/2     Running    0          11m
mimir-store-gateway-zone-b-0                2/2     Running    0          11m
mimir-store-gateway-zone-c-0                2/2     Running    0          11m
```

#### Describe the solution you'd like

Somewhere in [values.yaml](https://github.com/grafana/mimir/blob/f8f4be0724a06ee3eac61daf1de779e5806a9420/operations/helm/charts/mimir-distributed/values.yaml#L2321) add podAnnotations similar to how we can with [nginx](https://github.com/grafana/mimir/blob/f8f4be0724a06ee3eac61daf1de779e5806a9420/operations/helm/charts/mimir-distributed/values.yaml#L2395C3-L2395C17)

The yaml would look something like this:

```
  minio:
    enabled: true
    podLabels:
      sidecar.istio.io/inject: false
```

#### Describe alternatives you've considered

The only other alternative is to disable mutual tls injection on the entire namespace

#### Additional context

n/a

**Comment by narqo** [comment]
Mimir doesn't itself provisions minio. Instead `minio` is installed as the chart's [dependency][1]. You can pass any values `minio` chart supports, as normal values. E.g.

```
% helm template test-mimir . --set 'minio.podAnnotations.foo=bar'

···
  ---
  # Source: mimir-distributed/charts/minio/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: test-mimir-minio
    labels:
      app: minio
      chart: minio-5.0.14
      release: test-mimir
      heritage: Helm
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: minio
        release: test-mimir
    template:
      metadata:
        name: test-mimir-minio
        labels:
          app: minio
          release: test-mimir
        annotations:
          foo: bar # 👈 Note the "foo=bar" annotation
```

[1]: https://helm.sh/docs/helm/helm_dependency/#helm
