### ISSUE TITLE
Non-ingesters fail to validate config with spread-minimizing token generation strategy

### ISSUE THREAD

**Issue by euroelessar** [grafana/mimir#7822]
#### Describe the bug
Non-ingester components fail to validate mimir config if `ingester.ring.token_generation_strategy` is set to `spread-minimizing`:
```
error validating config: invalid ingester config: unable to extract instance id from "mimir-query-scheduler-55f8bb8f9b-48pgb"
```

#### To Reproduce

Helm chart version: 5.2.1 (mimir-distributed)
Mimir version: 2.11

Add the following to the chart values:
```
mimir:
  structuredConfig:
    ingester:
      ring:
        tokens_file_path: ''
        token_generation_strategy: spread-minimizing
        spread_minimizing_zones: az-1,az-2,az-3
        spread_minimizing_join_ring_in_order: true
```

All components, except ingester, will start crashing on startup with:
```
error validating config: invalid ingester config: unable to extract instance id from "mimir-query-scheduler-55f8bb8f9b-48pgb"
```

#### Expected behavior

Non-ingester components should ignore instance id as this part of config is not relevant to them.

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

**Comment by rknightion** [comment]
I had similar issues recently I think: https://github.com/grafana/mimir/discussions/7708

**Comment by dimitarvdimitrov** [comment]
A workaround would be to set the four config options to enable spread-minimizing tokens as CLI flags to the ingester statefulset: ingester.extraArgs in the values.yaml. This way the distributor wouldn't see this config and wouldn't try to validate the ingester config.

```
ingester:
  extraArgs:
    ingester.ring.tokens-file-path: ""
    ingester.ring.token-generation-strategy: spread-minimizing
    ingester.ring.spread-minimizing-zones: 1a,1b,1c
    ingester.ring.spread-minimizing-join-ring-in-order: true
```
