### ISSUE TITLE
Improving the Helm chart to integrate external object storage with Mimir.

### ISSUE THREAD

**Issue by mohammadll** [grafana/mimir#7952]
A few days ago, I was trying to integrate my external object storage with Mimir using the `grafana/mimir-distributed` Helm chart, but it was a little confusing because it was necessary to copy the whole `mimir.config` configuration and then modify `alertmanager_storage`, `blocks_storage`, and `ruler_storage`. It would be better if there were a separate section like `mimir.storage` to configure storage and bucket names once.

Example:

    storage:
      bucketNames:
        tsdb: <NAME>
        ruler: <NAME>
    type: s3
    s3:
      endpoint: <URL>
      secretAccessKey: <SECRET-KEY>
      accessKeyId: <ACCESS-KEY>

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

**Comment by narqo** [comment]
The Helm chart [provides `mimir.structuredConfig`][1], which allows overriding individual chunks of the config. For your examples, it would look like this:

```yaml
# values.yaml

mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
      s3:
        endpoint: <URL>
        secret_access_key: <SECRET-KEY>
        access_key_id: <ACCESS-KEY>
    alertmanager_storage:
      s3:
        bucket_name: <NAME>
    ruler_storage:
      s3:
        bucket_name: <NAME>
```

Another option to fine-tune the parameters of individual mimir modules is to pass them as flags via `<module>.extraArgs`. This is what we prefer doing with jsonnet (that we use in our infrastructure).

[1]: https://github.com/grafana/mimir/blob/91dd4380e5c82b883396dee4bb3f485ca924def6/operations/helm/charts/mimir-distributed/values.yaml#L426-L444
