### ISSUE TITLE
Querier "connection termination" to query-frontend with vanilla deployment of mimir-distributed helm chart

### ISSUE THREAD

**Issue by SeanKilleen** [grafana/mimir#7963]
#### Describe the bug

I have a (I think?) relatively straightforward installation of the `mimir-distributed` helm chart.

Upon deploying it, the querier appears to be unable to contact the query-frontend.

sample logs from the querier container
```
ts=2024-04-23T18:03:17.693470735Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.071927164Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.253604285Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.359267982Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
ts=2024-04-23T18:03:18.403495138Z caller=frontend_processor.go:91 level=error msg="error processing requests" address=100.64.3.196:9095 err="rpc error: code = Unavailable desc = upstream connect error or disconnect/reset before headers. reset reason: connection termination"
```

and from the query-frontend:

```
 ts=2024-04-23T18:04:01.135792002Z caller=frontend.go:358 level=info msg="not ready: number of queriers connected to query-frontend is 0"
ts=2024-04-23T18:04:01.135902602Z caller=frontend.go:358 level=info msg="not ready: number of queriers connected to query-frontend is 0"
```

#### To Reproduce
Steps to reproduce the behavior -- note I already have a minio instance running and once I added the config there appear to be no errors around this.

mimir.tftpl (modified via terraform's `templatefile` command):

```yaml
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          bucket_name: "${S3_BUCKET_NAME}"
          endpoint: "${S3_ENDPOINT}"
          access_key_id: "${S3_ACCESS_KEY_ID}"
          secret_access_key: "${S3_SECRET_ACCESS_KEY}"
          insecure: true
          http:
            insecure_skip_verify: true
ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false
querier:
  replicas: 1
minio:
  enabled: false
alertmanager:
  enabled: false
ruler:
  enabled: false
vaultAgent:
  enabled: false
overrides_exporter:
  enabled: false
query_scheduler:
  enabled: false
```

the Terraform for the chart: 

```hcl
locals {
  grafana_mimir_template = templatefile("helm_chart_values/grafana_mimir.tftpl", {
    S3_ACCESS_KEY_ID     = kubernetes_secret.minio_creds.data["root-user"]
    S3_SECRET_ACCESS_KEY = var.minio_root_password
    S3_BUCKET_NAME       = "mimir"
    S3_ENDPOINT          = "${helm_release.minio_mimir[0].name}.${helm_release.minio_mimir[0].namespace}.svc.cluster.local:9000"
  })
}

resource "helm_release" "mimir" {
  count = var.uses_mimir ? 1 : 0

  depends_on = [kubernetes_namespace.o11y, helm_release.minio_mimir]
  name       = "mimir"
  namespace  = kubernetes_namespace.o11y.metadata[0].name
  repository = "https://grafana.github.io/helm-charts"
  chart      = "mimir-distributed"
  version    = "5.2.3" # I tried with 5.3 first and then moved backward.

  values = ["${local.grafana_mimir_template}"]
```

#### Expected behavior

The Helm chart to be deployed successfully and an instance of Mimir to be up and running without seeing errors in the querier and query-frontend

#### Environment

- Infrastructure: Kubernetes (SAP BTP Kyma)
- Deployment tool: Helm chart via Terraform

**Comment by SeanKilleen** [comment]
ℹ️ I removed some of the complexity by allowing mimir to create the Minio instance as well. The issue still persists with the below configuration:

helm chart values:

```yaml
ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
store_gateway:
  zoneAwareReplication:
    enabled: false
querier:
  replicas: 1
  extraArgs:
    "log.level": "debug"
minio:
  enabled: true
alertmanager:
  enabled: false
ruler:
  enabled: false
vaultAgent:
  enabled: false
overrides_exporter:
  enabled: false
query_scheduler:
  enabled: false
```

and the helm chart:

```hcl
resource "helm_release" "mimir" {
  count = var.uses_mimir ? 1 : 0

  depends_on = [kubernetes_namespace.o11y]
  name       = "mimir"
  namespace  = kubernetes_namespace.o11y.metadata[0].name
  repository = "https://grafana.github.io/helm-charts"
  chart      = "mimir-distributed"
  version    = "5.2.3"

  values = ["${local.grafana_mimir_template}"]

  set {
    name  = "minio.rootUser"
    value = kubernetes_secret.minio_creds.data["root-user"]
  }

  set {
    name  = "minio.rootPassword"
    value = var.minio_root_password
  }
```

No errors in other components that I can see, but error continuing on the querier.
