### ISSUE TITLE
Unable to deploy helm-chart mimir-distributed with ArgoCD when setting any of `rbac.podSecurityContext` to `null`

### ISSUE THREAD

**Issue by bo0ts** [grafana/mimir#8059]
#### Describe the bug

We configure `rbac` for `mimir-distributed` like this and deploy the chart through argocd.

```
rbac:
  create: true
  type: scc
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
```

and end up with the following error when the manifests are rendered by ArgoCD:

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm template . --name-template mimir --namespace grafana --kube-version 1.27 --values <path to cached source>/grafana-mimir/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: execution error at (mimir/charts/mimir-distributed/templates/validate.yaml:251:4): You have selected rbac.type=scc, you must set the values fsGroup, runAsGroup, runAsUser to null in rbac.podSecurityContext Use --debug flag to render out invalid YAML
```

This is caused by https://github.com/argoproj/argo-cd/issues/15566 and is clearly an issue on the side of `ArgoCD`.

Could the mimir-distributed helm chart be extended with a switch to disable validation to work around this issue?

#### To Reproduce
1. Try to deploy the helm chart mimir-distributed with argocd using the above settings
2. See the error in argocd.

#### Environment

* `mimir-distributed` `5.2.3`
* `argocd` `2.9.11`
* `k8s v1.27.1`

**Comment by bo0ts** [comment]
This is still an issue with the mimir-distributed chart `5.3.0` and ArgoCD `2.10.11`.

**Comment by narqo** [comment]
> You have selected rbac.type=scc, you must set the values fsGroup, runAsGroup, runAsUser to null in rbac.podSecurityContext

This seems to be a [documented issue](https://grafana.com/docs/helm-charts/mimir-distributed/latest/run-production-environment-with-helm/#deploy-on-openshift): one needs to null'ify the `rollout_operator.podSecurityContext` (which is the dependency of Mimir chart). Have you tried this set of values:

```yaml
rbac:
  create: false
  type: scc
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null

rollout_operator:
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
```

Note that the Mimir documentation mentions a bug in the `helm`, that doesn't allow resetting fields of dependencies. The issue seems to be resolved, although there are reports that mention it doesn't work in some cases.

Here is my testing scenario:

```
% helm version
version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"dirty", GoVersion:"go1.23.2"}

% helm template ./operations/helm/charts/mimir-distributed/ -f ./gh-mimir-8059-values.yaml

···
# Source: mimir-distributed/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-mimir
  labels:
    helm.sh/chart: mimir-distributed-5.5.0
    app.kubernetes.io/name: mimir
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.14.0"
    app.kubernetes.io/managed-by: Helm
  namespace: "default"
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  verbs:
    - use
  resourceNames:
    - release-name-mimir
···
```

Please, reopen the issue if this still doesn't work.

**Comment by narqo** [comment]
It seems that there are more bugs in Helm, that don't allow resetting values in the dependencies in some cases. What seems to work in my testing is adding the `mimir_distributed.rbac` and `mimir_distributed.rollout_operator` properties to the chart's default `values.yaml` AND don't pass the `--values values.yaml`, when the `values.yaml` is the one with the defaults.

That is

```
.
├── mimir
│  ├── charts/
│  │  └── mimir-distributed-5.5.1.tgz
│  ├── templates/
│  ├── Chart.lock
│  ├── Chart.yaml
│  └── values.yaml  // ❗️defaults for "mimir_distributed.rbac" and "mimir_distributed.rollout_operator" 
└── custom.yaml // other custom values

% helm template ./mimir -f custom.yaml
```

Example https://github.com/narqo/test-helm-mimir

> add a switch to disable the validate check

There is a reason for the validation to be there. What do you expect in result by letting the chart provision a set of Kubernetes resources, that aren't compatible with the infrastructure? That is, my understanding is that the default pod security context isn't compatible with OpenShift, because it sets arbitrary user and group IDs (as was [outlined here](https://github.com/grafana/mimir/pull/3457#issuecomment-1361179935)). Cannot tell if anything changed around OpenShift's details in the past years. But generally we cannot support a configuration, that allows a user to run a broken system.

I'll reopen the issue until we find a reasonable middle group on how to resolve it.

**Comment by bo0ts** [comment]
I've just tested the workaround you provided combined with a new ArgoCD version and it now works. Thanks a lot! This is good enough for us.

**Comment by vincentnonim** [comment]
Hi,

I just encounter this issue with the following error message in ArgoCD: 
```
Failed to load target state: failed to generate manifest for source 1 of 3: rpc error: code = Unknown desc = failed to execute helm template command: failed to get command args to log: `helm template . --name-template mimir --namespace cmp-mimir --kube-version 1.30 --values <path to cached source>/values/dev/values.yaml <api versions removed> --include-crds` failed exit status 1: Error: execution error at (mimir-distributed/templates/validate.yaml:259:4): You have selected rbac.type=scc, you must set the values fsGroup, runAsGroup, runAsUser to null in rollout_operator.podSecurityContext Use --debug flag to render out invalid YAML
```

My values.yaml looks like this:
```yaml
rbac:
  create: true
  type: scc
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
rollout_operator:
  podSecurityContext:
    fsGroup: null
    runAsGroup: null
    runAsUser: null
```

It was working fine using ArgoCD 2.14.13 and Helm 3.16.4 but after an ArgoCD update to 3.0.12 with Helm 3.17.1 it starts throwing the error.

I run the `helm template ... --debug` command with Helm 3.16 successfully but then it failed with Helm 3.17, so it's probably related to one of their changes.

I was not sure if this is a bug of Helm of something to change in the Mimir distributed chart.

Thanks for help.
