### ISSUE TITLE
Helm: Missing fields in Topology Spread Constraints

### ISSUE THREAD

**Issue by morsik** [grafana/mimir#8108]
[This template](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/lib/topologySpreadConstraints.tpl) doesn't provide way to specify `nodeTaintsPolicy` which is very important to specify not counting tainted nodes into spread calculation - and because of that I am unable to properly deploy Mimir using `topologySpreadConstraints` as I have 1 AZ specifically set to be tained due to high latency and it's used only for special 3rd-nodes-for-clustered-apps. Other fields like `matchLabelKeys` are also missing... :(

Maybe it would be just easier to get rid of this loop and just allow to define whatever I need? Because this issue may come back later if new features will be added into Kubernetes.

See: https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition

My config across all my apps that works good for my usecase:

```yaml
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    nodeTaintsPolicy: Honor
    labelSelector:
      matchLabels:
        app.kubernetes.io/component: compactor
    matchLabelKeys:
    - pod-template-hash
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    nodeTaintsPolicy: Honor
    labelSelector:
      matchLabels:
        app.kubernetes.io/component: compactor
    matchLabelKeys:
    - pod-template-hash
 ```
