### ISSUE TITLE
unable to run Mimir in single ingestor - `too many unhealthy instances in the ring`

### ISSUE THREAD

**Issue by kirankumar-grootan** [grafana/mimir#8253]
unable to run Mimir in single replica ingester via helm chart

```
mimir:
  structuredConfig:
    store_gateway:
      sharding_ring:
        replication_factor: 1
    ingester:
      ring:
        replication_factor: 1
  ingester:
    replicas: 1

```

when I run query from grafana it shows `too many unhealthy instances in the ring`. I dont need HA for dev cluster thats why Im reducing the ingester to 1
