### ISSUE TITLE
Add support for secrets in Alertmanager receivers

### ISSUE THREAD

**Issue by taobojlen** [grafana/mimir#8259]
#### Is your feature request related to a problem? Please describe.

I want to set up an Alertmanager receiver. This receiver needs a bearer token included in any requests, so I'd like to set a `credentials_file` as defined in the [Prometheus Alertmanager docs](https://prometheus.io/docs/alerting/latest/configuration/#http_config).

This is related to the discussion at https://github.com/grafana/mimir/discussions/5359.

#### Describe the solution you'd like

Basically, exactly what is specified in the Prometheus Alertmanager docs. Something that would allow me to use an existing Helm secret, e.g. with
```
alertmanager:
  extraVolumes:
    - name: webhook-token
       secret:
         secretName: webhook-token
  extraVolumeMounts:
    - name: webhook-token
       mountPath: /etc/secrets/webhook_token
       subpath: token
       readOnly: true
  fallbackConfig: |
    receivers:
      - name: my_webhook
         webhook_configs:
           - url: https://example.com
              http_config:
                authorization:
                  credentials_file: /etc/secrets/webhook_token
```

#### Describe alternatives you've considered

Alternatively, the ability to read from environment variables could work.
