### ISSUE TITLE
Unable to deploy helm-chart mimir-distributed EKS ipv6

### ISSUE THREAD

**Issue by francisko-it** [grafana/mimir#8325]
#### Describe the bug
I deployed the helm chart on a EKS with  ipv6, but some component crash with the error:

`"error getting addresses for interface" inf=en0 err="route ip+net: no such network interface"`

#### To Reproduce

1. Install EKS in ipv6 mode
2. install helm chart grafana/mimir-distributed version 5.4.0-weekly.293

#### Environment

- Infrastructure: EKS 1,29 , vpc ipv6
- Deployment tool: Helm v3.12.3

#### Additional Context

```
ruler:
  enabled: true
  ring:
    instance_enable_ipv6: true

overrides-exporter:
  ring:
    instance_enable_ipv6: true

frontend:
  instance_enable_ipv6: true

distributor:
  ring:
    instance_enable_ipv6: true

ingester:
  ring:
    instance_enable_ipv6: true

query_scheduler:
  ring:
    instance_enable_ipv6: true

store_gateway:
  sharding_ring:
    instance_enable_ipv6: true
    
compactor:
  sharding_ring:
    instance_enable_ipv6: true
```

#### example logs

```
ts=2024-06-10T15:11:13.149400086Z caller=main.go:227 level=info msg="Starting application" version="(version=2.12.0, branch=r293, revision=c212608)"
ts=2024-06-10T15:11:13.152910276Z caller=server.go:352 level=info msg="server listening on addresses" http=[::]:8080 grpc=[::]:9095
ts=2024-06-10T15:11:13.160342764Z caller=memberlist_client.go:435 level=info msg="Using memberlist cluster label and node name" cluster_label= node=distributed-ruler-55646c588d-mvclj-a0774894
ts=2024-06-10T15:11:13.160995872Z caller=log.go:245 level=warn msg="Binding to public address without encryption!"
ts=2024-06-10T15:11:13.162759882Z caller=memberlist_client.go:541 level=info msg="memberlist fast-join starting" nodes_found=9 to_join=4
ts=2024-06-10T15:11:13.169663913Z caller=memberlist_client.go:561 level=info msg="memberlist fast-join finished" joined_nodes=3 elapsed_time=8.563328ms
ts=2024-06-10T15:11:13.169698457Z caller=memberlist_client.go:573 level=info phase=startup msg="joining memberlist cluster" join_members=dns+distributed-gossip-ring.mimir.svc.cluster.local.:7946
ts=2024-06-10T15:11:13.174373817Z caller=mapper.go:52 level=info msg="cleaning up mapped rules directory" path=/data
ts=2024-06-10T15:11:13.174693397Z caller=netutil.go:90 level=warn msg="error getting addresses for interface" inf=en0 err="route ip+net: no such network interface"
ts=2024-06-10T15:11:13.174864875Z caller=log.go:103 level=error msg="error running application" err="no useable address found for interfaces [eth0 en0]\nfailed to initialize ruler's lifecycler config\ngithub.com/grafana/mimir/pkg/ruler.enableSharding\n\t/__w/mimir/mimir/pkg/ruler/ruler.go:389\ngithub.com/grafana/mimir/pkg/ruler.newRuler\n\t/__w/mimir/mimir/pkg/ruler/ruler.go:378\ngithub.com/grafana/mimir/pkg/ruler.NewRuler\n\t/__w/mimir/mimir/pkg/ruler/ruler.go:340\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initRuler\n\t/__w/mimir/mimir/pkg/mimir/modules.go:897\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:851\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:229\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1222\nsetup ruler sharding ring\ngithub.com/grafana/mimir/pkg/ruler.newRuler\n\t/__w/mimir/mimir/pkg/ruler/ruler.go:379\ngithub.com/grafana/mimir/pkg/ruler.NewRuler\n\t/__w/mimir/mimir/pkg/ruler/ruler.go:340\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).initRuler\n\t/__w/mimir/mimir/pkg/mimir/modules.go:897\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:136\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:851\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:229\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1222\nerror initialising module: ruler\ngithub.com/grafana/dskit/modules.(*Manager).initModule\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:138\ngithub.com/grafana/dskit/modules.(*Manager).InitModuleServices\n\t/__w/mimir/mimir/vendor/github.com/grafana/dskit/modules/modules.go:108\ngithub.com/grafana/mimir/pkg/mimir.(*Mimir).Run\n\t/__w/mimir/mimir/pkg/mimir/mimir.go:851\nmain.main\n\t/__w/mimir/mimir/cmd/mimir/main.go:229\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:271\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_arm64.s:1222"
```

```[tasklist]
### Tasks
```

**Comment by pelzerim** [comment]
The ipv6 options belong into the `mimir.structuredConfig`, not into the helm config. This one worked for me:

```
[...] # rest of helm chart
mimir:
  structuredConfig:
    memberlist:
      bind_addr:
        - '::'

    ruler:
      ring:
        instance_enable_ipv6: true

    overrides_exporter:
      ring:
        instance_enable_ipv6: true

    frontend:
      instance_enable_ipv6: true

    distributor:
      ring:
        instance_enable_ipv6: true

    ingester:
      ring:
        instance_enable_ipv6: true

    query_scheduler:
      ring:
        instance_enable_ipv6: true

    store_gateway:
      sharding_ring:
        instance_enable_ipv6: true

    compactor:
      sharding_ring:
        instance_enable_ipv6: true
```
