### ISSUE TITLE
failed to get token ranges for ingester err="zone not set"

### ISSUE THREAD

**Issue by Assaf1928** [grafana/mimir#8605]
#### Describe the bug
After last version update (3.1) I get the next error:
level=error ts=2024-07-04T12:19:47.79081202Z caller=recalculate_owned_streams.go:55 msg="failed to get token ranges for ingester" err="zone not set"

this is my config-yml file:

```
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100



limits_config:
  retention_period: 720h

schema_config:
  configs:
    - from: 2021-08-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
    
# # chunk_store_config:
# #   max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  alertmanager_url: http://localhost:9093

# ingester:
#   lifecycler:
#     ring:
#       kvstore:
#         store: inmemory
#       replication_factor: 1
#       zone: "default"
#     join_after: 30s
#     final_sleep: 0s
#   wal:
#     enabled: true
#     dir: /loki/wal

distributor:
  ring:
    kvstore:
      store: inmemory


compactor:
  working_directory: /loki/compactor
```
