### ISSUE TITLE
Lifecycler addresses have inconsistent key names

### ISSUE THREAD

**Issue by jdbaldry** [grafana/mimir#865]
**Describe the bug**
When configuring the distributor and ingester lifecycler addresses explicitly, rather than relying on interface detection, there are different keys for the distributor and ingester configuration.

```yaml
distributor:
  ring:
    instance_addr: 127.0.0.1
ingester:
  lifecycler:
    address: 127.0.0.1
```

Additionally, the documentation for at least the ingester address configuration is hidden from docs. I think it would be useful to expose it as it is unlikely that server network interfaces will conform to the increasingly common [predictable network interface names](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/).

**Expected behavior**
Configuration keys for the same logical concept should have the same identifier.
