### ISSUE TITLE
Google Cloud Service Accounts secrets can't be injected using Env variables

### ISSUE THREAD

**Issue by davinkevin** [grafana/mimir#8704]
#### Describe the bug

The [official mimir documentation](https://grafana.com/docs/mimir/latest/configure/configure-object-storage-backend/#gcs) demonstrates how to connect `mimir` to an external storage based on GCS in Google Cloud. 

<img width="807" alt="image" src="https://github.com/user-attachments/assets/e094fd6c-a55a-40e1-879b-80f13320c9db">

A comment states this should be done via an Env variable because this value has to secured. 

However, if we provide the content described in the documentation as an env variables, the system is not able to parse the configuration *because* the secret is a multiline JSON file and the [expansion system](https://github.com/grafana/mimir/blob/8571f6cc9876e2322d60ac03673d93f66646bd0b/cmd/mimir/main.go#L313-L329) is not yaml-aware. 

#### To Reproduce

Our system runs in k8s, so I provide `manifests` here:

```yaml
# mimir.yaml
target: compactor,distributor,ingester,querier,query-frontend,store-gateway

common:
  storage:
    backend: ${COMMON_STORAGE_BACKEND}
    gcs:
      bucket_name: ${COMMON_STORAGE_GCS_BUCKET_NAME}
      service_account: >-
        ${COMMON_STORAGE_GCS_SERVICE_ACCOUNT}
```

```yaml
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {}
  name: mimir
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels: {}
  strategy:
    type: Recreate
  template:
    metadata:
      labels: {}
    spec:
      containers:
        - args:
            - -config.expand-env=true
            - -config.file=/opt/mimir/mimir.yaml
          env:
            - name: COMMON_STORAGE_BACKEND
              value: gcs
            - name: COMMON_STORAGE_GCS_BUCKET_NAME
              value: a-bucket-just-for-this-issue
            - name: COMMON_STORAGE_GCS_SERVICE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  key: key.json
                  name: google-cloud-service-account
          image: grafana/mimir:2.12.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /api/v1/status/buildinfo
              port: http-mimir
              scheme: HTTP
          name: mimir
          ports:
            - containerPort: 8080
              name: http-mimir
              protocol: TCP
            - containerPort: 9096
              name: grpc-mimir
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ready
              port: http-mimir
              scheme: HTTP
          volumeMounts:
            - mountPath: /data
              name: mimir-tmp
            - mountPath: /opt/mimir/mimir.yaml
              name: config
              subPath: mimir.yaml
      volumes:
        - emptyDir: {}
          name: mimir-tmp
        - configMap:
            name: mimir
          name: config
```

```json
{
  "type": "service_account",
  "project_id": "my-project",
  "private_key_id": "1234abc",
  "private_key": "-----BEGIN PRIVATE KEY-----\n\n-----END PRIVATE KEY-----\n",
  "client_email": "test@my-project.iam.gserviceaccount.com",
  "client_id": "5678",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/test%40my-project.iam.gserviceaccount.com"
}
```

```yaml
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mimir-configuration-with-gcp-service-account

labels:
  - pairs:
      app.kubernetes.io/part-of: mimir
      app.kubernetes.io/for: configuration-with-gcp-service-account
    includeSelectors: true

resources:
  - deployment.yaml
  - namespace.yaml

configMapGenerator:
  - name: mimir
    files:
      - mimir.yaml

secretGenerator:
  - name: google-cloud-service-account
    files:
      - key.json
```

Zip with all resources: [issue.zip](https://github.com/user-attachments/files/16194948/issue.zip)

After the deployment, we can see this from the mimir output: 

```
error loading config from /opt/gradle/mimir/mimir.yaml: Error parsing config file: yaml: line 3: did not find expected key
```

#### Expected behavior

I expect the env variable to be injected in a way I can leverage the service account for authentication, and I don't produce an invalid `yaml`. 

This can be down by doing an "yaml aware" injection or by stripping new lines from the secret, the implementation doesn't matter as soon as I can achieve what the doc recommends 😇

I've checked the mimir source code and confirmed the `yaml` is not correctly indented after the expansion done by [this function](https://github.com/grafana/mimir/blob/8571f6cc9876e2322d60ac03673d93f66646bd0b/cmd/mimir/main.go#L313-L329)

#### Environment

- Infrastructure: K8s, but should be the same for every conjunction of `mimir` + `expandVars` + multiline env vars
- Deployment tool: `kubectl`
