### ISSUE TITLE
cannot configure `querier.query_store_after` value

### ISSUE THREAD

**Issue by mkyc** [grafana/mimir#8739]
#### Describe the bug

If I add `querier.query_store_after` to `mimir.yaml` file I'll get: 

```shell
error validating config: invalid limits config for querier: the -querier.query-ingesters-within setting must be greater than -querier.query-store-after otherwise queries might return partial results
```

and then if I add `querier.query_ingesters_within` to `mimir.yaml` file I'll get: 

```shell
  line 73: field query_ingesters_within not found in type querier.Config
```

#### To Reproduce

1. install `mimir-distributed` version `5.4.0` from `https://grafana.github.io/helm-charts`
2. configure it with following values file: 

```yaml
mimir:
  structuredConfig:
    multitenancy_enabled: false
    common:
      storage:
        backend: s3
        s3:
          endpoint: "s3.${region}.amazonaws.com"
          region: "${region}"
          bucket_name: "${bucket}"
    server:
      log_level: debug
    frontend:
      log_queries_longer_than: 5s
    blocks_storage:
      tsdb:
        retention_period: 168h #7d
      bucket_store:
        ignore_blocks_within: 165h #7d-2h
    querier:
      query_store_after: 166h #7d-2h
      query_ingesters_within: 167h #7d-1h

serviceAccount:
  create: true
  annotations:
    "eks.amazonaws.com/role-arn": "${iam_role_arn}"

alertmanager:
  enabled: false
distributor:
  replicas: 1
ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: true
    size: 100Gi
    storageClass: ebs-sc
overrides_exporter:
  enabled: false
ruler:
  enabled: false
querier:
  replicas: 2
query_frontend:
  replicas: 1
query_scheduler:
  enabled: false
store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: true
    size: 100Gi
    storageClass: ebs-sc
compactor:
  replicas: 1
  persistentVolume:
    enabled: true
    size: 100Gi
    storageClass: ebs-sc

chunks-cache:
  enabled: false
index-cache:
  enabled: false
metadata-cache:
  enabled: false
results-cache:
  enabled: false

rollout_operator:
  enabled: false

minio:
  enabled: false

ingress:
  enabled: false

nginx:
  enabled: true
  service:
    type: NodePort

metaMonitoring:
  serviceMonitor:
    enabled: true

```

#### Additional Context

I found config code [here](https://github.com/grafana/mimir/blob/main/pkg/querier/querier.go#L45) but I cannot find that validation rules.

**Comment by 56quarters** [comment]
The `query_ingesters_within` setting has moved to the `limits` section since it is now per-tenant. The error message needs to be updated.

**Comment by 56quarters** [comment]
Actually, the error message is correct because it's talking about the CLI flag. The YAML setting is now under `limits` but the CLI flag is `querier.query-ingesters-within`

**Comment by mkyc** [comment]
hmmmm ... ok, that works: 

```yaml
...
    blocks_storage:
      tsdb:
        retention_period: 168h #7d
    querier:
      query_store_after: 160h #7d-8h
    limits:
      query_ingesters_within: 167h #7d-1h
```

Closing it but I believe error message should be improved.
