### ISSUE TITLE
relabel_configs: 

### ISSUE THREAD

**Issue by MaheshAruchamy** [grafana/mimir#8759]
trying to implement relabel_configs in mimir.yaml file but getting syntax error. Could you please give me whre it is gone wrong. Attaching yaml file. Pasting yaml snippet developed for relabe_configs
```
distributor:
# Droping blackbox alerts
  relabel_configs:
   - source_labels: [__name__]
    regex: '^blackbox_.*'
    action: drop
```
[mimir_dev_config.txt](https://github.com/user-attachments/files/16277588/mimir_dev_config.txt)

Reg,
Mahesh.
