### ISSUE TITLE
Mixin charts require scrape rate of 15s

### ISSUE THREAD

**Issue by davhdavh** [grafana/mimir#8840]
#### Describe the bug

https://github.com/grafana/mimir/blob/32eee50d75bcd53d5fb4971cd75344658a526db3/operations/mimir-mixin/config.libsonnet#L675-L678

should use `$__rate_interval` instead to implement exactly what the comment says.

#### To Reproduce

1. Add dashboards, servicemonitor and rules and alerts using helm
```yaml
  metaMonitoring:
    dashboards:
      enabled: true
    prometheusRule:
      mimirRules: true
      mimirAlerts: true
    serviceMonitor:
      enabled: true
      clusterLabel: 0
```
3. Configure alloy to scrape by default every 60s.
4. Most charts are empty

#### Expected behavior

Charts show data, even with slower collection rate.

#### Environment

- k8s
- helm
