### ISSUE TITLE
Docs: NetworkPolicies

### ISSUE THREAD

**Issue by genofire** [grafana/mimir#8950]
#### Is your documentation request related to a feature? If so, which one?

Communication between Pods

#### Describe the solution that you’d like or the expected outcome

Helm-Chart with Networkpolicies

----

i start one, for networkpolicies only ingress and here querier ports:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mimir-query-scheduler
  namespace: phoenix-monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: query-scheduler
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: query-frontend
      ports:
        - port: 9095
          protocol: TCP
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: querier
      ports:
        - port: 9095
          protocol: TCP
```
