### ISSUE TITLE
kvstore (of e.g. distributor ha_tracker) in redis/valkey

### ISSUE THREAD

**Issue by genofire** [grafana/mimir#9002]
#### Is your feature request related to a problem? Please describe.

To support beside etcd and consul also redis/valkey kvstores

#### Describe the solution you'd like

redis/valkey is also a really common tool for keyvalue storage (and cacheing)

#### Additional context
an example how the configuration could look like
```yaml
limits:
  accept_ha_samples: true
  ha_cluster_label: "env_id"
  ha_replica_label: "prometheus_replica"

distributor:
  ha_tracker:
    enable_ha_tracker: true
    ha_tracker_update_timeout: 15s
    ha_tracker_update_timeout_jitter_max: 5s
    ha_tracker_failover_timeout: 30s
  kvstore:
    store: redis
redis:
  endpoint: "valkey.mimir.svc"
```
