### ISSUE TITLE
feat: add support for docker `healthcheck` to `grafana/mimir` image

### ISSUE THREAD

**Issue by DeadNews** [grafana/mimir#9034]
#### Is your feature request related to a problem? Please describe.

Enable the [healthcheck](https://docs.docker.com/compose/compose-file/05-services/#healthcheck) for the docker container.

#### Describe the solution you'd like

Add `wget` to the docker image [via busybox](https://github.com/grafana/loki/blob/811f5f015cd5da4e25d800307b905c3385406be3/cmd/loki/Dockerfile#L20).

Like [loki](https://github.com/grafana/loki/blob/811f5f015cd5da4e25d800307b905c3385406be3/examples/getting-started/docker-compose.yaml#L19-L23) does:

```yaml
healthcheck:
  test:
    [
      "CMD-SHELL",
      "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1",
    ]
  interval: 10s
  timeout: 5s
  retries: 5
```

#### Describe alternatives you've considered

Use internal commands to check the health of the service.

Like, `traefik`, [redis](https://github.com/grafana/grafana/blob/4a753dd2d5b2c0a39a1934c9bac9141bbaa3cd05/devenv/docker/blocks/auth/authentik/docker-compose.yaml#L22-L27), [postgres](https://github.com/grafana/grafana/blob/4a753dd2d5b2c0a39a1934c9bac9141bbaa3cd05/devenv/docker/blocks/postgres/docker-compose.yaml#L10-L14), `minio` and others do:

```yaml
healthcheck:
  test: [CMD, traefik, healthcheck, --ping]
  interval: 1m
  retries: 3
  timeout: 10s
  start_period: 1m
```

or [this](https://github.com/fbonalair/traefik-crowdsec-bouncer/pull/8/files#diff-985ff87d24b89ecf8ad3862a8b30d84ee2760d1c56842d22fcac7550107f624c) way.

#### Additional context

ref: https://github.com/grafana/loki/issues/11590 https://github.com/grafana/loki/pull/11711
