### ISSUE TITLE
Adding podLabels in global section breaking parsing

### ISSUE THREAD

**Issue by kunalmehta-eve** [grafana/mimir#9046]
#### Describe the bug
Adding podLabels in global section breaking parsing

global:
  podLabels:
    azure.workload.identity/use: "true"
    
    YAML parse error on mimir-distributed/templates/compactor/compactor-statefulset.yaml: error converting YAML to JSON: yaml: line 38: did not find expected key
    

#### To Reproduce

1. Start Mimir (SHA or version)
2. Perform Operations(Read/Write/Others)

#### Environment

- Infrastructure: Kubernetes
- Deployment tool: helm

**Comment by narqo** [comment]
From a quick look, I couldn't reproduce it with the provided values (see `9046-helm-values.yaml` below).

```
% cat 9046-helm-values.yaml
global:
  podLabels:
    azure.workload.identity/use: "true"

% helm template test-mimir . -f 9046-helm-values.yaml
···
# Source: mimir-distributed/templates/compactor/compactor-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
···
spec:
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
        helm.sh/chart: mimir-distributed-5.5.0-weekly.304
        app.kubernetes.io/name: mimir
        app.kubernetes.io/instance: test-mimir
        app.kubernetes.io/version: "r304"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: compactor
        app.kubernetes.io/part-of: memberlist

```

@kunalmehta-eve could you fill up the missing details:
- What version of Mimir you're using
- What do you feed in with the helm's values
- Something else to reproduce the issue?
