### ISSUE TITLE
Mimir UI Prometheus 404

### ISSUE THREAD

**Issue by flowramps** [grafana/mimir#9084]
#### Event occurred

I get 404 when I hit the /prometheus endpoint and I can't see the promtheus UI, but when I query some endpoints like: /prometheus/api/v1/labels I can get information!  

![image](https://github.com/user-attachments/assets/e7787431-a29a-497a-b39a-10aa105ca0fd)

![image](https://github.com/user-attachments/assets/9dbed1ce-82be-42d4-b975-ee9e74d05b93)

#### To play

1. Enpoint exposed and configured with the values ​​to expose with the gateway option 
2. example values ​​without the official domain 
3. values

```
gateway:
  # -- The gateway is deployed by default for enterprise installations (enterprise.enabled=true).
  # Toggle this to have it deployed for non-enterprise installations too.
  enabledNonEnterprise: true

  # -- Number of replicas for the Deployment
  replicas: 1

  # -- HorizontalPodAutoscaler
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 70
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 64Mi

  # -- Deployment strategy. See `kubectl explain deployment.spec.strategy` for more,
  # ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 15%

  ingress:
    enabled: true
    nameOverride: ""
    # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
    ingressClassName: "nginx"
    # -- Annotations for the Ingress
    annotations: {}
    # -- Hosts configuration for the Ingress
    hosts:
      # -- Passed through the `tpl` function to allow templating.
      - host: dns.exemplo.com
        paths:
          - path: /
            # -- pathType (e.g. ImplementationSpecific, Prefix, .. etc.) might also be required by some Ingress Controllers
            pathType: Prefix
    # -- TLS configuration for the nginx ingress
    tls:
      - secretName: dev-tls
        # --  Hosts included in the tls certificate. Passed through the `tpl` function to allow templating.
        hosts:
          - dns.exemplo.com
  readinessProbe:
    httpGet:
      path: /ready
      port: http-metrics
    initialDelaySeconds: 15
    timeoutSeconds: 1

  nginx:
    # -- Enable logging of 2xx and 3xx HTTP requests
    verboseLogging: true


```
#### Expected behavior

View the prometheus UI and manipulate rulers to work alerts with mimir's internal alertmanager

#### Environment

- Infrastructure: [Kubernetes,EKS]
- Deployment tool: [helm]

#### Additional Context

I'm trying to integrate mimir rulers with alertmanager, however, I can't configure the rulers and I can't run the Prometheus UI, but when I hit the /alertmanager endpoint it loads the alertmanager UI but doesn't display the configs and I can't understand how I can do this integration, I've already reviewed the documentation and haven't found the best way to proceed.

![image](https://github.com/user-attachments/assets/f33d4f67-f2bb-4ccf-8489-e04dcf383abd)

![image](https://github.com/user-attachments/assets/1d70456b-170b-43b6-bd94-9f01ac8a7202)
