### ISSUE TITLE
[Helm] Distirbutor gprc values shouldn't be hard coded

### ISSUE THREAD

**Issue by lasermoth** [grafana/mimir#9263]
## Issue 

Currently the `server.grpc.keepalive` settings are [hard coded](https://github.com/grafana/mimir/blob/c34951638dc9b9182e1a1f9d564391b2febfe37a/operations/helm/charts/mimir-distributed/templates/distributor/distributor-dep.yaml#L57C1-L60C36), as well as the shutdown-delay. 

```yaml
            - "-server.grpc.keepalive.max-connection-age=60s"
            - "-server.grpc.keepalive.max-connection-age-grace=5m"
            - "-server.grpc.keepalive.max-connection-idle=1m"
            - "-shutdown-delay=90s"
```

While these were added for parity with the jssonnet deployment, and the comment explains the reasoning, ideally we should have these in the `values.yaml` so they can be tuned, or overridden by the user.

As an example for my particular use case, we have a staging environment that has minimal traffic and we would like to tune these to allow proper graceful shutdown on GKE spot instances within the 15second graceful termination period described [here](https://cloud.google.com/kubernetes-engine/docs/concepts/spot-vms#termination-graceful-shutdown) to help reduce cost of this deployment.

## Proposal

Move these into `values.yaml`. 

This could either be done via an object

```
...
distributor:
  shutdownDelay: 90s

  server:
    gprc:
      keepalive:
        # The duration for the maximum amount of time a connection may exist before it will be closed
        maxConnectionAge: 60s
        # An additive period after max-connection-age after which the connection will be forcibly closed.
        maxConnectionAgeGrace: rm
        # The duration after which an idle connection should be closed.
        maxConnectionIdle: 1m
...
```

Or alternatively they could be moved to the existing `extraArgs` object.
