### ISSUE TITLE
mimir-distributed helm template does not correctly accept ingress.hosts

### ISSUE THREAD

**Issue by trondhindenes** [grafana/mimir#9722]
#### Describe the bug
Trying to deploy mimir-distributed chart version 5.5.0 with these values:
```
ingester:
  replicas: 2
  zoneAwareReplication:
    enabled: false
store_gateway:
  replicas: 2
  zoneAwareReplication:
    enabled: false
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: supersecret
    external-dns.alpha.kubernetes.io/target: cluster.stuff.com
  hosts:
  - host: stuff.wuff.guff
    paths:
    - path: /
```
Causes this error:
```
Error: template: mimir-distributed/templates/ingress.yaml:31:19: executing "mimir-distributed/templates/ingress.yaml" at <.>: wrong type for value; expected string; got map[string]interface {}
helm.go:86: 2024-10-23 13:34:09.471765459 +0200 CEST m=+0.974764386 [debug] template: mimir-distributed/templates/ingress.yaml:31:19: executing "mimir-distributed/templates/ingress.yaml" at <.>: wrong type for value; expected string; got map[string]interface {}

```

#### To Reproduce
See above

#### Expected behavior

It should work
