### ISSUE TITLE
Query lookback enforcement doesn't return full dataset when federating across tenants of different retention periods

### ISSUE THREAD

**Issue by jonDufty** [grafana/mimir#9727]
#### Describe the bug

After upgrading to mimir 2.14 we found that all of our queries longer than 7 days were only returning 7 days worth of data. We run a multi-tenanted system, where we have different sized tenants with different retention periods, typically 7d, 1m and 1y. Users of the platform need to be able to query across multiple tenants, so our default Mimir datasource uses query federation to do this

We found that querying one of the large tenants in isolation for longer period (e.g. 30 days) would return the full data set, but when querying across all tenants, we would only get 7 days worth of data.

I believe this behaviour is a result of https://github.com/grafana/mimir/pull/8388. Where the query frontend takes the minimum retention period out of all tenants, and takes the minimum of that and the max query lookback. So when we included the smaller tenants with a 7 day retention period, the max lookback for any query would be 7 days, despite also including larger tenants that had more than 7 days of data.

#### To Reproduce

1. Have multiple tenants with varying retention periods, e.g. 1h and 1d
2. Query mimir for a duration greater than the smallest retention period (i.e. 1d), and only specify the largest tenant. It should return a full day of data
3. Run the query again but query both tenants. It should only return 1h of data

#### Expected behavior

When querying across multiple tenants I would expect the max lookback to be equivalent to the largest retention period to avoid truncating any results

#### Environment

- Infrastructure: Kubernetes EKS
- Deployment tool: helm + jsonnet
- Mimir version 2.14

**Mimir config**

<details>
<summary>Main Config</summary>

```
  compactor:
    compaction_concurrency: 2
    compaction_interval: "30m"
    data_dir: "/data"
    deletion_delay: "2h"
    first_level_compaction_wait_period: "25m"
    max_closing_blocks_concurrency: 2
    max_opening_blocks_concurrency: 4
    sharding_ring:
      heartbeat_period: "1m"
      heartbeat_timeout: "4m"
      wait_stability_min_duration: "1m"
    symbols_flushers_concurrency: 4
  frontend:
    cache_results: true
    log_queries_longer_than: "5s"
    max_outstanding_per_tenant: 4096
    parallelize_shardable_queries: true
    query_sharding_target_series_per_shard: 2500
    results_cache:
      backend: "memcached"
      memcached:
        max_item_size: 1048576
        timeout: "500ms"
  frontend_worker:
    grpc_client_config:
      max_send_msg_size: 419430400
  limits:
    align_queries_with_step: true
    cardinality_analysis_enabled: true
    max_cache_freshness: "15m"
    max_query_parallelism: 400
    max_total_query_length: "12000h"
    native_histograms_ingestion_enabled: true
    out_of_order_time_window: "15m"
    query_sharding_max_sharded_queries: 640
    query_sharding_total_shards: 32
  querier:
    max_concurrent: 20
    timeout: "2m"
  query_scheduler:
    max_outstanding_requests_per_tenant: 4096
  runtime_config:
    file: "/var/mimir/runtime.yaml"
  server:
    grpc_server_max_recv_msg_size: 524288000
    grpc_server_max_send_msg_size: 524288000
    log_format: "json"
  store_gateway:
    sharding_ring:
      heartbeat_period: "1m"
      heartbeat_timeout: "4m"
      kvstore:
        prefix: "multi-zone/"
      tokens_file_path: "/data/tokens"
      unregister_on_shutdown: false
      wait_stability_min_duration: "1m"
      zone_awareness_enabled: true
  tenant_federation:
    enabled: true
  usage_stats:
    enabled: false
    installation_mode: "helm"
```
</details>

<details>
<summary>Runtime/Tenant Config</summary>
Indicative example of our tenant setup

```
overrides:
      large:
        compactor_blocks_retention_period: "1y"
        compactor_split_and_merge_shards: 6
        compactor_split_groups: 12
        ingestion_rate: 30000000
        max_fetched_chunks_per_query: 10000000
        max_label_names_per_series: 50
      medium:
        compactor_blocks_retention_period: "4w"
        ingestion_rate: 100000
        max_label_names_per_series: 50
      small:
        compactor_blocks_retention_period: "1w"
        ingestion_rate: 100000
        max_label_names_per_series: 50
```
</details>

#### Additional context

The specific line of code in question is here https://github.com/grafana/mimir/pull/8388/files#diff-92de40a72c3f7eb8744de54750b3f1279255c1e494ca560878a6407a4c46e3e9R133

**Comment by bcrisp4** [comment]
+1 - also seeing this behavior and it is causing problems in my multi-tenanted system.

**Comment by alexanderldavis** [comment]
+1 - we also see this in our multi-tenant system. We have reverted to <2.14.

**Comment by drcrees** [comment]
Could this issue get some traction, please? We are forced to remain on a version <2.14 until it is resolved...

**Comment by mirobertod** [comment]
Hi, any update on this issue? We're facing the same behavior

**Comment by pracucci** [comment]
This PR should fix it: https://github.com/grafana/mimir/pull/11069

**Comment by Giri0422** [comment]
@pracucci  i am still having this issue i deployed chart version (mimir-distributed-5.8.0-weekly.336r336)
i have set retention as Dev/Qa 60days and Beta/Prod 180 days but my Queries are limited to 60days where i have data for more then 60days for Beta/Prod.

**Comment by pracucci** [comment]
> [@pracucci](https://github.com/pracucci) i am still having this issue i deployed chart version (mimir-distributed-5.8.0-weekly.336r336) i have set retention as Dev/Qa 60days and Beta/Prod 180 days but my Queries are limited to 60days where i have data for more then 60days for Beta/Prod.

@Giri0422 Could you share your entire Mimir configuration, redacted of any sensitive data, please?

**Comment by Giri0422** [comment]
```
mimir:
  structuredConfig:
    tenant_federation:
      enabled: true
    ruler:
      tenant_federation:
        enabled: true

  config: |
    usage_stats:
      installation_mode: helm

    activity_tracker:
      filepath: /active-query-tracker/activity.log

    alertmanager:
      data_dir: /data
      enable_api: true
      external_url: /alertmanager
      {{- if .Values.alertmanager.zoneAwareReplication.enabled }}
      sharding_ring:
        zone_awareness_enabled: true
      {{- end }}
      {{- if .Values.alertmanager.fallbackConfig }}
      fallback_config_file: /configs/alertmanager_fallback_config.yaml
      {{- end }}


    # This configures how the store-gateway synchronizes blocks stored in the bucket. It uses Minio by default for getting started (configured via flags) but this should be changed for production deployments.
    blocks_storage:
      backend: azure
      azure:
        account_name: algiacstoeafrwkmimir
        container_name: 'mimir'
        endpoint_suffix: 'blob.core.windows.net'
        account_key: "${AZURE_ACCOUNT_KEY}" 
      tsdb:
        dir: '/data/tsdb'
        block_ranges_period: ["0h10m0s"]
      bucket_store:
        #ignore_deletion_mark_delay: 24h  sync with old values
        max_concurrent: 500
        block_sync_concurrency: 50
        meta_sync_concurrency: 50
        {{- if index .Values "chunks-cache" "enabled" }}
        chunks_cache:
          backend: memcached
          max_get_range_requests: 0
          memcached:
            addresses: {{ include "mimir.chunksCacheAddress" . }}
            max_item_size: {{ mul (index .Values "chunks-cache").maxItemMemory 1024 1024 }}
            timeout: 1000ms
            max_idle_connections: 150
        {{- end }}
        {{- if index .Values "index-cache" "enabled" }}
        index_cache:
          backend: memcached
          memcached:
            addresses: {{ include "mimir.indexCacheAddress" . }}
            max_item_size: {{ mul (index .Values "index-cache").maxItemMemory 1024 1024 }}
            timeout: 1000ms
            max_idle_connections: 150
        {{- end }}
        
        bucket_index:
          max_stale_period: 12h
        {{- if index .Values "metadata-cache" "enabled" }}
        metadata_cache:
          backend: memcached
          memcached:
            addresses: {{ include "mimir.metadataCacheAddress" . }}
            max_item_size: {{ mul (index .Values "metadata-cache").maxItemMemory 1024 1024 }}
            max_idle_connections: 150
        {{- end }}
        sync_dir: /data/tsdb-sync
      tsdb:
        dir: /data/tsdb
        head_compaction_interval: 1m
        wal_replay_concurrency: 0
        ship_concurrency: 100


    compactor:
      compaction_interval: 30m
      deletion_delay: 2h
      max_closing_blocks_concurrency: 2
      max_opening_blocks_concurrency: 4
      symbols_flushers_concurrency: 4
      first_level_compaction_wait_period: 25m
      data_dir: "/data"
      sharding_ring:
        wait_stability_min_duration: 1m
        heartbeat_period: 1m
        heartbeat_timeout: 4m

    distributor:
      ring:
        heartbeat_period: 1m
        heartbeat_timeout: 4m

    frontend:
      max_outstanding_per_tenant: 10000
      parallelize_shardable_queries: true
      {{- if index .Values "results-cache" "enabled" }}
      results_cache:
        backend: memcached
        memcached:
          addresses: {{ include "mimir.resultsCacheAddress" . }}
          max_item_size: {{ mul (index .Values "results-cache").maxItemMemory 1024 1024 }}
      cache_results: true
      query_sharding_target_series_per_shard: 2500
      {{- end }}
      {{- if and .Values.query_scheduler.enabled (not .Values.federation_frontend.disableOtherComponents) }}
      scheduler_address: {{ template "mimir.fullname" . }}-query-scheduler-headless.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
      {{- end }}

    frontend_worker:
      grpc_client_config:
        max_send_msg_size: 419430400 # 400MiB
      {{- if .Values.query_scheduler.enabled }}
      scheduler_address: {{ template "mimir.fullname" . }}-query-scheduler-headless.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
      {{- else }}
      frontend_address: {{ template "mimir.fullname" . }}-query-frontend-headless.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" . }}
      {{- end }}
      
    ingester:
      ring:
        final_sleep: 0s
        num_tokens: 512
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
        heartbeat_period: 2m
        heartbeat_timeout: 10m
        {{- if .Values.ingester.zoneAwareReplication.enabled }}
        zone_awareness_enabled: true
        {{- end }}

    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600


    server:
      #log_level: debug
      grpc_server_max_concurrent_streams: 0
      grpc_server_keepalive_timeout: 600s
      http_server_write_timeout: 10m0s
    limits:
      # Limit queries to 500 days. You can override this on a per-tenant basis.
      max_total_query_length: 12000h
      # Adjust max query parallelism to 16x sharding, without sharding we can run 15d queries fully in parallel.
      # With sharding we can further shard each day another 16 times. 15 days * 16 shards = 240 subqueries.
      max_query_parallelism: 1000
      # Avoid caching results newer than 10m because some samples can be delayed
      # This presents caching incomplete results
      max_cache_freshness: 10m
      max_global_series_per_user: 0
      ingestion_rate: 999999999999999999
      ingestion_burst_size: 999999999999999
      ruler_max_rules_per_rule_group: 500
      ruler_max_rule_groups_per_tenant: 500
      max_fetched_chunks_per_query: 0
      query_sharding_total_shards: 0
      compactor_partial_block_deletion_delay: 0
      compactor_blocks_retention_period: 180d
      max_query_lookback: 180d

    memberlist:
      abort_if_cluster_join_fails: false
      compression_enabled: false
      join_members:
      - dns+{{ include "mimir.fullname" . }}-gossip-ring.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:{{ include "mimir.memberlistBindPort" . }}

    querier:
      # With query sharding we run more but smaller queries. We must strike a balance
      # which allows us to process more sharded queries in parallel when requested, but not overload
      # queriers during non-sharded queries.
      max_concurrent: 256
      timeout: 10m0s

    query_scheduler:
      # Increase from default of 100 to account for queries created by query sharding
      max_outstanding_requests_per_tenant: 10000
      # backoff_config:
      #   min_period: 1000ms
      #   max_period: 300s
      #   max_retries: 20
      


    ruler:
      alertmanager_url: dnssrvnoa+http://_http-metrics._tcp.{{ template "mimir.fullname" . }}-alertmanager-headless.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}/alertmanager
      enable_api: true
      rule_path: /data
      {{- if .Values.ruler.remoteEvaluationDedicatedQueryPath }}
      query_frontend:
        address: dns:///{{ template "mimir.fullname" . }}-ruler-query-frontend.{{ .Release.Namespace }}.svc:{{ include "mimir.serverGrpcListenPort" .  }}
      {{- end }}

    {{- if or (.Values.minio.enabled) (index .Values "metadata-cache" "enabled") }}
    ruler_storage:
      {{- if index .Values "metadata-cache" "enabled" }}
      cache:
        backend: memcached
        memcached:
          addresses: {{ include "mimir.metadataCacheAddress" . }}
          max_item_size: {{ mul (index .Values "metadata-cache").maxItemMemory 1024 1024 }}
      {{- end }}
    {{- end }}

    {{- if not .Values.federation_frontend.disableOtherComponents }}
    runtime_config:
      file: /var/{{ include "mimir.name" . }}/runtime.yaml
    {{- end }}

    store_gateway:
      sharding_ring:
        heartbeat_period: 1m
        heartbeat_timeout: 4m
        wait_stability_min_duration: 1m
        {{- if .Values.store_gateway.zoneAwareReplication.enabled }}
        kvstore:
          prefix: multi-zone/
        {{- end }}
        tokens_file_path: /data/tokens
        unregister_on_shutdown: false
        {{- if .Values.store_gateway.zoneAwareReplication.enabled }}
        zone_awareness_enabled: true
        {{- end }}


rbac:
  create: false

runtimeConfig:
  ingester_limits: # limits that each ingester replica enforces
    max_ingestion_rate: 0
    max_series: 0
    max_tenants: 0
    max_inflight_push_requests: 0
  distributor_limits: # limits that each distributor replica enforces
    max_ingestion_rate: 0
    max_inflight_push_requests: 0
    max_inflight_push_requests_bytes: 0
  overrides:
  # Development
	  alg-cdh-aks-d-usea-fisauthea:
	    compactor_blocks_retention_period: 60d 
  # QA
	  alg-cdh-aks-q-usea-multi:
	    compactor_blocks_retention_period: 60d
  # Beta
	  alg-fdn-aks-d-usea-multi:
	    compactor_blocks_retention_period: 180d
	  alg-iac-aks-d-usea-int01:
	    compactor_blocks_retention_period: 180d
  # Production:
	  alg-iac-aks-d-usea-int02:
	    compactor_blocks_retention_period: 180d
```
@pracucci  here you go.

**Comment by darioef** [comment]
Same problem here. I updated to chart version 5.7.0 (Mimir 2.16.0) and I can't see anything older than 7 days.

I only have retention configured in 2 tenants. The smallest tenant retention is 7d but I have another tenants with retention not defined (unlimited) and I can't get older data from them.

My tenant configuration:

```
  runtimeConfig:
    overrides:
      development-01:
        compactor_blocks_retention_period: 7d
      staging-01:
        compactor_blocks_retention_period: 15d
```
