### ISSUE TITLE
extraVolumes block fails for alertmanager

### ISSUE THREAD

**Issue by sem1993** [grafana/mimir#9775]
#### Describe the bug
Change from `indent` to `nindent` in[ alertmanager-dep.yaml](https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/alertmanager/alertmanager-dep.yaml#L149-L154) template.

#### To Reproduce
Specify such block for `alertmanager` in `values.yaml`:
```
extraVolumes:
  - name: test-volume
     secret:
       secretName: test-secret
```

1. Start Mimir (SHA or version) - chart 5.5.1
2. Perform Operations(Read/Write/Others) - install

#### Expected behavior

Clear installation without additional Helm chart tweaking.

#### Environment

- Infrastructure: [e.g., Kubernetes, bare-metal, laptop] - Kubernetes cluster v.1.29
- Deployment tool: [e.g., helm, jsonnet] - Helm
